cloudwatch compute log manager
dagster-io/dagster pull request #10045
Opened 2022-10-16 23:03 UTC by prha

### Summary & Motivation

### How I Tested These Changes

2022-10-16 23:03 UTC, prha commented
Current dependencies on/for this PR:
* master
  * **PR #9429** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9429" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #9956** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9956" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #9957** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9957" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #9958** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9958" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #9959** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9959" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #9960** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9960" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
              * **PR #9961** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9961" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                * **PR #9962** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9962" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                  * **PR #10045** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10045" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/10045?utm_source=stack-comment).

2022-10-16 23:03 UTC, prha commented
Current dependencies on/for this PR:
* master
  * **PR #9429** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9429" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #9956** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9956" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #9957** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9957" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #9958** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9958" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #9959** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9959" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #9960** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9960" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
              * **PR #9961** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9961" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                * **PR #9962** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9962" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                  * **PR #10045** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10045" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/10045?utm_source=stack-comment).

2022-10-16 23:03 UTC, prha commented
Current dependencies on/for this PR:
* master
  * **PR #9429** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9429" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #9956** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9956" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #9957** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9957" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #9958** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9958" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #9959** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9959" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #9960** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9960" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
              * **PR #9961** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9961" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                * **PR #9962** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9962" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                  * **PR #10045** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10045" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/10045?utm_source=stack-comment).

2022-10-17 16:41 UTC, jmsanders requested changes

2022-10-17 17:32 UTC, prha commented on python_modules/libraries/dagster-aws/dagster_aws/cloudwatch/cloudwatch_compute_log_manager.py
> +        log_group = f"$252Fdocker-compose$252F{self._project_name}"
yeah, this is good feedback, thanks

2022-10-17 17:34 UTC, prha commented on python_modules/libraries/dagster-aws/dagster_aws/cloudwatch/cloudwatch_compute_log_manager.py
> +        metadata_uri = os.getenv("ECS_CONTAINER_METADATA_URI")
This is improperly named.  This should really be the `LogsCapturedInECSThatPointToCloudwatchLogManager`.

2022-10-17 17:37 UTC, prha commented on python_modules/libraries/dagster-aws/dagster_aws/cloudwatch/cloudwatch_compute_log_manager.py
> +        metadata_uri = os.getenv("ECS_CONTAINER_METADATA_URI")
I guess I'm trying to suss out how people would want to configure their logging sidecars.

2023-02-14 22:08 UTC, closed without merging