Fix bugs with nested Any type and Dict input loading
dagster-io/dagster pull request #10122
Opened 2022-10-21 00:38 UTC by dpeng817

### Summary & Motivation

### How I Tested These Changes

2022-10-21 00:38 UTC, dpeng817 commented
Current dependencies on/for this PR:
* master
  * **PR #10122** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10122" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/10122?utm_source=stack-comment).

2022-10-24 16:58 UTC, alangenfeld reviewed
On board with the general solution here - this is a nuanced thing that a better error message will help people get through. We should probably make sure the error message points out its due to `Any` type and adding a better type hint would resolve.

2022-10-24 16:58 UTC, alangenfeld commented on python_modules/dagster/dagster/_core/types/builtin_config_schemas.py
> +        check.failed(
is `check` the right type of error to throw here? How do these errors show up in `dagit`? I would expect a dedicated `DagsterInvalidConfigError` something - are these inner errors caught and turned in to that?

also how come this is not being caught at schema validation time? Doesn't the config schema know the valid keys that are possible?

2022-10-26 19:58 UTC, alangenfeld submitted a review, later dismissed
q mgmt

2022-10-28 22:11 UTC, dpeng817 reviewed
How the error manifests in dagit: ![Screen Shot 2022-10-28 at 3.10.41 PM.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/BNzu24Bttry3X3xg41kv/b7af97c7-6099-48af-b4aa-eef7c43783c0/Screen%20Shot%202022-10-28%20at%203.10.41%20PM.png)

2022-11-03 19:16 UTC, alangenfeld requested changes

2022-11-03 19:16 UTC, alangenfeld commented on python_modules/dagster/dagster/_core/types/builtin_config_schemas.py
> +        check.failed(
> schema type of a dict type loader is Permissive

ah - thats the root of the problem. We should change it to use the `Map` type that @benpankow  added 
https://github.com/dagster-io/dagster/blame/master/python_modules/dagster/dagster/_config/field_utils.py#L158-L180

2022-11-08 17:40 UTC, alangenfeld approved these changes
nice

2022-11-08 17:40 UTC, alangenfeld commented on python_modules/dagster/dagster/_core/types/python_dict.py
> +            ).scalar_type
whats this about? I think i probably get it but add a clarifying comment

2022-11-08 17:40 UTC, alangenfeld commented on python_modules/dagster/dagster_tests/core_tests/runtime_types_tests/test_python_dict.py
> -    # https://github.com/dagster-io/dagster/issues/3180
omg a resolved TODO comment. its a miracle

2022-11-09 21:09 UTC, merged