[snowflake] quick start portion of the guide
dagster-io/dagster pull request #10812
Opened 2022-11-30 20:03 UTC by jamiedemaria

### Summary & Motivation
Splitting https://github.com/dagster-io/dagster/pull/10806 into a couple different PRs

This part of the guide is just the "quick start" section of the larger guide. it's been restructured a bit as well. let me know what you think. I did make many major changes to content yet, mostly playing with the structure

### How I Tested These Changes

2022-11-30 20:25 UTC, slopp commented
I left some Vercel comments on the content while I was there, but this structure is awesome. I left a few structural comments that are small:

1. I think we can leave out the scary concepts section from pre-reqs and instead link to it at the end as a next step
2. The configure section should maybe incl the `build_snowflake_io_manager` part?
3. I'd suffix the two labels on the config tabs w/ Required and Optional 

The structure (and content) of defining tables vs assets and then using them is total goodness.

2022-11-30 20:44 UTC, jamiedemaria commented on python_modules/dagster/dagster/_core/storage/db_io_manager.py
>          self._db_client = db_client
revert. not sure how this got in from another pr

2022-11-30 20:54 UTC, jamiedemaria commented
@slopp for 2:  there's now a `snowflake_pandas_io_manager` that you can directly import from `dagster_snowflake_pandas` I'm going to use that in the guide by default until more types are supported and then add a section describing the different IO managers to choose from

2022-11-30 21:14 UTC, rexledesma requested changes

2022-11-30 21:14 UTC, rexledesma commented on docs/content/integrations/snowflake.mdx
> +                    "schema": "IRIS", # optional
This should be organized by required and optional.

2022-11-30 21:14 UTC, rexledesma commented on docs/content/integrations/snowflake.mdx
> +@asset
explicitly tag the io_manager here, don't use the magic default `io_manager`

2022-11-30 21:14 UTC, rexledesma commented on docs/content/integrations/snowflake.mdx
> +daffodil_dataset = SourceAsset(key="daffodil_dataset")
we should only show this code in the snippet - the other stuff is extra.

2022-11-30 21:27 UTC, yuhan commented
i like this quickstart - it's short and neat. left a few comments in the preview but i think it's a good shape to push out!

im leaving this open for a bit to others a chance to comment : )

2022-12-01 16:12 UTC, jamiedemaria commented
@erinkcochran87 you can do either or both, the main distinction is that one is for creating new tables that will be maintained/updated by dagster and one is for giving dagster access to existing tables that may be updated by external tools. I'll add some explanation before the tab group explaining this

2022-12-01 17:23 UTC, yuhan approved these changes
🚢

2022-12-01 17:34 UTC, erinkcochran87 approved these changes
:shipit:

2022-12-05 17:54 UTC, merged