PipelineRunStatus -> DagsterRunStatus
dagster-io/dagster pull request #10846
Opened 2022-12-01 23:10 UTC by smackesey

### Summary & Motivation

This is a simple repo-wide rename of `PipelineRunStatus` ->
`DagsterRunStatus`. They were already aliases of one another.

### How I Tested These Changes

Existing BK tests.

2022-12-01 23:10 UTC, smackesey commented
Current dependencies on/for this PR:
* master
  * **PR #10846** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10846" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/10846?utm_source=stack-comment).

2022-12-05 22:00 UTC, schrockn approved these changes
tl;dr

2022-12-05 22:01 UTC, schrockn requested changes
Actually I believe this is used in serializable classes. What is the plan there? e.g. PipelineRunReaction

2022-12-05 22:06 UTC, smackesey commented
>Actually I believe this is used in serializable classes. What is the plan there? e.g. PipelineRunReaction

`DagsterRun` pre-existed this PR, it just wasn't used consistently-- there was already the below line to take handle the serialization.

```
register_serdes_enum_fallbacks({"PipelineRunStatus": DagsterRunStatus})
```

2022-12-05 22:11 UTC, schrockn approved these changes
Ah lovely, thank you

2022-12-06 16:36 UTC, merged