ExecutionResult typing
dagster-io/dagster pull request #10857
Opened 2022-12-02 13:03 UTC by smackesey

### Summary & Motivation

Add type annotations for execution result classes. Also some method
renames to change `solid` to `node`.

### How I Tested These Changes

Existing BK tests.

2022-12-02 13:03 UTC, smackesey commented
Current dependencies on/for this PR:
* master
  * **PR #10810** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10810" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #10811** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10811" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #10846** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10846" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #10847** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10847" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #10848** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10848" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #10850** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10850" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
              * **PR #10857** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10857" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈
              * **PR #10833** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10833" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #10816** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10816" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/10857?utm_source=stack-comment).

2022-12-05 21:59 UTC, schrockn requested changes
Per slack conversation, extract out trivial renames from the more substantive changes in this PR

2022-12-06 18:39 UTC, smackesey commented
@schrockn This is now split into 3 PRs

2022-12-06 19:03 UTC, schrockn commented on python_modules/dagster/dagster/_core/definitions/solid_container.py
> +                check.failed(f"Unexpected solid_def type {node_def}")
Change string to not have solid

2022-12-06 19:04 UTC, schrockn approved these changes
Cool. Please respect nits but good to go

2022-12-06 19:04 UTC, schrockn commented on python_modules/dagster/dagster/_core/definitions/solid_container.py
> +    return {ps.name: ps for ps in nodes}
rename `ps` to `node`

2022-12-07 12:51 UTC, merged