Retry registering task definitions
dagster-io/dagster pull request #11192
Opened 2022-12-16 19:17 UTC by jmsanders

When multiple runs try to register a task definition simultaneously, we can hit an ECS API error:

```
botocore.errorfactory.ClientException: An error occurred (ClientException)
when calling the RegisterTaskDefinition operation: Too many concurrent
attempts to create a new revision of the specified family.
```

Our task definition reuse strategy creates a race condition where:

- multiple simultaneous runs can't find a task defintion
- run A successfully registers the task definition, run B hits the error

Now run B will retry and see that it can reuse the task definition that run A created.

Testing this is proving to be tricky - I initially added a lock to our stub and ran man concurrent threads against it. But getting the botocore stubber interactions to work well with multiple threads was a challenge. I'm putting this up for review now and I'll follow up with a better test
- likely one that makes heavy use of mock.patch but I'm open to suggestions.

2022-12-16 19:37 UTC, jmsanders commented on python_modules/libraries/dagster-aws/dagster_aws/ecs/launcher.py
> +                retry_on=(ClientError,),
There might be a more narrow error we can catch on here.

2022-12-16 19:59 UTC, gibsondan requested changes
as currently written this is going to call describe_task_definition on each iteration here: https://github.com/dagster-io/dagster/blob/master/python_modules/libraries/dagster-aws/dagster_aws/ecs/launcher.py#L527 - I think we want to be tactical and only do it around the register call? At least for this specific error that we're retrying around. To reduce the risk of getting rate limited

2022-12-16 20:34 UTC, gibsondan approved these changes

2022-12-16 21:02 UTC, jmsanders commented
I think we want that behavior - otherwise if Run B requires a task definition that's different than the one Run A requested, it'd fail.

2022-12-19 23:09 UTC, jmsanders commented on python_modules/libraries/dagster-aws/dagster_aws/ecs/launcher.py
> +                retry_on=(ClientError,),
For now, I broadened this to `Exception`

2022-12-19 23:11 UTC, jmsanders commented
I went a little crazy with our StubbedEcs to allow us to test this 😅 

It was either that or a very verbose, confusing, brittle set of mocks. Or a very complicated integration test setup. Open to alternative suggestions.

2022-12-20 14:25 UTC, merged