[structured config] Add support for class, field descriptions
dagster-io/dagster pull request #11274
Opened 2022-12-20 15:17 UTC by benpankow

### Summary & Motivation

### How I Tested These Changes

2022-12-20 15:18 UTC, benpankow commented
Current dependencies on/for this PR:
* master
  * **PR #11268** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11268" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #11272** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11272" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #11274** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11274" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/11274?utm_source=stack-comment).

2022-12-20 19:45 UTC, schrockn requested changes
Why support Annotated *and* Fields?

2022-12-20 20:40 UTC, benpankow commented
> Why support Annotated _and_ Fields?

This [support is on Pydantic's end](https://docs.pydantic.dev/usage/schema/#typingannotated-fields) - we could constrain our recommendations to only use one or the other. 

> Rather than assigning a `Field` value, it can be specified in the type hint with `typing.Annotated`


`Field` is probably easier to support because it's available on all Python versions, `Annotated` is a 3.9 feature (without `typing_extensions`.

2022-12-20 20:58 UTC, schrockn approved these changes
Got it thanks for clarification.

From slack:

"to be clear you didn’t have to write any additional code to support Annotation https://github.com/dagster-io/dagster/pull/11274#event-8081680891"

"Yup, it all gets coerced by pydantic into the same Field fields

3:53
Probably makes sense to just not mention Annotation/suggest it though since it’s not supported by all python versions."

2022-12-21 17:46 UTC, benpankow commented
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/11274?utm_source=stack-comment).
<!-- SHOW_IN_GRAPHITE_UI -->

Job Reference: TXP57Jx30eGCn07R3Kfh

2022-12-21 18:49 UTC, merged