[apidoc] asset_selection repository -> Definitions
dagster-io/dagster pull request #11303
Opened 2022-12-21 01:30 UTC by yuhan

### Summary & Motivation
also update an error message to mention Definitions not repository
### How I Tested These Changes

2022-12-21 01:30 UTC, yuhan commented
Current dependencies on/for this PR:
* master
  * **PR #11303** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11303" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/11303?utm_source=stack-comment).

2022-12-21 22:50 UTC, schrockn requested changes

2022-12-21 22:50 UTC, schrockn commented on python_modules/dagster/dagster/_core/definitions/asset_selection.py
> +                "are correctly added to the `Definitions`."
I think user-facing error strings should mention both concepts for now. Otherwise might get super confusing for people who have not migrated.

2023-03-06 22:50 UTC, erinkcochran87 commented
ping on this @yuhan, as it's hanging out in the Dev Rel Notion queue

2023-03-07 00:53 UTC, schrockn approved these changes
Ok good to go. I think enough time has passed since my previous objection.

2023-03-08 02:19 UTC, merged