Add support for DefaultAzureCrential for AzureBlobComputeLogManager
dagster-io/dagster pull request #11310
Opened 2022-12-21 14:47 UTC by mpicard

### Summary & Motivation

As an Azure user, I want to easily authenticate with Azure in multiple common scenarios using the `azure.identity.DefaultAzureIdentity` so that all my environments, locally and in azure are securely authenticated. 

### How I Tested These Changes

I unit tested this and also manually tested it in a locally and an azure environment.

2023-01-11 08:58 UTC, mpicard commented
@jamiedemaria

2023-01-13 15:38 UTC, jamiedemaria commented
Build kite results:
`helm/dagster/schema/schema_tests/test_instance.py` has some failing tests - you can run this test locally so see the issue, but it looks like mismatched config entries due to the new azure credentials

`ruff` formatting error - we recently switched from using `isort` and `pylint` to using `ruff`. I recommend rebasing/merging from master to ensure you have a version of the codebase formatted with `ruff` and then running `make ruff` from the top level dagster directory. This will format your code according to the new standards

2023-01-13 15:44 UTC, jamiedemaria requested changes
one small request, but otherwise this looks good!

2023-01-16 09:23 UTC, mpicard commented on python_modules/libraries/dagster-azure/dagster_azure/blob/compute_log_manager.py
> +
Sure thing, I made the changes

2023-01-16 09:25 UTC, mpicard commented
I updated the helm schema test, it still fails locally, maybe you can help me understand why it's still failing? I seem to have refactored the test properly I believe

2023-01-19 19:30 UTC, prha commented
Had a hard time pushing updates to your PR, but here's a patch file that I think should resolve the failing tests:
[azure_creds.patch](https://github.com/dagster-io/dagster/files/10460390/azure_creds.patch)

2023-01-20 14:25 UTC, jamiedemaria approved these changes

2023-01-20 14:25 UTC, merged