Allow specifying resources in Solid/Asset params list
dagster-io/dagster pull request #11322
Opened 2022-12-21 19:38 UTC by benpankow

### Summary & Motivation

### How I Tested These Changes

2022-12-21 19:38 UTC, benpankow commented
Current dependencies on/for this PR:
* master
  * **PR #11322** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11322" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈
    * **PR #11321** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11321" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/11322?utm_source=stack-comment).

2022-12-21 22:47 UTC, schrockn requested changes

2022-12-21 22:47 UTC, schrockn commented on python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
> +                .union({arg.name for arg in get_resource_args(fn)})
I think we should strongly consider disallowing specifying `required_resource_keys`/`resource_defs` and the argument-based approach for now, similar to how we do not allow `config` argument and `config_schema`. We can always loosen this later, but I would prefer to be strict for now.

2022-12-21 22:47 UTC, schrockn commented on python_modules/dagster/dagster/_core/definitions/decorators/op_decorator.py
> +        resolved_resource_keys = set(self.required_resource_keys or []).union(
same here

2022-12-21 22:47 UTC, schrockn commented on python_modules/dagster/dagster/_core/definitions/decorators/solid_decorator.py
> +        resolved_resource_keys = set(self.required_resource_keys or []).union(
same

2022-12-22 17:08 UTC, schrockn approved these changes
Looks great.

Given this is an exploration, I don't think we strictly need it, but make a note that we will need to test and support (or explicitly error) all different use cases where input names and upstream asset names might conflict with resource names.

2022-12-22 17:15 UTC, schrockn requested changes
Actually we definitely need some test cases with ops with inputs and assets that have upstream assets. Please add.

2022-12-23 16:19 UTC, benpankow commented
Added some tests which go over upstream assets/ops. Doesn't handle the case in which names conflict, since we don't have a good way to resolve this at the moment without threading through resources to the execution planning logic (this may be what we want to do long-term).

2022-12-23 17:34 UTC, schrockn approved these changes
👍🏻

2022-12-23 17:34 UTC, schrockn commented on python_modules/dagster/dagster/_core/definitions/decorators/solid_decorator.py
> +            "Cannot specify resource requirements in both @solid decorator and as arguments to the decorated function",
s/solid/op

2022-12-23 19:05 UTC, benpankow commented
**Graphite Merge Job**

Current status: 🔄 Waiting for checks to pass

This pull request is currently waiting for CI and mergeability checks to pass before being merged.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/11322?utm_source=stack-comment).
<!-- SHOW_IN_GRAPHITE_UI -->

Job Reference: uHrT8DIrkchoQsyuEMKn

2022-12-23 19:06 UTC, merged