Add configure_with_values to AnonymousConfigurableDefinition and implement configured in terms of it
dagster-io/dagster pull request #11434
Opened 2022-12-29 22:16 UTC by schrockn

### Summary & Motivation

### How I Tested These Changes

2022-12-29 22:17 UTC, schrockn commented
Current dependencies on/for this PR:
* master
  * **PR #11433** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11433" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #11434** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11434" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/11434?utm_source=stack-comment).

2022-12-29 23:50 UTC, schrockn commented
Note: this is more of an RFC to get feedback on the general _approach_ rather than for commit. I think we need to spec this out a little more and think about all the uses cases. However I think this is a promising angle and I want to make sure that I am not missing anything.

2022-12-30 16:16 UTC, dpeng817 commented on python_modules/dagster/dagster/_core/definitions/configurable.py
> +    evr = validate_config(field.config_type, additional_default_values)
another nice benefit of this is that we'll now see errors with configured at definition time rather than during runtime.

2022-12-30 16:23 UTC, dpeng817 reviewed
I'm super bullish on this idea, just seems like a huge improvement for 90% of use cases. 
A few questions:
- Would the existing config mapping behavior still be something that we espouse, or would that be hidden backcompat functionality?
- Do we force people to provide "full" config when using `configured`? Seems like it would be relatively straightforward to just validate the individual defaults provided instead of the full schema for the definition, and then folks could provide partial defaults (while we're at it, this approach could also be used to allow partial defaults for job defs).

2022-12-30 17:38 UTC, schrockn commented
> Would the existing config mapping behavior still be something that we espouse, or would that be hidden backcompat functionality?

I think at a minimum we should de-emphasize. I'd want to have more clarity around our long-term vision for config before committing to it. But my thinking is certainly in the direction of shifting the entire config system to be pydantic-native in our next major release, in which case deprecating config mapping would make sense.

> Do we force people to provide "full" config when using configured? Seems like it would be relatively straightforward to just validate the individual defaults provided instead of the full schema for the definition, and then folks could provide partial defaults (while we're at it, this approach could also be used to allow partial defaults for job defs).

Ah that sounds like a nice idea. Agree seems totally tractable.

2022-12-30 18:14 UTC, schrockn commented
@gibsondan I'd like your thoughts here as well. In particular I'm envisioning that along with this change we would also change the daemons to apply defaults to config and then persist the entire config slug with every run, rather than relying on default evaluation at job execution time. Curious re:

1) How hard that would be to implement and 
2) Any bad behavior this would cause. Any obvious this is that if config schema changed between persisting the config and the actual runtime, but anything else beyond that?

2022-12-31 01:21 UTC, gibsondan commented
when you say "change the daemons to apply defaults to config" - we're talking about like the scheduler and sensor daemons? Or when you kick off an ad hoc run from dagit and then it gets stuck in the queue? So i think the relevant hook here is the execution plan generation grpc call. 

We already lock it to a specific image when we do this so I'm not super worried about the config schema changing between run submit time and run launch time

2022-12-31 01:25 UTC, gibsondan commented
the relevant part of the codebase is here for the scheduler: https://github.com/dagster-io/dagster/blob/ab6ab928e2cb447291ada416e391e94083929b9a/python_modules/dagster/dagster/_scheduler/scheduler.py#L705-L741 

it takes the passed in run config, uses it to make an execution plan snapshot, and then creates a run with the passed in run config and the snapshot.

Seems like as part of that grpc call to make the execution plan snapshot you could also pass back some kind of resolved run config and either stick that on the run, or persist it separately on the snapshot so that you have both the user-specified run config and the resolved run config as needed.

Alex would probably have good thoughts here too when he is back on Tuesday, he is more familiar with execution plan stuff than I

But overall this seems very tractable to me

2022-12-31 01:37 UTC, schrockn commented
Got it. Yeah it looks like we have passed back the fully resolved dictionary in `ResolvedRunConfig` when we build the execution plan and then jam that fully resolved dictionary into the `ExecutionPlanSnapshot` that gets passed back over the rpc layer. Thanks for the pointer.

2023-01-03 19:31 UTC, sryza commented
I am overall very positive on this direction though.

2023-01-03 20:34 UTC, schrockn commented
> With the struct-based config, are we going to essentially be deprecating configured? If so, might we want to leave the old behavior for configured to minimize risk and just add the new behavior to struct-based config?

Yup totally reasonable. We are going to press on with using this strategy for new resources temporarily to facilitate some prototyping: https://github.com/dagster-io/dagster/pull/11470

> It could potentially be useful to render some sort of "config value lineage" in Dagit, to help people understand where their config is being set. One of the things I find most difficult about dealing with config in software is understanding where it came from. How would this fit with that?

What do you mean by config value lineage in this context? Definitely one part of the vision here is to be able to display configured values of resources along with those resources. Is that what you mean?

> Do we want some config to be non-override-able at runtime? If so, how would someone specify that?

Right now they wouldn't be able to specify that but definitely something we should consider.

> Is "default" still the right word for how we want to message this for users? Would "definition-level" or something be more accurate?

Especially with the proposal to have non-override-able config, default definitely makes less sense as a name.

I have to step away from a few minutes but these are great questions

2023-01-03 21:25 UTC, sryza commented
> What do you mean by config value lineage in this context? Definitely one part of the vision here is to be able to display configured values of resources along with those resources. Is that what you mean?

I mean helping people understand where their config values are being set. Some of the places where config can be set:
1. As the default value provided by a library resource.
2. A definition-time override of a default value provided by a library resource.
3. When launching a run.

So I'm wondering if we'd want to help users understand the distinction between (1) and (2). This is obviously speculative, but just trying to understand the space of potential impacts of a change like this.

2023-01-05 17:38 UTC, schrockn commented
These exact lineage issues came up in our prep for the user council meetin tmrw. We are going to surface lineage + the risk of having configured values be editable.

2023-01-10 19:55 UTC, sryza requested changes
requesting changes for queue management

2023-08-28 18:02 UTC, closed without merging