only count materializations within backfill
dagster-io/dagster pull request #11506
Opened 2023-01-04 19:59 UTC by sryza

### Summary & Motivation

Asset backfills look at what asset partitions have already been materialized to decide what partitions need to be submitted.

Prior to this change, the backfill code would look at all materializations of the asset, independent of whether they were part of the backfill. This meant that any materialization prior to the backfill would stop the backfill from submitting runs.

This change filters to only materializations that were part of the backfill. It functions by adding a backfill tag to the relevant materializations

An alternative way to implement this would have been to look for the backfill tag on the runs, instead of on the asset materializations. This would have required joining the event log with the run tags table.

### How I Tested These Changes

Added a test that fails before the change

2023-01-04 20:03 UTC, prha commented
Need to make sure this is guarded against the schema migrations req'd for asset tags.  Previously, this was gated on users who wanted to use asset partitions (new feature), while this will affect all materializations within backfilled jobs.

2023-01-04 20:52 UTC, prha requested changes
This needs guards against various stages of migration state, and probably some tests for that.

2023-01-04 22:09 UTC, sryza commented
I added a PR that makes event tag filtering work both pre- and post- migration: https://github.com/dagster-io/dagster/pull/11509.

2023-01-04 22:51 UTC, sryza commented on python_modules/dagster/dagster/_core/execution/asset_backfill.py
> +            tags=frozendict({BACKFILL_ID_TAG: backfill_id}),
Depends on https://github.com/dagster-io/dagster/pull/11509 to work in the unmigrated case

2023-01-05 01:25 UTC, prha approved these changes

2023-01-05 01:29 UTC, merged