[pyright] [core] _core/storage/event_log/sql_event_log
dagster-io/dagster pull request #11699
Opened 2023-01-13 15:15 UTC by smackesey

### Summary & Motivation

### How I Tested These Changes

2023-01-13 15:15 UTC, smackesey commented
Current dependencies on/for this PR:
* master
  * **PR #11002** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11002" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #11330** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11330" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #11001** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11001" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #11038** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11038" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #11051** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11051" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #11362** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11362" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #11695** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11695" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #11696** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11696" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #11697** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11697" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
              * **PR #11698** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11698" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                * **PR #11699** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11699" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈
                  * **PR #11363** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11363" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                    * **PR #11364** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11364" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                      * **PR #11365** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11365" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                        * **PR #11366** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11366" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                          * **PR #11367** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11367" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                            * **PR #11368** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11368" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                              * **PR #11369** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11369" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                                * **PR #10983** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10983" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/11699?utm_source=stack-comment).

2023-01-13 15:15 UTC, smackesey commented
Current dependencies on/for this PR:
* master
  * **PR #11002** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11002" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #11330** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11330" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #11001** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11001" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #11038** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11038" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #11051** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11051" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #11362** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11362" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #11695** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11695" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #11696** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11696" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #11697** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11697" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
              * **PR #11698** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11698" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                * **PR #11699** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11699" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈
                  * **PR #11363** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11363" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                    * **PR #11364** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11364" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                      * **PR #11365** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11365" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                        * **PR #11366** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11366" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                          * **PR #11367** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11367" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                            * **PR #11368** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11368" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                              * **PR #11369** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11369" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                                * **PR #10983** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10983" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/11699?utm_source=stack-comment).

2023-01-13 15:15 UTC, smackesey commented
Current dependencies on/for this PR:
* master
  * **PR #11002** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11002" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #11330** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11330" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #11001** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11001" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #11038** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11038" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #11051** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11051" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #11362** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11362" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #11695** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11695" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #11696** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11696" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #11697** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11697" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
              * **PR #11698** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11698" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                * **PR #11699** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11699" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈
                  * **PR #11363** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11363" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                    * **PR #11364** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11364" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                      * **PR #11365** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11365" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                        * **PR #11366** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11366" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                          * **PR #11367** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11367" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                            * **PR #11368** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11368" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                              * **PR #11369** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11369" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                                * **PR #10983** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10983" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/11699?utm_source=stack-comment).

2023-01-13 15:15 UTC, smackesey commented
Current dependencies on/for this PR:
* master
  * **PR #11002** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11002" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #11330** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11330" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #11001** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11001" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #11038** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11038" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #11051** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11051" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #11362** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11362" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #11695** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11695" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #11696** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11696" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #11697** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11697" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
              * **PR #11698** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11698" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                * **PR #11699** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11699" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈
                  * **PR #11363** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11363" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                    * **PR #11364** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11364" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                      * **PR #11365** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11365" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                        * **PR #11366** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11366" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                          * **PR #11367** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11367" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                            * **PR #11368** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11368" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                              * **PR #11369** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11369" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                                * **PR #10983** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10983" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/11699?utm_source=stack-comment).

2023-01-13 15:15 UTC, smackesey commented
Current dependencies on/for this PR:
* master
  * **PR #11002** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11002" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #11330** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11330" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #11001** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11001" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #11038** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11038" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #11051** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11051" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #11362** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11362" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #11695** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11695" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #11696** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11696" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #11697** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11697" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
              * **PR #11698** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11698" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                * **PR #11699** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11699" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈
                  * **PR #11363** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11363" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                    * **PR #11364** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11364" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                      * **PR #11365** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11365" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                        * **PR #11366** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11366" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                          * **PR #11367** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11367" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                            * **PR #11368** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11368" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                              * **PR #11369** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11369" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                                * **PR #10983** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/10983" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/11699?utm_source=stack-comment).

2023-01-14 14:20 UTC, schrockn requested changes
So this is a behavior change.

Before when an error is encountered the entire deserialization process stops and we return whatever we had.

Now we _continue_ to try to deserialize and might return different results than before. I don't think you should do this change without the understanding all context and implications.

My recommendation is define record_id in the outer scope.

2023-01-15 19:34 UTC, schrockn approved these changes

2023-01-17 17:06 UTC, merged