[structured config] Migrate resources from project-fully-featured to struct config resources
dagster-io/dagster pull request #11785
Opened 2023-01-18 23:20 UTC by benpankow

### Summary & Motivation

### How I Tested These Changes

2023-01-18 23:20 UTC, benpankow commented
Current dependencies on/for this PR:
* master
  * **PR #11773** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11773" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #11645** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11645" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #11785** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11785" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/11785?utm_source=stack-comment).

2023-01-20 19:16 UTC, schrockn requested changes
I think this feels pretty good overall. Can we make s3_bucket a bare string?

2023-01-20 19:16 UTC, schrockn commented on examples/experimental/project_fully_featured_v2_resources/project_fully_featured_v2_resources/resources/common_bucket_s3_pickle_io_manager.py
> +    s3_bucket: ResourceDependency[str]
does this even need to be a resource?

2023-01-20 23:21 UTC, benpankow commented on examples/experimental/project_fully_featured_v2_resources/project_fully_featured_v2_resources/resources/common_bucket_s3_pickle_io_manager.py
> +    s3_bucket: ResourceDependency[str]
no, good point

2023-02-01 15:33 UTC, schrockn requested changes
Looks like a rebase error

2023-02-04 09:46 UTC, schrockn approved these changes
This is great

2023-02-04 09:46 UTC, schrockn commented on examples/experimental/project_fully_featured_v2_resources/project_fully_featured_v2_resources/resources/hn_resource.py
> +    @cached_method
Seems a bit odd to auto-cache this

2023-02-16 19:19 UTC, merged