Simple dagster install script
dagster-io/dagster pull request #11838
Opened 2023-01-23 18:27 UTC by shalabhc

### Summary & Motivation

### How I Tested These Changes

2023-01-23 18:27 UTC, shalabhc commented
Current dependencies on/for this PR:
* master
  * **PR #11838** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11838" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/11838?utm_source=stack-comment).

2023-01-31 21:01 UTC, gibsondan reviewed
Would we also do the whole curl from url | python thing?

It is nice that this handles the M1 stuff automatically under the hood..

2023-01-31 22:03 UTC, smackesey commented
This looks good.

One thought: if this is targeted to people uncomfortable with even `pip`, I would not expect them to be comfortable creating a virtual env. But the script seems to assume some knowledge of virtual envs:

```
To install in a venv, run python from the venv: `/path/to/venv/bin/python3 install_dagster.py`
```

Makes me think the script should handle venv creation as well.

2023-03-02 01:47 UTC, shalabhc commented
The grpcio issue seems resolved for now - not sure if we still want this.

2023-04-03 16:13 UTC, gibsondan requested changes
i think we have this semi-tabled for now, but good to have it around if we decide we want it in the future

2025-04-02 01:21 UTC, closed without merging