Add tests to experimental script-to-assets branching IO manager package
dagster-io/dagster pull request #11920
Opened 2023-01-28 01:02 UTC by benpankow

### Summary & Motivation

### How I Tested These Changes

2023-01-28 01:03 UTC, benpankow commented
Current dependencies on/for this PR:
* master
  * **PR #11773** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11773" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #11645** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11645" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #11920** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11920" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈
      * **PR #11785** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11785" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #11791** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11791" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/11920?utm_source=stack-comment).

2023-01-28 01:03 UTC, benpankow commented
Current dependencies on/for this PR:
* master
  * **PR #11773** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11773" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #11645** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11645" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #11920** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11920" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈
      * **PR #11785** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11785" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #11791** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11791" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/11920?utm_source=stack-comment).

2023-02-02 20:19 UTC, schrockn submitted a review, later dismissed
rebase plz

2023-02-03 20:46 UTC, schrockn requested changes
Looking like we are going a full download on every test? That is a bad idea. We could cache a response and read it off of disk or something.

2023-02-03 20:46 UTC, schrockn commented on examples/experimental/script_to_assets_branching_io_manager/script_to_assets_branching_io_manager_tests/test_branching_functionality.py
> +    )
look at `get_implicit_job_def_for_assets` on RepositoryDefinition

2023-02-03 20:46 UTC, schrockn commented on examples/experimental/script_to_assets_branching_io_manager/script_to_assets_branching_io_manager_tests/test_branching_functionality.py
> +    return check.not_none(instance.get_run_by_id(run.run_id))
wait is this test going to download from hackernews API on every run? We shouldn't do that.

2024-12-30 16:55 UTC, closed without merging