Add code versions to ExternalAssetGraph
dagster-io/dagster pull request #11950
Opened 2023-01-29 21:14 UTC by smackesey

### Summary & Motivation

Add code versions to `ExternalAssetGraph`. It was unclear to me whether
these should actually be added to the parent `AssetGraph` instead.

### How I Tested These Changes

New unit test.

2023-01-29 21:15 UTC, smackesey commented
Current dependencies on/for this PR:
* master
  * **PR #11950** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11950" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈
    * **PR #11951** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11951" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #11952** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/11952" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/11950?utm_source=stack-comment).

2023-01-30 16:17 UTC, sryza requested changes
I think these should be added to `AssetGraph` instead, like you mentioned.  Because e.g. we'll want to use them inside the asset reconciliation sensor, which uses internal asset graphs.

2023-01-30 16:46 UTC, sryza approved these changes

2023-01-30 16:48 UTC, sryza commented
plz update PR title before merging

2023-01-30 17:17 UTC, merged