Remove frozenlist class
dagster-io/dagster pull request #12293
Opened 2023-02-12 17:49 UTC by smackesey

### Summary & Motivation

Removes the frozenlist class. See: https://github.com/dagster-io/internal/discussions/4859#discussioncomment-4950032

Progress on relevant issues:

- #3008
- #3641

### How I Tested These Changes

BK

2023-02-12 17:49 UTC, smackesey commented
Current dependencies on/for this PR:
* master
  * **PR #12293** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12293" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/12293?utm_source=stack-comment).

2023-03-22 18:31 UTC, alangenfeld requested changes
seems fine overall to me - just add some more tests to encode behavior expectations

2023-03-22 18:31 UTC, alangenfeld commented on python_modules/dagster/dagster/_utils/__init__.py
> +def hash_named_tuple(named_tuple: NamedTuple) -> int:
lets put these `hash_` functions under direct test to encode what exact behaviors we expect them to have ie dicts hash the same despite order, lists do not etc

2023-03-23 15:50 UTC, alangenfeld approved these changes

2023-03-23 17:19 UTC, merged