[dagster-airflow] add `make_persistent_airflow_db_resource`
dagster-io/dagster pull request #12305
Opened 2023-02-13 18:14 UTC by Ramshackle-Jamathon

### Summary & Motivation

This pr adds a new airflow_db resource definition called `AirflowPersistentDatabase` this can be used instead of the current default ephemeral airflow database. By persisting airflow dag run state dagster-airflow is able to support most of the remaining airflow features that don't current work with the ephemeral airflow db specifically:
- retry-from-failure in Dagster
- Using prev_execution_date in Airflow-templated DAGs
- SubDAGOperators
- Airflow Pools

### How I Tested These Changes

- unit tests

2023-02-14 08:48 UTC, schrockn requested changes
I think there is a bunch of copy paste here we should eliminate

2023-02-14 08:48 UTC, schrockn commented on examples/with_airflow/with_airflow/__init__.py
> +# from .assets import (
rm

2023-02-14 08:48 UTC, schrockn commented on python_modules/libraries/dagster-airflow/dagster_airflow/resources/airflow_persistent_db.py
> +            )
I seem to recall very similar code in the `AirflowEphemeralDatabase`. Can these be consolidated?

2023-02-14 08:48 UTC, schrockn commented on python_modules/libraries/dagster-airflow/dagster_airflow/resources/airflow_persistent_db.py
> +        return execution_date
and this is a direct copypaste job i think

2023-03-06 22:34 UTC, yuhan approved these changes

2023-03-06 22:35 UTC, yuhan commented
please also make sure to include `make_persistent_airflow_db_resource` in the apidocs

2023-03-07 14:11 UTC, Ramshackle-Jamathon commented
pr for docs is here https://github.com/dagster-io/dagster/pull/12485

2023-03-07 14:11 UTC, merged