[dagit] Support backfills on partition-mapped asset selections
dagster-io/dagster pull request #12458
Opened 2023-02-22 00:24 UTC by bengotow

### Summary & Motivation

This PR:

- Replaces the Materialize button's "assets must be in the same partition space" and "assets must be in the same repo / job" error dialogs with a new "pure asset backfill" version of the backfill modal.

- This version has some additional messaging indicating that it will auto-infer the runs + partitions needed to execute the backfill. It does not offer the ability to launch a single run, does not offer to filter to "Missing only", and does not show you a preview of how many runs will be launched.

### How I Tested These Changes

IN PROGRESS: This code is complex and really needs test coverage. It's going to take a lot of work to bring all of the cases under test but this PR adds a .test.tsx file, cases covering this new behavior, and the required mocks. Adding more exhaustive test cases should be easier now that this is in place!

2023-02-22 17:51 UTC, sryza commented
I just tried this out and noticed that the asset key displayed at the top is the leaf asset, not the root assets:

<img width="564" alt="image" src="https://user-images.githubusercontent.com/654855/220713162-16b2f841-cce2-418d-b2fc-5b4556d33f9f.png">

Here's my graph:

<img width="516" alt="image" src="https://user-images.githubusercontent.com/654855/220713319-92bf81d1-059f-47b3-829c-97b99c6a938e.png">

2023-02-22 17:53 UTC, sryza commented
I also ran into this error when I launched: 

```
ValueError: time data '2023-02-19' does not match format '%Y-%m-%d-%H:%M'
  File "/Users/sryza/dagster/python_modules/dagster-graphql/dagster_graphql/implementation/utils.py", line 130, in _fn
    return fn(*args, **kwargs)
  File "/Users/sryza/dagster/python_modules/dagster-graphql/dagster_graphql/implementation/execution/backfill.py", line 148, in create_and_launch_partition_backfill
    backfill = PartitionBackfill.from_asset_partitions(
  File "/Users/sryza/dagster/python_modules/dagster/dagster/_core/execution/backfill.py", line 284, in from_asset_partitions
    serialized_asset_backfill_data=AssetBackfillData.from_asset_partitions(
  File "/Users/sryza/dagster/python_modules/dagster/dagster/_core/execution/asset_backfill.py", line 185, in from_asset_partitions
    target_subset |= asset_graph.bfs_filter_subsets(
  File "/Users/sryza/dagster/python_modules/dagster/dagster/_core/definitions/asset_graph.py", line 426, in bfs_filter_subsets
    partition_mapping.get_downstream_partitions_for_partitions(
  File "/Users/sryza/dagster/python_modules/dagster/dagster/_core/definitions/time_window_partition_mapping.py", line 134, in get_downstream_partitions_for_partitions
    return self._map_partitions(
  File "/Users/sryza/dagster/python_modules/dagster/dagster/_core/definitions/time_window_partition_mapping.py", line 172, in _map_partitions
    for from_partition_time_window in from_partitions_subset.included_time_windows:
  File "/Users/sryza/dagster/python_modules/dagster/dagster/_core/definitions/time_window_partitions.py", line 1222, in included_time_windows
    result_time_windows, _ = self._add_partitions_to_time_windows(
  File "/Users/sryza/dagster/python_modules/dagster/dagster/_core/definitions/time_window_partitions.py", line 1310, in _add_partitions_to_time_windows
    time_windows = self._partitions_def.time_windows_for_partition_keys(
  File "/Users/sryza/dagster/python_modules/dagster/dagster/_core/definitions/time_window_partitions.py", line 284, in time_windows_for_partition_keys
    sorted_pks = sorted(partition_keys, key=lambda pk: datetime.strptime(pk, self.fmt))
  File "/Users/sryza/dagster/python_modules/dagster/dagster/_core/definitions/time_window_partitions.py", line 284, in <lambda>
    sorted_pks = sorted(partition_keys, key=lambda pk: datetime.strptime(pk, self.fmt))
  File "/Users/sryza/.pyenv/versions/3.9.11/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/Users/sryza/.pyenv/versions/3.9.11/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
```

2023-02-22 19:33 UTC, sryza requested changes
Requesting changes based on the error I git

2023-02-22 20:27 UTC, bengotow commented
Hey @sryza sounds good! Re: that error, does the backend expect partition keys for a specific asset? (eg: do the backend and UI need to agree on which asset is the root one?) I think right now my assumption is that the backend will accept partition keys belonging to ANY of the assets and fill in the rest... it sounds like from that error that it got partitions of asset3 and expected partitions of asset1, but I didn't think it mattered beyond a UI choice.

2023-02-22 20:28 UTC, bengotow commented
Also just to verify, if asset1 and asset2 did not have the same partitioning in your example, the UI will still pick one ~at random between those two?

2023-02-22 20:45 UTC, sryza commented
asset3 isn't one of the root assets, and the partitions need to correspond to the partitions of the root assets (which all need to have the same partitioning or the backfill isn't allowed)

2023-02-22 21:26 UTC, bengotow commented
Oh wow all the roots need the same partitioning? Ok I think we can check that client-side and verify it before showing this modal - will add a test for it too since it's a bit subtle.

2023-02-22 22:26 UTC, sryza commented
> Oh wow all the roots need the same partitioning?

Right

2023-02-22 22:42 UTC, bengotow commented
Ok @sryza  this has been updated and there's a new test case as well. We identify the root assets of your selection and if they do not share a partition definition you get this error:

<img width="971" alt="image" src="https://user-images.githubusercontent.com/1037212/220776762-d7e6cad8-65a4-4373-be0b-d0046b93cd47.png">

2023-02-22 23:37 UTC, sryza approved these changes
I played around with this a little bit, and it seems to be working correctly

2023-02-23 20:54 UTC, hellendag approved these changes

2023-02-24 22:24 UTC, bengotow commented
Test failures are unrelated (finally) - going to go ahead and merge this 🙌

2023-02-24 22:24 UTC, merged