Add support for loading multiple modules from pyproject.toml
dagster-io/dagster pull request #12551
Opened 2023-02-25 17:04 UTC by bendnorman

### Summary & Motivation
It would be nice to load multiple modules using `pyproject.toml` so users don't have to type out all the modules they want to load using the CLI command. See issue #11439 and discussion #11167.

### How I Tested These Changes
I added a new unit test in `dagster_tests/cli_tests/test_toml_loading.py`

2023-03-02 20:52 UTC, gibsondan commented
This seems totally reasonable to me. @schrockn do you feel OK about the syntax here? The alternative would be to have separate 'module_name' (when its singular) and 'module_names' (when it's plural) but a single key is probably better for consistency.

2023-03-08 17:44 UTC, schrockn commented
My bad on the tardiness to the review here.

One alternative to consider here is a different more "advanced" entry to allow for future extensions.

`modules = [{module_name: foo}, {module_name: bar}]`

and also also the specification of attribute and location_name here.

The most generic and future-proof being: 
'code_locations = [{type:module, module_name: foo}, {type:module, module_name: bar}]`

My recommendation is a new `modules` toml entry.

2023-03-09 23:29 UTC, gibsondan requested changes
Back to you for any thoughts about incorporating @schrockn 's suggestion. Thanks again for sending this out!

2024-10-01 03:05 UTC, PedramNavid commented
Closing stale PR.

2024-10-01 03:05 UTC, closed without merging

2024-10-02 17:11 UTC, bendnorman commented
This was resolved by #22327 👍