[refactor] metadata dict over metadata_entries
dagster-io/dagster pull request #12770
Opened 2023-03-07 14:30 UTC by smackesey

### Summary & Motivation

### How I Tested These Changes

2023-03-07 14:31 UTC, smackesey commented
Current dependencies on/for this PR:
* master
  * **PR #12724** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12724" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #12769** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12769" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #12725** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12725" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #12726** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12726" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #12523** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12523" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #12524** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12524" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #12553** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12553" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
              * **PR #12714** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12714" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                * **PR #12715** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12715" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #12716** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12716" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #12713** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12713" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #12770** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12770" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/12770?utm_source=stack-comment).

2023-03-07 14:31 UTC, smackesey commented
Current dependencies on/for this PR:
* master
  * **PR #12724** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12724" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #12769** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12769" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #12725** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12725" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #12726** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12726" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #12523** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12523" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #12524** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12524" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #12553** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12553" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
              * **PR #12714** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12714" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                * **PR #12715** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12715" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #12716** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12716" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #12713** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12713" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #12770** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12770" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/12770?utm_source=stack-comment).

2023-03-07 14:31 UTC, smackesey commented
Current dependencies on/for this PR:
* master
  * **PR #12724** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12724" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #12769** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12769" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #12725** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12725" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #12726** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12726" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #12523** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12523" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #12524** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12524" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #12553** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12553" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
              * **PR #12714** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12714" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                * **PR #12715** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12715" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #12716** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12716" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #12713** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12713" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #12770** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12770" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/12770?utm_source=stack-comment).

2023-03-28 21:50 UTC, dpeng817 commented on python_modules/dagster/dagster/_core/definitions/metadata/__init__.py
> +                    "1.4.0",
1.3.0?

2023-03-28 22:28 UTC, dpeng817 requested changes
I feel like there's some actual new content buried within this refactor and I'm finding it all a bit hard to parse - as I understand it there are a few distinct pieces here: 
- Refactoring metadata fields to no longer produce metadata entries
- Adding a field serializer that serializes metadata dictionaries as lists of metadata entries
- Changing out all arguments/properties that use metadata_entries to use metadata

In at least some of these examples, I think these count as breaking changes, specifically in the cases where there is no alternative? Such as `SourceAsset` - so we couldn't merge that for example immediately.

Can we break this PR up into those constituent parts?  Lmk your thoughts

2023-03-29 00:07 UTC, smackesey commented
>I think these count as breaking changes

Unless I've made a mistake, I don't believe there are any breaking changes in this PR. I concentrated them all in an upstack PR to be separately evaluated.

re `SourceAsset`, prior to this PR there is no public API for passing in `MetadataEntry`. And though many classes currently store metadata as `Sequence[MetadataEntry]`, it's not publicly exposed.

In places where `MetadataEntry` _can_ currently be passed in publicly, in this PR it is still accepted (as in e.g. `AssetMaterialization`)-- the storage format just changes to dict.

2023-03-29 16:41 UTC, dpeng817 reviewed
Yea what you're saying makes sense. I think with the additional context it's more parseable - only thing I wonder is if we should potentially keep MetadataEntry around in some code graveyard and add tests that ensure that the format of `MetadataFieldSerializer` matches with that API? As it is, I guess my only request would be tests for `MetadataFieldSerializer` in general

2023-03-29 17:12 UTC, smackesey commented on python_modules/libraries/dagster-wandb/dagster_wandb/io_manager.py
> -            serialization_module = parameters.get("serialization_module", {})  # type: ignore
yes it's no longer needed

2023-03-29 17:22 UTC, smackesey commented
@dpeng817 Added a field serializer test in `general_tests/test_backcompat.py`

2023-03-30 16:51 UTC, dpeng817 approved these changes
Nice

2023-03-30 17:39 UTC, merged