[dagster-fivetran] Migrate to Pythonic resources
dagster-io/dagster pull request #12976
Opened 2023-03-15 22:56 UTC by benpankow

## Summary

Converts the `dagster-fivetran` internals to use the new config and resource systems:

- Assets and ops now use Pythonic config rather than config_schema
- Assets and ops retrieve resource dependencies through params rather than the `context` / `required_resource_keys`
- `FivetranResource` is now a `ConfigurableResource`, holding its own config schema. The `fivetran_resource` function resource now wraps this class rather than holding the config.

## Test Plan

Existing unit tests.

2023-03-15 22:57 UTC, benpankow commented
Current dependencies on/for this PR:
* master
  * **PR #12975** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12975" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #12976** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12976" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/12976?utm_source=stack-comment).

2023-04-05 13:22 UTC, schrockn requested changes
pretty great showcase diff demonstrating the improve ergonomic

2023-04-05 13:22 UTC, schrockn commented on python_modules/libraries/dagster-fivetran/dagster_fivetran/ops.py
> +from pydantic import Field as PyField
alias

2023-04-05 13:22 UTC, schrockn commented on python_modules/libraries/dagster-fivetran/dagster_fivetran/ops.py
> +        ...,
elim unnecessary ellipsis

2023-04-05 13:22 UTC, schrockn commented on python_modules/libraries/dagster-fivetran/dagster_fivetran/ops.py
> +        poll_timeout=config.poll_timeout,
this is most pleasing

2023-04-07 13:55 UTC, schrockn approved these changes
Use the new helper, but looks great otherwise 👍🏻

2023-04-07 13:55 UTC, schrockn commented on python_modules/libraries/dagster-fivetran/dagster_fivetran/resources.py
> +    return FivetranResource(**context.resource_config).resource_fn(context)  # type: ignore
use `from_resource_context`

2023-04-07 22:08 UTC, merged