[refactor] Delete AssetGroup
dagster-io/dagster pull request #13028
Opened 2023-03-19 16:15 UTC by smackesey

## Summary & Motivation

Delete `AssetGroup`.

From an examination of the code, the only place `AssetGroup` was used in
an internal pathway was during workspace construction. When examining a
Python module, if no job/pipeline/definitions/repo was found, then all
assets would be scraped into a container `AssetGroup`. This just served
to bundle the assets for a short time, until they could be dumped into a
list of repository definitions when converting the loadable target to a
repository.

This PR dispenses with the container `AssetGroup` and just passes a list
containing all of the `AssetsDefinition` and `SourceAsset` objects in
its place. This required only a few adjustments, since none of the
functionality of `AssetGroup` is used anyway.

Aside from these functional changes, this also required updating some
toys and tests to use alternatives to `AssetGroup`, like `Definitions`.

## How I Tested These Changes

Existing test suite.

2023-03-19 16:16 UTC, smackesey commented
Current dependencies on/for this PR:
* master
  * **PR #13024** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13024" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #13025** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13025" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #13028** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13028" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/13028?utm_source=stack-comment).

2023-03-20 15:31 UTC, sryza requested changes
Very in favor of deleting AssetGroup, but I think many of the tests in test_asset_group, etc. are the only tests that cover some important code paths.

I've been chipping away at migrating these tests elsewhere.  E.g. I merged this: https://github.com/dagster-io/dagster/pull/12606.

And I've been working on a PR that migrates most of the rest of them: https://github.com/dagster-io/dagster/pull/13033.

2023-03-20 15:42 UTC, smackesey commented
>And I've been working on a PR that migrates most of the rest of them

Nice-- how should we proceed then? Just leave this open until you migrate them all in that PR? Or would it be easier to merge that PR as-is and migrate the rest of them in this one?

2023-04-19 18:56 UTC, smackesey commented
@sryza Any more progress on that other PR or can it be merged and the rest of the tests ported in this one? I'm thinking this would be nice to merge together with the `PipelineDefinition/`ModeDefinition`/`PresetDefinition` deletion.

2023-04-21 14:25 UTC, smackesey commented
>I think the path forward requires handling all the remaining tests in test_asset_group.py - i.e. by migrating them to not use AssetGroup or by confirming that they're handled by existing tests.

OK-- what if you you remove the few (small) modifications to non-test-code in the other PR and land the test port that you have, then I'll just port the rest of them here-- it looks like there's only a few left.

2023-04-23 23:38 UTC, sryza commented on python_modules/dagster/dagster_tests/asset_defs_tests/test_assets_job.py
> +# asset_definitions = Definitions(
stray comment

2023-04-23 23:38 UTC, sryza commented on python_modules/dagster/dagster_tests/asset_defs_tests/test_assets_job.py
> +    assert (
I think it's better to use `materialize_to_memory` here and in similar situations

2023-04-24 21:12 UTC, smackesey commented on python_modules/dagster/dagster_tests/asset_defs_tests/test_assets_job.py
> +# asset_definitions = Definitions(
good catch

2023-04-24 21:21 UTC, sryza commented on python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py
> +        # assert events[0].get_dagster_event().asset_key == AssetKey("foo")
Comments

2023-04-25 13:43 UTC, smackesey commented on python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_assets.py
> +        # assert events[0].get_dagster_event().asset_key == AssetKey("foo")
fixed

2023-04-25 15:34 UTC, sryza approved these changes

2023-04-26 00:06 UTC, sryza reviewed
I noticed that this does not remove asset_group.py. Should it?

2023-04-26 00:55 UTC, merged