Add a cancellation reason when a run is canceled
dagster-io/dagster pull request #13072
Opened 2023-03-21 23:57 UTC by dpeng817

## Summary & Motivation

## How I Tested These Changes

2023-03-21 23:58 UTC, dpeng817 commented
Current dependencies on/for this PR:
* master
  * **PR #12920** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12920" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #13072** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13072" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/13072?utm_source=stack-comment).

2023-04-03 21:03 UTC, gibsondan requested changes
what if we kept moving things up the chain and moved the report_run_canceling call into the callsite here as well? I think there is exactly one callsite in graphql, could we emit it in that callsite?

2023-04-03 21:03 UTC, gibsondan commented on python_modules/dagster/dagster/_core/run_coordinator/base.py
> +    def cancel_run(self, run_id, cancelation_source):
technically run coordinators are user-pluggable so we will want to default this to None to make this not a breaking change

2023-04-03 21:03 UTC, gibsondan commented on python_modules/libraries/dagster-aws/dagster_aws/ecs/launcher.py
> -        self._instance.report_run_canceling(run, message=message)
does this belong on the other PR?

2023-04-04 23:53 UTC, dpeng817 commented
Removing this in favor of having long-running run termination just mark the run as failed

2023-04-04 23:53 UTC, closed without merging