[dagit] redirect trailing slash on GraphQL route
dagster-io/dagster pull request #13181
Opened 2023-03-27 19:36 UTC by benpankow

## Summary

Adds a redirect from the graphql URL with a trailing slash: `localhost:3000/graphql/`->`localhost:3000/graphql`. A user recently ran into this: https://elementl-workspace.slack.com/archives/C046ZK3KQ5D/p1679944131264839?thread_ts=1679942695.590929&cid=C046ZK3KQ5D

2023-03-27 19:36 UTC, benpankow commented
Current dependencies on/for this PR:
* master
  * **PR #13181** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13181" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/13181?utm_source=stack-comment).

2023-03-28 01:09 UTC, brad-alexander commented
A compelling reason to omit the redirect (or make it optional) would be to prevent accidental performance issues.  It looks like even if you use sessions in `requests`, it does not remember 307 or even 308 responses, and will always make two roundtrips for every request.  This probably wouldn't be much of a hit if the server is on the same network, but if the server is under significant load, or over slow WAN/VPN it could be significant overhead - especially if it is a large POST request.

2023-03-28 15:43 UTC, alangenfeld commented
should we take an approach similar to what we did here and just dupe the routes instead 
https://github.com/dagster-io/internal/pull/876/files

2023-03-28 15:44 UTC, alangenfeld requested changes
to your queue

2023-03-28 16:18 UTC, alangenfeld commented
related https://github.com/encode/starlette/issues/869 though that doesn't necessarily help much

2024-12-10 23:38 UTC, closed without merging