[docs] test
dagster-io/dagster pull request #13211
Opened 2023-03-28 23:26 UTC by benpankow

## Summary & Motivation

## How I Tested These Changes

2023-03-28 23:26 UTC, benpankow commented
Current dependencies on/for this PR:
* master
  * **PR #13211** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13211" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/13211?utm_source=stack-comment).

2023-03-29 16:16 UTC, prha commented
Can you check this against non-mdx docs changes?

2023-03-29 17:47 UTC, prha requested changes
make sure to

2023-03-29 17:47 UTC, prha commented on .github/workflows/build-docs.yml
> -  push:
I think we still want to build on landing to master... I believe this is important with how the docs push is run.

Why are we changing the path filter?

2023-03-29 17:48 UTC, prha requested changes
I think we still want to build on landing to master... I believe this is important with how the docs push is run.

Why are we changing the path filter?

2023-03-29 18:13 UTC, benpankow commented
> I think we still want to build on landing to master... I believe this is important with how the docs push is run.
> 
> Why are we changing the path filter?

This was just to get it to run for the sake of testing. Will switch back before merging 👍

2023-03-29 19:03 UTC, merged