[resource verification][2b/n] Implement GRPC call for ConfigVerifiable checks using tick abstraction
dagster-io/dagster pull request #13332
Opened 2023-04-03 16:52 UTC by benpankow

## Summary & Motivation

## How I Tested These Changes

2023-04-03 16:52 UTC, benpankow commented
Current dependencies on/for this PR:
* master
  * **PR #12728** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12728" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #12729** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12729" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #12832** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12832" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #12833** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/12833" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #13007** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13007" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #13008** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13008" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
              * **PR #13048** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13048" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                * **PR #13049** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13049" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                  * **PR #13051** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13051" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                    * **PR #13067** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13067" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                    * **PR #13104** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13104" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                      * **PR #13332** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13332" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈
                      * **PR #13105** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13105" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                        * **PR #13106** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13106" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
                          * **PR #13107** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13107" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/13332?utm_source=stack-comment).

2023-04-03 16:58 UTC, benpankow commented on python_modules/dagster/dagster/_core/host_representation/code_location.py
> +                result = self.client.resource_verification(
This uses a direct GRPC call vs a yield like the other instigator invocations, not sure if that needs to be changed.

2023-04-03 17:00 UTC, benpankow commented on python_modules/dagster/dagster/_core/host_representation/code_location.py
> +                        raise Exception(
We also don't have a mechanism to (non-manually) retry here - unable to reach user code server becomes a failure.

2023-04-04 15:06 UTC, schrockn requested changes
moving to your queue pending discussion about this workstream

2023-04-12 21:29 UTC, closed without merging