[pythonic resources] Error early if a user annotates a param with a ConfigResourceFactory or bare ResourceDef
dagster-io/dagster pull request #13395
Opened 2023-04-05 19:04 UTC by benpankow

## Summary

Throws an error early if the user annotates an op, asset, schedule, or sensor function param with a `ConfigurableResourceFactory` or bare `ResourceDefinition` that is not a `ConfigurableResource`, e.g.

```python
class MyFactory(ConfigurableResourceFactory[str]):
    ...

# should be my_resource: Resource[str]!

@op
def my_op(my_resource: MyFactory):
    ...
```

## Test PLan

unit tests

2023-04-05 19:04 UTC, benpankow commented
Current dependencies on/for this PR:
* master
  * **PR #13376** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13376" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #13377** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13377" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #13395** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13395" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/13395?utm_source=stack-comment).

2023-04-05 19:15 UTC, schrockn approved these changes
cool

2023-04-05 19:20 UTC, schrockn requested changes
wait a sec there was an change submitted while i reviewed

2023-04-05 19:29 UTC, schrockn requested changes
So I generally think that boolean flags like this should be avoided. This leads future users of `get_resource_args` to ask: should I error aggressively? Why would I not check errors? Etc etc. In this case my interpretation is that you can only setting `err_aggressively=True` near entry points.

Instead I would recommend having a separate function (`validate_resource_annotatable_function` ?)  that does this type of error checking, and do it ASAP (e.g in the relevant `__init__` or immediately after the user passes the `fn` to the framework) and leave `get_resource_args` unmodified  Alternatively a separate function which does this more extensive error checking and then in turn calls `get_resource_args` that is named appropriately.

That you have to do all those dynamic imports is another "smell" that indicates that you might be jamming higher level logic into a lower layer piece of code.

2023-04-05 20:17 UTC, schrockn approved these changes

2023-04-07 13:58 UTC, schrockn approved these changes

2023-04-07 13:58 UTC, schrockn commented on python_modules/dagster/dagster/_core/definitions/resource_annotation.py
> +
consider moving this function to `structured_config` given the all the dynamic imports

2023-04-07 20:53 UTC, merged