[pythonic resources] Add from_resource_context utility
dagster-io/dagster pull request #13403
Opened 2023-04-05 22:32 UTC by benpankow

## Summary

Adds a small utility which helps building resources from `ConfigurableResourceFactory` classes by taking an init context and returning the output resource value.

Based on discussion in https://github.com/dagster-io/dagster/pull/12978#discussion_r1159066432

## Test Plan

Small unit test.

2023-04-05 22:32 UTC, benpankow commented
Current dependencies on/for this PR:
* master
  * **PR #13403** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13403" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/13403?utm_source=stack-comment).

2023-04-05 22:38 UTC, schrockn requested changes
have the test and the docstring use `infer_schema_from_config_class`

2023-04-05 22:40 UTC, benpankow commented on python_modules/dagster/dagster/_config/structured_config/__init__.py
> +            @resource(config_schema={"my_str": str})
Should we expose `infer_schema_from_config_class` at the top level (e.g. `dagster. infer_schema_from_config_class`)? right now it's just an internal utility

2023-04-05 22:52 UTC, schrockn commented on python_modules/dagster/dagster/_config/structured_config/__init__.py
> +            @resource(config_schema={"my_str": str})
`@classmethod` on `Config`?

2023-04-05 23:05 UTC, benpankow commented on python_modules/dagster/dagster/_config/structured_config/__init__.py
> +            @resource(config_schema={"my_str": str})
seems reasonable, updated

2023-04-05 23:20 UTC, schrockn commented on python_modules/dagster/dagster/_config/structured_config/__init__.py
> +
how about `to_config_schema` and have it return `DefinitionConfigSchema`? That would prevent possible confusion with pydantic.Field

2023-04-05 23:20 UTC, schrockn commented on python_modules/dagster/dagster/_config/structured_config/__init__.py
> +
that would also line up with `config_schema` kwarg on the `@resource` et al

2023-04-05 23:21 UTC, schrockn submitted a review, later dismissed
Per inline comments

2023-04-06 13:13 UTC, schrockn approved these changes
great. please heed final comment!

2023-04-06 13:13 UTC, schrockn commented on python_modules/dagster/dagster/_config/structured_config/__init__.py
> +            @resource(config_schema={"my_str": str})
Please update to `@resource(config_schema=MyResource.to_config_schema())`

2023-04-06 17:26 UTC, merged