[pythonic config] Better direct invocation experience with config
dagster-io/dagster pull request #13459
Opened 2023-04-09 00:57 UTC by benpankow

## Summary

Now, ops and assets which use config  can specify that config as `args` or `kwargs` (previously this only worked through context)

For example, the following are all valid ways to invoke this op:

```
class MyConfig(Config):
    z: int

@op
def my_op(context, x: int, y: int, config: MyConfig):
    return x + y + config.z

# pass config as arg
my_op(build_op_context(), 1, 2, MyConfig(z=3))

# pass config as kwarg
my_op(build_op_context(), 1, 2, config=MyConfig(z=3))

# pass config through context (no arg/kwarg)
my_op(build_op_context(config={"z": 3}), 1, 2)
```

## Test Plan

A few new tests.

2023-04-09 00:57 UTC, benpankow commented
Current dependencies on/for this PR:
* master
  * **PR #13456** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13456" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #13459** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13459" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/13459?utm_source=stack-comment).

2023-04-09 19:29 UTC, schrockn requested changes
Just requesting changes because the PR it is stack on will change substantially

2023-04-11 14:08 UTC, schrockn approved these changes
great. please heed final nits

2023-04-11 14:08 UTC, schrockn commented on python_modules/dagster/dagster/_core/definitions/op_invocation.py
> +    config_input: Any
`config_arg`

2023-04-11 14:08 UTC, schrockn commented on python_modules/dagster/dagster/_core/definitions/op_invocation.py
> +        if k not in resource_inputs_from_args_and_kwargs and k != "config"
with our new understanding of the definition or the word resource I think we can safely rename this to `resources_from_args_and_kwargs`. Alternatively `resources_by_param_name`

2023-04-11 14:08 UTC, schrockn commented on python_modules/dagster/dagster/_core/definitions/op_invocation.py
> +        context = context.replace_config(config_input)
might be nice to inline the instance of check to avoid rewriting `config_arg`/`config_input`

2023-04-11 21:34 UTC, merged