[pythonic config] Update cached_method field-setting logic
dagster-io/dagster pull request #13522
Opened 2023-04-11 20:39 UTC by benpankow

## Summary

Updates the `@cached_method` caching logic to save in a more specifically named field `field.__name__ + 'cached_method_cache'`. The Pythonic config setter logic is updated to use this more specific suffix, to reduce the chance of it colliding with a user-created field.

2023-04-11 20:39 UTC, benpankow commented
Current dependencies on/for this PR:
* master
  * **PR #13522** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13522" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/13522?utm_source=stack-comment).

2023-04-12 21:05 UTC, schrockn requested changes

2023-04-12 21:05 UTC, schrockn commented on python_modules/dagster/dagster/_utils/cached_method.py
> +CACHED_METHOD_FIELD_SUFFIX = "_cached_method_cache"
let's add a couple underscores just to make sure it doesn't conflict with legitimate user-provided name

2023-04-12 21:06 UTC, schrockn commented on python_modules/dagster/dagster/_utils/cached_method.py
> +CACHED_METHOD_FIELD_SUFFIX = "_cached_method_cache"
Let's add `"__internal__"`

2023-04-12 21:58 UTC, schrockn approved these changes
per discussion let's get this landed

2023-04-12 21:58 UTC, merged

2023-04-12 21:58 UTC, schrockn commented
I'm going to stack https://github.com/dagster-io/dagster/pull/13581 on top of this