[examples] Move Pythonic config/resources project_fully_featured port to replace base one"
dagster-io/dagster pull request #13603
Opened 2023-04-13 17:14 UTC by benpankow

## Summary

Moves the experimental port of `project_fully_featured` over to the main copy.

## Test Plan

Existing unit tests.

2023-04-13 17:14 UTC, benpankow commented
Current dependencies on/for this PR:
* master
  * **PR #13603** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13603" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/13603?utm_source=stack-comment).

2023-04-17 19:43 UTC, schrockn commented
For ease of review could you delete the experimental version in a separate PR? With a clean PR we could also point people to it for an example of a conversion PR.

2023-04-17 23:59 UTC, schrockn requested changes
Back to your queue. Make deletion of experimental separate PR

2023-04-19 00:40 UTC, schrockn approved these changes

2023-04-19 02:40 UTC, merged