[pythonic config] Update testing concepts page
dagster-io/dagster pull request #13664
Opened 2023-04-14 23:06 UTC by benpankow

## Summary & Motivation

## How I Tested These Changes

2023-04-14 23:07 UTC, benpankow commented
Current dependencies on/for this PR:
* master
  * **PR #13663** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13663" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #13664** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13664" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/13664?utm_source=stack-comment).

2023-04-17 20:41 UTC, yuhan approved these changes

2023-04-17 20:41 UTC, yuhan commented on docs/content/concepts/testing.mdx
> +Finally, if your op relies on context, you can build and pass a context. The following op uses the context logger:
```suggestion
Finally, if your op relies on op context, you can build and pass a context. The following op uses the context logger:
```
nit: to make it clear it's op context not resource context

2023-04-17 23:44 UTC, schrockn requested changes
I think it is important to have one example of a resource with a `get_client` method and how we recommend doing that with a mock

2023-04-18 12:59 UTC, schrockn approved these changes

2023-04-18 16:16 UTC, merged