[pythonic config] Add ability to create int EnvVars
dagster-io/dagster pull request #13681
Opened 2023-04-17 16:05 UTC by benpankow

## Summary

Introduces a way to use `EnvVar` values with int fields:

```python
class MyIntConfig(Config):
  an_int: int

MyIntConfig(an_int=EnvVar.int("AN_INT_ENV"))
```

## Test Plan

New unit tests.

2023-04-17 16:05 UTC, benpankow commented
Current dependencies on/for this PR:
* master
  * **PR #13681** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13681" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/13681?utm_source=stack-comment).

2023-04-17 16:15 UTC, schrockn requested changes
float in sep diff?

2023-04-17 16:31 UTC, benpankow commented
ah yup, left that in by mistake - updated

2023-04-18 12:36 UTC, schrockn approved these changes
👍🏻

2023-04-18 12:39 UTC, schrockn commented
FWIW adding float source should be relatively straightforward. You can mimic the other implementations in python_modules/dagster/dagster/_config/source.py

2023-04-18 16:13 UTC, merged