[docs] [resources-config-overhaul] - Update Job Execution Concept page
dagster-io/dagster pull request #13704
Opened 2023-04-17 22:36 UTC by yuhan

## Summary & Motivation
update execution config. but i think we also need to expose something like `MultiprocessConfig`

## How I Tested These Changes

2023-04-17 22:36 UTC, yuhan commented
Current dependencies on/for this PR:
* master
  * **PR #13704** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13704" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/13704?utm_source=stack-comment).

2023-04-18 00:33 UTC, schrockn requested changes
I think we should wait to land until we can type this whole thing with `DefaultExecutorConfig`

2023-04-18 00:33 UTC, schrockn commented on docs/content/concepts/ops-jobs-graphs/job-execution.mdx
>              }
@benpankow  we should be able to support strongly typed config on executors

2023-04-18 17:15 UTC, erinkcochran87 commented on docs/content/guides/limiting-concurrency-in-data-pipelines.mdx
> +                    "max_concurrent": 0,
Same comment here as on job execution - this change puts the example at odds with the paragraph that comes before it.

2024-05-02 23:32 UTC, yuhan commented
closing - too old to pick up. will start a new branch

2024-05-02 23:32 UTC, closed without merging