Add monitoring daemon hooks to free concurrency slots for canceled runs
dagster-io/dagster pull request #13772
Opened 2023-04-19 17:51 UTC by prha

## Summary & Motivation
Canceled runs may retain concurrency slots

## How I Tested These Changes
BK

2023-04-19 17:51 UTC, prha commented
Current dependencies on/for this PR:
* master
  * **PR #13769** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13769" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #13770** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13770" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #13771** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13771" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #13772** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13772" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/13772?utm_source=stack-comment).

2023-04-19 17:51 UTC, prha commented
Current dependencies on/for this PR:
* master
  * **PR #13769** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13769" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #13770** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13770" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #13771** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13771" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #13772** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13772" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/13772?utm_source=stack-comment).

2023-05-11 20:26 UTC, alangenfeld reviewed
we certainly want to do this for failure as well since there may be not graceful clean-up then

may need to have a buffer of time between run cancel/fail before the slots are free in cases where the underlying computation is still going. Imagine a k8s run pod termination but the the step pod is still going using the resource 

may want to have a daemon query for slots acquired more than TIMEOUT ago and check the run status and then free

2023-05-11 21:26 UTC, prha commented
> may want to have a daemon query for slots acquired more than TIMEOUT ago and check the run status and then free

Oh that's a good idea!  I've had it in the back of my mind that I need to figure out how to implement this.

2023-05-12 15:31 UTC, alangenfeld requested changes
to you

2023-05-25 16:48 UTC, schrockn requested changes

2023-05-25 16:48 UTC, schrockn commented on python_modules/dagster/dagster/_daemon/monitoring/monitoring_daemon.py
> +                monitor_canceled_run(instance, run_record, logger)
I don't see how we will ever see runs with this status given that 

`statuses=IN_PROGRESS_RUN_STATUSES + [DagsterRunStatus.CANCELING]`

on line 187 does not include `CANCELED`

2023-06-05 00:26 UTC, merged