Add CLI methods for managing instance-wide concurrency limits
dagster-io/dagster pull request #13771
Opened 2023-04-19 17:50 UTC by prha

## Summary & Motivation
Adds CLI interface for getting/setting concurrency limits

## How I Tested These Changes
BK

2023-04-19 17:51 UTC, prha commented
Current dependencies on/for this PR:
* master
  * **PR #13769** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13769" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #13770** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13770" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #13771** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13771" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/13771?utm_source=stack-comment).

2023-05-11 20:22 UTC, alangenfeld reviewed
you have sample output to add to the PR summary/test?

2023-05-11 20:22 UTC, alangenfeld commented on python_modules/dagster/dagster/_cli/instance.py
> +        if kwargs.get("all"):
why kwargs?

2023-05-12 14:32 UTC, alangenfeld requested changes
this one is real close - bouncing for queue management

2023-05-22 18:48 UTC, alangenfeld approved these changes

2023-06-06 18:01 UTC, merged