Add partition_key field to RunStatusSensorContext
dagster-io/dagster pull request #13811
Opened 2023-04-20 18:24 UTC by pdstrnadJC

## Summary & Motivation
Follow up from discussion here: https://github.com/dagster-io/dagster/discussions/13283

This is a very minor change to expose the partition as a top level field in `RunStatusSensorContext`. Previously this information was only available by checking the tags that are available on the `DagsterRun` object within the `RunStatusSensorContext`.

## How I Tested These Changes
Updated unit tests with a scenario that covers the case when a run status sensor is defined on a partitioned job.

2023-04-20 19:48 UTC, tacastillo commented
Thanks for raising this! I appreciate the effort you put into it. Based on the Discussion you linked, I think @sryza said he could review or find someone that can review.

2023-04-20 22:05 UTC, sryza requested changes
Thanks for this PR @pdstrnadJC!

A few issues came up in the build. There was a test failure that seems like it might be related:
```
[2023-04-20T20:57:31Z] dagster_tests/daemon_sensor_tests/test_pythonic_resources.py::test_resources_run_status_sensor[sensor_run_status_with_cm] FAILED [ 26%]
```

Also, are you able to run `make black` and `make ruff` for autoformatting and linting?

2023-04-20 22:31 UTC, pdstrnadJC commented
Taking a look at that test failure (also, I just pushed commit with black and ruff changes)

2023-04-21 17:29 UTC, pdstrnadJC commented
Sorry, I hadn't run all tests in daemon_sensor_tests - they run fine now.

2023-04-21 18:31 UTC, pdstrnadJC commented
Still failing - I'm going to run all tests locally

2023-04-21 18:44 UTC, sryza approved these changes
@pdstrnadJC the failure is unrelated. I'm going to merge this. Thanks for the contribution!

2023-04-21 18:44 UTC, merged