Better error handling for serdes failures during grpc calls
dagster-io/dagster pull request #13886
Opened 2023-04-25 14:47 UTC by gibsondan

Summary:
In a few different api calls here we were try catching the inner impl method, but not catching the exception and serializing it up if there was an error during the resulting serialize_value call itself. Add some additional try/catch wrappers for that.

## Summary & Motivation

## How I Tested These Changes

2023-04-25 15:01 UTC, alangenfeld requested changes

2023-04-25 15:01 UTC, alangenfeld commented on python_modules/dagster/dagster/_grpc/server.py
> +        try:
^ [1]

2023-04-25 15:02 UTC, alangenfeld commented on python_modules/dagster/dagster/_grpc/server.py
> +            serialized_response = serialize_value(
I think the consistent pattern is a good argument for sticking with the try / catch blocks

2023-04-25 15:04 UTC, alangenfeld commented
thoughts on testing for this? its certainly possible to have tests for all the errors but not sure how much work that would take

2023-04-25 15:06 UTC, gibsondan commented
yeah i have some sneaky tests in mind

On Tue, Apr 25, 2023 at 10:04 AM Alex Langenfeld ***@***.***>
wrote:

> thoughts on testing for this? its certainly possible to have tests for all
> the errors but not sure how much work that would take
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dagster-io/dagster/pull/13886#issuecomment-1521952799>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACAPJC67H6TEDIYIX56CMXDXC7RXPANCNFSM6AAAAAAXLDYVRM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-04-25 15:15 UTC, gibsondan commented on python_modules/dagster/dagster/_grpc/server.py
> +            serialized_response = serialize_value(
yeah i kinda just wanna maintain the invariant that if anything throws, even if surprising or unexpected, we get a stack trace over the wire

2023-04-27 20:06 UTC, alangenfeld approved these changes
nice

2023-04-28 14:25 UTC, merged