[dagster-mlflow] Update to use Pythonic resources
dagster-io/dagster pull request #13897
Opened 2023-04-25 21:16 UTC by benpankow

## Summary & Motivation

## How I Tested These Changes

2023-04-25 21:16 UTC, benpankow commented
Current dependencies on/for this PR:
* master
  * **PR #13897** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/13897" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/13897?utm_source=stack-comment).

2023-05-26 14:09 UTC, schrockn requested changes
Inline changes

2023-05-26 14:09 UTC, schrockn commented on python_modules/libraries/dagster-mlflow/dagster_mlflow/resources.py
> +from pydantic import Field as PyField
I think we not alias pydantic.Field and alias dagster.Field if we need both

2023-05-26 14:09 UTC, schrockn commented on python_modules/libraries/dagster-mlflow/dagster_mlflow/resources.py
> +        client.cleanup_on_error()
`cleanup_on_error` should be in a finally block.

Also in terms of naming convention, what would you think about `open_tracking_client` to indicate that it is a context manager?

2024-09-30 19:59 UTC, closed without merging

2024-12-03 10:56 UTC, cameronUJ commented
Is there any update on the progress of updating this integration @benpankow? I can see this MR was closed, is this because you are taking a different approach?