[pythonic resources] Support setting fixed/secret values at Definitions-time
dagster-io/dagster pull request #14044
Opened 2023-05-02 00:42 UTC by benpankow

## Summary

Introduces a pattern for setting secret values on a ConfigurableResource. The new `FixedConfig` function wraps a config value (or env var) and ensures that the value will not show up in the resources UI and cannot be overridden in the launchpad.

## Test Plan

A few unit tests, snapshot test ensuring resource snap doesn't include the value.

2023-05-02 00:42 UTC, benpankow commented
Current dependencies on/for this PR:
* master
  * **PR #14039** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/14039" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #14040** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/14040" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #14042** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/14042" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #14044** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/14044" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/14044?utm_source=stack-comment).

2023-05-02 18:42 UTC, benpankow commented on python_modules/dagster/dagster/_config/pythonic_config/__init__.py
> +def FixedConfig(value: C) -> C:
This is pretty hacky and I'm pretty hesitant to ship something like this. There may be a better way to handle this (or just return `Any`) that will not cause type issues.

2023-05-03 20:52 UTC, schrockn commented
Is there a solution that does not involve us adding another concept? Could we instead direct users to override init and set a `PrivateAttr` or something?

2023-05-03 20:52 UTC, schrockn requested changes
Asking question about whether we need this at all. See comment.

2023-05-03 21:49 UTC, benpankow commented
> Is there a solution that does not involve us adding another concept? Could we instead direct users to override init and set a `PrivateAttr` or something?

I think we could support this on the resource definition side by allowing users to somehow annotate a parameter as secret.

I do think this PR handles a slightly different case - because the fixed/secret values are specified by the passed config rather than the resource definition I think this is a bit more broadly useful - e.g. defining a SnowflakeResource which has fixed config that can't be changed in the launchpad except for the schema. 


```python

defs = Definitions(
    ...
    resources={
        "snowflake": SnowflakeResource(
            schema="my_default_overridable_schema",
            username=FixedConfig("user"),
            password=FixedConfig(password),
            account=FixedConfig("na1234"),
        )
    )
)

2023-05-03 23:49 UTC, schrockn commented
I see. `FixedConfig` definitely seems a bit odd to me. And I don't think we should use the word "secret" here anywhere because that is subtley. Maybe "HiddenConfig" or "ErasedConfig"

2023-05-05 16:39 UTC, benpankow commented
Here `Fixed` was meant to indicate that the config can't be changed or overridden in the launchpad. Maybe `ImmutableConfig`?

Stepping back I think there are a few possible patterns we could use to address (secret/fixed config), which are related but separate concerns:

1. Wrapping config value in an indicator, which is encompassed in this PR. The benefits of this approach is that we can decide on a subset of values to fix & hide form the UI. This does bunch together "hiding config" and "fixing config" when a user might only want to do one or the other. There's a world in which we ship two indicators.

  ```python
  class MyResource(ConfigurableResource):
    username: str
    password: str = Field(is_secret=True)
  ```

2. Applying a secret indicator to the resource definition itself, as discussed above. This is useful for cases where we know particular config values will be secret and want to systemically hide them in the UI. This arises in #14114. This does not handle the case of users wanting to make secret values fixed/unable to be overridden.

  ```python
  class MyResource(ConfigurableResource):
    username: str
    password: str
  
  MyResource(username=ImmutableConfig("foo"), password=HiddenConfig("bar"))
  ```

4. Using a special method to configure fixed or secret config, rather than the constructor. This loses out on the ergonomics of the typed constructor for our config/resource classes.
  ```python
  class MyResource(ConfigurableResource):
    username: str
    password: str
  
  # one way to model the method
  MyResource(...).with_immutable("password")```

There might be some combination of the above that feels best (e.g. wrapper for fixed, definition-sided indicator for secrets?)

2023-05-05 17:44 UTC, schrockn commented
```
class AResource2(ConfigurableResource):
    number: int
    _private_thing: str = PrivateAttr("private")
a_resource_2 = AResource2(_private_thing="foo", number=1)
print(a_resource_2._private_thing)
print(a_resource_2._convert_to_config_dictionary())
```

Let's see if we use vanilla `PrivateAttr`

2025-02-13 22:23 UTC, closed without merging