Custom Op name for load_assets_from_dbt_*
dagster-io/dagster pull request #14190
Opened 2023-05-09 18:11 UTC by wkeifenheim

## Summary & Motivation
See issue  #13873

This PR does not include capturing other CLI parameters  [`profile`, `target`, `vars`] towards dynamically generating op names.

## How I Tested These Changes
The `test_op_custom_name` test builds two asset collections from dbt, each with a different target, and no other differences (of dbt config). Loading from the different manifests while (distinctly) setting the new `op_name` parameter yields `op` names that do not collide.

_Example of one custom op name from the dbt load, within the `AssetsDefintion` object_
![image](https://github.com/dagster-io/dagster/assets/639361/895c9221-ce5e-4806-b676-e755e65a5576)

I have also manually tested this by modifying the `assets_dbt_python` example to load multiple asset groups of the dbt project. Each group targets a different database destination, and in this example consume from a common source. The multiple instances of the dbt project worked as intended. Without the custom `op_name` field we would fail once the different dbt asset groups are added to `Definitions`.
![image](https://github.com/dagster-io/dagster/assets/639361/808201d6-2154-4674-8252-63de898dc9a6)

2023-05-09 18:34 UTC, smackesey commented
cc @OwenKephart

2023-05-09 21:20 UTC, OwenKephart requested changes
thanks for making this change! everything code-wise seems good to me, but had some comments around simplifying the test code / formatting.

also, make sure to run `make black` at the root of the repo before committing.

2023-05-09 21:20 UTC, OwenKephart commented on python_modules/libraries/dagster-dbt/dagster_dbt_tests/test_asset_defs.py
> +def test_op_custom_name(instances, test_project_dir, dbt_config_dir, dbt_target_dir):
I think this test could be simplified a ton, just by having all of the load_assets_from_dbt_manifest calls share the same manifest.json file (sample_manifest.json would work).

as long as the keys are distinct (which is handled by the key_prefix already), the actual contents of the manifest shouldn't matter for the purposes of this test.

also, as there's technically only one set of instances, we can probably skip parameterizing the test and just hard-code those in.

2023-05-09 21:20 UTC, OwenKephart commented on python_modules/libraries/dagster-dbt/dagster_dbt_tests/test_asset_defs.py
> +    assert len(op_names) == len(set(op_names)),\
a bit of a nitpick, but would prefer multi-line strings to be in this format:

```
assert len(op_names) == len(set(op_names)), (
    f"Multiple instances of a dbt project cannot have the same op name.\n"
    f"dbt targets were: {instances}\n"
    f"op names generated were: {op_names}"
)
```

2023-05-10 16:27 UTC, OwenKephart approved these changes
Thanks again for the contribution! Merging this in now, and it'll be in next week's release

2023-05-10 16:28 UTC, merged