[pythonic resources][rfc] Adjust EnvVar behavior to explicitly disallow direct usage
dagster-io/dagster pull request #14490
Opened 2023-05-26 11:44 UTC by benpankow

## Summary

Alternative RFC to #14488. Keeps `EnvVar` as a direct subclass of `str` but errors on resolving the value via `__str__` to explicitly prevent users from using `EnvVar` outside of resource/config contexts. Right now we're sort of in the worst of both worlds where a user can use an `EnvVar` in inapproporiate places and they get an odd result.

## Test Plan

Small unit test, existing unit tests. Will expand suite if this is a direction we want to go.

2023-05-26 11:44 UTC, benpankow commented
Current dependencies on/for this PR:
* master
  * **PR #14490** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/14490" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/14490?utm_source=stack-comment).

2023-05-26 13:42 UTC, schrockn commented
This one seems better to me. We could also offer a method to access the underlying value so that users won't have to import `os` if they find that annoying.

2023-09-29 18:43 UTC, schrockn commented on python_modules/dagster/dagster/_config/field_utils.py
> +            " IntEnvVar should only be used as input to Dagster config or resources."
Add:

"If you want to access the environment variable directly, you can call `get_value` on this object, or `os.getenv` directly"

2023-09-29 18:45 UTC, schrockn requested changes
Let's do a turn on the error messaging, which is the most important part of this PR.

2023-09-29 18:45 UTC, schrockn commented on python_modules/dagster/dagster/_config/field_utils.py
> +        )
Same here.

2023-09-29 18:45 UTC, schrockn commented on python_modules/dagster/dagster/_config/field_utils.py
> +            " IntEnvVar should only be used as input to Dagster config or resources."
We could also save.

"The purpose of `EnvVar` is to defer retrieval to right before the step is executed, and to be viewable in the UI"

2023-09-29 23:37 UTC, benpankow commented
Updated copy 👍

2023-09-30 08:08 UTC, schrockn approved these changes
Great. Consider a common function to share between two callsites to generate error string.

2023-09-30 08:08 UTC, schrockn commented on python_modules/dagster/dagster/_config/field_utils.py
> +            " EnvVar defers resolution of the env var value until run time, and should only be"
spell out "environment variable" instead of "env var"

2023-09-30 19:01 UTC, merged