Fix test case with no assert
dagster-io/dagster pull request #14522
Opened 2023-05-30 14:50 UTC by johannkm

## Summary & Motivation

## How I Tested These Changes

2023-05-30 14:50 UTC, johannkm commented
Current dependencies on/for this PR:
* master
  * **PR #14522** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/14522" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/14522?utm_source=stack-comment).

2023-06-01 05:42 UTC, prha commented
Maybe we should just delete this test... the mock isn't going to work in cloud.

2023-06-01 05:43 UTC, prha requested changes
to your queue... can also commandeer if you prefer

2023-06-01 15:56 UTC, prha approved these changes

2023-06-01 18:04 UTC, merged