makes the schedule execution independent from tick history
dagster-io/dagster pull request #14555
Opened 2023-05-31 21:38 UTC by prha

## Summary & Motivation
With the monthly schedules and a 30-day purge window, we can run into an issue where schedules will repeatedly try to kick off duplicate runs because they are trying to read from the tick history.

This diff adds the last tick into the schedule state, to prevent from this dependency on the tick history being maintained.

(keeping a sensible tick history for observability on these sparse schedules is a separate issue to be tackled in a different PR).

## How I Tested These Changes
BK

2023-06-01 04:17 UTC, prha commented
Current dependencies on/for this PR:
* master
  * **PR #14555** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/14555" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈
    * **PR #14561** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/14561" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/14555?utm_source=stack-comment).

2023-06-01 18:07 UTC, alangenfeld reviewed
i think this is fine - would like @gibsondan to view as well

2023-06-01 18:32 UTC, gibsondan reviewed
"(keeping a sensible tick history for observability on these sparse schedules is a separate issue to be tackled in a different PR)."

If the solution (which as i understand it would be to always keep the last N ticks) fixes both problems, are we sure it's a separate issue? Wouldn't that fix this problem too with no additional changes required?

2023-06-02 14:23 UTC, gibsondan requested changes
to you for that question - just making sure we actually need this if we think we are likely to do the other thing

2023-08-03 22:03 UTC, closed without merging