[pythonic config] Add support for Pythonic config classes to @configured
dagster-io/dagster pull request #14624
Opened 2023-06-05 21:18 UTC by benpankow

## Summary

Adds support for taking in and returning Pythonic config classes with the `@configured` decorator. This is useful for wrapping ops with lots of config options.

```python

class MyComplexOpConfig(Config):
  a_bool: bool
  an_int: int
  a_string: str

@op
def my_op(config: MyComplexOpConfig):
   ...

class MySimplifiedOpConfig(Config):
  an_int: int

@configured(my_op)
def my_simpler_op(config: MySimplifiedOpConfig):
  return MyComplexOpConfig(a_bool=True, a_string="foo", an_int=config.an_int)
```

## Test Plan

New unit tests, more forthcoming

2023-06-05 21:19 UTC, benpankow commented
Current dependencies on/for this PR:
* master
  * **PR #14624** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/14624" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/14624?utm_source=stack-comment).

2023-06-05 22:42 UTC, schrockn commented
How did this come up? User feedback?

2023-06-05 22:57 UTC, benpankow commented
> How did this come up? User feedback?

Yes, a user was interested in a pattern where they write a generic op with many config options and then construct a variety of `@configured` ops for use in jobs

2023-06-06 09:18 UTC, schrockn requested changes
Looks good overall. Let's update appropriate docblocks/docs in the same PR (or in a stack).

2023-06-06 09:18 UTC, schrockn commented on python_modules/dagster/dagster/_core/definitions/configurable.py
> +    if safe_is_subclass(param.annotation, Config):
prefer early return here too.

2023-06-08 12:46 UTC, schrockn approved these changes
Great 👍🏻

2023-06-08 16:46 UTC, merged