Initial commit on guide on computing with Dask on Dagster
dagster-io/dagster pull request #14798
Opened 2023-06-14 17:19 UTC by odette-elementl

## Summary & Motivation

## How I Tested These Changes

2023-06-21 14:34 UTC, sryza reviewed
I left a few comments - otherwise I think this looks good!

Can we make sure the code is tested?

2023-06-21 14:34 UTC, sryza commented on docs/content/guides/dagster/parallel-computing-dask.mdx
> +When using Dask with Dagster, you can use the `DaskResource` to set up a Dask client and simplify a pipeline that uses Dask across multiple assets. In this example, a local`dask.distributed` client i
Add space between "local" and "dask.distributed" I think.

2023-06-21 14:34 UTC, sryza commented on docs/content/guides/dagster/parallel-computing-dask.mdx
> +# isort: skip_file
I don't think we want this isort directive to show up in the example code. Do we need to skip import sorting?

2023-06-21 14:34 UTC, sryza commented on docs/content/guides/dagster/parallel-computing-dask.mdx
> +When using Dask with Dagster, you can use the `DaskResource` to set up a Dask client and simplify a pipeline that uses Dask across multiple assets. In this example, a local`dask.distributed` client i
> you can use the `DaskResource`

This makes it sound like Dagster provides its own `DaskResource`. I think something like "You can define a `DaskResource` to share Dask configuration across multiple assets" would be more accurate.

2023-06-21 14:34 UTC, sryza commented on docs/content/guides/dagster/parallel-computing-dask.mdx
> +The `dask.distributed.LocalCluster` API allows customization of the cluster, which can be leveraged through Dagster’s `resource`. In the following example, configuration is setup at the resource leve
I don't think "resource" should be monospaced,  because it doesn't correspond to a particular code symbol.

2023-06-21 14:34 UTC, sryza commented on docs/content/guides/dagster/parallel-computing-dask.mdx
> +def simple_dask_asset(context, MyDaskResource: DaskResource):
variable names should be lower case, maybe just `dask_resource` or `dask`

2023-06-21 14:34 UTC, sryza commented on docs/content/guides/dagster/parallel-computing-dask.mdx
> +def simple_dask_asset(context, MyDaskResource: DaskResource):
it looks like `context` isn't used, so best to just omit it

2023-06-21 14:34 UTC, sryza commented on docs/content/guides/dagster/parallel-computing-dask.mdx
> +def simple_dask_asset(context, MyDaskResource: DaskResource):
including a return type annotation would help make it clear what this function is doing

also, does our default IO manager work with dask dataframes?

2023-08-17 17:59 UTC, yuhan requested changes
queue management - we rolled out https://dagster.io/blog/dagster-dask, so maybe close this one?

2023-08-17 18:20 UTC, closed without merging