fix: Handle multi-dimensional partitions in W&B integration
dagster-io/dagster pull request #14823
Opened 2023-06-15 19:41 UTC by chrishiste

## Summary & Motivation
A client who uses the W&B integration contacted our customer support regarding an issue with Multi-Partitions.

Dagster, by default, adds a pipe (|) between partitions. However, W&B doesn't permit the usage of pipes in an Artifact name. To resolve this, the present Pull Request replaces all pipe characters with dashes.

## How I Tested These Changes
The modifications were tested and verified locally.

2023-06-15 20:17 UTC, OwenKephart requested changes
Thanks for looking into this! The change seems reasonable, mind just running `make black` at the top level to fix a formatting issue?

Edit: ah an also you'll need to cast the `artifact_name` to a str type to avoid any typing issues, as in theory the type system thinks it can be None at this point (make pyright)

2023-06-15 21:22 UTC, chrishiste commented
@OwenKephart Sorry about that and thanks for the tip. Should be all good now :)

2023-06-16 20:39 UTC, OwenKephart approved these changes
Thanks for the contribution!

2023-06-16 20:40 UTC, merged

2023-06-16 20:40 UTC, OwenKephart commented
Just merged this in, it'll go out in next week's release :)

2023-06-19 15:12 UTC, chrishiste commented
@OwenKephart Thanks a lot for the help :)