change default profiles dir in dbt examples
dagster-io/dagster pull request #15038
Opened 2023-06-29 20:50 UTC by sryza

This makes the examples cleaner, and also lets people run the dbt projects by just going into the project directories and running `dbt build` etc.

DbtCli will automatically look for the profiles.yml inside the root of the dbt projects.

2023-06-29 21:29 UTC, rexledesma requested changes
This will not work out of the box since `load_assets_from_dbt_project` needs to be compatible with `DbtCli`.

We will need to branch on the underlying op logic, depending on what resource was passed in.

2023-06-29 21:29 UTC, rexledesma commented on examples/assets_dbt_python/dbt_project/profiles.yml
`profiles.yml` was move to the top level, but we should also just remove the `config/` directory in the dbt project. The user id shouldn't be checked in anyways.

2023-06-29 21:36 UTC, sryza commented on examples/assets_dbt_python/dbt_project/profiles.yml
oops I missed that - thanks for catching

2023-06-30 14:56 UTC, rexledesma reviewed
This change should just be merged with the previous PR since `DbtCli` doesn't accept `profiles_dir` in the first place

2023-07-05 23:16 UTC, sryza commented
closing and smushing into https://github.com/dagster-io/dagster/pull/15036

2023-07-05 23:16 UTC, closed without merging

2023-07-05 23:17 UTC, sryza commented
because they can't be merged independently