[pythonic config] Add basic support for fixed-length Tuples
dagster-io/dagster pull request #15183
Opened 2023-07-07 23:51 UTC by benpankow

## Summary

Adds basic support for tuples in the Pythonic config system. This converts to the underlying Array Dagster type for the purposes of the launchpad.

```python
class AnOpConfig(Config):
    a_tuple: Tuple[int, int, str]

@op
def a_struct_config_op(config: AnOpConfig):
    assert config.a_tuple == (1, 2, "test")

a_struct_config_op(AnOpConfig(a_tuple=(1, 2, "test")))
```

A stacked change will enable this to work for variable-size tuples (w/ ellipses)

## Test Plan

New unit tests, tested locally in launchpad.

2023-07-07 23:52 UTC, benpankow commented
Current dependencies on/for this PR:
* master
  * **PR #15183** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/15183" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/15183?utm_source=stack-comment).

2023-12-05 17:23 UTC, dpeng817 submitted a review, later dismissed
PR looks a bit stale; should this still be merged?

2023-12-19 15:34 UTC, dpeng817 approved these changes
Nice

2024-02-20 19:11 UTC, schrockn requested changes
Seems like a good change. Is there a docs change to accompany this?

2024-12-10 19:31 UTC, closed without merging