accept Path and dict args for manifest argument of `@dbt_assets`
dagster-io/dagster pull request #15186
Opened 2023-07-08 16:34 UTC by sryza

## Summary & Motivation

The aim here is to make it so that users don't need to understand dagster-dbt's notion of a DbtManifest until they need it.

The current `DbtManifest` class is kind of two things:
1. A simple wrapper around a raw manifest
2. A set of override-able methods that act as a translation layer between dbt concepts and Dagster concepts

It's probably going to make sense to rename `DbtManifest` to something like `DagsterDbtManifest` or `DbtManifestAdapter` in order to disambiguate from the dbt library's `Manifest` class and to make it clear that the manifest is responsible for (2).

Allowing a Path or JSON blob allows users who don't need to think about (2) to avoid dealing with this Dagster concept, as well as removing a small amount of boilerplate.

## How I Tested These Changes

2023-07-10 01:39 UTC, rexledesma requested changes

2023-07-10 01:39 UTC, rexledesma commented on python_modules/libraries/dagster-dbt/dagster_dbt/asset_decorator.py
> +            create Dagster asset definitions for.
This is an odd sentence.

```suggestion
        manifest (Union[Mapping[str, Any], DbtManifest, Path]): The contents of a dbt
            manifest.json file that contains the representation of a dbt project (models, tests, macros, etc). We use this representation to create corresponding Dagster assets. Alternatively, the path to a manifest.json can be specified.
```

2023-07-10 01:39 UTC, rexledesma commented on python_modules/libraries/dagster-dbt/dagster_dbt/asset_decorator.py
> +            @dbt_assets(manifest=Path("target", "manifest.json"))
Might have to check the other docstrings in `resources_v2` to make sure its now following this new convention

2023-07-10 01:39 UTC, rexledesma commented on python_modules/libraries/dagster-dbt/dagster_dbt_tests/test_asset_decorator.py
> +        manifest_json = json.load(f)
nit: use `pathlib` for opening the file
```suggestion
    with manifest_path.open() as f:
        manifest_json = json.load(f)
```

2023-07-10 01:39 UTC, rexledesma commented on python_modules/libraries/dagster-dbt/dagster_dbt_tests/test_asset_decorator.py
> +def test_json_manifest():
Can we just combine make this into one test, and just parameterize `manifest`?

2023-07-10 01:39 UTC, rexledesma commented on python_modules/libraries/dagster-dbt/dagster_dbt_tests/test_asset_decorator.py
> +def test_json_manifest():
Can we just combine make this into one test, and just parameterize `manifest`?

```suggestion
@pytest.mark.parametrize("manifest", ...)
def test_dbt_assets_from_manifest():
```

2023-07-10 16:51 UTC, slopp reviewed
I like this change, I've seen users of `load_assets_from_dbt_manifest` be confused as to why that function doesn't accept a path but requires users to write the `json.loads` themselves. 

My only other thought is that sometimes in large dbt projects even loading that json file can be very slow. I'd hope that maybe with the new dbt python interface they might optimize that serialization and, ideally, we could take advantage of whatever manifest-to-python reader they create and maintain.

2023-07-11 02:04 UTC, rexledesma approved these changes

2023-07-11 18:10 UTC, merged