feat(dbt): deprecate old style dbt project configuration for Dagster
dagster-io/dagster pull request #15324
Opened 2023-07-17 19:18 UTC by rexledesma

## Summary & Motivation
Deprecate the following:

- `dagster_auto_materialize_policy`
- `dagster_freshness_policy`

## How I Tested These Changes
N/A

2023-07-17 19:18 UTC, rexledesma commented
Current dependencies on/for this PR:
* master
  * **PR #15324** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/15324" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/15324?utm_source=stack-comment).

2023-07-19 18:16 UTC, sryza reviewed
The auto-materialize and freshness changes look good. I think the group changes are no longer applicable.

2023-07-26 21:46 UTC, OwenKephart requested changes
minor comment

2023-07-26 21:46 UTC, OwenKephart commented on python_modules/libraries/dagster-dbt/dagster_dbt/asset_utils.py
> +    deprecation_warning(
doesn't this end up emitting warnings for people who have no freshness policy set at all? I think we should do this like:

```python
legacy_freshness_policy = _legacy_freshness_policy_fn(legacy_freshness_policy_config)
if legacy_freshness_policy:
    # deprecation warning
return legacy_freshness_policy
```

2023-07-26 21:57 UTC, OwenKephart approved these changes

2023-07-26 22:24 UTC, merged