[dagster-fivetran] Add default-on 'error on reschedule' config
dagster-io/dagster pull request #15643
Opened 2023-08-02 17:46 UTC by benpankow

## Summary

By default, sets up the Fivetran resource to throw a run failure if a sync is rescheduled, with the option to disable.

## Test Plan

New unit test.

2023-08-02 17:46 UTC, benpankow commented
Current dependencies on/for this PR:
* master
  * **PR #15625** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/15625" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #15643** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/15643" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/15643?utm_source=stack-comment).

2023-08-02 17:50 UTC, alangenfeld commented on python_modules/libraries/dagster-fivetran/dagster_fivetran/resources.py
> +                               " because it has exceeded API limits.")
think this should include a reason for why we think its unreasonable to continue polling for it

2023-08-07 20:00 UTC, alangenfeld commented on python_modules/libraries/dagster-fivetran/dagster_fivetran/resources.py
> +                raise Failure(
maybe raise a named exception here since this is more of an exceptional condition then an explicit "failure"

2023-08-07 20:01 UTC, alangenfeld requested changes
back to you to respin to try to communicate better the exceptional condition and why its raising / giving up on polling

2024-09-30 19:59 UTC, closed without merging