[brownfield-essentials] Revision to ExternalExecutionContext
dagster-io/dagster pull request #15818
Opened 2023-08-11 21:26 UTC by smackesey

## Summary & Motivation

## How I Tested These Changes

2023-08-11 21:26 UTC, smackesey commented
Current dependencies on/for this PR:
* master
  * **PR #15818** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/15818" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/15818?utm_source=stack-comment).

2023-08-14 19:56 UTC, smackesey commented on python_modules/dagster/dagster/_core/execution/context/compute.py
> +
Needed to be added to support reporting metadata by asset key (as opposed to `add_output_metadata`) from the context.

2023-08-14 20:00 UTC, smackesey commented on python_modules/dagster/dagster/_core/execution/context/compute.py
> +
Added to support reporting the data version back from remote execution (there is no `Output` object, where we would normally set the `data_version`).

2023-08-14 20:25 UTC, smackesey commented
>I think all of these (with the possible exception of tags and provenance) are guaranteed to be "small data" so I think we should unconditionally pass them by default.

OK I changed this PR to make fields support multiple asset keys instead of remove fields.

2023-08-14 23:18 UTC, schrockn requested changes
req'ing changes pending rename of userdata

2023-08-14 23:57 UTC, smackesey commented on python_modules/dagster-external/dagster_external/context.py
>          return self._data["userdata"]
yeah I just didn't want to solve the naming issue before proceeding with this so I used the first thing that popped in my head

2023-08-15 14:15 UTC, smackesey commented on python_modules/dagster-external/dagster_external/context.py
> +        return self._data["code_version_by_asset_key"]
done

2023-08-15 16:08 UTC, schrockn approved these changes
![https://media.tenor.com/iNJ3cA3wV18AAAAC/the-simpsons-mr-burns.gif](https://media.tenor.com/iNJ3cA3wV18AAAAC/the-simpsons-mr-burns.gif)

2023-08-15 16:53 UTC, merged