[brownfield-essentials] CLI for dagster-external
dagster-io/dagster pull request #15845
Opened 2023-08-15 00:40 UTC by smackesey

## Summary & Motivation

Add CLI support for `dagster-external`. Due to the rapidly evolving API and lack of a CLI support library (e.g. `click`), I prototyped here with a dynamic CLI that receives generic command line arguments and checks them against the API of ExternalExecutionContext. We'll probably want to change this approach as this stabilizes.

The CLI supports the 3 current write methods of `ExternalExecutionContext` as well as a `get-context` command:

```
# dumps ExternalExecutionContextData to stdout as JSON
dagster-external get-context  # => { "asset_keys": [...], "partition_key": ... }

dagster-external report-asset-metadata --asset-key=foo --label=bar --value=baz
dagster-external report-asset-data-version --asset-key=foo --value=alpha
dagster-external log --message='good evening sir' --level=info
```

Some changes to FIFO IO were required to make this work. When a file descriptior writing a FIFO is closed, the read end receives an EOF and closes if there are no other open file descriptors writing the FIFO. This was causing the first CLI invocation to close the orchestration process FIFO, which needs to remain open to read output from subsequent CLI invocations. The (hacky) solution to this is to keep an unsued fd for the FIFO open for writing in the orchestration process. This keeps at least one write descriptor open in between CLI invocations and prevents premature closing of the FIFO. The FIFO can then be manually closed by the orchestration process after external execution is complete.

## How I Tested These Changes

New unit tests

2023-08-15 00:40 UTC, smackesey commented
Current dependencies on/for this PR:
* master
  * **PR #15818** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/15818" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #15845** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/15845" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/15845?utm_source=stack-comment).

2023-08-15 19:27 UTC, schrockn commented
Before I dig into all, can you write up a summary for the intended use/use case for the CLI? When do we expect users to invoke this CLI?

2023-08-15 19:27 UTC, schrockn requested changes
Haven't looked at code. Req'ing changes just to include intended usage and motivation in the summary.

2023-08-15 19:37 UTC, smackesey commented
>can you write up a summary for the intended use/use case for the CLI

Added a section on this.

2023-08-15 20:02 UTC, schrockn commented
"The primary intended use case for the CLI is materializing assets using logic written in languages other than Python."

I think we should focus on getting the Python APIs right and iterating on this before embarking on this path. I think this will useful to keep around for reference to review later, but I don't think we should check this in quite yet until we stabilize our APIs more.

2023-08-15 22:27 UTC, schrockn requested changes
Ensuring the you see comment. I think we should pump the brakes on this

2023-08-15 23:09 UTC, smackesey commented
>Ensuring the you see comment. I think we should pump the brakes on this

Sure no rush, we can discuss tmrw

2025-02-07 02:02 UTC, closed without merging

2025-02-07 02:02 UTC, smackesey commented
Closing because old and it's called `dagster-pipes` now.