don't fail backfill due to DagsterAssetBackfillDataLoadError
dagster-io/dagster pull request #15860
Opened 2023-08-15 17:56 UTC by johannkm

## Summary & Motivation

## How I Tested These Changes

2023-08-15 17:56 UTC, johannkm commented
Current dependencies on/for this PR:
* master
  * **PR #15860** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/15860" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/15860?utm_source=stack-comment).

2023-08-15 19:12 UTC, johannkm commented on python_modules/dagster/dagster/_daemon/backfill.py
> +                logger.error(f"Backfill error for {backfill.backfill_id}: {error_info.to_string()}. Will retry.")
I don't think we need to now, but in the future we could update the error here and make the ui surface an error even while the backfill isn't failed

2023-08-15 21:05 UTC, gibsondan requested changes
do we need to raise and catch the exception here? Or could we modify the place where we were raising the exception? https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/_core/execution/asset_backfill.py#L523-L530

Could that callsite log a warning and continue on instead of raising something that gets bubbled up all the way?

2023-08-15 21:05 UTC, gibsondan commented on python_modules/dagster/dagster/_daemon/backfill.py
> +            if os.environ.get("RETRY_CODE_LOCATION_ERROR") and isinstance(e, DagsterAssetBackfillDataLoadError):
the name here seems very general for a fairly specific error

2023-08-22 17:11 UTC, gibsondan approved these changes

2023-08-22 17:11 UTC, gibsondan commented on python_modules/dagster/dagster/_core/execution/asset_backfill.py
> +                f" {backfill.backfill_id}:\n{ex}. {unloadable_locations_error}"
Language tweak suggestion to mimic the corresponding feature in the scheduler that retries once user code is available again:


"Backfill was unable to continue due to a missing asset or partition in the asset graph. The backfill will resume once it is available again. {unloadable_locations_error}"

2023-08-22 18:02 UTC, merged