Add step key to asset materialization planned events
dagster-io/dagster pull request #16193
Opened 2023-08-30 00:16 UTC by dpeng817

Adds step key to asset materialization planned events. Having this information available means we don't need to introspect from the execution plan snapshot in other places.

2023-08-30 00:16 UTC, dpeng817 commented
Current dependencies on/for this PR:
* master
  * **PR #16193** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16193" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.svg" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/16193?utm_source=stack-comment).

2023-09-14 13:02 UTC, johannkm requested changes

2023-09-14 13:02 UTC, johannkm commented on python_modules/dagster/dagster/_core/instance/__init__.py
> +                            step_key=execution_plan_snapshot.get_step_key_for_asset_key(asset_key),
we already have step.key here right?

2023-09-15 21:33 UTC, johannkm approved these changes
for you to land once comment addressed

2023-09-16 18:01 UTC, dpeng817 commented on python_modules/dagster/dagster/_core/instance/__init__.py
> +                            step_key=execution_plan_snapshot.get_step_key_for_asset_key(asset_key),
true

2023-09-16 18:01 UTC, merged