add asset_key property to context
dagster-io/dagster pull request #16268
Opened 2023-09-01 15:38 UTC by jamiedemaria

## Summary & Motivation

## How I Tested These Changes

2023-09-01 15:39 UTC, jamiedemaria commented
Current dependencies on/for this PR:
* master
  * **PR #16268** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16268" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/16268?utm_source=stack-comment).

2023-09-01 16:00 UTC, schrockn commented
What is the error message if it is a `multi_asset`?

2023-09-01 16:06 UTC, jamiedemaria commented
it'll fall back on `check.failed(f"Output '{output_name}' has no asset")` in `asset_key_for_output`. so it'll say `Output 'result' has no asset` which is not great. I could add a check before calling `asset_key_for_output` and raise a specific error if it's a multi asset

2023-09-01 16:09 UTC, schrockn commented
Yeah let's do a specific error message

On Fri, Sep 01, 2023 at 12:06 PM, jamiedemaria < ***@***.*** > wrote:

> 
> 
> 
> it'll fall back on check.failed(f"Output '{output_name}' has no asset") in
> asset_key_for_output. so it'll say Output 'result' has no asset which is
> not great. I could add a check before calling asset_key_for_output and
> raise a specific error if it's a multi asset
> 
> 
> 
> —
> Reply to this email directly, view it on GitHub (
> https://github.com/dagster-io/dagster/pull/16268#issuecomment-1702983483 )
> , or unsubscribe (
> https://github.com/notifications/unsubscribe-auth/AG3IK6LG7CN2AX2Z56GIXU3XYIBZHANCNFSM6AAAAAA4HXVU6Q
> ).
> You are receiving this because your review was requested. Message ID: <dagster-io/dagster/pull/16268/c1702983483
> @ github. com>
> 
> 
>

2023-09-01 17:16 UTC, alangenfeld commented on python_modules/dagster/dagster/_core/execution/context/compute.py
> +            check.failed(
nit: prefer `raise DagsterInvariantViolation` over check error

2023-09-01 17:21 UTC, schrockn requested changes
Yeah what Alex said. check generally should be thought as the moral equivalent of a assert or type failure, rather than this which is more about business logic.

Please add test to verify error behavior then this looks gtg.

2023-09-01 20:51 UTC, jamiedemaria commented
where do context tests live?

2023-09-01 21:22 UTC, schrockn commented
> where do context tests live?

Don't know off the top of my head! I think I would just grep around the codebase and find the most reasonable spot I could.

2023-09-01 21:22 UTC, alangenfeld commented
>  where do context tests live?

personally dont think its terribly important where you put the test, so what ever you prefer. I've recently used `python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py` 

I think its worth testing both `execute_in_process` / `materialize` and direct invocation since they use different context impls and its worth making sure it works in both

2023-09-01 22:00 UTC, jamiedemaria commented
yeah i wasn't finding a place where context methods were getting tested, hence the question. I'll just throw it in `test_assets` then

2023-09-05 18:46 UTC, schrockn approved these changes
Please heed final comments. Thanks!

2023-09-05 18:46 UTC, schrockn commented on python_modules/dagster/dagster/_core/execution/context/compute.py
> +                "Cannot call `context.asset_key` in a multi_asset. Use"
"Cannot call `context.asset_key` in a multi_asset that materializes more than one asset"

2023-09-05 18:46 UTC, schrockn commented on python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py
> +        materialize([asset_key_context])
Can you do a string match for "Cannot call `context.asset_key` in a multi_asset" in the test case

2023-09-06 15:59 UTC, merged