Dagster k8s better handling of failed jobs
dagster-io/dagster pull request #16303
Opened 2023-09-03 17:26 UTC by Milias

## Summary & Motivation

Hello,

This is a relatively minor change to library `dagster-k8s` such that it deals better with cases in which the Kubernetes job has both failed and active jobs. In this way situations such as those described in #6236 are better handled.

This is the first time contributing to this project. I have followed the [contributing guide](https://docs.dagster.io/community/contributing) and hopefully everything is fine.

I look forward to your comments!

## How I Tested These Changes

I prepared the new unit test by running an existing job on Kubernetes with `backoff_limit: 3` and deleting the pod manually to trigger re-execution. Without this change exception `DagsterK8sError` is raised as:

```
dagster_k8s.client.DagsterK8sError: Encountered failed job pods for job dagster-step-4042dc71c0e6a277db11063e58ed74b1-1 with status: {'active': 1,
 'completed_indexes': None,
 'completion_time': None,
 'conditions': None,
 'failed': 1,
 'ready': 0,
 'start_time': datetime.datetime(2023, 9, 3, 16, 50, 10, tzinfo=tzlocal()),
 'succeeded': None,
 'uncounted_terminated_pods': {'failed': None, 'succeeded': None}}, in namespace <namespace>

  File "/usr/local/lib/python3.10/site-packages/dagster_celery_k8s/executor.py", line 450, in _execute_step_k8s_job
    api_client.wait_for_job_success(
  File "/usr/local/lib/python3.10/site-packages/dagster_k8s/client.py", line 350, in wait_for_job_success
    self.wait_for_running_job_to_succeed(
  File "/usr/local/lib/python3.10/site-packages/dagster_k8s/client.py", line 399, in wait_for_running_job_to_succeed
    raise DagsterK8sError(
```

I monitored using `kubectl` what was running and Kubernetes correctly started a new pod, which means that dictionary `status` contains `active: 1`. Therefore, I added the new statement to the conditional as you can see in the diff. In the unit test two jobs are returned with these properties to test that the job is correctly recognized as successful.

2023-09-06 09:26 UTC, Milias commented
Thanks for triggering the pipeline! Will apply ruff and push again.

2023-09-11 14:12 UTC, Milias commented
Hello, would it be possible to trigger the build again please?

Thanks!

2023-09-14 18:40 UTC, Milias commented
Hello again, @gibsondan, would it be possible to trigger the pipeline, please?

Thanks a lot!

2023-09-25 08:28 UTC, Milias commented
Hi, @gibsondan would it be possible for you to review this, please?

Thanks!

2023-09-25 14:34 UTC, gibsondan requested changes
Hi @Milias - sorry for the delay here. 

The backoff_limit change here seems reasonable to me (although i'm not 100% certain that our executors will still behave correctly if you set backoff_limit > 0, even after this change)

The 'don't raise an exception if there's any k8s error while retrieving pod logs' change seems more controversial. I think that's the kind of thing that should go in the callsite so that different callers of this method can catch the exception and handle it the way that's best for their use case. Here's an example where we do that today: https://github.com/dagster-io/dagster/blob/master/python_modules/libraries/dagster-k8s/dagster_k8s/client.py#L761-L781

For the specific callsite here in the celery executor, it's actually pretty important that the log events from the pod come back - we use it to make decisions about whether or not particular steps have started or stopped for example: https://github.com/dagster-io/dagster/blob/master/python_modules/libraries/dagster-celery/dagster_celery/core_execution_loop.py#L102-L110

We've discussed changing this to source from our event log (like the k8s_job_executor does) instead of parsing the pod logs into structured events - I think we would need to make some change like that before it would be safe to fail open when there's an issue fetching pod logs.

Would it be possible to split this change into two given that? I don't see any big risks with the backoff_limit change (assuming that it's true that we'll only arise in this situation if a user has explicitly increased the backoff_limit) but the logs change likely needs more discussion.

2023-09-25 21:43 UTC, Milias commented
Hi @gibsondan , thanks a lot for the review!

Your explanation is extremely appreciated, it really helps understanding the other executors.

I think you are absolutely right that this change will not fix all the issues with `backoff_limit > 0`, in particular I have seen it fail because no logs were available (the reason to also add that in this PR). Knowing that the executor itself has to deal with these exceptions, I see that in the second error pasted above indeed comes from [`dagster_celery_k8s`](https://github.com/dagster-io/dagster/blob/master/python_modules/libraries/dagster-celery-k8s/dagster_celery_k8s/executor.py#L536), not from `dagster-k8s`.

I will push another version without the changes to the log, thank you for noticing and explaining!

However, now I'm a bit confused. I see that in `dagster-celery-k8s` exception `kubernetes.client.rest.ApiException` is handled. In the second error above instead exception `kubernetes.client.exceptions.ApiException` is raised. Would it make sense then to change [this line](https://github.com/dagster-io/dagster/blob/master/python_modules/libraries/dagster-celery-k8s/dagster_celery_k8s/executor.py#L536) to this exception?

I will make this change in a separate commit for you to review and if it is not convincing I'll revert it.

2023-09-26 01:27 UTC, gibsondan approved these changes

2023-09-26 01:27 UTC, merged