Allow OpExecutionContext.add_output_metadata to be called multiple times per output
dagster-io/dagster pull request #16391
Opened 2023-09-08 12:58 UTC by smackesey

## Summary & Motivation

`OpExecutionContext.add_output_metadata` imposes a restriction that it can only be called once-per-output. It's unclear to me what the reason for this restriction is, and it complicates the implementation of metadata reporting in `dagster-ext`. This PR removes the restriction.

cc @dpeng817 since it looks like you added `add_output_metadata` way back in #6530 

## How I Tested These Changes

Modified existing unit tests.

2023-09-08 12:58 UTC, smackesey commented
Current dependencies on/for this PR:
* master
  * **PR #16383** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16383" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #16391** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16391" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/16391?utm_source=stack-comment).

2023-09-08 20:42 UTC, schrockn requested changes
This is a good showcase on why pseudo-mutative methods on long-lived context objects are a bad idea. 

I believe this is much intuitive behavior, but not sure if anyone objects. I also seem to recall a GH issue about this somewhere, however brief searching did not yield a result.

This need tests demonstrating the new behavior it enables, hence the request changes, but supportive of this change.

2023-09-08 20:57 UTC, smackesey commented
>This need tests demonstrating the new behavior it enables, hence the request changes, but supportive of this change.

The new behavior in this PR is tested in `test_metadata_multiple_logging_entries`-- basically this just changes the old test, which tested for an error on multiple calls, to instead test that both entries are logged.

2023-09-08 21:12 UTC, schrockn commented
At minimum need to demonstrate the behavior when you add metadata with the same key multiple times.

2023-09-11 16:04 UTC, smackesey commented
>At minimum need to demonstrate the behavior when you add metadata with the same key multiple times.

Added doc and test for this.

2023-09-11 17:11 UTC, schrockn approved these changes
Cool. Please heed final comments.

2023-09-11 17:11 UTC, schrockn commented on python_modules/dagster/dagster/_core/execution/context/compute.py
> +        This can be invoked multiple times per output in the body of an op. If the same key
"If the same key is passed multiple times, the value associated with last call will be used" is a little more specifiy

2023-09-11 17:11 UTC, schrockn commented on python_modules/dagster/dagster_tests/definitions_tests/decorators_tests/test_op.py
> +        context.add_output_metadata({"foo": "baz"})  # overwrites first
"bar" -> "first_value", "baz" -> "second_value" would make this more clear

2023-09-11 17:45 UTC, merged