Fighting parameter anxiety: Add the ability to have hidden kwargs that emit deprecation warnings
dagster-io/dagster pull request #16543
Opened 2023-09-15 10:51 UTC by schrockn

## Summary & Motivation

This PR proposes a pattern where in the case where we have required kwargs in the past, when we deprecate params we hide them from the type signature entirely, but still support them via a kwargs grabbag.

We have a parameter problem. Our public APIs consistently have too many parameters. This induces parameter anxiety. Tons of parameters are scary. The testing area of the function increases a lot. With every parameter there is a combinatorial explosion of possible states. 

Everytime I type “(“ in vscode, I am assaulted with a wall of parameters. This triggers my programmer lizard brain into flight or flight mode.

A big source of this in our code base is deprecated parameters. And this dynamic also causes us to hesitate to deprecate parameters.

This PR proposes a middle ground where we hide parameters from the type signature. Code still works and is backwards compatible. However, for the increasingly large share of programmers that heavily rely on the in-editor experience to explore APIs, these parameters will not exist, which is ideal.

There are some downsides. Existing code paths will lose static type checking. And the presence of kwargs is itself its own source of anxiety.

However I think we should consider this pattern.

## How I Tested These Changes

BK. Confirmed non_argument_deps does not appear in typeahead

2023-09-15 10:51 UTC, schrockn commented
Current dependencies on/for this PR:
* master
  * **PR #16543** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16543" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/16543?utm_source=stack-comment).

2023-09-15 17:24 UTC, PedramNavid commented
Very supportive of this idea, agree that generally kwargs aren't great, I think the good outweighs the harm here. I often rely on what my type system tells me I can use as direction on what to do, not having deprecated items in here simplifies the API and makes it easier to do the right thing.

2023-09-15 17:29 UTC, schrockn commented
@smackesey thinks there might be some new first-class support for deprecations in the python ecosystem that might be a better solution. I'll let him comment.

2023-10-12 16:08 UTC, alangenfeld requested changes
I'm cool with this, back to you to consider names & add test coverage

2023-10-12 16:08 UTC, alangenfeld commented on python_modules/dagster/dagster/_annotations.py
> +        # )
rm?

2023-10-12 16:08 UTC, alangenfeld commented on python_modules/dagster/dagster/_annotations.py
> +    require_param_in_signature: bool = True,
nit: maybe something in the direction of `param_handled_via_kwargs`? With the current name I feel like you have to take a couple mental hops to "it doesnt need to be in the signature" to the end goal of "hide this arg via kwargs"

2024-04-30 14:08 UTC, closed without merging