Remove pointless construction of all_executable_keys in materialize
dagster-io/dagster pull request #16582
Opened 2023-09-17 09:30 UTC by schrockn

## Summary & Motivation

This was unused and only served to confuse

## How I Tested These Changes

BK

2023-09-17 09:30 UTC, schrockn commented
Current dependencies on/for this PR:
* master
  * **PR #16573** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16573" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #16574** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16574" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #16575** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16575" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #16576** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16576" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #16577** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16577" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #16578** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16578" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
              * **PR #16579** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16579" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
                * **PR #16581** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16581" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
                  * **PR #16582** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16582" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/16582?utm_source=stack-comment).

2023-09-18 22:06 UTC, alangenfeld requested changes
we made need some validation like this but im hopeful we can avoid co-mingling executable and non executable assets in the same jobs at all

2023-09-18 22:06 UTC, alangenfeld commented on python_modules/dagster/dagster/_core/definitions/assets_job.py
> +
related to https://github.com/dagster-io/dagster/pull/16586#issuecomment-1724511225

hopefully we get to a point where unexecutable assets are just not put in to *any* jobs, or if not that far still something which changes the nature of what we are trying to enforce here

2023-09-21 22:50 UTC, schrockn reviewed
@alangenfeld are you adding this error as part of your stack? Or should I just close this

2023-09-21 23:22 UTC, closed without merging