Make execute_in_process automatically exclude non-executable asset
dagster-io/dagster pull request #16586
Opened 2023-09-17 15:00 UTC by schrockn

## Summary & Motivation

Our strategy is going to be for executions to skip non-executable assets.

## How I Tested These Changes

BK

2023-09-17 15:00 UTC, schrockn commented
Current dependencies on/for this PR:
* master
  * **PR #16573** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16573" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #16574** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16574" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #16575** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16575" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #16576** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16576" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #16577** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16577" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #16578** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16578" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
              * **PR #16579** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16579" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
                * **PR #16581** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16581" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
                  * **PR #16582** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16582" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
                    * **PR #16586** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16586" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈
                    * **PR #16583** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16583" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/16586?utm_source=stack-comment).

2023-09-18 13:46 UTC, johannkm reviewed
WOT enters the codebase

LGTM, will let others weigh in

2023-09-18 13:46 UTC, johannkm commented on python_modules/dagster/dagster/_core/definitions/job_definition_execution.py
> +# selection bugs from create_tainted_job_for_execution.
```suggestion
# selection bugs from create_untainted_job_for_execution.
```

2023-09-18 14:16 UTC, schrockn commented on python_modules/dagster/dagster/_core/definitions/job_definition_execution.py
> +# selection bugs from create_tainted_job_for_execution.
addressed in my followup

2023-09-18 21:55 UTC, alangenfeld commented
>  This allows someone to defines a job that includes unexecutable assets

Do we need to let users explicitly define jobs with un-executable assets? What if we only allowed them to be passed directly to `Definitions` via `assets` and then did some bullshit in `get_base_asset_jobs` 
https://github.com/dagster-io/dagster/blame/master/python_modules/dagster/dagster/_core/definitions/assets_job.py#L60

Really hoping to find a way to avoid the complexity demons contained within the current version of this PR

2023-09-18 21:59 UTC, schrockn commented
> Do we need to let users explicitly define jobs with un-executable assets? What if we only allowed them to be passed directly to Definitions via assets and then did some bullshit in get_base_asset_jobs
> https://github.com/dagster-io/dagster/blame/master/python_modules/dagster/dagster/_core/definitions/assets_job.py#L60
> 
> Really hoping to find a way to avoid the complexity demons contained within the current version of this PR

Yeah I can take run at it from that dimension. I also would prefer not to have to do this.

2023-09-18 22:02 UTC, schrockn commented
However @alangenfeld there are deep assumptions in the system that assets must be part of _a_ job, hence the creation of the base asset jobs and their ilk, and that has downstream implications all the way through snapshots and into system processes. I did think this approach was preferable to creating yet-another magical job whose sole purpose was as a vessel for these assets.

2023-09-18 22:26 UTC, alangenfeld commented
> there are deep assumptions in the system that assets must be part of a job

Looking at `ExternalAssetNode` i expected there to be some room for play. The list of those nodes is separate from the job/op snapshots and uses name pointers to the jobs/ops or lack thereof in the case of source assets.  Given the nature of what were trying to do here it feels roughly right in my head for these assets to manifest as ExternalAssetNodes with no backing jobs/ops.  Will be curious what blockers exist down this path. 

>  I did think this approach was preferable to creating yet-another magical job whose sole purpose was as a vessel for these assets.

hmmm I dunno man. May need to talk it out after we see how this current exploration goes.

2023-09-21 21:53 UTC, alangenfeld requested changes
I think https://github.com/dagster-io/dagster/pull/16637 shows promise as a better alternative for this

2023-09-21 22:28 UTC, schrockn commented
> I think #16637 shows promise as a better alternative for this

💯. Truly a joy to close this

2023-09-21 22:28 UTC, closed without merging