partition methods on AssetExecutionContext
dagster-io/dagster pull request #16625
Opened 2023-09-19 16:32 UTC by jamiedemaria

## Summary & Motivation

## How I Tested These Changes

2023-09-19 16:33 UTC, jamiedemaria commented
Current dependencies on/for this PR:
* master
  * **PR #16480** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16480" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #16596** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16596" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #16493** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16493" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #16598** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16598" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #16507** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16507" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #16625** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16625" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈
    * **PR #16486** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16486" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #16487** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16487" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/16625?utm_source=stack-comment).

2023-09-19 16:37 UTC, jamiedemaria commented on python_modules/dagster/dagster/_core/execution/context/compute.py
> +        self, asset_key: CoercibleToAssetKey, is_dependency: bool = False
still not super happy with the `is_dependency` solution to the self dependent asset problem. here's my comment from the first PR exploring this:

--- 
the is_dependency bool param here is to handle the self-dependent partition case. Basically when you have a self-dependent partition, if you said `context.partition_key_for_asset_key("my_asset")` it's unclear if you want the partition key of my_asset as a dependency, or as is being currently materialized. I'm handling this (for now at least) by allowing users to specify `is_dependency` to indicate they want it loaded as a dependency.

In all other cases, the function should be able to figure out the correct partition key to load given the current asset

I'm not set on this solution, so if you have any concerns or other ideas let me know

2023-09-20 21:57 UTC, jamiedemaria commented
Discussing and aligning on partition method APIs here https://github.com/dagster-io/internal/discussions/6704. then will implement in this PR

2023-10-12 16:01 UTC, alangenfeld requested changes
whats the overlap with this and https://github.com/dagster-io/dagster/pull/16480? 

back to your queue

2023-10-13 19:18 UTC, jamiedemaria commented
closing for now. I think determining the partition method APIs will be best done in a discussion.

2023-10-13 19:18 UTC, closed without merging