support direct invocation with AssetExecutionContext
dagster-io/dagster pull request #16635
Opened 2023-09-19 21:38 UTC by jamiedemaria

## Summary & Motivation

## How I Tested These Changes

2023-09-19 21:39 UTC, jamiedemaria commented
Current dependencies on/for this PR:
* master
  * **PR #16480** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16480" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #16596** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16596" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #16493** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16493" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #16635** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16635" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈
        * **PR #16598** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16598" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #16507** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16507" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #16625** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16625" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #16486** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16486" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #16487** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16487" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/16635?utm_source=stack-comment).

2023-09-20 01:22 UTC, schrockn requested changes

2023-09-20 01:22 UTC, schrockn commented on python_modules/dagster/dagster/_core/execution/context/invocation.py
> +        self._exit_stack.close()
I don't see why you need to have an `exit_stack` in here. However I do believe the inner `OpExecutionContext``__enter__`, `__exit__`, and `__del__` methods will have to delegate to the underlying context in order for this to work.

Make sure to test resources that require setup and teardown to validate.

2023-09-20 01:22 UTC, schrockn commented on python_modules/dagster/dagster/_core/definitions/op_invocation.py
> +            context = cast(UnboundOpExecutionContext, args[0])
isn't even worth doing all the casting at this point? Seems like the typechecker will be totally confused as to what type "context" is anyways.

From brief inspection it appears the only requirement of the `context` local variable is that it have a `bind` method, so it you really want that typed you can introduce an interface that has this, but this looks like mostly pointless, unnecessary gymnastics to appease typechecking gods, unless I am misreading this

2023-09-21 20:32 UTC, jamiedemaria commented on python_modules/dagster/dagster/_core/definitions/op_invocation.py
> +    context: Union["BoundOpExecutionContext", "BoundAssetExecutionContext"],
I'm running into issues trying to consolidate this type hint. the function `validate_and_coerce_op_result_to_iterator` expects an `OpExecutionContext` so swapping this type hint to the `BoundExecutionContext` parent class causes type checker complaints

2023-09-22 20:29 UTC, jamiedemaria commented on python_modules/dagster/dagster/_core/execution/context/invocation.py
> +class BoundExecutionContext(OpExecutionContext):
Having this interface be a child of `OpExecutionContext` feels shady, but it's the only way i was able to find to make the type checker happy. 

When AssetExecutionContext eventually splits from OpExecutionContext there will be a good amount of work to do to make the path through `op_invocation.py` happy with the two types

2023-10-13 19:19 UTC, jamiedemaria commented
converting to draft to get out of review queues. will need to re-open or open a similar PR when method deprecations for Asset context start

2023-11-17 21:31 UTC, jamiedemaria commented
https://github.com/dagster-io/dagster/pull/18044 replaces this

2023-11-17 21:31 UTC, closed without merging