Add AssetChecksDefinitionProps to replace untyped dictionary shenanigans
dagster-io/dagster pull request #16747
Opened 2023-09-23 22:58 UTC by schrockn

## Summary & Motivation

## How I Tested These Changes

2023-09-23 22:58 UTC, schrockn commented
Current dependencies on/for this PR:
* master
  * **PR #16747** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16747" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/16747?utm_source=stack-comment).

2023-09-25 15:41 UTC, sryza reviewed
A downside here is that a user who wants to construct an `AssetChecksDefinition` needs to go through the extra hoop of constructing one of these props objects. 

Might it make sense to make `AssetChecksDefinition` itself a `NamedTuple`?

2023-09-25 15:42 UTC, schrockn commented
> Might it make sense to make `AssetChecksDefinition` itself a `NamedTuple`?

I don't think so. You want the option to add variables in `__init__` or on demand.

2023-09-25 15:45 UTC, schrockn commented
> A downside here is that a user who wants to construct an AssetChecksDefinition needs to go through the extra hoop of constructing one of these props objects. 

I agree this is a nuisance, but a fairly minor one IMO since people constructing `AssetChecksDefinition`s directly are likely to be framework authors. 

I can take a stab at some shenanigans, but it will likely involve having an `__init__` or `__new__` with broken out arguments and keeping them in sync with unit tests that iterate over the types themselves.

2023-09-27 15:56 UTC, schrockn reviewed
@alangenfeld this is the pattern I want to institute to prevent the description shenanigans you called brutal in https://github.com/dagster-io/dagster/pull/16755#pullrequestreview-1647055234

2023-10-12 16:41 UTC, alangenfeld requested changes
I like the conceptual set-up of explicitly capturing the immutable props separate from memoization/utility instance members.

`self._props.XXX` is a little bit unfortunate but it does make it clear on every touch whats "fundamental" properties of the definition vs not

2023-10-12 16:41 UTC, alangenfeld commented on python_modules/dagster/dagster_tests/definitions_tests/test_i_definition_prop_class_matches_init_adherence.py
> +    )
this is just here because you couldn't figure out how to pluck `TPropsType` &  `TDefType` from the class object?

2023-10-12 16:41 UTC, alangenfeld commented on python_modules/dagster/dagster/_utils/test/__init__.py
> +        module = dagster
what motivated this change?

2023-10-12 16:41 UTC, alangenfeld commented on python_modules/dagster/dagster/_core/definitions/asset_checks.py
> +class IDefinitionPropsClassMatchesInit(Generic[TPropsType, TDefType], ABC):
nit: something in the direction of `IDefinitionWithProps` / `PropsBackedDefinition`, i think it makes more sense to target the fundamentlal pattern then a specific thing we enforce when participating in it

2023-10-12 16:41 UTC, alangenfeld commented on python_modules/dagster/dagster/_core/definitions/asset_checks.py
> +            )._asdict()
[1]

2023-10-12 16:41 UTC, alangenfeld commented on python_modules/dagster/dagster/_core/definitions/asset_checks.py
> +    def from_props(props: TPropsType) -> TDefType: ...
this appears unused - should we instead capture [1] with a method on this class?

2024-04-30 14:06 UTC, closed without merging