Add link to dbt nux in dbt integration page
dagster-io/dagster pull request #16885
Opened 2023-09-28 18:59 UTC by clairelin135

## Summary & Motivation

## How I Tested These Changes

2023-09-28 18:59 UTC, clairelin135 commented
Current dependencies on/for this PR:
* master
  * **PR #16885** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16885" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/16885?utm_source=stack-comment).

2023-10-09 17:46 UTC, clairelin135 commented
@sryza @erinkcochran87 could I get a review on this when you have the chance?

2023-10-09 21:28 UTC, clairelin135 commented on docs/content/integrations/dbt.mdx
> +  <a href="https://dagster.cloud/signup?next=/prod/getting-started%3Ftab%3Dimport_dbt_core_project%26serverless%3D1">
yup, added

2023-10-09 21:48 UTC, erinkcochran87 approved these changes

2023-10-09 21:54 UTC, sryza approved these changes

2023-10-09 22:00 UTC, sryza requested changes
Sorry for the approve-then-request changes, but thinking about this, I think we could be a little more clear about how we present this. I'm worried that readers of this page will see the banner at the top and assume this is the only way for Dagster to work with dbt.

This leads me to think that maybe we should omit it at the top, and instead find a way to make it more prominent within the "Getting started" section.

2023-10-10 02:36 UTC, erinkcochran87 commented
If you want to keep the callout, we could also update the copy - ex:

**Using Dagster Cloud?** You can automatically load your dbt models as Dagster assets by importing a dbt project in Dagster Cloud.

Definitely not a hill I'll die on tho

2023-10-10 17:36 UTC, clairelin135 commented
@erinkcochran87's suggestion above makes sense to me, I updated this PR.

@sryza let me know if this still looks confusing

2023-10-10 18:03 UTC, sryza approved these changes
I think this is much better

2023-10-10 18:26 UTC, merged