[pipes] init_dagster_pipes -> open_dagster_pipes context manager
dagster-io/dagster pull request #16988
Opened 2023-10-03 20:39 UTC by smackesey

## Summary & Motivation

## How I Tested These Changes

2023-10-03 20:40 UTC, smackesey commented
Current dependencies on/for this PR:
* master
  * **PR #16986** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16986" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #16988** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/16988" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/16988?utm_source=stack-comment).

2023-10-03 21:04 UTC, schrockn commented on python_modules/dagster-pipes/dagster_pipes/__init__.py
> +PIPES_CLOSED_MESSAGE: PipesMessage = _make_message("closed", None)
is this change necessary for this PR? This seems like a big change.

2023-10-03 21:13 UTC, schrockn requested changes
Adding the control messages is a big change. Is it strictly necessary?

2023-10-03 21:13 UTC, schrockn commented on python_modules/dagster-pipes/dagster_pipes/__init__.py
> +        atexit.register(context.close)
why not just call this in `init_dagster_pipes`?

2023-10-03 21:32 UTC, smackesey commented on python_modules/dagster-pipes/dagster_pipes/__init__.py
> +        context = PipesContext(context_data, message_channel, stack)
Yeah passing the stack isn't great. The only other option I see (aside from larger refactor) is passing a lambda instead-- both options are meh, I'm indifferent as to which one.

2023-10-03 21:33 UTC, smackesey commented on python_modules/dagster-pipes/dagster_pipes/__init__.py
> +        if self._closed:
I think it should be an error because I can't think of a reason to `close()` twice (so it would indicate a mistake) but I didn't think very hard

2023-10-03 21:34 UTC, smackesey commented on python_modules/dagster-pipes/dagster_pipes/__init__.py
> +        io_stack: ExitStack,
that's just how we trigger the existing close/flush routine on the injector/writer

2023-10-03 21:38 UTC, smackesey commented
>Adding the control messages is a big change. Is it strictly necessary?

- Adding the close control is necessary since we want to enforce the contract (that `close` is called). Without the `close` control, there's no enforcement mechanism.
- Adding open control is not strictly necessary but it made sense to me to add it at the same time as `close`

2023-10-03 22:01 UTC, alangenfeld reviewed
> Adding the close control is necessary since we want to enforce the contract

I think its feasible to move the control messages and [1] out to their own PR, and may make sense given the exact behavior we want merits its own relatively detailed discussion (i think)

2023-10-03 22:01 UTC, alangenfeld commented on python_modules/dagster-pipes/dagster_pipes/__init__.py
> +        context = PipesContext(context_data, message_channel, stack)
think we could pass the loader and writer in to the context and move the stack management internal to `PipesContext`

2023-10-03 22:08 UTC, alangenfeld commented on python_modules/dagster-pipes/dagster_pipes/__init__.py
> +        if self._closed:
our ol friend `open` goes with idempotent close 
```
>>> f = open('/tmp/f.txt')
>>> f.close()
>>> f.close()
>>> f.close()
```

2023-10-03 22:15 UTC, smackesey commented
>think we could pass the loader and writer in to the context and move the stack management internal to PipesContext

This feels kinda awkward to me because it makes construction of `PipesContext` more complicated. Better to pass it the objects it directly uses. It also requires us to either load the params or pass the params loader into the constructor.

Ofc I also dislike passing the stack. What do you think of passing a lambda `close_callback`?

2023-10-03 22:24 UTC, smackesey commented
>I think its feasible to move the control messages and [1] out to their own PR, and may make sense given the exact behavior we want merits its own relatively detailed discussion (i think)

done: https://github.com/dagster-io/dagster/pull/16992

2023-10-03 22:25 UTC, smackesey commented on python_modules/dagster-pipes/dagster_pipes/__init__.py
> +        if self._closed:
>our ol friend open goes with idempotent close

fair point, I'm sold

2023-10-03 22:35 UTC, alangenfeld commented
> Better to pass it the objects it directly uses then throwaways it will use to derive the objects it uses

I think its likely that we will want access to these objects that currently feel throwaway from the `PipesContext`. Cases I'm currently thinking:
* detecting / reporting when component threads have had exceptions 
* reporting details on the specific components and their configuration in the structured  open / close messages 

It makes senes in my head that `PipesContext` receives these component objects and then is responsible for context managing them as well as potentially poking at them before and after. 

I'm not sure that this means its the right factoring for this PR, but I do think its worth consideration. 

honestly I think the exit stack passing is probably fine for now and we can shuffle it around later.

2023-10-03 23:33 UTC, schrockn requested changes
Seems like we need test cases demonstrating that `open_dagster_pipes` _without_ a `with` block works.

2023-10-03 23:33 UTC, schrockn commented on examples/experimental/assets_yaml_dsl/assets_yaml_dsl/pure_assets_dsl/sql_script.py
> +        context.log.info(f"Ran {sql}")
this with a `with` does please my programmer brain much more

2023-10-03 23:35 UTC, schrockn commented
Also I think we should consider `PipesContext.__init__` non-public and feel free to refactor it at will.

2023-10-04 01:45 UTC, smackesey commented
>I think its likely that we will want access to these objects that currently feel throwaway from the PipesContext. Cases I'm currently thinking:

Makes sense to me. OK I'm moving it in.

>Also I think we should consider PipesContext.__init__ non-public and feel free to refactor it at will.

agree

>Seems like we need test cases demonstrating that open_dagster_pipes without a with block works.

There is a test for that, `test_manual_close`

2023-10-04 08:11 UTC, schrockn approved these changes
[![approvedarthvader](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/WjlTemxb6oA4PgZFmj08/a564ccce-472a-4073-b531-c2193efa896a/approvedarthvader.jpeg)](https://app.graphite.dev/macros/dagster-io)

2023-10-04 08:11 UTC, schrockn commented on python_modules/dagster-pipes/dagster_pipes/__init__.py
> +                "ExtContext has not been initialized. You must call `open_dagster_pipes()`."
change to `PipesContext` while you're here

2023-10-04 08:11 UTC, schrockn commented on python_modules/dagster-pipes/dagster_pipes_tests/test_context.py
>      )
this must be unused given that you didn't have to change it. Delete.

2023-10-04 12:04 UTC, merged