Update node install on build script
dagster-io/dagster pull request #17018
Opened 2023-10-04 23:36 UTC by salazarm

## Summary & Motivation
https://dagsterlabs.slack.com/archives/C03CCE471E0/p1696454877943329

## How I Tested These Changes
buildkite

2023-10-05 13:34 UTC, hellendag commented on .buildkite/dagster-buildkite/dagster_buildkite/steps/dagster_ui.py
>              # Todo: Fix BK images to use newer Node versions, remove this.
Update comment?

2023-10-05 13:34 UTC, hellendag commented on .buildkite/dagster-buildkite/dagster_buildkite/steps/dagster_ui.py
> +            "sudo yum install nodejs -y --setopt=nodesource-nodejs.module_hotfixes=1",
What are these args based on?

2023-10-06 06:26 UTC, salazarm commented on .buildkite/dagster-buildkite/dagster_buildkite/steps/dagster_ui.py
> +            "sudo yum install nodejs -y --setopt=nodesource-nodejs.module_hotfixes=1",
I copy pasted the recommended install command ¯\_(ツ)_/¯

2023-10-11 19:51 UTC, gibsondan commented on js_modules/dagster-ui/packages/ui-core/src/asset-graph/sidebar/Sidebar.tsx
> +      if (selectWhenDataAvailable && selectedNodeHasDataAvailable) {
unrelated i assume, remove?

2023-10-11 19:52 UTC, gibsondan requested changes
looks like buildkite doesn't have yum sadly

2023-10-11 19:52 UTC, gibsondan commented
(based on BK results)

2023-11-13 12:48 UTC, closed without merging