[pipes/external assets] s3 data lake demo of using external assets + pipes
dagster-io/dagster pull request #17098
Opened 2023-10-09 18:41 UTC by Ramshackle-Jamathon

## Summary & Motivation
![Screenshot 2023-10-09 at 2 40 54 PM](https://github.com/dagster-io/dagster/assets/5943242/02692df2-5f84-41b8-98f9-4b73427376a0)

This pr adds a synthetic example of using external assets to ingest an s3 data-lake (made up of cdn logs) into dagster, making an asset check against them and triggering a downstream k8s job that uses pipes with an asset sensor.

to use:

1. `dagster dev` in the project root
2. `python external_assets_event_generator.py`

## How I Tested These Changes

2023-10-09 22:32 UTC, Ramshackle-Jamathon commented on examples/experimental/external_assets/s3_lambda.py
> +def lambda_handler(event, context):
@schrockn this is the s3 event lambda code

2023-10-10 12:26 UTC, schrockn commented on examples/experimental/external_assets/dockerfile
> +FROM python:3.10-slim
Nit: Why "dockerfile" and not "Dockerfile"?

2023-10-10 12:30 UTC, schrockn commented on python_modules/dagster/dagster/_core/definitions/asset_spec.py
>          ],
remove all these changes

2023-10-10 12:30 UTC, schrockn commented on python_modules/dagster/dagster/_core/definitions/external_asset.py
> +            partitions_def=spec.partitions_def,
fm

2023-10-10 12:31 UTC, schrockn requested changes
Looks good overall. Req'ing changes to remove additions to `AssetSpec`. I have some feedback but we can defer those to later PRs. I want to get this into master ASAP so we can iterate.

2023-10-10 12:31 UTC, schrockn reviewed
So spin this without the changes to `AssetSpec` and then we can merge.

2023-10-10 13:30 UTC, schrockn approved these changes

2023-10-10 14:21 UTC, merged