Make adding asset evaluations idempotent
dagster-io/dagster pull request #17274
Opened 2023-10-17 22:19 UTC by gibsondan

Summary:
This allows us to upsert the same evaluations in the asset daemon multiple times in the event that a tick fails

Sadly for this to work in sqlite it requires adding the evals one by one instead of in a batch. If you are using AMP on a large asset graph though, you should be using postgres or mysql, not sqlite.

Test Plan: BK

## Summary & Motivation

## How I Tested These Changes

2023-10-17 22:21 UTC, gibsondan commented on python_modules/dagster/dagster/_utils/test/schedule_storage.py
> +        # add a mix of keys - one that already is using the unique index and one that is not
wow github really struggled with identifying what i actually changed here, i just added this case at the end and put the first part in a for loop to run twice

2023-10-18 03:35 UTC, johannkm requested changes
for q about if we need upsert vs. swallowing insert conflicts and moving on. I see you added a test case where we update asset_one on eval 11 so I guess we expect to do a different write?

I don't have the latest context for how you're solving the idempotency (without the giant run batch). Does it require making evaluations mutable? I guess we could still consider them immutable once the daemon has incremented its cursor

2023-10-18 03:35 UTC, johannkm commented on python_modules/libraries/dagster-postgres/dagster_postgres/schedule_storage/schedule_storage.py
> +                AssetDaemonAssetEvaluationsTable.c.asset_key,
order doesn't matter here does it

2023-10-18 03:35 UTC, johannkm commented on python_modules/libraries/dagster-postgres/dagster_postgres/schedule_storage/schedule_storage.py
> +                "num_requested": insert_stmt.excluded.num_requested,
do we actually need to update here? Are there cases where the second time we write an evaluation, it's different?

2023-10-18 03:54 UTC, gibsondan commented
Yeah I have a scheme in mind where we first do one write without a run ID
(for tracking purposes in case the tick crashes) and then later update the
same evaluation row with the run ID once it has actually been submitted

Even if I was not doing that, I’d argue that the contract of the function
implies it should work that way though

On Tue, Oct 17, 2023 at 10:35 PM Johann Miller ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> for q about if we need upsert vs. swallowing insert conflicts and moving
> on. I see you added a test case where we update asset_one on eval 11 so I
> guess we expect to do a different write?
>
> I don't have the latest context for how you're solving the idempotency
> (without the giant run batch). Does it require making evaluations mutable?
> I guess we could still consider them immutable once the daemon has
> incremented its cursor
> ------------------------------
>
> In
> python_modules/libraries/dagster-postgres/dagster_postgres/schedule_storage/schedule_storage.py
> <https://github.com/dagster-io/dagster/pull/17274#discussion_r1363088581>:
>
> > +            [
> +                {
> +                    "evaluation_id": evaluation_id,
> +                    "asset_key": evaluation.asset_key.to_string(),
> +                    "asset_evaluation_body": serialize_value(evaluation),
> +                    "num_requested": evaluation.num_requested,
> +                    "num_skipped": evaluation.num_skipped,
> +                    "num_discarded": evaluation.num_discarded,
> +                }
> +                for evaluation in asset_evaluations
> +            ]
> +        )
> +        upsert_stmt = insert_stmt.on_conflict_do_update(
> +            index_elements=[
> +                AssetDaemonAssetEvaluationsTable.c.evaluation_id,
> +                AssetDaemonAssetEvaluationsTable.c.asset_key,
>
> order doesn't matter here does it
> ------------------------------
>
> In
> python_modules/libraries/dagster-postgres/dagster_postgres/schedule_storage/schedule_storage.py
> <https://github.com/dagster-io/dagster/pull/17274#discussion_r1363092178>:
>
> > +                    "asset_evaluation_body": serialize_value(evaluation),
> +                    "num_requested": evaluation.num_requested,
> +                    "num_skipped": evaluation.num_skipped,
> +                    "num_discarded": evaluation.num_discarded,
> +                }
> +                for evaluation in asset_evaluations
> +            ]
> +        )
> +        upsert_stmt = insert_stmt.on_conflict_do_update(
> +            index_elements=[
> +                AssetDaemonAssetEvaluationsTable.c.evaluation_id,
> +                AssetDaemonAssetEvaluationsTable.c.asset_key,
> +            ],
> +            set_={
> +                "asset_evaluation_body": insert_stmt.excluded.asset_evaluation_body,
> +                "num_requested": insert_stmt.excluded.num_requested,
>
> do we actually need to update here? Are there cases where the second time
> we write an evaluation, it's different?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dagster-io/dagster/pull/17274#pullrequestreview-1683875552>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACAPJC546772TLYENYC3SDTX75FA7AVCNFSM6AAAAAA6ERIZWCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTMOBTHA3TKNJVGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-10-18 03:57 UTC, johannkm approved these changes
sounds good

2023-10-19 21:30 UTC, merged