Fix the cursor comparison
dagster-io/dagster pull request #17625
Opened 2023-11-02 11:49 UTC by sisidra

Compare with the normalized cursor instead of user supplied one

## Summary & Motivation

As other code locations nearby state correctly - cursor value can differ between semantically equivalent json serialization formats.
This one code expression does not use normalized value, so it will return invalid results.

## How I Tested These Changes

Locally, there needs to be a unittest added.

2023-11-02 15:43 UTC, sryza commented
Hey @prha - it looks like you wrote this code initially - would you be able to take a look at this one?

2023-11-02 17:40 UTC, prha requested changes

2023-11-02 17:40 UTC, prha commented on python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py
> +        and (not cursor or asset_key.to_string() > normalized_cursor_str)
```suggestion
        and (not normalized_cursor_str or asset_key.to_string() > normalized_cursor_str)
```

2023-11-10 03:03 UTC, prha approved these changes

2023-11-10 03:04 UTC, merged