fix: add missing volumes and volumeMounts in job-instance-migrate.yaml
dagster-io/dagster pull request #17803
Opened 2023-11-08 09:12 UTC by nhuray

## Summary & Motivation

Hi community,

This is a small PR related to an issue I got yesterday migrating the Dagster instance in our environment.

I followed the documentation [here](https://docs.dagster.io/deployment/guides/kubernetes/how-to-migrate-your-instance) but the migration failed because our environment use an **external Postgres DB** (running in GCP Cloud SQL). 

The instance is configured to **only accepts SSL connections** so the `values.yaml` I use is mounting a `volume` (and a `volumeMount`) for the dagster services accessing the Database (e.g `daemon`, `webserver`...)

The issue is the `job-instance-migrate.yaml` template does not include the snippets to add the `volume` and `volumeMount`.

## How I Tested These Changes

I copied my `values.yaml` with the `volume` and `volumeMounts`.

Then I just run in the `helm/dagster` directory: 

```bash
helm template dagster . \
          --set "migrate.enabled=true" \
          --show-only templates/job-instance-migrate.yaml \
          --values values.yaml
```

2023-11-08 15:19 UTC, hivp reviewed
lgtm

2023-11-08 15:48 UTC, jamiedemaria commented
@gibsondan  is this a PR you'd be able to take a look at? feel free to pass it off to someone else too

2023-12-12 12:19 UTC, nhuray commented
@jamiedemaria any news from @gibsondan about that PR ?

2023-12-12 18:29 UTC, gibsondan requested changes
Hi @nhuray - apologies that some wires got crossed here and this didn't get into my queue until now.

I think this looks great - would it be possible to add a quick test to our helm chart test suite along the lines of https://github.com/dagster-io/dagster/blob/master/helm/dagster/schema/schema_tests/test_instance_migrate.py#L53 that verifies that these volumes and volumeMounts are propagated correctly so that we can ensure this stays working going forward? Happy to accept this once that's in place.

2024-01-11 19:22 UTC, nhuray commented
@gibsondan Sorry for the late answer I did not see your comment. 

I added a test to the Helm test suite to ensure the volumes and volumeMounts are present when we evaluate the template.

2024-01-16 17:24 UTC, gibsondan approved these changes
thanks!

2024-01-16 17:24 UTC, merged