[pipes] implicit_materialization flag
dagster-io/dagster pull request #17921
Opened 2023-11-10 21:48 UTC by alangenfeld

Makes the current behavior to produce implicit `MaterializeResult` s for assets which receive no events toggleable with a kwarg bool.

motivated by https://github.com/dagster-io/dagster/issues/17868

## How I Tested These Changes

2023-11-10 21:48 UTC, alangenfeld commented
Current dependencies on/for this PR:
* master
  * **PR #17921** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/17921?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/17921?utm_source=stack-comment).

2023-11-10 21:52 UTC, alangenfeld commented on python_modules/dagster/dagster/_core/pipes/client.py
> +    ) -> Sequence["PipesExecutionResult"]:
i went pretty far on an impl that exposed separate methods with "reported" in the name to distinguish but came back to the ol bool toggle approach. Open to any other ideas or names

2023-11-13 14:01 UTC, schrockn requested changes
Can we make this a `open_pipes_session` only feature and then only alter that `PipesSession` API? That way we can add the "reported" variant there only?

2023-11-16 19:42 UTC, alangenfeld commented
> Can we make this a open_pipes_session only feature and then only alter that PipesSession API? That way we can add the "reported" variant there only?

This would bubble to being on every `PipesClient` `run` method, which i think may be worse. What do yo think?

2023-11-16 20:00 UTC, alangenfeld commented
updated the PR to sessions/clients approach in its own commit so the two can be compared more easily. Its not as bad as i initially imagined but its still not obvious to me which is preferable.

2023-11-20 16:23 UTC, schrockn commented
> updated the PR to sessions/clients approach in its own commit so the two can be compared more easily. Its not as bad as i initially imagined but its still not obvious to me which is preferable.

I'm a bit confused here as there are still flags in this PR? Maybe I am being dense here.

2023-11-20 16:57 UTC, alangenfeld commented
My bad. Now in this PR the 3 commits are:
1. bool flag on results methods
2. bool flag on the session/clients
3. reported variants of results methods

Notably in the latest commit I added reported methods to `PipesClientCompletedInvocation` since I am skeptical that this functionality should require bailing out of clients. The reported variants of the results methods there don't feel great.

2023-11-20 17:00 UTC, alangenfeld commented on python_modules/dagster/dagster_tests/execution_tests/pipes_tests/test_subprocess.py
> +    ):
may need to tweak the `set_requires_typed_event_stream` exception content to account for this failure condition, though theres already a lot in that message

2023-11-20 17:53 UTC, schrockn commented
I generally prefer the non-boolean version of this. Open to persuasion in other direction.

2023-11-20 19:13 UTC, alangenfeld commented
While I generally dislike bool args, being able to force use by name / kwargs is a nice mitigation. 

I think the things pushing me towards bool flag over separate methods are
* the fact that this creates N additional methods instead of just 1, since `get_results` and `get_materialize_result` both need the explicitl-only flavor.
* considering when and where we need to communicate their existence to users. Should the exceptions that mention `get_results` and `get_materialize_result` also mention their `reported` siblings? Will a user seeing these variants in their IDE be able to reason about which to use? The default bool flag does a nicer job of hiding itself til you need it I think. 
 * Information entropy wise, i feel like a explicit and verbose bool argument like `implicit_materialization` (or even something longer) is fine, but making a super long method name like `get_only_explicitly_reported_results()` feels not OK. Could be i'm just missing the right method name that is clear and relatively terse.

2023-11-20 20:57 UTC, schrockn approved these changes
Cool I defer to your instincts on this. Move back to the kwarg bool and call it day 👍🏻

2023-11-27 22:28 UTC, merged