test dagster-dbt select with test tags
dagster-io/dagster pull request #17988
Opened 2023-11-14 06:15 UTC by johannkm

## Summary & Motivation

## How I Tested These Changes

2023-11-14 06:16 UTC, johannkm commented
Current dependencies on/for this PR:
* master
  * **PR #17988** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/17988?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/17988?utm_source=stack-comment).

2023-11-15 15:17 UTC, rexledesma requested changes
Looks good, just remove the cruft

2023-11-15 15:17 UTC, rexledesma commented on python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/test_dagster_asset_checks/models/schema.yml
> -              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
revert

2023-11-15 15:17 UTC, rexledesma commented on python_modules/libraries/dagster-dbt/dagster_dbt_tests/dbt_projects/test_dagster_asset_checks/partial_parse.msgpack
remove these other artifacts (partial_parse, perf_info, semantic_manifest)

2023-11-15 19:55 UTC, rexledesma approved these changes

2023-11-15 21:19 UTC, merged