Only consider/resolve the specific job being executed in a run worker or step worker
dagster-io/dagster pull request #18908
Opened 2023-12-27 16:04 UTC by gibsondan

Summary:
Addresses a perf bottleneck when there are a lot of jobs and resolving their assets or resource requirements takes a long time.

## Summary & Motivation

## How I Tested These Changes

2023-12-27 16:07 UTC, gibsondan commented on python_modules/dagster/dagster/_grpc/impl.py
> +    os.environ["DAGSTER_RUN_JOB_NAME"] = recon_pipeline.job_name
this was set in all the other run launchers already

2024-01-02 17:26 UTC, gibsondan commented
somewhat unsure about this (global env var determining behavior seems a bit gross) but wanted to send it out for thoughts - technically this is something the user could also do while defining their definitions

2024-01-02 17:37 UTC, alangenfeld reviewed
> when there are a lot of define_asset_job jobs and resolving their assets or resource requirements takes a long time

The `jobs` argument on `CachingRepositoryData` already supports taking a callable for deferring resolution as referenced in the `from_dict` doc block. Does moving the `unresolved_job_def.resolve` call in to callable and deferring it get the heavy parts out of the critical path for run setup? 

This current implementation feels a bit brittle and spooky to me. I think I could get behind the env var changing behavior, but would want to see some heavier modeling of that behavior difference instead of sprinkling in `continue`s  and the like.

2024-01-02 18:49 UTC, gibsondan commented
That would also resolve it, yeah - we might lose some resource validation that currently happens there though (which is probably fixable, you could do that validation when its lazily resolved later)

2024-01-05 16:55 UTC, alangenfeld requested changes
to your queue

2024-01-17 18:07 UTC, closed without merging