feat: Add optional resources to initContainers
dagster-io/dagster pull request #19212
Opened 2024-01-15 12:28 UTC by MattyKuzyk

## Summary & Motivation
In our organization, strict OPA policies are enforced to make sure `resources` are specified on every container, including `initContainers`. To this end, this PR allows users to specify limits for `initContainers` within the daemon and the webserver.

I made it so that both init containers have their resources specified in the same block. I don't think anything more precise than that is necessary.

## How I Tested These Changes
I tested these changes by packaging the helm chart locally, then installing to my local Docker desktop cluster via the following:

```
helm install dagster dagster-0.0.1-dev.tgz --set dagsterWebserver.image.tag=latest --set dagsterDaemon.image.tag=latest --set pipelineRun.image.tag=latest --set dagsterDaemon.initContainers.resources.limits.cpu=200m
```

I also made some changes to the `values` before packaging for updating the user deployments.

I then verified that the interface works and that the resources I specified were present. I also verified that there were no resources present on the `dagsterWebserver` pod:
```
  initContainers:
  - command:
    - sh
    - -c
    - until pg_isready -h dagster-postgresql -p 5432 -U test; do echo waiting for
      database; sleep 2; done;
    image: library/postgres:14.6
    imagePullPolicy: IfNotPresent
    name: check-db-ready
    resources:
      limits:
        cpu: 200m
      requests:
        cpu: 200m
```

2024-01-17 20:19 UTC, gibsondan requested changes
thanks for sending this out!

I put one naming suggestion inline. You'll also want to update the JSON schema following the guidelines here: https://github.com/dagster-io/dagster/blob/master/helm/dagster/README.md?plain=1#L104

and finally it would be good to add a test that uses the new field like the ones here: https://github.com/dagster-io/dagster/blob/master/helm/dagster/schema/schema_tests/test_dagit.py#L476

Then this should be good to go!

2024-01-17 20:19 UTC, gibsondan commented on helm/dagster/schema/schema/charts/dagster/subschema/daemon.py
> +    initContainers: Optional[Dict[str, kubernetes.Resources]]
I think the type here should just be kubernetes.Resources as currently written (unless it was originally intended to be a map from container name to resources?)

2024-01-22 19:23 UTC, gibsondan commented
Ran unit tests on this and it looks clean other than some minor auto-formatting things: https://buildkite.com/dagster/unit-tests/builds/353 - can you run "make ruff" in the checked out dagster repo to resolve them and re-update? I can also checkout the fork and push an update when I have a sec to do so

2024-01-23 00:19 UTC, MattyKuzyk commented
Apologies, done.

2024-01-29 05:17 UTC, MattyKuzyk commented
Bump @gibsondan 🙏

2024-01-29 15:43 UTC, gibsondan commented
Landing this in https://github.com/dagster-io/dagster/pull/19465 after one small tweak and a rebase to make sure that the generated Helm schema is up to date. Thanks again for sending this out!

2024-01-30 07:06 UTC, closed without merging