feat: Use automountServiceAccountToken false
dagster-io/dagster pull request #19217
Opened 2024-01-15 17:32 UTC by MattyKuzyk

## Summary & Motivation
In our organization, strict OPA policies are enforced to make sure that the service account token isn't auto-mounted into the service account. This change makes the service account token "opt-in" for any deployments that wish to use it. As I understand it, making this configurable isn't necessary since this is strictly a more secure opt-in way of doing things.

Other Helm charts, such as Pachyderm, make the same opinion [here](https://github.com/pachyderm/pachyderm/blob/1515ce37fa789069ccb731d44ccc41a8e6429018/etc/helm/pachyderm/templates/pachd/rbac/serviceaccount.yaml#L8).

## How I Tested These Changes
Packaged the Helm chart and installed it on my local `docker-desktop`. Successfully ran a job. Upon inspecting the dagster webserver pod, I can see the following in the pod spec:

```
spec:
  automountServiceAccountToken: true
  containers:
  - command:
    - /bin/bash
    - -c
    - ' dagster-webserver -h 0.0.0.0 -p 80 -w /dagster-workspace/workspace.yaml'```

2024-02-01 17:05 UTC, gibsondan requested changes
to ensure that this is not a breaking change we need to ensure that any pods that are created and use this service account also set automountServiceAccountToken: True, correct?

if that's the case then i think there are some other spots that need coverage:
- additional places that create pods using dagster.serviceAccountName, e.g. https://github.com/dagster-io/dagster/blob/master/helm/dagster/templates/deployment-celery-queues.yaml#L38 (grepping for dagster.serviceAccountName and dagsterUserDeployments.serviceAccountName should catch all of these)
- trickier would be the run pods that are created using that service account. I think that would require adding automountServiceAccountToken under pod_spec_config here? https://github.com/dagster-io/dagster/blob/master/helm/dagster/charts/dagster-user-deployments/templates/helpers/_helpers.tpl#L140-L146

2024-02-05 02:47 UTC, MattyKuzyk commented
@gibsondan Good catch. I'll update those.

Note that our team is successfully using User Code Deployments in our deployment with the code already in this PR. We use the K8s run launcher and the default executor but launch our workloads via K8s Pipes.

Questions/observations:

- On our deployment, the run manager pods `dagster-run-*` all have `automountServiceAccountToken: true`, I believe it's inherited from the user code deployment due to `includeConfigInLaunchedRuns.enabled = true`. To not break backwards compatibility, as you said we need to update the run launcher itself. Not sure if I should do this in the `pod_spec_config` or directly in the `k8s_run_launcher`. I think the latter would be best.
- Executors. Like I said we launch our workloads via pipes from the run launcher inprocess. When the pods are spawned via the k8s or celery executors they will also need to include this field I believe? Will also look into it.

2024-02-05 03:21 UTC, gibsondan reviewed
i'm not aware of anything that would automatically propagate automountServiceAccountToken: true from the user code deployment to the run launcher from just the code that's in this PR - the change I suggested was intended to make it propagate when includeConfigInLaunchedRuns is set.

2024-02-05 03:22 UTC, gibsondan reviewed
i think you're correct that the change would need to be in the run launcher though - you would want it to be set for everybody, even people who don't have includeConfigInLaunchedRuns set.

2024-02-05 08:43 UTC, MattyKuzyk commented
Now `automountServiceAccountToken` will be set to true via the `construct_dagster_k8s_job` function whenever the run manager is spawned.

The [executors](https://github.com/dagster-io/dagster/blob/0dd0e9f9c72a123beb363b2665cb066de3eea90e/python_modules/libraries/dagster-k8s/dagster_k8s/executor.py#L279) seem to use this as well to generate their config. I added a test to the executor and job unit tests to ensure the field is there.

Let me know if this is sufficient or if there is a better way. The code to generate all this config is a bit above my head. I believe it's better to do it here than to put it in Helm, as it's a required field.

2024-02-05 17:26 UTC, gibsondan approved these changes
That should work. Thanks!

2024-02-05 17:26 UTC, merged

2024-02-09 10:39 UTC, audriusb commented
next time, add it swichable in the values. now it brakes if the automount was in use.

2024-02-09 12:17 UTC, gibsondan commented
Hi @Audrius, can you share more details about the problem that you’re
seeing? The intention was that every pod spun up by dagster would still be
mounting the service token.

On Fri, Feb 9, 2024 at 4:39 AM Audrius ***@***.***> wrote:

> next time, add it swichable in the values. now it brakes if the automount
> was in use.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dagster-io/dagster/pull/19217#issuecomment-1935691624>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACAPJCZTEVYU7A5UQJJQFPTYSX4FXAVCNFSM6AAAAABB3TTT6GVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMZVGY4TCNRSGQ>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2024-02-09 12:26 UTC, audriusb commented
So what we get is, that user-deployment uses a service account, and when jobs are launched, they fail not being able to find token file.
Manually changing it back to: true on the SA itself helped.
Locking on a previous chart version helped as well.
I will look into what is exactly wrong here on Monday and come back with more. Info

2024-02-09 12:30 UTC, gibsondan commented
Do you have a stack trace for the error that you’re seeing? There should
have been a change in this PR that still mounted the service token whenever
a job was launched - it was just the default value on the service account
that was changed.

On Fri, Feb 9, 2024 at 6:26 AM Audrius ***@***.***> wrote:

> So what we get is, that user-deployment uses a service account, and when
> jobs are launched, they fail not being able to find token file.
> Manually changing it back to: true on the SA itself helped.
> Locking on a previous chart version helped as well.
> I will look into what is exactly wrong here on Monday and come back with
> more. Info
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dagster-io/dagster/pull/19217#issuecomment-1935840622>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACAPJC6KQRF7N2UATKABJDLYSYIY7AVCNFSM6AAAAABB3TTT6GVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMZVHA2DANRSGI>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2024-02-09 17:46 UTC, gibsondan commented
@audriusb thinking more, one situation where I could imagine this happening is if you are using the k8s_job_executor to run each step in its own kubernetes pod and your dagster code is still running an older version - is the error that you're seeing when trying to spin up a new pod for a step/op? If it's for a run I'm confused why the Python change in this PR wouldn't account for that.

2024-02-09 17:48 UTC, audriusb commented
I'm sorry for being a bit rude before. It's weekend already and i wont get to my conputer until Monday. Will look more closely into what is actually going on. Yes, i think that was k8s executor, but i can't confirm atm.

2024-02-09 20:19 UTC, gibsondan commented
No problem at all, thanks for reporting the problem - if it was in the k8s_job_executor, I sent out a change that should give us a better back-compat story here: https://github.com/dagster-io/dagster/pull/19716 - we should be able to include this in our next release. Updating the code that your jobs are using to also use dagster 1.6.4 should also resolve the problem as a workaround if that's an option.

2024-05-15 16:52 UTC, paralyzah commented
I agree with @audriusb. It will much better if you will leave some room for templating of automountServiceAccountToken on values.yaml level. For instance, in our environments any workload with automountServiceAccountToken: true will be rejected.