[external-assets] Allow asset jobs to combine materializations and observations
dagster-io/dagster pull request #19667
Opened 2024-02-07 23:40 UTC by smackesey

## Summary & Motivation

## How I Tested These Changes

2024-02-07 23:40 UTC, smackesey commented
Current dependencies on/for this PR:
* `master`
  * **PR #19667** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/19667?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/19667?utm_source=stack-comment).

2024-02-08 12:07 UTC, smackesey commented on python_modules/dagster/dagster_tests/definitions_tests/test_external_assets.py
> +    }
Cleaner to test dependencies in the definitions asset graph than the global asset job, which is an implementation detail.

2024-02-12 21:01 UTC, schrockn reviewed
Some intermediate comments while I process this more. As I stated in slack, I consider this diff extremely risky as written and I implore you to consider approaches that break this up into smaller, more incremental, lower risk changes. I can grab some time with you later.

2024-02-12 21:43 UTC, smackesey commented on python_modules/dagster/dagster_tests/definitions_tests/test_external_assets.py
> +    job_def_with_shim = get_job_for_assets(defs_with_shim, an_asset)
We no longer need to provide the external asset when getting the job that uses it purely for loading.

2024-02-13 02:04 UTC, schrockn requested changes
Per offline discussion, @smackesey is going to do a series of pre-refactors to `build_assets_job` and `from_graph_and_assets_node_mapping` to make incremental changes to those functions more palatable.

2024-03-01 19:07 UTC, smackesey commented
@schrockn This PR was originally large and did a lot but is now small and does only what the title describes. Summary updated.

2024-03-11 16:41 UTC, schrockn approved these changes
Very exciting!

2024-03-11 17:01 UTC, merged