[external-assets] Standardize terminology on "execution unit"
dagster-io/dagster pull request #20140
Opened 2024-02-28 23:03 UTC by smackesey

## Summary & Motivation

## How I Tested These Changes

2024-02-28 23:04 UTC, smackesey commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20140?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* **#20132** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20132?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#20114** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20114?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#20140** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20140?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#20129** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20129?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#20118** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20118?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/20140?utm_source=stack-comment).

2024-03-01 19:10 UTC, OwenKephart approved these changes
certainly an improvement 🙏

2024-03-04 20:42 UTC, schrockn commented
So to be clear, an "execution unit" is defined as a "a set of assets and asset checks that must be executed together because they are attached to the same op and `can_subset` is false"

?

2024-03-04 20:54 UTC, smackesey commented
>So to be clear, an "execution unit" is defined as a "a set of assets and asset checks that must be executed together because they are attached to the same op and can_subset is false"?

Sounds accurate to me

2024-03-05 16:53 UTC, schrockn requested changes
Per zoom convo:

execution unit -> execution set (the set of asset or check sets executed together)
atomic execution id -> execution set identifier

2024-03-05 16:53 UTC, schrockn commented
cc: @OwenKephart for your thoughts on this naming proposal

2024-03-05 19:29 UTC, smackesey commented
I've performed the rename to "execution_set_identifier"

2024-03-05 20:06 UTC, OwenKephart commented
@schrockn @smackesey to be honest, I'm not seeing a major difference between "execution unit" and "execution set" -- fine with this outcome.

2024-03-05 20:55 UTC, schrockn commented
> [kn](https://github.com/schrockn) @smackesey to be honest, I'm not seeing a major difference between "execution unit" and "execution set" -- fine with this outcome.

@OwenKephart the thinking is that the word "set" indicates the "set of keys in an asset graph that must be executed together". This aligns with the `can_subset` language in our public API.

2024-03-05 21:55 UTC, schrockn approved these changes

2024-03-05 22:02 UTC, merged