[external-assets] Create external assets defs for undefined assets in repo construction
dagster-io/dagster pull request #20145
Opened 2024-02-29 13:25 UTC by smackesey

## Summary & Motivation

## How I Tested These Changes

2024-02-29 13:26 UTC, smackesey commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20145?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* **#20145** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20145?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#20140** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20140?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#20114](https://github.com/dagster-io/dagster/pull/20114) <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20114?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* **#20129** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20129?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#20118** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20118?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/20145?utm_source=stack-comment).

2024-03-04 20:40 UTC, schrockn commented
Does this cause any user-facing changes? Do we render bare asset key references differently?

2024-03-04 20:53 UTC, schrockn requested changes
Req'ing changes for q mgmt

2024-03-04 21:22 UTC, smackesey commented
>Does this cause any user-facing changes? Do we render bare asset key references differently?

I didn't realize this but it turns out that we do. Given these defs with `foo_source` "bare" and `bar_source` a defined `SourceAsset`:

```
### 240304-stub_vs_source.py

from dagster import (
    asset,
    Definitions,
    AssetExecutionContext,
    SourceAsset,
)



@asset(deps=["foo_source"])
def foo(context: AssetExecutionContext):
    ...

bar_source = SourceAsset("bar_source")

@asset
def bar(context: AssetExecutionContext, bar_source):
    ...

defs = Definitions(
    assets=[foo, bar, bar_source],
)
```

Before this PR:

<img width="1092" alt="Screenshot 2024-03-04 at 4 13 38 PM" src="https://github.com/dagster-io/dagster/assets/1531373/bacd5065-843d-4194-9e83-1bf415dd42a1">

After this PR:

<img width="1092" alt="Screenshot 2024-03-04 at 4 14 14 PM" src="https://github.com/dagster-io/dagster/assets/1531373/df0fbbb2-79ae-48d4-a782-b280119312ec">

I'm not really sure why we do this since both `foo_source` and `bar_source` are AFAICT treated otherwise identically, but maybe we stick some special metadata on the auto-created stub defs to keep rendering the same?

2024-03-05 12:47 UTC, schrockn commented
@smackesey on reflection I think this actually a fairly important product decision.

It gives us the opportunity to allow people to model external assets without even forcing them to explicitly learn the concept upfront. It will just appear in the UI. However we need to be deliberate about that decision as there are arguments both ways.

We should either

1) Do nothing
2) Add metadata to retain the old behavior
3) Propose this change to (esp Sandy and Josh) in an internal discussion

2024-03-05 14:00 UTC, smackesey commented
So after some further investigation, the rendering change is smaller than I thought. The above difference I showed is _only_ observed when looking at the default asset group. There is no change when looking at an asset job, which looks like this both before and after the change:

![image](https://github.com/dagster-io/dagster/assets/1531373/3b4c7331-facc-4851-8b05-7b83f356ff9c)

I believe the status quo style is probably not the result of a principled decision. Basically, the same graph rendering code is used for op-jobs, asset-jobs, and asset groups. The "small" style is used to show that a job is loading from source assets that aren't defined in the job, or an asset group has dependencies outside the group. The reason we see a difference when viewing the default group is that, in the status quo, the `group_name` of the `ExternalAssetNode` representing bare dependencies is null, whereas after this change it is `default`.

Further, I don't think the group name was ever _intended_ to be set to null for bare dependencies, because we explicitly set it when defining the `ExternalAssetNode` for them-- it just happens to always be `None` because of the convoluted logic of `get_external_asset_nodes_from_defs:

```
    asset_keys_without_definitions = all_upstream_asset_keys.difference(assets_defs_by_key.keys())

    asset_nodes = [
        ExternalAssetNode(
            asset_key=asset_key,
            dependencies=list(deps[asset_key].values()),
            depended_by=list(dep_by[asset_key].values()),
            execution_type=AssetExecutionType.UNEXECUTABLE,
            job_names=[],
            group_name=group_name_by_asset_key.get(asset_key),  ## HERE
            code_version=code_version_by_asset_key.get(asset_key),
        )
        for asset_key in asset_keys_without_definitions
    ]
```

In any case, I updated the PR to keep the `group_name` of a bare dep as null until we make the above decision. I hope that allows us to proceed with this PR w/out being blocked on that decision. (Bare deps were already represented as `ExternalAssetNode`, the initially observed rendering change here was just from a slight change to the representation, i.e. having group name become `"default"`).

FWIW I favor option (3), i.e. feel that bare deps should be treated just like explicitly defined SourceAsset. I had some discussion on it with @OwenKephart here: https://dagsterlabs.slack.com/archives/C03A0D72A6T/p1709238575807419

2024-03-05 16:42 UTC, schrockn approved these changes
Can you create linear task for eliminating SYSTEM_METADATA_KEY_AUTO_CREATED_STUB_ASSET and link to the issue in the places where we will want to delete when we come to a resolution on what to do about these bare references?

2024-03-05 18:32 UTC, merged