Typed dict validation
dagster-io/dagster pull request #20248
Opened 2024-03-04 23:34 UTC by dpeng817

Method for validating a passed in typed dict. This is useful for anomaly detection stuff.

2024-03-04 23:34 UTC, dpeng817 commented
* **#20248** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20248?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dpeng817 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-03-05 23:27 UTC, sryza reviewed
I wonder if this should be inside `dagster._check`?

2024-03-07 00:35 UTC, sryza commented
See question above

2024-03-07 00:44 UTC, dpeng817 commented
ah whoops forgot to re-push. I did end up moving it @sryza

2024-03-07 15:57 UTC, sryza requested changes
I wonder if it would make sense for `check.inst` to handle this behavior.

```python
check.inst(my_dict, MyTypedDictClass)
```

Not strongly held though. I requested changes only based on my comment about argument order.

2024-03-07 15:57 UTC, sryza commented on python_modules/dagster/dagster/_check/__init__.py
> +def validate_typeddict(cls: Type[_TypedDictClass], potential_typeddict: dict) -> _TypedDictClass:
I think we should switch the arg order here, for consistency with `isinstance` and `check.inst`

2024-03-07 16:09 UTC, dpeng817 commented
I think that's somewhat of a misuse of the terminology, the passed-in dict isn't an "instance" of the typed dict in the traditional sense, it just matches the spec, so I'd prefer to just keep the methods separate/explicit about what they're doing.

2024-03-07 21:54 UTC, dpeng817 commented
no longer necessary - switched to pydantic basemodels.

2024-03-07 21:54 UTC, closed without merging