TiemstampMetadataValue
dagster-io/dagster pull request #20328
Opened 2024-03-07 15:48 UTC by sryza

## Summary & Motivation

Introduces a `TimestampMetadataValue` type, that wraps a Unix timestamp. The advantage of using this metadata type instead of a float is that the frontend can display it as a timezone instead of as a bug number.  Does not contain a timezone, so the frontend can display it in a timezone that's consistent with the rest of the timezones on the frontend.

Issue: https://github.com/dagster-io/dagster/issues/13344

## How I Tested These Changes

2024-03-08 15:35 UTC, hellendag commented
The TypeScript errors [here](https://buildkite.com/dagster/dagster-dagster/builds/77980#018e1c44-d4bd-437a-b66e-0a0ee78f305b/211-429) are legit, you'll need to update the relevant switch statements to include the new type.

2024-03-08 15:44 UTC, hellendag requested changes
Just requesting the changes to fix the TS errors. Otherwise seems fine to me. Let me know if I can be of help getting the UI in place.

2024-03-08 16:52 UTC, sryza commented on python_modules/dagster/dagster/_core/definitions/metadata/__init__.py
> +                datetime is provided, the timestamp will be extracted. datetimes without timestamps
thanks for catching

2024-03-08 18:38 UTC, sryza commented
>  Let me know if I can be of help getting the UI in place.

Can I take you up on this? Made a change that I thought would fix it, but still seeing an error. And not sure about how to get them to show up as formatted datetimes.

2024-03-14 20:02 UTC, hellendag approved these changes

2024-03-14 21:24 UTC, merged