Optimize querying with latest_run_required_tags
dagster-io/dagster pull request #20333
Opened 2024-03-07 18:02 UTC by OwenKephart

## Summary & Motivation

Previously, if you had many upstream updated partitions, we'd need to do an individual "latest_materialization_record" query for each of them.

Now, we take advantage of the fact that we do a single batched fetch of the latest materialization storage ids for each upstream partition, meaning we know the storage ids of all the records we need to fetch. From there, we can do a single call (per upstream asset, assuming there aren't more than 10,000 updated partitions) to fetch the records for each of those storage ids.

After doing some perf-checking, this is not actually a silver bullet, as if there is only a single upstream partition that needs to be checked, the perf gain is pretty unimpressive. It's basically just that the query time no longer scales very quickly in relation to the number of upstream updated partitions. So before if there were 100 upstream updated partitions that needed to get queried, that'd take like 20 seconds, and now it'll still take ~1 second.

## How I Tested These Changes

2024-03-07 18:02 UTC, OwenKephart commented
* **#20333** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20333?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @OwenKephart and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-03-21 15:51 UTC, gibsondan commented on python_modules/dagster/dagster/_core/definitions/auto_materialize_rule.py
> +        step = get_max_event_records_limit()
i'm seeing some indication in my testing that this step limit may be a little high (hitting some 15 second timeouts when there are actually >10k events to fetch, e.g. in a large empty-cursor run) - in real life the timeout is higher than 15 seconds, but we may still want more headroom here

2024-04-02 16:22 UTC, gibsondan requested changes
i think we should lower the default batch size here (maybe 1000?) and make it configurable via env var, otherwise i am very excited to ship this

2024-04-24 00:53 UTC, gibsondan approved these changes

2024-04-24 00:59 UTC, merged