Make check.inst and check.opt_inst type-narrowing
dagster-io/dagster pull request #20431
Opened 2024-03-12 13:05 UTC by schrockn

## Summary & Motivation

We previously had a discussion about making check.inst type-narrowing. I cannot recall the exact tradeoffs but in my mind it makes no sense to have the parameter of `inst` be typed to T. `inst` should be useful for bridging the gap between typed and untyped code, or to deal with APIs where `isinstance` is required and it is ergonomic to return the value you are checking. 

Other you are forced to do patterns like

```python
# super confusing because the cast is a lie
check.inst(cast(int, untyped_value), int)
```
or
```python
check.inst(untyped_value, int)
assert isinstance(untyped_value) # appease typechecker
```

Much more satisfying is the one liner that requires no additional imports:

```python
int_value = check.inst(untyped_value, int)
```

## How I Tested These Changes

BK

2024-03-12 13:05 UTC, schrockn commented
* **#20431** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20431?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @schrockn and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-03-12 13:07 UTC, schrockn reviewed
@smackesey I know you will have opinions here

2024-03-12 19:36 UTC, alangenfeld reviewed
I don't see how `T` is connected to to the `ttype: TypeOrTupleOfTypes` argument here. Looks like `pyright` isn't happy with this in its current form either.

Theres this comment here
https://github.com/dagster-io/dagster/blame/master/python_modules/dagster/dagster/_check/__init__.py#L616-L618
originating from https://github.com/dagster-io/dagster/commit/f613452a3b328db0edaf7f1ab314594bc645b538

from when I tried to hook this up initially and it did not work. Not sure exactly what `issues with abstract classes` means. Maybe this is something pyright can handle better now.

2024-03-12 19:47 UTC, alangenfeld requested changes
I am not aware of an argument to not have check.inst narrow if you can get it working. Back to you to try it out and see if you can get `pyright` passing.

2024-03-12 19:59 UTC, smackesey commented
+1 to Alex's comment. It would be great if this worked, I have tried to make it work before-- maybe pyright has evolved sufficiently to allow this.

To make this work you'd need to bind `T` using the `ttype` arg though.

2024-03-13 14:59 UTC, schrockn commented
Closing based on the fact that this didn't work!

2024-03-13 14:59 UTC, closed without merging