strict_dataclass
dagster-io/dagster pull request #20461
Opened 2024-03-13 21:02 UTC by sryza

## Summary & Motivation

This one was a doozy.

Introduces a `@strict_dataclass` decorator, with the aim of replacing our usage of `NamedTuple` and `pydantic.BaseModel`.

#### Why not `pydantic.BaseModel`?

1. This would require remembering to use `frozen=True`, which is annoying and error-prone.
1. It doesn't work with positional arguments. Even if we declare positional arguments bad for new classes, many of our existing NamedTuples are public APIs that will need to support positional arguments for the forseeable future.

#### Why not `@pydantic.dataclass(frozen=True, config=dict(extra="forbid"))`

This would require remembering to use `frozen=True, config=dict(extra="forbid")`, which is annoying and error-prone.

## How I Tested These Changes

2024-03-13 21:12 UTC, maximearmstrong approved these changes
💯

2024-03-13 21:18 UTC, schrockn requested changes
Based on [brief](https://github.com/pydantic/pydantic/issues/710) googling I'm not persuaded that we should wrap `dataclass` rather than `BaseModel`.  

`BaseModel` is the main way that people use pydantic and I think our default position should be reflecting the default way that people use it.

I'm also a little wary of adding the dependency on `dataclass_transform` here.

2024-03-13 21:19 UTC, schrockn commented
How many of our namedtuples are public APIs and would need to support positionals?

I also think it would be fairly straightforward to support positional by customizing `__init__` our subclass.

2024-03-13 21:34 UTC, sryza commented
> BaseModel is the main way that people use pydantic and I think our default position should be reflecting the default way that people use it.

Do you have evidence for this? Also, my suspicion is that a lot more people are familiar with dataclasses than pydantic.

> I'm also a little wary of adding the dependency on dataclass_transform here.

`pydantic.dataclasses.dataclass` already uses it FWIW (which is how I discovered it).

2024-03-13 21:42 UTC, sryza commented
> How many of our namedtuples are public APIs and would need to support positionals?

This is a sample from scanning through the first ~third of our public exports:
- AssetCheckSpec
- AssetCheckKey
- AssetKey
- AssetIn
- AssetMaterialization
- AssetOut
- DataProvenance
- DataVersion
- DependencyDefinition
- MultiDependencyDefinition
- NodeInvocation
- GraphIn
- GraphOut
- In
- Out
- InputMapping
- OutputMapping

2024-03-13 21:50 UTC, schrockn commented
> Do you have evidence for this? Also, my suspicion is that a lot more people are familiar with dataclasses than pydantic.

All of their docs lead with it:

<img width="786" alt="Screenshot 2024-03-13 at 5 49 03 PM" src="https://github.com/dagster-io/dagster/assets/28738937/909e0f1e-36d3-4969-abd3-627f4c0ac8a1">

All examples of pydantic usage I've ever seen uses `BaseModel`

Dataclasses are presented as a compatibility layer.

If we want the dataclass API, why not just wrap the out-of-the-box dataclass in python?

2024-03-13 21:53 UTC, sryza commented
> All of their docs lead with it:

Fair.

> If we want the dataclass API, why not just wrap the out-of-the-box dataclass in python?

It doesn't do runtime type-checking, so it wouldn't be a replacement for all the type-checking code we have.

2024-03-13 22:50 UTC, schrockn commented
> It doesn't do runtime type-checking, so it wouldn't be a replacement for all the type-checking code we have.

Ah yes of course. 

> @schrockn it's certainly not the only benefit of pydantic, but probably the number 1 thing that makes me excited about switching from NamedTuples to pydantic is the opportunity to get rid of all our boilerplate constructors. So would be very sad to move to a pydantic approach that requires to keep many of these.

Yes that will be nice. However just to manage expectations that we will still need custom initializers for any serdes class that has changed, or for any class where we want to massage arguments (e.g. CoercibleToAssetKey argument that ends up an AssetKey field).

In terms of my comment "I also think it would be fairly straightforward to support positional by customizing __init__ our subclass" I want to be clear I'm talking about supporting this is our own BaseModel class, rather than forcing all subclasses to customize __init__

2024-03-13 22:58 UTC, sryza commented
> In terms of my comment "I also think it would be fairly straightforward to support positional by customizing init our subclass" I want to be clear I'm talking about supporting this is our own BaseModel class, rather than forcing all subclasses to customize init

Ah I misunderstood.  If we can find a way to do this then I agree that's the best option.  However I did a bunch of investigation on this this morning and couldn't figure out a way to do it that preserves static type checking.  If you have ideas about avenues to investigate to get this to work, I'd be happy to explore them.

2024-03-14 01:41 UTC, sryza commented
> In terms of those existing public classes, a good deal of them require custom initialization anyways.

Of the classes listed in my comment [above](https://github.com/dagster-io/dagster/pull/20461#issuecomment-1995914556), I believe the 6 whose names start with "Asset" all require special constructors, and the other 10 do not.  When I sampled a few more further down in the file, I got a similar ratio.

> My recommendation is a dagster-specific class Inheriting from BaseModel (that sets frozen to True, etc) rather than a dataclass wrapper since that is "standard"/"default" pydantic.

Yeah this was the first thing that I tried and it has a lot of things going for it. But still concerned about the amount of boilerplate it implies.

> I would be surprised if there weren't edge case bugs in the cross product of pydantic versions, python versions, and typing_extension versions in the dataclass wrapper variant. Whereas in the above there is less chance of that.

Would definitely be bad if this were the case. FWIW the minimum version of pydantic that we support imports typing_extensions.dataclass_transform: https://github.com/pydantic/pydantic/blob/v1.10.1/pydantic/dataclasses.py#L39


I suspect you won't be super hot on this, but just to enumerate the space of options, another direction to consider is supporting both. E.g. we could have a subclass of  `BaseModel` similar to your example above as our general recommended way of defining new classes, and also a `@strict_dataclass_positional_args` decorator for the subset with positional args.

2024-03-14 05:25 UTC, sryza commented
A point against the dataclass approach, which gives me pause, is that overriding __init__ gets more complicated. Will need to play around with this but I think we might need to override __new__ instead.

2024-03-14 10:53 UTC, schrockn commented
> Of the classes listed in my comment https://github.com/dagster-io/dagster/pull/20461#issuecomment-1995914556, I believe the 6 whose names start with "Asset" all require special constructors, and the other 10 do not. When I sampled a few more further down in the file, I got a similar ratio.

Don't think so. Any of them that have `dagster_type` need one because of:

```python
        return super(In, cls).__new__(
            cls,
            dagster_type=(
                NoValueSentinel
                if dagster_type is NoValueSentinel
                else resolve_dagster_type(dagster_type)
            ),
```

> Yeah this was the first thing that I tried and it has a lot of things going for it. But still concerned about the amount of boilerplate it implies.

Given the above (and the point about serializable classes), I think both approaches have similar amounts of boilerplate in practice and in the cases where we do need a custom constructor we won't need the check calls so it will feel quite a bit better.

2024-03-14 11:59 UTC, schrockn commented
Serdes change POC: https://github.com/dagster-io/dagster/pull/20470

2024-03-14 20:20 UTC, closed without merging