fix: remove input path logging causing false positives on source assets updated
dagster-io/dagster pull request #20521
Opened 2024-03-16 12:36 UTC by ion-elgreco

## Summary & Motivation
The UPathIOManager adds for no reason the path on the input asset, if the input asset is a source asset now it will have an additional observation causing a false positive across your asset lineage thinking all the assets are now outdated even though the source asset did not get a new version.

## How I Tested These Changes

2024-03-20 23:02 UTC, stickyhipp requested changes
Hi @ion-elgreco - Thanks for this fix, are you able to add test coverage and I can get it merge.  Thanks!
-Peter

2024-03-25 16:07 UTC, ion-elgreco commented
@stickyhipp sorry for the late response, but why would this need test coverage? It's simply a removal, I would be testing if input_metadata is empty (which is already normal behavior).

2024-04-04 21:07 UTC, OwenKephart commented
@ion-elgreco I think the core issue that you're experiencing indicates a problem with the auto-materialize system, rather than this specific decision to emit an AssetObservation when loading an input or not. While I don't think it's a hard requirement that this metadata be emitted, I'd prefer a solution that fixes the problem in the auto-materialize system, as other IOManagers may independently decide to emit metadata during the loading process, and would experience the same error in that case.

In general, the intended behavior for the eager policy is to only materialize a downstream asset in response to an upstream source being observed in the case that:

a) it is an observable source asset (not just a regular SourceAsset), and
b) the new observation has a non-None DataVersion value set, which is different from the previously-observed DataVersion for that observable source

So in this case, because those observations produced by the IOManager do not have data versions set, the expected behavior would be that no materialization would be launched in response, and seeing something different there points to a bug.

That being said, I was not able to reproduce this error in either of the following ways, running on the latest version of Dagster (in each case, the AMP system fired a single run for the downstream asset, then stopped, even though asset observations were recorded when inputs were loaded):

```python
from dagster import AutoMaterializePolicy, SourceAsset, asset

src = SourceAsset("src")


@asset(auto_materialize_policy=AutoMaterializePolicy.eager())
def downstream(src):
    return src
```

```python
from dagster import AutoMaterializePolicy, asset, observable_source_asset
from dagster._core.definitions.data_version import DataVersion


@observable_source_asset
def src():
    return DataVersion("0")


@asset(auto_materialize_policy=AutoMaterializePolicy.eager())
def downstream(src):
    return src
```

Are you able to produce a minimal repro of this behavior?

2024-04-19 11:28 UTC, ion-elgreco commented
@OwenKephart are you guys looking into this UI bug?

2024-04-19 21:42 UTC, OwenKephart commented
@ion-elgreco we are currently working on updating the backend computation of these statuses, which should resolve this issue

2024-04-30 09:12 UTC, closed without merging