ScheduleDefinition: Unhelpful Depreciation Raise
dagster-io/dagster pull request #20523
Opened 2024-03-16 20:56 UTC by 2Ryan09

## Summary & Motivation
There is a `DepreciationWarning` for the `ScheduleDefinition` constructor that triggers regardless of the inputs given. 

Given the `DepreciationWarning` indicates the depreciation of the use of `environment_vars` in the constructor, expected use would no emitting of the warning when the `environment_vars` is unused.

**Cause**: `check.opt_mapping_param` returns `dict()` when the object passed into it is `None`. This is counter to to the `@deprecated` decorator which required a value of `None` to not emit the warning.

## How I Tested These Changes

This showed up in our local usage of dagster in an attempt to find `DeprecationWarning`s across the codebase, in which this one we are unable to resolve due to the inconsistent behavior mentioned above. 

This PR includes a `test__empty_schedule_definition__no_raise_DepreciationWarning` which fails upon any `DeprecationWarning` raised when constructing an empty `ScheduleDefinition`.

2024-03-18 23:36 UTC, sryza commented
@2Ryan09 I'm surprised that you're hitting a deprecation warning here, because the `opt_mapping_param` invocation that normalizes it into an empty dict should be occurring after the constructor is invoked. Are you accessing the `environment_vars` property on `ScheduleDefinition` somewhere in your code?

2024-03-20 22:38 UTC, sryza requested changes
@2Ryan09 got it - I think what's happening is that, somewhere inside `Definitions`, we're invoking `with_updated_job` on the schedule definition, which creates a new one with the dict.

Based on this, I don't think that the test added in this PR actually reproduces the warning that this PR fixes.

I think this is a trivial enough change that we can go without the test, but can give you pointers on how to write a test that will reproduce it if you'd like.

2024-03-20 22:38 UTC, sryza commented on python_modules/dagster/dagster/_core/definitions/schedule_definition.py
> +        self._environment_vars = self._environment_vars or None
We can use `opt_nullable_mapping_param` instead of `opt_mapping_param` to avoid this line

2024-03-21 02:29 UTC, 2Ryan09 commented
Just pushed those that change and deleted the test. I might take you up on those pointers :)

2024-03-21 21:07 UTC, sryza approved these changes
LGTM. Thanks @2Ryan09 !

2024-03-21 21:07 UTC, merged