MetadataEntries -> MetadataMixin
dagster-io/dagster pull request #20625
Opened 2024-03-21 17:23 UTC by sryza

## Summary & Motivation

## How I Tested These Changes

2024-03-22 20:01 UTC, rexledesma reviewed
I am curious to see an exact example of how multiple `NamespacedMetadataMixin` classes interact with one another.

Do we expect something like the following?

```
class MyMetadata(TableMetadataMixin, MyOtherMetadataMixin):
    ...
```

It also feels odd for a user to instantiate a Mixin instance directly.

2024-03-22 20:01 UTC, rexledesma commented on python_modules/dagster/dagster/_core/definitions/metadata/__init__.py
> +class TableMetadataMixin(NamespacedMetadataMixin, frozen=True):
After composing the mixin, are we sure we get another mixin? When I think of subclassing `XXXMixin`, I probably have to implement an abstractmethod to get it to work.

This is not the case for `TableMetadataMixin` -- it has no additional abstractmethods. Or are we implying that `namespace` could be overridden again?

```suggestion
class TableMetadata(NamespacedMetadataMixin, frozen=True):
```

2024-03-22 20:32 UTC, sryza commented
> It also feels odd for a user to instantiate a Mixin instance directly.

Yeah, I think that's the weirdest aspect of this approach.

I don't think we should expect users (inside the Dagster codebase or eventually outside) to need to subclass `TableMetadataMixin` (or whatever we choose to call it) in order to use it to set or interpret metadata.

If we think that rules out `TableMetadataMixin` etc., then a few other ideas:
- `TableMetadata`
- `TableStructuredMetadata`
- `TableTypedMetadata`
- `TableMetadataEntrySet`
- `TableMetadataSet`

@tacastillo's [feedback on asset tags](https://www.notion.so/dagster/Asset-Tags-Feedback-56f772a08a224ce897f91c18799b961f) made me think that there's at least a chance we'll want to introduce a similar pattern for tags. So we might want to choose a naming pattern that could work there as well? E.g.

- `PurinaTagsMixin`
- `PurinaTags`
- `PurinaStructuredTags`
- `PurinaTypedTags`
- `PurinaTagsSet`

Curious on thoughts from @schrockn.


Btw, when we get this resolved, will rebase PRs like https://github.com/dagster-io/dagster/pull/20500.

2024-03-22 20:36 UTC, schrockn commented
100% Mixin is a weird name. Even though I threw it out there I don't like it. I just want a singular name. I basically think _any_ singular name is better than a pluralized one.

`TagSet` and `MetadataSet` seem pretty good to me. "Add the tabular metadata set to this asset, and Dagster will treat it like a tabular asset" sounds reasonable to me.

2024-03-23 00:00 UTC, sryza commented
Re-spun with `MetadataSet`.  A potential issue here now that I think about it is that one might expect a class ending in `Set` to be a subclass of `AbstractSet`.  Don't know if this is a blocking consideration. Going to drop this here for now and try to form a deeper opinion later.

2024-03-25 18:57 UTC, rexledesma commented
Can we just drop `Set`? 

Just looking at the API doc:

```python
my_metadata: NamespacedMetadataSet = ...
return MaterializeResult(metadata={**my_metadata, ...})
```

we name the variable `my_metadata` and the argument is `metadata`. So looks like this is preferrable and feels more in alignment.

```python
my_metadata: NamespacedMetadata = ...
return MaterializeResult(metadata={**my_metadata, ...})
```

2024-03-25 19:02 UTC, sryza commented
> Can we just drop Set?

I think this works decently well with metadata, because it's an invariable noun (term I just learned from the internet). If we extended this pattern to tags though, we'd end up with `TableTags`, which hits the plurality issue.

2024-03-26 17:45 UTC, rexledesma reviewed
How about `XXXMetadata`, and for tags, `XXXTagging`?

2024-04-10 11:16 UTC, schrockn requested changes
Just doing some queue management. What's our status here?

2024-04-10 12:50 UTC, sryza commented
@schrockn waiting on your input. Here's a summary of the options discussed above:
- `TableMetadataSet` / `TableTagSet`
  - Upside: avoids plurals
  - Downside: would expect to be able to be a subclass of `AbstractSet`, but this is not actually a set
- `TableMetadata` / `TableTagging`
  - Upside: avoids plurals
  - Downside: "tagging" is awkward IMO

Other options not yet discussed: `TableMetadataDict`, `TableMetadataMapping`

2024-04-10 14:05 UTC, schrockn commented
IMO the `AbstractSet` overlap is a pretty niche concern and shouldn't be weighted heavily. I think the "set" approach is good. @rexledesma how strongly do you feel about this?

2024-04-10 14:06 UTC, schrockn commented on python_modules/dagster/dagster_tests/definitions_tests/metadata_tests/test_table_metadata_mixin.py
> +from dagster import AssetKey, AssetMaterialization, TableColumn, TableSchema
change this filename to `_set.pt` rather than `_mixin.py`

2024-04-15 22:25 UTC, schrockn approved these changes

2024-04-15 23:51 UTC, merged