Prefer observables over regular source assets when rendering in UI.
dagster-io/dagster pull request #20680
Opened 2024-03-22 22:54 UTC by dpeng817

Solves an issue we ran into in purina where we treat observable source assets the same as any other source asset when rendering in the UI, and so you end up with an unexecutable asset which should actually be executable.

2024-03-22 22:54 UTC, dpeng817 commented
* **#20680** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20680?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dpeng817 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-03-22 23:43 UTC, sryza requested changes
I do think it's worth adding a test for this. Curious if @clairelin135 has pointers on the best place to do so. I can help dig one up if not.

2024-03-22 23:43 UTC, sryza commented on python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py
> +        # If an asset node is already in the dict, we only discard it if that preexisting node is
```suggestion
        # If an asset node is already in the dict, we only overwrite it if that preexisting node is
```

2024-03-23 15:08 UTC, sryza commented
Circling back here, would take a look at `TestCrossRepoAssetDependedBy` - graphql test that involves multiple code locations

2024-03-25 18:27 UTC, sryza approved these changes
Nice. Left a nitpicky comment on a comment. Otherwise looks great.

2024-03-25 18:34 UTC, dpeng817 commented on python_modules/dagster-graphql/dagster_graphql/implementation/fetch_assets.py
> +        # If an asset node is already in the dict, we only discard it if that preexisting node is
oops missed this. fixed now.

2024-03-26 17:21 UTC, merged