remove key from asset details overview sidebar
dagster-io/dagster pull request #20715
Opened 2024-03-25 19:05 UTC by sryza

## Summary & Motivation

It's already shown at the top of the page. When in doubt, less is more!

State before this PR:
![image](https://github.com/dagster-io/dagster/assets/654855/c47e731d-ca50-4bcd-8f00-d056d33bda16)

## How I Tested These Changes

2024-03-25 19:07 UTC, salazarm approved these changes

2024-03-25 19:36 UTC, rexledesma requested changes
Hmm, I think I prefer having it in the context of the other definition level information (e.g. group, code location, etc).

The asset key header also doesn't really clarify that the entire path `purina / intermediate / materialization_metadata` is the entire key because the prefix is less emphasized.

We should change that before landing this imo. At least render the entire asset key path with the same weight.

2024-03-25 23:59 UTC, sryza commented
> Hmm, I think I prefer having it in the context of the other definition level information (e.g. group, code location, etc).

Agree that there's something nice about having it there, but I think real estate is at such a premium that I'm hesitant to include information that can be found elsewhere. Here's a set of other properties that I think we'll likely want to include in the sidebar as soon as we start collecting them:
- Source code link
- Number of rows
- Address

Keeping key will likely mean putting something else important below the fold.

> The asset key header also doesn't really clarify that the entire path purina / intermediate / materialization_metadata is the entire key because the prefix is less emphasized.

@braunjj - thoughts on bolding the entire asset key at the top, based on @rexledesma's suggestion above?

<img width="407" alt="image" src="https://github.com/dagster-io/dagster/assets/654855/5399f673-64cc-49ca-88f4-c399c01a413a">

2024-03-27 16:41 UTC, rexledesma approved these changes
Discussed offline, we should go ahead with this

2024-03-27 17:09 UTC, merged