[external-renames] Rename ExternalAssetNode and associates
dagster-io/dagster pull request #20788
Opened 2024-03-28 15:31 UTC by smackesey

## Summary & Motivation

## How I Tested These Changes

2024-03-28 15:31 UTC, smackesey commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20788?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#20788** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20788?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#20787** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20787?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @smackesey and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-03-29 12:22 UTC, schrockn commented on python_modules/dagster/dagster/_core/remote_representation/external_data.py
>  @whitelist_for_serdes(
What is our test coverage like for all these historical renames?

2024-03-29 12:22 UTC, schrockn requested changes
Now that we are geting into the realm of doing backwards compat of storage, we have to talk about a testing strategy.

2024-03-29 13:48 UTC, smackesey commented
>Now that we are getting into the realm of doing backwards compat of storage, we have to talk about a testing strategy.

I definitely think we could stand to beef up our backcompat integration testing, but I think the standard in our codebase is that simple serdes class/field renames are covered by our general serdes layer tests, which thoroughly test all the `whitelist_for_serdes` args. For example when `atomic_execution_unit_id` was renamed to `execution_set_identifier` a few months ago, no tests specific to this were added.

It's custom serialization logic that demands new unit tests, and there is no custom serialization logic here.

2024-03-29 13:50 UTC, schrockn commented
Given the scale of the renames proposed here I think we have to do better than that. Right now we could easily submit a type and we wouldn't catch it until we release and someone loads a historical event.

Open to suggestions here but I think the _minimum_ is that we can catch typos.

2024-09-27 21:00 UTC, smackesey commented
This backcompat test improvement PR should defend against a lot more rename typos (in particular asset related ones): https://github.com/dagster-io/dagster/pull/24523

2024-09-30 14:44 UTC, schrockn approved these changes

2024-09-30 16:46 UTC, merged