RFC: Expose Definitions (and RepositoryDefinition) on OpExecutionContext / AssetExecutionContext
dagster-io/dagster pull request #20946
Opened 2024-04-01 17:36 UTC by gibsondan

Summary:
Provides a way to obtain the Definitions object that produced the job. Right now the only way to get this information for advanced use cases (for example, introspecting the asset graph in the body of an asset or op) is to either re-import it inline (potentially incurring a slow import again since it won't be cached by Python due to being imported in a different way) or rely on private APIs in the case of RepositoryDefinition

Exposed RepositoryDefinition as well since the above issues still apply for users who may have not fully migrated to Definitions yet.

Looking for initial high-level feedback, if this seems like a reasonable path forward I will flesh out / add full suite of tests / etc.

## Summary & Motivation

## How I Tested These Changes

2024-04-01 17:47 UTC, sryza reviewed
Very excited about this change. I have run into situations where I wanted this to exist but found it difficult to make it so.

Thoughts:
- For the name of the public property on the context object, I had always assumed it would just be `defs`.  This makes it easy to make the connection with `defs = Definitions(...)`, and is also nice and short.  Which is a nice quality because it will often be at the beginning of a chain of accesses.
- Even if the code location isn't constructed using a `Definitions` object, I think the context property should still return a `Definitions` object, which contains the definitions however they were originally loaded. Am I correct in understanding that that's not the case in this PR?
- In light of the above bullet, do we need to thread `get_repository_definition` through? If someone needs it, they could just do `defs.context.get_repository_def()`?
- Can't entirely put my finger on it at this moment, but the term "Dagster definitions" rubs me the wrong way a little in this context. It's like: isn't the assumption already that everything is Dagster X?

2024-04-01 17:48 UTC, schrockn requested changes
My first instinct that we should not expose `Definitions` in this fashion to runs. `Definitions` to me is much like `AssetSpec` where it is only valid as an input/means to _construct_ our canonical objects, rather than the objects themselves. Our internals think in terms of `AssetNode`, not `AssetSpec`, because `AssetNode` is the internal representation (which has processed, canonicalized things, and also has information that can only happen once all definitions are constructed and bound.

This is a similar situation to that.

`RepositoryDefinition` is much more like an internal and I'm open to exposing that.

What is the exact use case we are solving with this?

2024-04-01 17:54 UTC, schrockn commented
Interested in @smackesey 's thoughts on the right path forward here.

2024-04-01 18:55 UTC, sryza commented
> Definitions to me is much like AssetSpec where it is only valid as an input/means to construct our canonical objects, rather than the objects themselves.

Currently we do a bunch of resolution at `Definitions` construction time.  So e.g. from a `Definitions` object you can get an `AssetGraph` with `AssetNode`s, as well as invoke `get_job_def` to get a resolved job definition.

That said, we've discussed directions like https://github.com/dagster-io/internal/discussions/8216, which might imply `Definitions` objects can be unresolved.

> RepositoryDefinition is much more like an internal and I'm open to exposing that.

My understanding was that a big advantage of the `Definitions` change was that we were going to be able to phase "repository" out of our ontology.  I.e. I don't think any new users should encounter this term.

2024-04-01 19:14 UTC, schrockn commented
> That said, we've discussed directions like https://github.com/dagster-io/internal/discussions/8216, which might imply Definitions objects should be able to be unresolved in the future.

Yeah there's a ton of directs we can go with it. I'm also very interested in allowing the recreation of `Definitions` objects without a process restart (for definitions backed by state).

That it creates a repository eagerly is purely an implementation detail. And in fact create `PendingRepositoryDefinition`, and we certainly don't want to leak that bit of horrific complexity to the users.

>My understanding was that a big advantage of the Definitions change was that we were going to be able to phase "repository" out of our ontology. I.e. I don't think any new users should encounter this term.

I think we need to consider what a reasonable internal representation would be. Curious for @smackesey's thoughts on that one.

2024-04-01 22:26 UTC, gibsondan commented
Seems like Definitions is a can of worms so scoped this down to just exposing the repository definition.

I agree that this shouldn't be front-and-center, but until we officially deprecate RepositoryDefinition it doesn't seem unreasonable to me to expose.

2024-04-01 22:28 UTC, gibsondan commented on python_modules/dagster/dagster/_core/execution/context/system.py
> +    repository_def_lambda: Callable[[], RepositoryDefinition]
i left this as a lambda at the moment, maybe overcautiously, to make sure that we don't stuff the whole repo in memory permanently on the context for the duration of the step unless it is specifically asked for within an op or asset

2024-04-02 19:26 UTC, gibsondan commented
Moved the property to be non-public for now - think this is ready for another look

2024-04-02 19:52 UTC, schrockn commented on python_modules/dagster/dagster/_core/execution/context_creation_job.py
> +        repository_def_lambda=lambda: context_creation_data.repository_def,
A bit confused re: the lambda optimization since I'm sure the garbage collector will keep this reference in the lambda closure around?

2024-04-02 19:53 UTC, schrockn submitted a review, later dismissed
Cool this makes sense to me. Req'ing changes based on skepticism of the passed-in lambda thing.

2024-04-02 20:15 UTC, gibsondan commented
I think you are right - the RepositoryDefinition is going to still be sitting around when you import it, this is just a reference to it. Removing the lambda

2024-04-02 20:19 UTC, schrockn approved these changes
Cool thx

2024-04-03 16:44 UTC, merged