[docs] add OpExecutionContext.dagster_run
dagster-io/dagster pull request #20957
Opened 2024-04-01 22:49 UTC by yuhan

## Summary & Motivation

## How I Tested These Changes

2024-04-01 22:49 UTC, yuhan commented
* **#20957** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20957?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @yuhan and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-04-01 22:57 UTC, tacastillo approved these changes
I don't have an explanation as to why I wouldn't want this. LGTM

2024-04-01 23:08 UTC, jamiedemaria requested changes
I agree with the doc string change, but we already have `OpExecutionContext.run` that also returns a `DagsterRun`. For `AssetExecutionContext` we deprecated `context.dagster_run` in favor of `context.run` so I would prefer to mark `OpExecutionContext.run` as public and leave `OpExecutionContext.dagster_run` non-public so it's easier to deprecate if we choose to in the future

2024-04-01 23:25 UTC, yuhan commented on python_modules/dagster/dagster/_core/execution/context/compute.py
> +        """DagsterRun: The current run."""
also updated this to be identical as `run` so we know they are the same and one is public and the other is not.

2024-04-01 23:25 UTC, yuhan commented
thanks @jamiedemaria! updated

2024-04-02 16:01 UTC, erinkcochran87 approved these changes

2024-04-02 16:51 UTC, jamiedemaria approved these changes

2024-04-02 20:23 UTC, yuhan commented
### Merge activity

* **Apr 2, 1:23 PM PDT**: @yuhan started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/20957).

2024-04-02 20:24 UTC, merged