fix: enforce all asset inputs are represented by supplied internal deps
dagster-io/dagster pull request #20965
Opened 2024-04-02 16:10 UTC by rexledesma

## Summary & Motivation
Resolves https://github.com/dagster-io/dagster/issues/15800.

## How I Tested These Changes
pytest

2024-04-02 16:10 UTC, rexledesma commented
* **#20965** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/20965?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rexledesma and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-04-04 16:04 UTC, jamiedemaria requested changes
one thing with the test, but otherwise this looks good to me!

2024-04-04 16:04 UTC, jamiedemaria commented on python_modules/dagster/dagster_tests/asset_defs_tests/test_assets.py
> +    with pytest.raises(Exception):
can you catch the specific error and match on the message?

2024-04-04 16:30 UTC, jamiedemaria approved these changes

2024-04-04 16:33 UTC, merged