Add destination_ids parameter to `load_asset_defs_from_fivetran_instance`
dagster-io/dagster pull request #21276
Opened 2024-04-18 02:08 UTC by lamalex

## Summary & Motivation
In a multi-tenant Fivetran setup not all connectors are relevant, or accessible. Without specifiying which destination_ids are desired in the worst case the Fivetran API will error due to insufficient API key permissions, or in the best case dagster will load irrelevant assets.
Specifying destination ID allows teams to just load connectors relevant to the fivetran destinations that they care about/own.

## How I Tested These Changes
Ran locally with `dagster dev`

2024-04-18 17:08 UTC, mlarose requested changes
thanks for your contribution! 

would you consider adding test cases for your functionality somewhere in this test file: https://github.com/dagster-io/dagster/blob/master/python_modules/libraries/dagster-fivetran/dagster_fivetran_tests/test_load_from_instance.py#L52

2024-04-18 17:08 UTC, mlarose commented on python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_defs.py
> +        if self._desination_ids is None:
```suggestion
        if not self._destination_ids:
```
treat empty list as false too, unless an empty array actually make sense for this call?

2024-04-18 23:44 UTC, lamalex commented on python_modules/libraries/dagster-fivetran/dagster_fivetran/asset_defs.py
> +        self._desination_ids = destination_ids
dang good catch, my bad!

2024-04-19 20:07 UTC, mlarose approved these changes

2024-04-19 20:07 UTC, merged