fix: set postgres timeout args via query
dagster-io/dagster pull request #21338
Opened 2024-04-22 17:02 UTC by jhlwscom

## Summary & Motivation

AWS RDS Proxy does not support cli options, so setting any mandatory connection options via statement improves compatibility.
Any custom options are still passed through as prior

## How I tested changes

- dagster_postgres pytests
- `dagster dev` and connect via rds proxy and directly, storage loads as expected

Resolves: #11762

2024-05-20 09:53 UTC, danielgafni commented
Would be very happy if this gets merged! I'm experiencing the same issue. @garethbrickman have you guys noticed this PR?

2024-05-20 20:39 UTC, garethbrickman commented
@danielgafni Got this one the agenda to review this Wednesday, thanks for the reminder! 👍

2024-06-10 23:04 UTC, telderfts commented
@garethbrickman Have you had a chance to review this? Quite a few people would like to use RDS proxies for connection pooling, etc and this is blocking that.

2024-06-11 09:13 UTC, jhlwscom commented
This iteration passes `python -m pytest python_modules/libraries/dagster-postgres/dagster_postgres_tests`, time to see what buildkite says.

2024-06-12 19:40 UTC, gibsondan commented
@jhlwscom seeing some test failures here in the dagster-postgres package that look potentially relevant: "TypeError: DefaultEngineStrategy.create() missing 1 required positional argument: 'name_or_url'"

2024-06-12 19:57 UTC, gibsondan commented on python_modules/libraries/dagster-postgres/dagster_postgres/event_log/event_log.py
> -            self.postgres_url,
it seems like at least on sqlalchemy 1, this needs to be a positional argument (or a 'name_or_url' kwarg)

2024-06-17 14:39 UTC, gibsondan requested changes
That should hopefully be a quick change to make the argument positional instead of a kwarg, after which this looks good to me. Be sure to run 'make ruff' and 'make pyright' when you resubmit. Apologies for the delay on getting this looked at.

2024-06-17 14:54 UTC, jhlwscom commented
Sorry for the delay on that tweak, was camping.

2024-06-17 16:24 UTC, gibsondan approved these changes
thanks!

2024-06-17 16:24 UTC, merged