RFC: AssetsDefinition.single
dagster-io/dagster pull request #21577
Opened 2024-05-02 00:39 UTC by sryza

## Summary & Motivation

## How I Tested These Changes

2024-05-02 23:11 UTC, schrockn commented
`AssetsDefinition.single` definitely is very strange. We create a "single" version of a pluralized class that is.... pluralized. It is goofy to say the least.

Should we just go for it and create `AssetDefinition`? Starting from scratch that would definitely be what we would want, given how our thinking has evolved.

We could just go for it and deal with the weirdness that `AssetsDefinition` and `AssetDefinition`.

2024-05-03 16:49 UTC, sryza commented
> AssetsDefinition.single definitely is very strange. We create a "single" version of a pluralized class that is.... pluralized. It is goofy to say the least.

Definitely agree that there's goofiness here.

> Should we just go for it and create AssetDefinition? Starting from scratch that would definitely be what we would want, given how our thinking has evolved.

Are you saying that, starting from scratch, we'd want both `AssetsDefinition` and `AssetDefinition`?
- If yes, then we'd have the problem with functions needing to accept and return `Sequence[Union[AssetDefinition, AssetsDefinition]]`.
- If no, then we'd need to revisit the complexities around multi-assets that led us to introduce `AssetsDefinition` in the first place. E.g. does `@multi_asset` return a list of `AssetDefinition`s? If so, what object holds the mapping of asset keys to op input names? Would `AssetDefinition`s have some sort of "multi_asset_identifier" that indicates they execute in the same step?

Maybe an academic discussion given where we are now, but if we could imagine an eventual world without  `AssetsDefinition`, that would make `AssetDefinition` feel more palatable to me as a solution here.

2024-05-03 17:00 UTC, schrockn commented
> Are you saying that, starting from scratch, we'd want both `AssetsDefinition` and `AssetDefinition`?

Definitely not. `AssetsDefinition` is not an accurate name at this point. `AssetsDefinition` is more like a unit of execution/step/task (i'm ignoring graphs for the moment) that connects computation to a set of entities in the asset graph layer.

One would create instances of `AssetDefinition`, `AssetCheckDefinition`. This would create entries for definitions in the catalog and the graph. Then one would associate an execution function with those definitions. You could even think of it more like a request. e.g. when X asset key is materialized invoke some function, which I think make subsetting cleaner to think about. 

A super wordy name for class would be `AssetGraphExecutionNode` or something. (Igonore name collision with NodeDefinition for now)

2024-05-03 17:22 UTC, sryza commented
> Definitely not. AssetsDefinition is not an accurate name at this point. AssetsDefinition is more like a unit of execution/step/task (i'm ignoring graphs for the moment) that connects computation to a set of entities in the asset graph layer.

I do think `AssetsDefinition` is an accurate name. An `AssetsDefinition` defines a set of assets, including all the static metadata about them and the function that produces them. I think most people would see that function as part of the definition, and in docs and the UI it makes sense to treat it as such.

This is not to say that all asset definitions need to have materialization functions. This is a conceptual leap that we've made recently that I think is positive.  _However_, in the cases where a materialization function _is_ represented in Dagster, I think that the function is conceptually part of the asset definition.

**On a practical level...**, what type would be produced by the and `@asset` decorator in a world where we have separate `AssetDefinition` and `AssetGraphExecutionNode` classes?

2024-05-03 17:29 UTC, schrockn commented
When you create an asset check it creates an `AssetsDefinition`. It is not an accurate name.

2024-05-03 22:20 UTC, sryza commented
@schrockn I should amend that to say that, with checks taken out of the picture, it's an accurate name. To make an accurate name that's inclusive of checks, I think we either need to swallow something very ugly like `AssetsAndChecksDefinition` or figure out what the name is for the entity that's a supertype of both asset and asset check. One potential solution is to say that a check is a very special kind of asset.

Stepping back a bit, I didn't add `AssetsDefinition` originally without noticing and grappling with the awkwardness of singular-plural aspect of the APIs. Despite that awkwardness, it was the best solution I could find given the design constraints and goals at the time. Some of those design constraints have changed (e.g. deemphasizing IO managers, comfortable drawing fewer distinctions between materializable and non-materializable assets), but many of them remain the same. I haven’t yet encountered or been able to devise a replacement that resolves the awkward parts of the current APIs without introducing substantial new issues.

This isn't to say that there's definitely no better solution out there, just that I don't think there's easy low hanging fruit.

Simultaneously, I believe there's some urgency in escaping the transitory state we're in with `SourceAsset`, as well as making Dagster a better home for non-materializable assets.  So if there's a solution we can find that doesn't require a lengthy soul-searching design process, and also doesn't push us through any big one-way doors, I think it's worth pursuing.

With that in mind, I think it's maybe worth decomposing this RFC into two questions:
1. Should users be able to instantiate `AssetsDefinition`s that don't have materialization / observation functions?
2. If yes, is `AssetsDefinition.single` the right API for this?

2024-05-06 10:46 UTC, schrockn commented
I think the mental model we should be shooting for here is the `AssetsDefinition` is oriented around an execution, rather than the metadata. `ExecutableAssetGraphNode` would be a wordy, but accurate, name for it. Its purpose in life would be to bind software definitions in the asset graph (e.g. asset definitions, asset check definitions) to nodes in the op graph. (op and graph definitions).

> Should users be able to instantiate AssetsDefinitions that don't have materialization / observation functions?

I think the answer should be no here. I think there are practical and conceptual reasons here. The practical reason is that with the cataloging work, we will potentially be importing huge numbers of external assets. I think it is important for users to be able instantiate lightweight objects to represent them. 

Conceptually I think having a class called `AssetDefinition` works beautifully given the direction of the docs you laid out in https://github.com/dagster-io/dagster/pull/21487. Confusion with `AssetsDefinition` is unfortunate of course, so that would have to be managed.

2024-05-06 17:10 UTC, sryza commented
> I think the mental model we should be shooting for here is the AssetsDefinition is oriented around an execution, rather than the metadata. ExecutableAssetGraphNode would be a wordy, but accurate, name for it. Its purpose in life would be to bind software definitions in the asset graph (e.g. asset definitions, asset check definitions) to nodes in the op graph. (op and graph definitions).

I think the `ExecutableAssetGraphNode` abstraction described here is a fundamentally different abstraction than `AssetsDefinition`. `AssetsDefinition` includes the asset metadata, while `ExecutableAssetGraphNode` would not.  I don't see that changing for `AssetsDefinition`: the combination of execution function and metadata is what makes APIs like `@asset` and `@multi_asset` work.

This isn't to say that we should never introduce an `ExecutableAssetGraphNode` abstraction  – I see the value there in certain contexts. Just that it's neither realistic nor desirable to evolve `AssetsDefinition` into this abstraction.

> The practical reason is that with the cataloging work, we will potentially be importing huge numbers of external assets. I think it is important for users to be able instantiate lightweight objects to represent them.

Are you concerned about this from a perf / memory perspective? I think there are a couple straightforward ways to manage this:
- Enable an `AssetsDefinition` that has no materialization / observation function to contain definitions for multiple assets.
- Condense the in-memory representation of `AssetsDefinition`. I think we all agree that all those dicts are not a necessary or desirable end state.

> Conceptually I think having a class called AssetDefinition works beautifully given the direction of the docs you laid out in https://github.com/dagster-io/dagster/pull/21487.

The way you're thinking about it, would this class include a field to represent the asset's materialization and/or observation function?

The way we present it in docs is that the asset definition includes the relevant function: "An asset definition is a description, in code, of an asset that should exist and how to produce and update that asset." [This PR](https://github.com/dagster-io/dagster/pull/21547/files) widens this to accommodate non-materializable assets, but still describes the function as part of the definition.

2024-05-06 17:14 UTC, schrockn commented
In my mind `ExecutableAssetGraphNode` is effectively a _rename_ of `AssetsDefinition`, but with a cleaner `__init__` and internal structure. It would take an arbitrary number of specs and a `NodeDefinition`. `AssetDefinition` would not have an observation or materialization function.

2024-05-06 17:27 UTC, schrockn commented
cx

2024-05-06 17:28 UTC, schrockn commented
Just make this concrete. I was thinking a structure like this:

```python
class AssetGraphEntityDefinition:
    key: EntityKey # new thing that replaces AssetOrCheckKey
    ...

# super lightweight classes
class AssetDefinition(AssetGraphEntityDefinition):
    key: AssetKey
    ...

class AssetCheckDefinition(AssetGraphEntityDefinition):
    key: AssetCheckKey
    ...


# just guessing on namae.
class AssetGraphExecutable:
    def __init__(
        self, 
        asset_graph_defs: List[AssetGraphEntityDefinition]
    ):
        ...

# exists for backcompat for a long time
class AssetsDefinition(AssetGraphEntityDefinition):
    # Super complicated constructor to adapt existing __init__ to base class __init__
    ...
```

2024-05-06 17:36 UTC, sryza commented
What would the docstring for `AssetGraphExecutable` be?

2024-05-06 22:22 UTC, sryza commented
@schrockn we chatted about this in person today a day a little, but wanted to jot down some relevant thoughts for the record: `AssetsDefinition` / `AssetGraphExecutable` is a container for a set of entity definitions, not just glue that links entity definitions to an executable. E.g.:
- It's the object that the user supplies to Dagster (via `Definitions`) to tell it about those entities.
- It's an object that a user can supply to a check factory to create checks that target it.
- It's an object that a user can supply to a function like `with_source_code_links`.
- In many cases, a reasonable name for a collection of multiple of these objects would be `assets`.

In a world without external assets, I think the docstring for it should be something like "Defines a set of entities that are executed with the same op or graph."

This all makes me think it should have a name that's closer to `EntitiesDefinition` than `AssetGraphExecutable`.

---

Another idea that I think is worth putting in play is for `@asset` and `@multi_asset` to return an `AssetGraph` (or maybe `AssetGraphFragment`).

Currently, an `AssetsDefinition` can be a graph-backed subsettable multi-asset, where each asset executes in its own op. This is almost indistinguishable from an `AssetGraph`. So arguably this would be calling a spade a spade and removing a meaningless distinction.

2024-05-07 00:02 UTC, schrockn commented
> This all makes me think it should have a name that's closer to EntitiesDefinition than AssetGraphExecutable.

I guess no matter what we decide one thing I will exercise veto right on is a pluralized name. It is just too brutal in terms of code ergonomics.

You are stuck with the Sophie's choice of naming variables or parameters in two very unsatisfactory ways:

1) `entities_defs: Sequence[EntitiesDefinition]`
2) `entities: Sequence[EntitiesDefinition]`

`entities_def` is more technically correct but is an awkward mouthful, especially when pluralizes as `entities_defs`. Policing this feels like going around lecturing people that it is actually "Attorneys General" and not "Attorney Generals". You might feel smart doing it but everyone ends up resenting you.

`entities` is a too-cute-by-half compromise where `entities=EntitiesDefinition(...)` is somehow wrong but `entities=[EntitiesDefinition(...)]` is correct.

Then try out the following for size:

```python
def print_all_keys(entities: Sequence[EntitiesDefinition]):
   for entity in entities: # these look like perfectly reasonable variable names
      print(entity.entity_keys) # then 🙈🙈🙈
```

So no matter what we do I'm a hard no on a pluralized name on such a core concept.

2024-05-07 14:19 UTC, sryza commented
@schrockn yeah I have no love for pluralized class names. Agree that something like `EntitySetDefinition` is better than `EntitiesDefinition`.

2024-05-07 14:23 UTC, schrockn commented
> @schrockn yeah I have no love for pluralized class names. Agree that something like `EntitySetDefinition` is better than `EntitiesDefinition`.

https://github.com/dagster-io/dagster/pull/21679 !

2024-05-08 16:58 UTC, schrockn requested changes
Bouncing back to your queue

2024-05-21 19:46 UTC, sryza commented
@schrockn - coming back to this after our conversation today about it, and summing up how I see things so far.

I have a strong suspicion that we can find a solution that:
- Enables defining an asset without an execution function
- Is not `SourceAsset`
- Avoids introducing new Python types
- Avoids twisting our current Python types in ways that make them more confusing to work with

Currently, in our arsenal of abstractions, we have:
- `AssetsDefinition`, which represents a set of asset definitions, which includes their associated execution function. Note that our current [concept docs](https://docs.dagster.io/concepts/assets/software-defined-assets) present the function as part of the asset definition.
- `AssetSpec', which represents the attributes of an asset, without an associated execution function.

Note that, after the "spec-ify-assets-def" stack is landed, an `AssetsDefinition` will basically be a list of `AssetSpec`s, an execution function, and properties for mapping between the two.

I think either of these directions could largely satisfy the goals above:
- Using `AssetSpec` as the canonical object to represent an asset definition without an execution function.
- Allowing `AssetsDefinition` objects to represent assets without associated execution functions. I.e. changing the docstring to "Defines a set of assets that are materializable or observable by at most one op or graph"

2024-05-22 10:25 UTC, schrockn commented
@sryza basically I think we need to resolve the question posed by https://github.com/dagster-io/dagster/pull/21985#issuecomment-2124420592 and then a path forward will be clear.

2024-05-24 14:58 UTC, closed without merging