[DS][27/n] Create WillBeRequestedCondition
dagster-io/dagster pull request #21640
Opened 2024-05-03 18:52 UTC by OwenKephart

## Summary & Motivation

Creates a WillBeRequestedCondition. Naming is somewhat sketch, but the basic idea is that in the past we've merged together this concept with existing rules.

I.e. in AMP-world, the "skip_on_parent_missing" rule is actually "skip on parent (missing and will not be requested this tick)".

This is obviously a bit confusing, and now that all of our dep conditions are composable, breaking this out into its own separate condition is desirable.

## How I Tested These Changes

2024-05-03 18:52 UTC, OwenKephart commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21640?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#21641** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21641?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21640** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21640?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#21615** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21615?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21613** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21613?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21612** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21612?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21573** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21573?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21546** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21546?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21545** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21545?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21541** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21541?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21540** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21540?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21539** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21539?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21538** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21538?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21537** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21537?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21536** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21536?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21535** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21535?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21521** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21521?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21520** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21520?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21511** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21511?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#21512](https://github.com/dagster-io/dagster/pull/21512) <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21512?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* **#21510** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21510?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21508** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21508?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21507** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21507?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21505** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21505?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21504** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21504?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21503** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21503?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21502** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21502?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21501** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21501?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21500** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21500?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21499** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21499?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @OwenKephart and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-05-04 18:38 UTC, ion-elgreco commented
Could you add a condition that instead of only working on any or all assets, on just an explicit subset?

2024-05-09 08:32 UTC, schrockn commented on python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operands/slice_conditions.py
> +class WillBeRequestedCondition(SliceSchedulingCondition):
nit: I think class name should include the word "tick" just like the static constructor and description

2024-05-09 08:33 UTC, schrockn requested changes
Just req'ing changes based on class name to make sure you see it since the name will get serialized and it is hard to change.

2024-05-10 22:10 UTC, OwenKephart commented
@ion-elgreco 

> Could you add a condition that instead of only working on any or all assets, it applies to an explicit subset?

Adding that functionality to `SchedulingCondition.any_deps_match` and similar is certainly in the plans -- currently conceptualizing adding `allow_keys` and `ignore_keys`  type arguments.

2024-05-14 12:01 UTC, schrockn approved these changes

2024-05-14 14:38 UTC, OwenKephart commented
### Merge activity

* **May 14, 10:38 AM EDT**: @OwenKephart started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/21640).

2024-05-14 14:46 UTC, merged