Try new style asset factotry
dagster-io/dagster pull request #21679
Opened 2024-05-07 08:46 UTC by schrockn

## Summary & Motivation

## How I Tested These Changes

2024-05-07 08:46 UTC, schrockn commented
* **#21679** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21679?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @schrockn and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-05-09 15:16 UTC, smackesey commented
I'm a big fan of the direction this is going. I need more time to pull all my thoughts together, but two questions come to mind.

First, this RFC is solving two problems:

- It's introducing the hypothesized "one-abstraction-to-rule-them-all" as a replacement for `AssetsDefinition`
- It's solving our bad factory API situation.

I'm certainly in favor of solving both these problems, but I'm not sure that they should be solved with the same abstraction-- I don't have a firm opinion here yet, but I'm hesitant to expose a new core primitive in a public API. One of the advantages of moving to a new core primitive would be a decoupling of abstractions in our user definitions layer from internals, but IIUC this solution would persist the coupling.

Second, I think there's some conceptual murkiness around what should qualify as an "entity". Do we want the core graph that users think of to be an _asset graph_ or a _computation graph_? Before asset observations and checks, these concepts were somewhat conflated because assets had at most one associated computation (the materialization function). We are moving to a world where an asset can have potentially many computations associated with it (various checks, whatever else we add).

Calling individual asset-associated computations "executable entities" feels kind of wrong to me, because it implies that the core entities of Dagster are computations rather than data assets. We already have the concept of an "op" as a generic "executable entity" of sorts, and I think we should lean in to that in whatever we do for a "generic asset-associated computation factory" API.

Like I said, I need to think some more on it, but that's my gut reaction.

2024-05-09 15:21 UTC, schrockn commented
I think you should frame this solely in the "It's solving our bad factory API situation." context and merely think of it as informing future internal restructuring.

2024-05-09 15:32 UTC, rexledesma reviewed
> This proposes a new class-based API for building executable definitions in Dagster, designed for the factory use case. Class-based APIs are more natural for pluggability for Python.

Totally agree with this direction. In addition, I believe the class-based pattern would be a great entry point for letting an organization define its own custom standardization on top of the DSL.

---

What I am less sure about is this the class hierarchy that we are proposing here. `ExecutableEntitySet` is a new, separate class hierarchy. Then there are translation methods, `to_assets_def`, `to_asset_checks_def`, that transform this new class hierarchy in line with the existing hierarchy.

Taking a step back, in an ideal world, I think a user should have been able to subclass `AssetsDefinition` to use class-based APIs. This is an assumption I am making. 

However, this is not the case because we never really designed `AssetsDefinition` to be manipulated by the user. Instead, we relied on separate decorators, `@asset` and `@multi_asset`,  that instantiated "AssetsDefinition" on behalf of the user. These decorators are our true entry points, not the class itself.

As a result, instantiating `AssetsDefinition` using its own class is incredibly complex for the user. Telling the user to subclass its current form would add to the complexity.

Could we instead subclass `AssetsDefinition` ourselves with a subset of its arguments, and make that the new entry point for users to subclass? That would essentially fill the role of your proposed `ExecutableEntitySet`.

In my mind, this proposed subclass is what `@multi_asset` should have been: a simple entry point to `AssetsDefinition` that creates a set of executable asset(s). Furthermore, `@asset` would not have been needed, since this subclass also fulfills the role of creating a singular asset.

2024-05-09 15:36 UTC, schrockn commented
I'd rather do this via composition rather than inheritance. This class is extremely clean and simple right now because of that structure. However I'm open to persuasion on this front if the upside is compelling.

2024-05-09 18:36 UTC, schrockn commented
Rebase stack on master

2024-05-09 21:09 UTC, sryza reviewed
I have some hesitation about rushing into this. Adding a new private class of course is harmless, but I think moving to using it inside our factories is a meaningful change, because many of our users look inside them for guidance on how they should structure their own factories.

Here are the particular pieces that give me pause about whether this is the right abstraction:
- Introducing the terms "entity" and/or "executable entity". I think @smackesey laid out the risks here well.
- Having fields on these classes introduces a new place where state can live. Versus - say - putting it inside the metadata for the asset. Do we have guidelines for how users should make this choice?
- Introducing a concept that is parallel to `AssetsDefinition` but different in subtle ways. E.g. a future where a bunch of methods accept `Union[AssetsDefinition, ExecutableEntitySet]` feels a bit dystopian. An inheritance relationship between the two would make this feel a little less scary.

Btw, and I know the following only addresses a fraction of what `ExecutableEntitySet` is trying to solve, but I think we should be opening to heavily deprecating existing parameters on `AssetsDefinition` and introducing new ones.

2024-05-09 23:50 UTC, schrockn commented
I agree that introducing the name "entity" is quite a bit and should be decoupled from the PR. However @sryza I did change the name to that based on your feedback to a previous name. I'm going to work on an alt name, probably around the word "subgraph".

> Having fields on these classes introduces a new place where state can live. Versus - say - putting it inside the metadata for the asset. Do we have guidelines for how users should make this choice?

This is straightforward. If they want the metadata persisted and displayed in UI use metadata. If not, use state. This is actually a big problem in our current APIs, and we get around it by stashing vanilla python objects in metadata (like the translator with `dbt_assets`) and it displays nonsense in the UI. This is much better, and good piece of evidence that this is a superior structure.

> Introducing a concept that is parallel to AssetsDefinition but different in subtle ways. E.g. a future where a bunch of methods accept Union[AssetsDefinition, ExecutableEntitySet] feels a bit dystopian. An inheritance relationship between the two would make this feel a little less scary.

 Composition felt nice (and more conservative, actually) but I can make an attempt with an inheritance relationship. A concern I have with `AssetsDefinition` is its copying semantics, which are mindbending, and will greatly complicate an inheritance relationship.

>  I think we should be opening to heavily deprecating existing parameters on AssetsDefinition and introducing new ones.

`AssetsDefinition` at this point is inaccurately named and has massive internal problems that I think are effectively unfixable because of backwards compatibility guarantees. With the introduction of `AssetNode`, we can hollow out its core, but molding its constructor will be a large amount of effort.  

I'm still high conviction that this is a much better path forward for factories. Given our heavy investment in that area I think this is timely. The abstractions we use the factory layer will bleed up through a higher level system like Nope or dagster-yaml.

2024-05-10 03:51 UTC, sryza commented
> However @sryza I did change the name to that based on your feedback to a previous name. I'm going to work on an alt name, probably around the word "subgraph".

Yeah just to clarify my position on the "entity", I think we'd ideally be able to find a name that's
- More general than "asset" (because it doesn't include checks)
- More specific than "entity" (because it includes everything)

In other conversations, I've used the word "entity" as a stand-in for "something more general than asset" because I couldn't think of something better.

> This is straightforward. If they want the metadata persisted and displayed in UI use metadata. If not, use state.

👍 that distinction between UI and not UI makes sense to me.

Not at all a blocker here, but potentially worth considering a direction where these classes inherit from `NamespacedMetadataSet` subclasses, to support typed metadata.

> Composition felt nice (and more conservative, actually) but I can make an attempt with an inheritance relationship

Yeah definitely with you on inheritance being trickier and less conservative. I think maybe an important question to clarify here is whether this is:
- A helpful layer for defining factories 
- A successor to `AssetsDefinition`

If the former, then I think the current composition pattern makes a lot of sense.  I wonder if we can choose a name that communicates this better. Like `Base<Entity>Definer` or something.

If the latter, then I think it makes this change overall higher-stakes, brings up the larger question of how these two interact, and makes inheritance potentially more attractive for the aforementioned `Union[AssetsDefinition, ExecutableEntitySet]` reason.

Btw, in the world of YAML/Nope, the abstraction I've been playing around with looks something like this:

```python
class DefinitionSetConfig(DagsterModel, ABC):
    @abstractmethod
    def build_definitions(self) -> Definitions:
        ...
```

2024-05-10 10:47 UTC, schrockn commented
I updated this with a new set of names. I did _not_ update the PR summary, so please ignore it at this point.

Also want to emphasize that as it stands this is an RFC and not intended for commit. This is to drive discussion.

Given the feedback of the direction of intermixing this with the `AssetsDefinition` class hierarchy I have gone the direction of introducing a more fundamental abstraction in the system. I have _not_ done the work of inheriting from or changing `AssetsDefinition` as my goal here is to drive a naming discussion.

I am also in this PR _not_ attempting to introduce a new term like "entity."

New proposed names:

I am proposing a new noun, an executable. An executable represents a set of definitions in the asset graph layer that are executed within the same node in the op layer. The class therefore is called `AssetGraphExecutable`. 

Alternatives I considered:

* `ExecutableSubgraph`. Not chosen because "subgraph" does not imply execution within the same op or graph.
* `ExecutableAssetGraphFragment`. Fragment didn't seem quite right to me
* `ExecutableDefinitionSet`. A bit of a mouthful
* `ExecutableDefinitionGroup`. Overloads group.

Somes pros of `AssetGraphExecutable`:

* If we refactor the framework internals around this we will send a lot of code like this:

```python
for assets_def in assets_defs:
    func(assets_def)
```

Turn into

```python
for executable in executables
   func(executable)
```

Which I think flows and is nice. I think we could also use the term `Executable` in conversation and it would flow.

* This gives us the opportunity to introduce `AssetGraphExecutionContext`, which can wrap up and consolidate a bunch of different context objects. It is the object that exists whenever you are doing _any_ computation that is operating within the context of the asset graph. It defaults to thinking in terms of many assets, checks, and other future concepts. 

* Similarly `AssetGraphExecutionResult = Iterable[Union[MaterializeResult, AssetCheckResult, ObserveResult]]` also seems pretty good to me.

Some cons:

* It's a new noun
* It is a more "core" change, rather than an additive layer to help factory creation. (This might be a pro? Just calling it out)
* "Executable" means other things in different contexts (i.e. operating systems).

2024-05-10 13:08 UTC, rexledesma commented
> I am proposing a new noun, an executable. An executable represents a set of definitions in the asset graph layer that are executed within the same node in the op layer. The class therefore is called AssetGraphExecutable.

Could we use [graph terminology](https://en.wikipedia.org/wiki/Glossary_of_graph_theory) more here? I think that might help us with naming.

> An executable represents a set of definitions in the asset graph layer

2024-05-10 13:57 UTC, schrockn commented
Yeah "node" here was a `NodeDefinition` specifically.

Subgraph definitely another top contender. However we I went to write this code:

```python
def _ensure_resources_dont_conflict(
    asset_graph: AssetGraph,
    resource_defs: Mapping[str, ResourceDefinition],
) -> None:
    """Ensures that resources between assets, source assets, and provided resource dictionary do not conflict."""


    subgraphs = {}
    for subgraphs in asset_graph.subgraphs:
        for resource_key, resource_def in subgraphs.resource_defs.items():
            if resource_key not in subgraphs:
                subgraphs[resource_key] = resource_def
            if subgraphs[resource_key] != resource_def:
                raise DagsterInvalidDefinitionError(
                    f"Conflicting versions of resource with key '{resource_key}' "
                    "were provided to different subgrpahs. When constructing a "
                    "job, all resource definitions provided to subgraphs must "
                    "match by reference equality for a given key."
                )
```

I balked at it and went for "execution"

2024-05-10 14:17 UTC, sryza commented
> However we I went to write this code:

I think we should take `resource_defs` off of `AssetsDefinition`. The reason we initially added this was that there was no way to attach resources to a repository / `Definitions` object. However, these resource defs are not truly scoped to the `AssetsDefinition`. They're required to be the same across all assets within the repository.

The `resource_defs` parameter on `@asset` and `@multi_asset` is experimental for this reason. Not marking the `resource_defs` parameter as experimental on `AssetsDefinition` was an unfortunate accidental omission, but I think we can credibly say it has always been experimental.

2024-05-10 14:26 UTC, schrockn commented
> They're required to be the same across all assets within the repository. 

This is inaccurate

```python
from typing import Any

from dagster import ConfigurableResource, asset
from dagster._core.definitions.definitions_class import Definitions
from dagster._core.definitions.resource_annotation import ResourceParam
from dagster._core.execution.context.init import InitResourceContext


class ResourceA: ...


class ConfigurableResourceA(ConfigurableResource):
    def create_resource(self, context: InitResourceContext) -> Any:
        return ResourceA()


class ResourceB: ...


class ConfigurableResourceB(ConfigurableResource):
    def create_resource(self, context: InitResourceContext) -> Any:
        return ResourceB()


@asset
def asset_requires_resource_a(resource_a: ResourceParam[ResourceA]): ...


@asset
def asset_requires_resource_b(resource_b: ResourceParam[ResourceB]): ...


defs = Definitions(
    resources={
        "resource_a": ConfigurableResourceA(),
        "resource_b": ConfigurableResourceB(),
    },
    assets=[
        asset_requires_resource_a,
        asset_requires_resource_b,
    ],
)


print(list(defs.get_assets_def("asset_requires_resource_a").resource_defs.keys()))
print(list(defs.get_assets_def("asset_requires_resource_a").resource_defs.keys()))
```

```
(dagster-internal.3.11.5-2024-04-26) ➜  dagster git:(master) ✗ python resources.py
['io_manager', 'resource_a']
['io_manager', 'resource_a']
(dagster-internal.3.11.5-2024-04-26) ➜  dagster git:(master) ✗
```

2024-05-10 14:27 UTC, schrockn commented
> They're required to be the same across all assets within the repository.

This is not accurate.

```python
from typing import Any

from dagster import ConfigurableResource, asset
from dagster._core.definitions.definitions_class import Definitions
from dagster._core.definitions.resource_annotation import ResourceParam
from dagster._core.execution.context.init import InitResourceContext


class ResourceA: ...


class ConfigurableResourceA(ConfigurableResource):
    def create_resource(self, context: InitResourceContext) -> Any:
        return ResourceA()


class ResourceB: ...


class ConfigurableResourceB(ConfigurableResource):
    def create_resource(self, context: InitResourceContext) -> Any:
        return ResourceB()


@asset
def asset_requires_resource_a(resource_a: ResourceParam[ResourceA]): ...


@asset
def asset_requires_resource_b(resource_b: ResourceParam[ResourceB]): ...


defs = Definitions(
    resources={
        "resource_a": ConfigurableResourceA(),
        "resource_b": ConfigurableResourceB(),
    },
    assets=[
        asset_requires_resource_a,
        asset_requires_resource_b,
    ],
)


print(list(defs.get_assets_def("asset_requires_resource_a").resource_defs.keys()))
print(list(defs.get_assets_def("asset_requires_resource_b").resource_defs.keys()))
```

```
(dagster-internal.3.11.5-2024-04-26) ➜  dagster git:(master) ✗ python resources.py
['io_manager', 'resource_a']
['io_manager', 'resource_b']
```

2024-05-10 15:19 UTC, sryza commented
> This is not accurate.

What I mean is that different assets within a repository can't have different resource def values for the same resource key. The corollary of this is that providing `resource_defs` at the `AssetsDefinition` level doesn't give you any more degrees of freedom than providing them at the repository-level.

2024-10-07 18:33 UTC, dpeng817 requested changes
for queue

2024-12-30 18:46 UTC, closed without merging