[DS][38/n] Use FailedSchedulingCondition and ScheduledSince condition in eager policy
dagster-io/dagster pull request #21741
Opened 2024-05-09 00:10 UTC by OwenKephart

## Summary & Motivation

As title. This was alluded to in the initial eager policy PR, this is putting them in action. In the case that the latest run for an asset partition failed, we will not request the asset if we've already requested it within the last hour. This puts a natural "rate limit" on the asset in the case that it is repeatedly failing, but does not interfere if the asset is materializing as expected.

## How I Tested These Changes

2024-05-09 00:10 UTC, OwenKephart commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21741?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#21741** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21741?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#21740** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21740?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21739** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21739?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21712** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21712?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21705** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21705?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21704** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21704?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21703** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21703?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21677** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21677?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21737** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21737?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21671** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21671?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21641** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21641?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#21670](https://github.com/dagster-io/dagster/pull/21670) <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21670?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* **#21640** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21640?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21648** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21648?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21615** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21615?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21613** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21613?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21612** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21612?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21573** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21573?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21546** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21546?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21545** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21545?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21541** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21541?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21540** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21540?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21539** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21539?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21538** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21538?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21537** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21537?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21536** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21536?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21535** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21535?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21521** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21521?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21520** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21520?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21511** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21511?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#21512](https://github.com/dagster-io/dagster/pull/21512) <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21512?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* **#21 [...]

2024-05-09 08:31 UTC, schrockn commented on python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_condition.py
> +        failed and has not already been scheduled within the last hour, to prevent repeated failures.
I think this is arbitrary enough that we should make it optionally parametrizable in the `eager` constructor.

2024-05-09 08:31 UTC, schrockn requested changes
Make parametrize-able?

Also a basic test seems sensible here.

2024-05-14 12:19 UTC, schrockn commented on python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_condition.py
> +    def eager(
Hmmm I am a little concerned at assigning a default time like this in a public API as it seems very arbitrary.

What evidence do we have that an hour is the right value and that users will expect this behavior?

2024-05-14 12:20 UTC, schrockn requested changes
Think we need to discuss this default here.

The conversative approach would be to add (perhaps temporarily) a new top-level constructor like `eager_with_rate_limit` or something which I would insta-approve.

2024-05-14 12:20 UTC, schrockn requested changes
Discuss or split out new method

2024-05-14 13:52 UTC, schrockn approved these changes

2024-05-14 14:38 UTC, OwenKephart commented
### Merge activity

* **May 14, 10:38 AM EDT**: @OwenKephart started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/21741).

2024-05-14 15:15 UTC, merged