[DS][41/n] Add ability to label ScheudlingCondition
dagster-io/dagster pull request #21839
Opened 2024-05-14 17:57 UTC by OwenKephart

## Summary & Motivation

As title -- this helps make sense of potentially-complicated trees of SchedulingConditions

## How I Tested These Changes

2024-05-14 17:57 UTC, OwenKephart commented
* **#21839** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21839?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @OwenKephart and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-05-14 18:04 UTC, schrockn submitted a review, later dismissed
Test for graphql layer?

2024-05-14 18:05 UTC, schrockn commented
The feature makes a ton of sense 👍🏻

2024-05-20 23:08 UTC, schrockn commented on python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_condition.py
> +        return self.model_copy(update={"label": label})
hmmmm do we really want to have to do this for every property?

2024-05-20 23:14 UTC, schrockn requested changes
I'm fairly hesitant to approve this without a full understanding of what we are going to do with label end-to-end from a design perspective. I intuitively believe that something like this is probably but this change is a bit of a "one way door" since we are serializing these values. I'd prefer to do this is in way that does not change our serialization format.

2024-07-16 21:29 UTC, closed without merging