[ds][x/n] Create RequestedPreviousTickCondition
dagster-io/dagster pull request #21972
Opened 2024-05-20 16:37 UTC by OwenKephart

## Summary & Motivation

## How I Tested These Changes

2024-05-20 16:37 UTC, OwenKephart commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21972?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#21974** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21974?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21973** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21973?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21972** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21972?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#21971** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21971?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21853** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21853?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#21854](https://github.com/dagster-io/dagster/pull/21854) <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21854?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* **#21844** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21844?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21839** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21839?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @OwenKephart and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-05-30 14:21 UTC, schrockn commented
What is the use case for detecting the previous tick only?

2024-05-30 14:51 UTC, schrockn requested changes
q mgmt

2024-05-30 20:01 UTC, schrockn commented on python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operands/slice_conditions.py
> +class NewlyRequestedCondition(SliceSchedulingCondition):
Should this just be `RequestedOnPreviousTick`. Seems more obvious?

2024-05-31 18:13 UTC, schrockn commented on python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operands/slice_conditions.py
> +class NewlyRequestedCondition(SliceSchedulingCondition):
Let's go with "Newly" terminology now. I still think we might come up with something bettetr in the next few weeks but this is concise and standardized and it is a "two-way door" for now

2024-05-31 18:13 UTC, schrockn approved these changes

2024-06-04 13:49 UTC, OwenKephart commented
### Merge activity

* **Jun 4, 9:49 AM EDT**: @OwenKephart started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/21972).

2024-06-04 13:57 UTC, merged