[DS][49/n] Add include_selection and exclude_selection to DepSchedulingCondition
dagster-io/dagster pull request #22048
Opened 2024-05-23 02:37 UTC by OwenKephart

## Summary & Motivation

As title -- previous iterations of this also added similar selection arguments to the ParentNewer condition. However, that didn't make a ton of sense because "ParentNewer" is purely a status like "code version updated" and calculating it in a different way is odd. Below this in the stack, we added a NewlyUpdated condition, which can compose with the AnyDepsCondition and take advantage of these arguments for users who want filter based on parent updates

## How I Tested These Changes

2024-05-23 02:37 UTC, OwenKephart commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22048?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#22048** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22048?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#21975** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21975?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#21989](https://github.com/dagster-io/dagster/pull/21989) <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21989?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* **#21974** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21974?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21973** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21973?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21972** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21972?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21971** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21971?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21853** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21853?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#21854](https://github.com/dagster-io/dagster/pull/21854) <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21854?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @OwenKephart and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-05-30 14:44 UTC, schrockn commented on python_modules/dagster/dagster/_core/definitions/declarative_scheduling/scheduling_condition.py
>          """Returns a SchedulingCondition that is true for an asset partition if at least one partition
Can we have single selection argument and support include/exclude with composition somehow?

2024-05-30 14:44 UTC, schrockn requested changes
seems a bit odd to have two top-level args

2024-05-30 20:49 UTC, OwenKephart commented
@schrockn added a couple test cases here illustrating the intended usage, but the basic idea is that if you want to represent "all parents except for <some selection>", it's basically impossible to do this using the same argument as "only parents within <some selection>"

In general, all AssetSelections must be relative to the selection of parents, and so passing in a "whitelist"-type selection (the `include_selection`) requires that we perform the operation <parent keys> & include_selection, whereas passing in an "blacklist"-type selection requires that we perform the operation <parent keys> & not exclude_selection, but "not" is not really an operator that makes sense in the context of an asset selection. You could try to hack it by making it parent_keys & (AssetSelection.all() - exclude_selection), but that can end up being quite inefficient if we imagine an asset graph having thousands of keys, and isn't a super intuitive way of conceptualizing these sorts of operations (in my opinion)

2024-06-03 18:25 UTC, schrockn requested changes
Per in-person discussion we considered using builders:

```python
Automation.all_deps_match(inner_condition).only_includes(some_selection)
Automation.all_deps_match(inner_condition).exclude(some_selection)
```

2024-06-04 08:57 UTC, schrockn commented on python_modules/dagster/dagster/_core/definitions/declarative_scheduling/operators/dep_operators.py
> +    def with_ignored_deps(self, selection: AssetSelection) -> "DepCondition":
I'd like to workshop these names a bit but that shouldn't block up here. I think just think it is a bit weird to have `deps` have a suffix but have an `AssetSelection` be a target, making it inconsistent where we use `deps` elsewhere.

I would prefer just `ignore` and `allow`.

Before:

```python
    condition = SchedulingCondition.any_deps_match(
        SchedulingCondition.missing(),
    ).with_ignored_deps(AssetSelection.keys("A") | AssetSelection.groups("bar"))
```

After:

```python
    condition = SchedulingCondition.any_deps_match(
        SchedulingCondition.missing(),
    ).ignore(AssetSelection.keys("A") | AssetSelection.groups("bar"))
```

2024-06-04 08:57 UTC, schrockn approved these changes
Let's do this. Consider naming suggestion.

2024-06-04 13:49 UTC, OwenKephart commented
### Merge activity

* **Jun 4, 9:49 AM EDT**: @OwenKephart started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/22048).

2024-06-04 14:10 UTC, merged