[DS][48/n] Allow AllPartitionsSubsets in TimeWindowPartitionMapping
dagster-io/dagster pull request #22058
Opened 2024-05-23 14:56 UTC by OwenKephart

## Summary & Motivation

As title -- I noticed that this caused an error upwards in the stack. There's no reason we can't map from an AllPartitionsSubset, we just need to convert it into a more explicit form first.

## How I Tested These Changes

2024-05-23 14:56 UTC, OwenKephart commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22058?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#21975** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21975?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 2  dependent PRs ([#21989](https://github.com/dagster-io/dagster/pull/21989) <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21989?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>, [#22048](https://github.com/dagster-io/dagster/pull/22048) <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22048?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* **#22058** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22058?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#21974** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21974?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21973** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21973?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21972** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21972?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21971** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21971?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#21853** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21853?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#21854](https://github.com/dagster-io/dagster/pull/21854) <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/21854?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @OwenKephart and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-05-30 14:39 UTC, schrockn commented on python_modules/dagster/dagster/_core/definitions/time_window_partition_mapping.py
> +            from_partitions_subset=from_partitions_subset,
<!--__GRAPHITE_HTML_TAG_START__--><i class='graphite__hidden'>[Re: lines 136 to 199]<br/><br/></i>

<!--__GRAPHITE_HTML_TAG_END__-->this seems a little copy-paste-y. anyway to consolidate?<!--__GRAPHITE_HTML_TAG_START__--><span class='graphite__hidden'><br/><br/>See this comment inline on <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22058?utm_source=unchanged-line-comment">Graphite</a>.</span>

<!--__GRAPHITE_HTML_TAG_END__-->

2024-05-30 14:39 UTC, schrockn requested changes
Makes sense. Let's see if we can dedup those codepaths a smidge.

2024-05-31 17:57 UTC, OwenKephart commented
@schrockn updated

2024-05-31 18:16 UTC, schrockn approved these changes

2024-06-04 13:49 UTC, OwenKephart commented
### Merge activity

* **Jun 4, 9:49 AM EDT**: @OwenKephart started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/22058).

2024-06-04 14:04 UTC, merged