RFC: We should stainless for our REST APIs
dagster-io/dagster pull request #22169
Opened 2024-05-30 13:39 UTC by schrockn

## Summary & Motivation

I noticed that we spent a bunch of time handrolling documentation about our REST API endpoints.

I think we should consider using stainless for this.

With stainless you provide an openAPI spec and they produce idiomatic SDKs in a bunch of different target programming languages.

For this example:

* Python: https://github.com/stainless-sdks/dagster-plus-rest-python
* Node: https://github.com/stainless-sdks/dagster-plus-rest-node

For this I handrolled an open api spec for demonstration purposes, but for real we would want to code to some Python framework that produces this for us.

## How I Tested These Changes

Looked at produced repos

2024-05-30 13:40 UTC, schrockn commented
* **#22169** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22169?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @schrockn and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-05-30 13:47 UTC, schrockn commented
My other thought here @alangenfeld @smackesey is that we could somehow repurpose this generated code and interface for all of our pipes clients. That way we wouldn't have a to build a bunch of language-specific stuff and we could keep pipes code in sync with generalized reporting APIs.

2024-05-30 16:32 UTC, erinkcochran87 commented
@schrockn I think those repos might be private - could you add me to them pls?

2024-05-30 16:45 UTC, schrockn commented
Ah here you go:

https://github.com/schrockn/stainless-test-python

https://github.com/schrockn/stainless-test-node

2024-07-25 15:42 UTC, alangenfeld requested changes
back to your queue

2024-09-27 13:41 UTC, closed without merging