remove op jobs from sensor concept page
dagster-io/dagster pull request #22182
Opened 2024-05-30 21:21 UTC by sryza

## Summary & Motivation

Pedram pointed out here that our sensor page leads with op jobs: https://www.notion.so/dagster/Sensors-are-Confusing-3d9a3b397340423981b343ed78ea4a9c. This is confusing. This PR changes the framing to be about assets.

This page could probably use a larger review / revamp, but I just wanted to do a brief sidequest with the minimum I could to fix this acute problem.

## How I Tested These Changes

2024-06-24 19:59 UTC, erinkcochran87 reviewed
Back to you!

2024-06-24 19:59 UTC, erinkcochran87 commented on docs/content/concepts/partitions-schedules-sensors/sensors.mdx
> +You can write a sensor that watches for changes to the input file and requests a run to re-materialize `my_asset` each time it encounters one:
```suggestion
You can write a sensor that watches for changes to the input file and requests a run to re-materialize `my_asset` each time a change occurs:
```

Kinda nitpicky, but this sounds clearer to me

2024-06-24 19:59 UTC, erinkcochran87 commented on docs/content/concepts/partitions-schedules-sensors/sensors.mdx
> +By default, this sensor runs every 30 seconds. It checks the last modified time for "inputfile.csv" and returns <PyObject object="RunRequest"/> based on it. Only one run will be launched for each uni
```suggestion
By default, this sensor runs every 30 seconds. It checks the last modified time for `inputfile.csv` and returns <PyObject object="RunRequest"/> based on it. Only one run will be launched for each unique value passed to the `run_key` parameter, which means that only one run will be launched each time the file is modified.
```

Added some formatting, but also:

> checks the last modified time for `inputfile.csv` and returns <PyObject object="RunRequest"/> based on it

"Based on it" meaning what, exactly? That the file has a more recently modified timestamp than the last time it was checked? Or does the run request do something with that timestamp data?

I imagine it's the former based on the sentence that follows this one, but being more specific here would be good

2024-10-01 05:23 UTC, PedramNavid requested changes
Back to you @sryza not sure if you have had a chance to address/dismiss the comments.

2024-10-08 20:49 UTC, sryza commented
@PedramNavid comments now addressed!

2024-11-15 23:19 UTC, neverett approved these changes

2025-05-08 22:38 UTC, PedramNavid requested changes
can be closed

2026-05-28 16:18 UTC, closed without merging