RFC: enable setting compute kind via asset tags
dagster-io/dagster pull request #22188
Opened 2024-05-30 23:35 UTC by sryza

## Summary & Motivation

## How I Tested These Changes

2024-05-31 01:30 UTC, PedramNavid commented
lgtm, although I couldn't find any reference to compute_kind as tags in our docs

2024-06-03 17:45 UTC, benpankow reviewed
This makes sense to me, and it is nice to bring storage kind and compute kind in parity.

@schrockn had some feedback on generalizing the kind tag system [here](https://github.com/dagster-io/internal/discussions/9937#discussioncomment-9607327) which might inform the direction we want to take this, not sure if you have thoughts

2024-06-03 17:45 UTC, benpankow commented on python_modules/dagster/dagster/_core/remote_representation/external_data.py
> -            compute_kind = node_def.tags.get("kind")
afaict this is the only use of the op tag, but might be worth pulling this into some sort of util to unify op/asset versions to pre-empt any dagster lib code dependent on compute kind outside of the UI (search, views, asset selection logic etc)

2024-08-16 21:59 UTC, schrockn requested changes
q mgmt

2024-08-16 22:14 UTC, closed without merging