cp
dagster-io/dagster pull request #22232
Opened 2024-06-03 03:09 UTC by schrockn

## Summary & Motivation

## How I Tested These Changes

2024-06-03 03:10 UTC, schrockn commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22232?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#22232** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22232?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#22230** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22230?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#22229** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22229?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#22228** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22228?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#22227** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22227?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#22225** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22225?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#22226](https://github.com/dagster-io/dagster/pull/22226) <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22226?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* **#22224** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22224?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#22223** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22223?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#22222** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22222?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @schrockn and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-06-03 11:10 UTC, schrockn commented on python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
> +                # upstream_asset_deps=None,
delete this upstack. Don't want to cause merge conflict.

2024-06-03 21:24 UTC, sryza requested changes
Will this lead to "@multi_asset" showing up in error messages related to the "@asset" decorator?

2024-06-06 19:11 UTC, schrockn commented on python_modules/dagster/dagster/_core/definitions/decorators/assets_definition_factory.py
> +            check.invariant(args.decorator_name == "@multi_asset", "Only hit this code path in multi_asset.")
X

2024-06-06 21:28 UTC, sryza approved these changes

2024-06-07 07:53 UTC, schrockn commented
### Merge activity

* **Jun 7, 3:53 AM EDT**: @schrockn started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/22232).

2024-06-07 07:58 UTC, merged