introduce ISubclassesMustSpecifyAllArgs utility
dagster-io/dagster pull request #22262
Opened 2024-06-03 19:48 UTC by benpankow

## Summary

Introduces an `ISubclassesMustSpecifyAllArgs` similar to #13970, which a class can implement to indicate that all subclasses should provide all kwargs to `super().__init__`.

This is not achievable with `IHasInternalInit` because of specific behavior around `__init__` vs calling an internal constructor (like `dagster_internal_init`).

Any class which implements this interface will be evaluated as part of our Python test suite, and the super call inspected to make sure it has a matching kwarg set.

Implements for `SensorEvaluationContext`, to prevent bugs like #17461 from arising in the future.

## Test Plan

Inspect/ast test

2024-06-03 19:48 UTC, benpankow commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22262?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#22262** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22262?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#22261** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22261?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @benpankow and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-06-03 22:33 UTC, schrockn requested changes
Can't we just remove all default values from the `SensorEvaluationContext` `__init__` method?

2024-06-03 23:10 UTC, benpankow commented
> Can't we just remove all default values from the `SensorEvaluationContext` `__init__` method?

We could - it is a publicly visible class that theoretically users could construct, would we consider this breaking?

2024-06-03 23:40 UTC, sryza commented
> We could - it is a publicly visible class that theoretically users could construct, would we consider this breaking?

They're expected to use `build_sensor_context`. The docstring says "Users should not instantiate this object directly". So I think it's fair game.

2024-06-04 01:14 UTC, schrockn commented
Eh I think @benpankow is right, I don't think we can break this.

2024-06-04 01:16 UTC, schrockn commented
I think this is complex enough where we have to "test the test". I.e have test cases that construct classes that violate the rules and verify that it throws.

2024-12-10 23:38 UTC, closed without merging