[check] call builder
dagster-io/dagster pull request #22260
Opened 2024-06-03 19:23 UTC by alangenfeld

Adds a utility funtion to check for programatiically building calls based on a type signatures. 

## How I Tested These Changes

added tests

2024-06-03 19:24 UTC, alangenfeld commented
* **#22043** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22043?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#22260** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22260?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alangenfeld and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-06-04 12:03 UTC, schrockn commented on python_modules/dagster/dagster/_check/__init__.py
> +        self.local_ns.update(ctx_frame.f_locals)
Could you add a docblock to describe what is going on here? I think I am inferring quite a bit but docblock would be very helpful.

2024-06-04 12:06 UTC, schrockn requested changes
Looks fantastic overall.

How hard would this be to apply to arbitrary function calls?

e.g.

```python
@checked
def foo(bar: int, baz: str) -> None:
  ...
```

Also do we have a sense of perf?

2024-06-04 12:08 UTC, schrockn reviewed
Also can you add test cases demonstrating the features of `EvalContext`?

Also demonstration of some error messages and stack traces in test plan would be nice too.

2024-06-04 12:09 UTC, schrockn commented on python_modules/dagster/dagster/_check/__init__.py
> +                            value_type=inner_pair_right,
avoiding indenttation this deep would be nice

2024-06-04 15:55 UTC, alangenfeld commented
> How hard would this be to apply to arbitrary function calls?

pretty sure trivial , was planning on adding in follow up

2024-06-04 22:22 UTC, alangenfeld commented
> Also do we have a sense of perf?

This is more about the top of the stack, but:

before and after using `scripts/object_profile.py` for converting `AssetKey` https://gist.github.com/alangenfeld/2f43d84748ed5dfd99849c665af18d82
no memory increase but time goes from ~334 to ~730 ns per call

and for this shoot out script: https://gist.github.com/alangenfeld/23c3e62fd1afe52136b73f4d533c0536
these results: https://gist.github.com/alangenfeld/ea2505b7923642bb78be852d8f5ebb35

so in this iteration, a little faster than pydantic but still slower than manual.

Banging on it a bit locally it seems to just be the extra function call overhead. I think using `exec` to generate the same code as what would be in the manual call is the next thing to explore.

2024-06-05 18:36 UTC, schrockn submitted a review, later dismissed
Req'ing based on docs for `EvalContext` and optionally reducing indentation of the workhorse fn

2024-06-05 22:26 UTC, schrockn approved these changes
[![make-it-so-picard](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/wS38mdcdU6aAeJobBdry/7c24ea68-bb2d-4292-9739-5ba30be4696b/make-it-so-picard.gif)](https://app.graphite.dev//settings/meme-library?org=dagster-io)

2024-06-06 19:43 UTC, merged