[dagster_model] support default values
dagster-io/dagster pull request #22374
Opened 2024-06-07 19:45 UTC by alangenfeld

* support empty models
* support setting default values in the model declaration
  * ensure things like [] and {} are not shared

## How I Tested These Changes

added tests

2024-06-07 19:46 UTC, alangenfeld commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22374?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#22374** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22374?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#22366** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22366?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alangenfeld and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-06-09 11:33 UTC, schrockn commented on python_modules/dagster/dagster/_model/decorator.py
> +        # field_set = getattr(self._cls, "__annotations__", {})
rm?

2024-06-09 11:34 UTC, schrockn commented on python_modules/dagster/dagster/_model/decorator.py
> +        eval_ctx.local_ns[_DEFAULT_VALUES_KEY] = defaults
shouldn't this mutation of `local_ns` happen in the constructor?

2024-06-09 11:37 UTC, schrockn requested changes
excited for this to go in. enough feedback to do a spin

2024-06-09 11:37 UTC, schrockn commented on python_modules/dagster/dagster/_model/decorator.py
> +        eval_ctx.local_ns[_DEFAULT_VALUES_KEY] = defaults
same here. not a fan of mutation outside ctor

2024-06-09 11:37 UTC, schrockn commented on python_modules/dagster/dagster/_model/decorator.py
> +        eval_ctx = EvalContext({}, {})
kwargs please for self-documentation

2024-06-09 11:37 UTC, schrockn commented on python_modules/dagster/dagster/_model/decorator.py
> +            "__bool__": _true,
❤️

2024-06-09 11:37 UTC, schrockn commented on python_modules/dagster/dagster/_model/decorator.py
> +    return kw_args_str, set_calls_str
there are getting complicated enough where some unit tests could be good, if nothing else than for documentation purposes.

2024-06-11 19:53 UTC, schrockn commented on python_modules/dagster/dagster/_check/__init__.py
> +            local_ns=local_ns,
at this point this is comment-worthy

2024-06-11 19:55 UTC, schrockn requested changes
Can you add comments to the places where I commented? This is getting fairly obtuse at this point.

2024-06-11 19:55 UTC, schrockn commented on python_modules/dagster/dagster/_model/decorator.py
> +            add_to_local_ns={_DEFAULT_VALUES_KEY: defaults},
Yeah this is the starting to get to "magical incantations" territory here with the hardcoded keys and the like.

2024-06-11 22:34 UTC, schrockn approved these changes

2024-06-11 22:41 UTC, merged