Fix observation handling for freshness checks
dagster-io/dagster pull request #22486
Opened 2024-06-11 22:04 UTC by dpeng817

Fix observation handling for freshness checks.

2024-06-11 22:04 UTC, dpeng817 commented
* **#22486** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22486?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dpeng817 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-06-12 18:56 UTC, sryza requested changes
Behavior seems like an improvement, but main feedback is that the name `retrieve_latest_record` here doesn't seem accurate any more. We should name and document in a way that makes clear what assumptions and compromises we're making.

2024-06-12 23:27 UTC, dpeng817 commented
@sryza good point. I renamed the function and addressed exactly what it's doing in detail via the docstring.

2024-06-13 01:01 UTC, sryza reviewed
This looks almost there, but I'm having trouble interpreting the word "parseable" in this context. It makes me think that the events might be malformed in some sort of way and we're having trouble deserializing them.

Thoughts on just calling it `retrieve_latest_update_record`? With a docstring caveat that it will somewhat-surprisingly return `None` in the following case:
- The asset has no materializations
- The latest observation has an no update time metadata, but earlier observations do

2024-06-13 18:28 UTC, sryza approved these changes

2024-06-13 20:01 UTC, merged