[RFC] Dagster Celery Runner
dagster-io/dagster pull request #22601
Opened 2024-06-19 15:06 UTC by egordm

# Summary & Motivation

Hello, I would like to propose a new feature to Dagster celery library by introducing Dagster Celery Runner. The PR also includes changes described in this RFC. We have been running this code in production for a while already and are confident that it is polished enough to be considered to be included as part of Dagster. 

## Context and scope
Our workload consists of:
* Multiple assets, each with on average 300 partitions.
* Hourly schedule to materialize these assets (for each partition).
* Each materialization job takes between 10 and 50 seconds.

Using Dagster K8s run launcher along with single process executor, we have noticed that:
* The workload puts too much load on our K8s cluster.
* Startup times become significant due to the small size of our jobs.
Without overcomplicating the solution, this setup did not seem as the way to go.

![K8s Runner drawio](https://github.com/dagster-io/dagster/assets/4254771/8a6805b6-accd-45e3-b8dc-37cec54e8561)

## Goals and non-goals
Our goal was to create setup which:
* Supports our workload.
* Minimizes the run launching overhead on our infrastructure.
* Maintains low job startup latency.
* At-least-once execution strategy (runners like k8s give us)
* Ability to scale horizontally.
* Run level isolation.
* Minimize downtime during deployment.

Non-goals:
* Op level isolation

## Alternatives considered

### Out-of-the-Box Dagster Celery
Original [dagster-celery](https://docs.dagster.io/deployment/guides/celery) package provides an alternative method of launching runs by dividing op execution across different workers.

This approach still relies on a runner to start the run, within which the executor passes the tasks onto individual celery workers. Using it together with K8s executor would not solve our problem, and combining it with Default Runner (starts runs on using the code server) would introduce new scalability and deployment issues (see diagram).

![Celery Executor drawio](https://github.com/dagster-io/dagster/assets/4254771/01e5e73e-c2af-4b33-a401-435bbb07061a)

While measuring performance of Dagster Celery executor, we did conclude that it did have the desired run startup latency and potential scalability.

## The actual design
Our proposed approach introduces a Dagster Celery runner which mimics the way K8s runner works, but starts the runs directly on Dagster celery workers (see diagram).

![Celery Runner drawio](https://github.com/dagster-io/dagster/assets/4254771/3005bbd4-097b-4761-addd-28fb08bd182e)

The main difference in this approach is that instead of launching a process containing an executor to monitor the steps, the task is submitted directly to the Celery Broker which in turn finds a worker to start the execution.

Once a task has been submitted to celery the daemon monitors the process using standard job monitoring requests which run at a configured interval. From celery backend the monitoring can read whether a job is 'in progress', 'done' or an alternative state.

### At-least-once-execution
Our production setup runs workers on k8s and uses stateless Redis as both Celery Broker and Backend.

There are three edge cases when using Celery with stateless Broker and Backend:
1. Redis broker crashes midway before starting the job, causing queue to drop jobs before they are picked up.
2. Redis backend crashes before the success result is communicated.
3. The worker is forcibly terminated, thus not communicating the result to the celery backend.

We mitigate case (1) by setting a sensible `start_timeout_seconds` on for run monitoring. If a job is not started in time, it will be marked as failed and caught by the retry policy.

Case (2) is handled out of the box as the worker still communicates the job status to Dagster run storage. In case a job is marked as completed in Dagster, the monitoring stops.

To handle case (3) we enforce a mandatory `dagster/max_runtime` tag on all jobs as it is otherwise impossible to distinguish a very slow job from a terminated one.

### Scalability
Because the workers facilitate job execution, scaling is as easy as adding more workers. The job monitoring is cheap because it requires a call to Redis backend from the monitoring daemon.

To make the solution more flexible, we add a run level tag specifying the celery queue to start the job on, thus allowing different workers to process different runs (akin to current op level queue tag).

### Deployment
Celery supports warm shutdown, meaning a worker will stop accepting new tasks once it receives a SIGTERM signal, but will finish existing ones. We combine this feature with k8s termination grace period and default rolling update to spin up new workers to pick up the new tasks.

### Run isolation
Using celery instead of k8s loses the resource isolation jobs have. We use default prefork pool along with `max-memory-per-child` and `max-tasks-per-child` settings to introduce soft limits on worker processes.

# How I Tested These Changes
* Created new tests based on the default runner tests. 
* Created example docker-compose.

2024-07-02 09:04 UTC, egordm commented
Hi @alangenfeld . I was wondering if someone could take a look or provide a review for this PR?
Thanks in advance.

2024-07-02 14:41 UTC, alangenfeld requested changes
Overall this seems reasonable to me, let me double check with the team about any concerns there would be about bring this in and maintaining it over time. 

Lets get the build passing by addressing the issues in https://buildkite.com/dagster/unit-tests/builds/740

2024-07-02 17:47 UTC, egordm commented on python_modules/libraries/dagster-celery/dagster_celery_tests/repo_runner.py
> +def nope():
That's bad naming indeed. :sweat_smile: 
I have updated it to a more descriptive name "celery_test_repository"

2024-07-02 17:48 UTC, egordm commented on python_modules/libraries/dagster-celery/dagster_celery/make_app.py
> +                "routing_key": f"dagster.{TASK_EXECUTE_PLAN_NAME}",
Good find! The keys should indeed align. Fixed!

2024-07-02 17:49 UTC, egordm commented on python_modules/libraries/dagster-celery/dagster_celery/launcher.py
> +        inst_data: ConfigurableClassData | None = None,
I have fixed CI build errors. The 3.10 union naming is now replaced by the `Optional` type.

2024-07-02 17:50 UTC, egordm commented
Thanks for looking into it! Sounds like a good plan. Let me know if there are any other changes necessary.

2024-07-08 16:02 UTC, alangenfeld approved these changes
While there are still concerns over the long term maintenance of this, this is a really well put together PR and

> We have been running this code in production for a while already and are confident

helps me believe that this should be usable and useful to others even if its slow to receive any further attention from the Dagster team directly. 

Thanks for the contribution!

2024-07-08 16:02 UTC, merged

2024-07-09 06:56 UTC, egordm commented
Awesome! Thanks!