feat(dbt): implement `build_dbt_asset_specs` to build `AssetSpec` from a dbt project
dagster-io/dagster pull request #22623
Opened 2024-06-20 20:20 UTC by rexledesma

## Summary & Motivation
Using `build_dbt_multi_asset_args`, transform its outputs to a set of `AssetSpec`.

Now, the user can create external assets for a dbt project. They do not need to specify the materialization function for a dbt project, if that is managed somewhere else.

## How I Tested These Changes

2024-06-20 20:20 UTC, rexledesma commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22623?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#22623** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22623?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#22622** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22622?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#22621** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/22621?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rexledesma and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-06-20 22:34 UTC, sryza requested changes
Nice. Eventually would be nice to generate the `AssetSpec`, but this seems like a the least invasive direction.

2024-06-21 14:26 UTC, schrockn approved these changes
Great thanks rex

2024-06-21 14:44 UTC, rexledesma commented
### Merge activity

* **Jun 21, 7:44 AM PDT**: [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/22623) rebased this pull request after merging its parent, because this pull request is set to merge when ready.

2024-06-21 14:45 UTC, merged