AssetGraphComputation.execution_type
dagster-io/dagster pull request #22624
Opened 2024-06-20 20:26 UTC by sryza

## Summary & Motivation

## How I Tested These Changes

2024-06-25 22:27 UTC, smackesey reviewed
One comment I'd like Nick's take on but otherwise I like it

2024-06-27 14:32 UTC, schrockn commented on python_modules/dagster/dagster/_core/definitions/decorators/asset_decorator.py
> +    _execution_type: Optional[AssetExecutionType] = None,
Yes I am opposed to this. I think "private" parameters like this are a smell and that stashing in metadata or something is preferable.

2024-06-27 14:33 UTC, schrockn requested changes
Let's find an approach that is not a "private" public parameter

2024-06-27 14:59 UTC, sryza commented
@smackesey @schrockn here's an approach without private parameters. It puts `@multi_observable_source_asset' directly on top of `DecoratorAssetsDefinitionBuilder`, instead of going through `@multi_asset`, which seems better anyway.

2024-06-28 12:57 UTC, schrockn approved these changes
Great this looks much better 👍🏻

2024-06-28 17:55 UTC, merged