accept `AssetSpec`s in `materialize`
dagster-io/dagster pull request #23216
Opened 2024-07-24 23:21 UTC by sryza

## Summary & Motivation

## How I Tested These Changes

2024-07-24 23:45 UTC, sryza commented on python_modules/dagster/dagster_tests/asset_defs_tests/test_materialize.py
> +        key=AssetKey(["the_source"]), metadata={"dagster/io_manager_key": "my_io_manager"}
this likely merits a discussion

2024-07-25 14:27 UTC, sryza commented on python_modules/dagster/dagster_tests/asset_defs_tests/test_materialize.py
> +        key=AssetKey(["the_source"]), metadata={"dagster/io_manager_key": "my_io_manager"}
Some background here: https://github.com/dagster-io/internal/discussions/10536#discussioncomment-10036256

2024-07-25 23:11 UTC, schrockn reviewed
Can you add a test case where someone adds an `AssetSpec`  that is already added in an `AssetsDefinition`? I think understand that error condition is key here. Overall this makes sense.

2024-07-25 23:11 UTC, schrockn requested changes
Test case for conflictig spec and assetsdefinition.

2024-07-26 18:13 UTC, sryza commented
👍 @schrockn added that test case: https://github.com/dagster-io/dagster/pull/23216/files#diff-10e165d419df4e8aa25f64b26f2445f4f3338e0ba5a3d37fdc1eaa2a2c946c9eR180

2024-07-26 18:17 UTC, schrockn approved these changes
Cool

2024-07-26 21:16 UTC, merged