Pipes aws glue interruption handler
dagster-io/dagster pull request #23354
Opened 2024-07-31 18:39 UTC by danielgafni

## Summary & Motivation

## How I Tested These Changes

2024-07-31 18:41 UTC, danielgafni commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23354?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#23354** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23354?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#23353** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23353?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @danielgafni and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-01 20:00 UTC, danielgafni commented
@schrockn should I be using `try: ... except DagsterExecutionInterruptedError: ...` instead of the current approach? I found it in other places in the codebase after submitting this PR.

2024-08-02 15:53 UTC, schrockn commented
Adding @alangenfeld as he is generally more up-to-speed on this type of issues. Should we be terminating external processes launched by a run if that run is aborted?

2024-08-02 17:31 UTC, alangenfeld requested changes
> should I be using try: ... except DagsterExecutionInterruptedError: ... instead of the current approach?

yea i think its a bit easier to reason about and you don't need to worry about removing the handler 

> Should we be terminating external processes launched by a run if that run is aborted?

The feedback we got when we initially did not clean them up is that we should since they are orphaned and unreported if they continue. We do make the behavior optional in the subprocess pipes client. 

you can reference https://github.com/dagster-io/dagster/pull/18685/files for some inspiration for how to put this under test

2024-08-05 21:23 UTC, schrockn requested changes
Managing my queue. @danielgafni let me know when you have incorporate alex's feedback and want me to look again.

2024-08-08 14:18 UTC, danielgafni commented
Hey @alangenfeld @schrockn, I added a test for Glue run interruption

2024-08-08 14:24 UTC, schrockn commented on python_modules/libraries/dagster-aws/dagster_aws/pipes.py
> +            if status := response["JobRun"]["JobRunState"] != "SUCCEEDED":
congrats for introducing only the third instance of the walrus to the codebase! I'm so trained not to use new features given how we have to support old Python version I totally forget they exist.

2024-08-08 14:30 UTC, schrockn approved these changes
Code seems fine to me. Please get the nod from @alangenfeld before merging as he is more conversant with these issues than I.

2024-08-08 16:27 UTC, alangenfeld approved these changes
nod

2024-08-08 17:55 UTC, merged