Upgrade to tox 4
dagster-io/dagster pull request #23449
Opened 2024-08-06 19:18 UTC by PedramNavid

## Summary & Motivation

Tox 3 was last updated in 2022. It's time to move to tox 4. The only breaking change is passenv variables need to be on a new line

## How I Tested These Changes

bk

2024-08-06 19:18 UTC, PedramNavid commented
* **#23449** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23449?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @PedramNavid and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-06 19:23 UTC, rexledesma reviewed
We should make this run against the full suite + all python versions just to double check that everything is fine.

You can add a magic string in your commit message to do that: https://www.notion.so/dagster/Buildkite-01a5666c2527462db2c3abe0d98cde45?pvs=4#55a86580485948c2877c55e62fe7fa39

2024-08-06 21:40 UTC, PedramNavid commented
> We should make this run against the full suite + all python versions just to double check that everything is fine.
> 
> You can add a magic string in your commit message to do that: https://www.notion.so/dagster/Buildkite-01a5666c2527462db2c3abe0d98cde45?pvs=4#55a86580485948c2877c55e62fe7fa39

good call, just ran

2024-08-06 22:43 UTC, rexledesma requested changes
Sweet, thanks! Is there a corresponding PR for `internal` as well? Going to request changes just to make sure that's present.

- Let's ensure `tox>=4` just to be safe
- Let's update `tox.ini.tmpl` in the python package scaffold as well

2024-08-06 22:43 UTC, rexledesma commented on python_modules/dagster/setup.py
> +            "tox",
```suggestion
            "tox>=4",
```

2024-08-06 23:02 UTC, PedramNavid commented
> Sweet, thanks! Is there a corresponding PR for `internal` as well? Going to request changes just to make sure that's present.
> 
> * Let's ensure `tox>=4` just to be safe
> * Let's update `tox.ini.tmpl` in the python package scaffold as well
Added! TIL about the python package scaffold. This whole time I was copy pasting files from other packages that looked decent 😭

2024-08-07 01:50 UTC, rexledesma approved these changes
yahoo

2024-08-07 14:18 UTC, schrockn commented
What are the concrete benefits we get out of the upgrade?

2024-08-07 15:16 UTC, PedramNavid commented
> What are the concrete benefits we get out of the upgrade?

There’s some performance improvements to start times and better handling of dependency changes, eg when adding a new package while developing.

But really, I sometimes end up with tox 4 in my environment somehow and it would never run and I’d end up reinstalling 3.2.5 which annoyed me, which was the real motivation for this

2024-08-07 15:24 UTC, schrockn commented
Makes sense! Obviously in support. Just wondering what concrete goodies we get.

2024-08-07 16:05 UTC, PedramNavid commented
> Makes sense! Obviously in support. Just wondering what concrete goodies we get.

Ohh there's also this:
 https://github.com/tox-dev/tox-uv
which requires tox>=4.16

2024-08-07 16:16 UTC, PedramNavid commented
### Merge activity

* **Aug 7, 12:16 PM EDT**: @PedramNavid started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/23449).

2024-08-07 16:17 UTC, merged

2024-08-07 16:17 UTC, rexledesma commented
FYI we already use `uv` in tox: https://github.com/dagster-io/dagster/pull/19871