feat: automatically enable container metric collection in a containerized environment
dagster-io/dagster pull request #23503
Opened 2024-08-08 12:05 UTC by mlarose

## Summary & Motivation

## How I Tested These Changes

2024-08-08 12:05 UTC, mlarose commented
* **#23503** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23503?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @mlarose and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-12 20:43 UTC, gibsondan reviewed
Is there a way to disable this for a given run? My immediate reaction is that this increases the risk factor significantly to have a new background thread running automatically on every run without a killswitch (or way to opt-in)

2024-09-12 20:45 UTC, gibsondan reviewed
would a safer rollout strategy be to start setting the tag on more and more runs, eventually all of them? That way if we need to we can roll it back quickly. There are also ways to mark certain tags as hidden so that they don't pollute the UI.

2024-09-13 14:06 UTC, gibsondan commented
i'm proposing that the source of truth for whether or not be spin up this background thread remains in the control plane (for example, via a tag that is set by the run coordinator at run submission time) rather than being set in user code 100% of the time, and we roll out the feature by increasing the times in which that tag is set - that way we can roll it out gradually and easily roll it back if we need to.

2024-09-13 15:24 UTC, gibsondan requested changes
discussed offline re: this one - sounds like source of truth will remain in the run coordinator

2024-09-13 15:35 UTC, closed without merging