[DA] Allow custom AutomationConditions to cross a serdes boundary
dagster-io/dagster pull request #23535
Opened 2024-08-08 23:13 UTC by OwenKephart

## Summary & Motivation

If users create a custom AutomationCondition, it will of course not be serializable. This updates the serialization logic to detect this case and convert the entire AutomationCondition into a format that retains the essential information but does not contain an evaluation function. This allows us to render it in the UI (if we so desire -- currently we only render historical values, not the current condition on the definition object).

Note that this serialization logic is happening in a somewhat-surprising spot, which is the AutoMaterializePolicy object. This is because we store AutomationConditions wrapped inside an AutoMaterializePolicy on the ExternalAssetNode. I'll move this logic over to ExternalAssetNode further up the stack.

## How I Tested These Changes

2024-08-08 23:14 UTC, OwenKephart commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23535?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#23536** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23536?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#23535** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23535?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#23534** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23534?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @OwenKephart and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-13 21:44 UTC, schrockn requested changes
Hmmm I think we should have a seperate layer of serializeable metadata objects for data that is cross-process and have AutomationCondition only in user-space. This sort of half serializable thing is quite confusing.

2024-08-13 22:55 UTC, OwenKephart commented
> Hmmm I think we should have a seperate layer of serializeable metadata objects for data that is cross-process and have AutomationCondition only in user-space. This sort of half serializable thing is quite confusing.

Yeah that makes sense -- if we're not evaluating the automation condition then there's currently no reason to have this information on the ExternalAssetNode, so to avoid committing to a format right now I've updated this to just set the value to None in the presence of user-code conditions

2024-08-16 19:08 UTC, schrockn commented
> if we're not evaluating the automation condition then there's currently no reason to have this information on the ExternalAssetNode

I'm confused by this. Do you mean if we're not evaluating it in the daemon?

No matter where we are executing the metadata is useful to us, is it not?

2024-08-16 21:28 UTC, OwenKephart commented
@schrockn In general the metadata is useful to us, but there is currently no place in the UI where this is rendered, so I avoided handling that in this PR.

Just tossed a PR to the top of the stack to handle putting a serializable snapshot on the ExternalAssetNode

2024-08-16 22:03 UTC, schrockn approved these changes

2024-08-16 22:03 UTC, schrockn commented on python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
>      def name(self) -> Optional[str]:
Can we make this non-optional then?

2024-08-16 22:03 UTC, schrockn commented on python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
> +    @property
`cached_property`?

seems potentially expensive (recursion etc)

2024-08-22 21:31 UTC, OwenKephart commented
### Merge activity

* **Aug 22, 5:31 PM EDT**: @OwenKephart started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/23535).

2024-08-22 21:37 UTC, merged