[DA][user-defined][11/n] Don't require `requires_cursor` to be set
dagster-io/dagster pull request #23605
Opened 2024-08-13 00:23 UTC by OwenKephart

## Summary & Motivation

Previously, it was required to opt into storing a cursor, as most builtin conditions do not require a cursor and it would be wasteful to store one. However, this is unintuitive for user-defined AutomationConditions, and so for non-builtins, we will automatically opt into using cursors.

## How I Tested These Changes

2024-08-13 00:23 UTC, OwenKephart commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23605?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#23605** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23605?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#23603** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23603?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#23599** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23599?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#23596** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23596?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#23593** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23593?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#23585** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23585?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#23584** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23584?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#23583** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23583?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#23581** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23581?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#23535** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23535?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#23536](https://github.com/dagster-io/dagster/pull/23536) <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23536?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* **#23534** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23534?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @OwenKephart and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-16 19:14 UTC, schrockn reviewed
And to be clear, this is so we can avoid an `Optional` on the cursor type signature? Is there any other reason to have `requires_cursor`?

2024-08-16 19:15 UTC, schrockn requested changes
q mgmt re: question of why this property exists at all

2024-08-16 21:33 UTC, OwenKephart commented
@schrockn `requires_cursor` is essentially a performance optimization. Cursoring in general requires tracking a fair amount of state (beyond just the free-form cursor value, we also keep track of the subset that was true on the previous tick). So by selectively setting it to `False` in the cases where we don't need it, we can avoid storing unnecessary information in the larger cursor.

I view this as more of an internal tool, rather than something a user would actively interact with (although there's nothing stopping someone from doing so if it becomes an issue for them).

This PR sets the default value to the more expensive, but more fully-featured "mode".

2024-08-22 20:32 UTC, schrockn approved these changes
kk got it thanks for explanation

2024-08-22 21:31 UTC, OwenKephart commented
### Merge activity

* **Aug 22, 5:31 PM EDT**: @OwenKephart started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/23605).

2024-08-22 22:14 UTC, merged