[DA][user-code][12/n] Improve log handling
dagster-io/dagster pull request #23625
Opened 2024-08-13 20:10 UTC by OwenKephart

## Summary & Motivation

Two things:

1. Change it from `context.logger` to `context.log` to better align with our existing interfaces
2. Make the log you get on each context object specific to the class that's being logged from (this is just quality of life)

## How I Tested These Changes

2024-08-13 20:10 UTC, OwenKephart commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23625?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#23625** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23625?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#23605** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23605?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#23603** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23603?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#23599** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23599?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#23596** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23596?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#23593** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23593?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#23585** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23585?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#23584** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23584?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#23583** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23583?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#23581** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23581?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#23535** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23535?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#23536](https://github.com/dagster-io/dagster/pull/23536) <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23536?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* **#23534** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23534?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @OwenKephart and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-13 21:58 UTC, schrockn commented on python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_context.py
> +        return self._root_log.getChild(self.condition.__class__.__name__)
what is the concrete impact of this on what actually gets logged?

2024-08-13 21:58 UTC, schrockn requested changes
Requesting changes mostly for q mgmt.

Showing before/after log messages in the test plan would be nice.

2024-08-15 02:07 UTC, OwenKephart commented
@schrockn Updated the description, open to the viewpoint that this is too fancy for its own good, but basically it just appends the class name of the currently-evaluated AutomationCondition to the logger's name

2024-08-22 20:32 UTC, schrockn approved these changes
great

2024-08-22 21:31 UTC, OwenKephart commented
### Merge activity

* **Aug 22, 5:31 PM EDT**: @OwenKephart started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/23625).

2024-08-22 22:18 UTC, merged