[DA] Add doc block to AutomationCondition, mark static constructors public
dagster-io/dagster pull request #23649
Opened 2024-08-14 16:29 UTC by OwenKephart

## Summary & Motivation

This allows information about this class to show up in our API docs

## How I Tested These Changes

2024-08-14 16:30 UTC, OwenKephart commented
* **#23649** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23649?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @OwenKephart and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-16 19:16 UTC, schrockn commented on python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
> +    AutomationConditions may be combined together into complex expressions using a variety of
I would just say "expressions" rather than "complex expressions"

2024-08-16 19:18 UTC, schrockn commented on python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
> +    AutomationConditions may be combined together into complex expressions using a variety of
I would use this example as an opportunity to explain what "given point in time" actually means.  Without an example it doesn't really sink in.

2024-08-16 19:18 UTC, schrockn commented on python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
> +    """
I would complete this example by showing how it is passed into an asset

2024-08-16 19:18 UTC, schrockn requested changes
inline comments

2024-08-21 17:13 UTC, sryza approved these changes

2024-08-21 17:16 UTC, merged