[usecase] adds example of copying a CSV to Snowflake
dagster-io/dagster pull request #23643
Opened 2024-08-14 13:18 UTC by cmpadden

## Summary & Motivation

- No external dependencies (e.g. pandas)
- Uses `SnowflakeResource`
- Uses `COPY INTO` statement

## How I Tested These Changes

- Use case preview

2024-08-14 20:30 UTC, PedramNavid requested changes
Small change, otherwise good to go. 
I assume you tested the code and it works? it looks good to me.

2024-08-14 20:30 UTC, PedramNavid commented on examples/use_case_repository/use_case_repository/guides/copy_csv_to_snowflake.md
> +4. Click on the "Launchpad" tab.
what is this 'launchpad'

2024-08-15 16:56 UTC, cmpadden commented on examples/use_case_repository/use_case_repository/guides/copy_csv_to_snowflake.md
> +4. Click on the "Launchpad" tab.
Simplified the instructions

2024-08-15 16:57 UTC, cmpadden commented
> Small change, otherwise good to go. I assume you tested the code and it works? it looks good to me.

Confirmed working as expected!

- Updated the example to better adhere to Snowflake's instructions.
https://docs.snowflake.com/en/sql-reference/sql/copy-into-table

- Confirmed that data loaded as expected in our test environment:
<img width="1479" alt="image" src="https://github.com/user-attachments/assets/66d9d545-c500-49a9-91de-1a7743686523">

2024-08-15 17:01 UTC, PedramNavid approved these changes
looks swell

2024-08-15 17:38 UTC, merged