[wip] airlift readme add migration
dagster-io/dagster pull request #23756
Opened 2024-08-20 16:46 UTC by benpankow

## Summary & Motivation

## How I Tested These Changes

2024-08-20 16:47 UTC, benpankow commented
* **#23756** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23756?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @benpankow and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-23 22:55 UTC, schrockn commented on examples/experimental/dagster-airlift/README.md
> +## Compatilibility
spelling

2024-08-23 22:55 UTC, schrockn commented on examples/experimental/dagster-airlift/README.md
> +First, you will need to install `dagster-airlift`:
say "in your Dagster environment"

2024-08-23 22:56 UTC, schrockn commented on examples/experimental/dagster-airlift/README.md
> -Note: When a code server is loaded for the first time it will query the target Airflow REST API. Subsequent process loads (e.g. a run worker loading) will used a cached response. If you want Dagster
why delete this? Seems like an important detail

2024-08-23 22:56 UTC, schrockn commented on examples/experimental/dagster-airlift/README.md
> +_Note: When the code location loads, Dagster will query the Airflow REST API in order to build a representation of your DAGs. In order for Dagster to reflect changes to your DAGs, you will need to re
oh just kidding it is here 👍🏻

2024-08-23 22:57 UTC, schrockn commented on examples/experimental/dagster-airlift/README.md
> +(TODO: New observation logic)
?

2024-08-23 22:57 UTC, schrockn commented on examples/experimental/dagster-airlift/README.md
> +In our example, we have three seqeuential tasks:
spelling "seqeuential"

2024-08-23 22:58 UTC, schrockn commented on examples/experimental/dagster-airlift/README.md
> +The `from_task` and `from_dag` utilities link created assets to their underlying tasks. Assets which are properly linked will be materialized by the Airlift sensor once the corresponding task complet
https://github.com/dagster-io/dagster/pull/23848

'dag_defs' and `task_defs` current proposal

2024-08-23 23:00 UTC, schrockn commented on examples/experimental/dagster-airlift/README.md
> +```
@dpeng817 

Just a heads up I want to change this to 

```yaml
tasks:
  - id: load_raw_customers
    migrated: False
```

We don't want to be subject to whatever rules there are for keys in yaml. Not sure what task id rules are across all flavors of Airflow.

2024-08-23 23:01 UTC, schrockn commented on examples/experimental/dagster-airlift/README.md
> +
We should at least have a dummy dag here

2024-08-23 23:01 UTC, schrockn commented on examples/experimental/dagster-airlift/README.md
> +1. First, ensure all associated assets are executable in Dagster by providing software-defined asset definitions in place of bare `AssetSpec`s.
I think you can omit "software-defined" here.

2024-08-23 23:03 UTC, schrockn requested changes
enough changes to do a spin

2024-08-26 17:07 UTC, schrockn commented on examples/experimental/dagster-airlift/README.md
> +```
@dpeng817

2024-08-26 19:39 UTC, schrockn approved these changes

2024-08-26 19:39 UTC, merged