AssetSlice -> EntitySlice
dagster-io/dagster pull request #23910
Opened 2024-08-26 14:26 UTC by OwenKephart

## Summary & Motivation

Similar to the previous PR, but this time for AssetSlice. This lets us create and use slices of arbitrary EntityKeys. To help make this a bit simpler, I refactored the internal representation of an AssetSlice / EntitySlice to store a separate key/value so that the type system could independently understand the key type. I also removed some unused methods / code paths to aovid needing to refactor them . In particular, I removed the `time_windows` property of AssetSlice as it was unused outside of tests. We can always bring that back if we find a use for it.

## How I Tested These Changes

## Changelog [New | Bug | Docs]

NOCHANGELOG

2024-08-26 14:26 UTC, OwenKephart commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23910?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#23910** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23910?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#23907** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23907?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#23905** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23905?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#23904** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23904?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#23843** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23843?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#23842](https://github.com/dagster-io/dagster/pull/23842) <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23842?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @OwenKephart and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-03 11:46 UTC, schrockn commented on python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py
> -      partition windows.
Is this docblock moved somewhere?

2024-09-03 11:47 UTC, schrockn requested changes
To discuss today. I believe you floated moving from "slice" to "subset" here which I'm sympathetic to.

2024-09-09 23:31 UTC, OwenKephart commented
@schrockn I have a PR upstack which does the rename of EntitySlice -> EntitySubset

2024-09-19 16:04 UTC, OwenKephart commented
### Merge activity

* **Sep 19, 12:04 PM EDT**: @OwenKephart started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/23910).

2024-09-19 16:25 UTC, merged