[dagster-pipes] separate `get_params` and `read_messages`
dagster-io/dagster pull request #24098
Opened 2024-08-30 14:26 UTC by danielgafni

## Summary & Motivation

Currently we expect `MessageReader.read_messages` to do 2 things at the same time:
- read messages - makes sense right?
- yield parameters to pass to the `MessageWriter` - this is problematic, because sometimes reading can only happen after the external process has been launched (see my notes in Notion), but the `MessageWriter` parameters have to be set before starting it.

So, I would like to separate these 2 things into 2 different methods.

This will allow us to reuse the same `MessageWriter` for both cases (messages location known in advance and only after external process has been started).

This is going to be useful for EMR Pipes I'm working on since I could reuse the excellent `PipesS3MessageReader` to read logs from S3 which are written by AWS EMR.

The `CloudWatchMessageReader` was adjusted to demonstrate the new ability to call `.read_messages` manually after the external process has been launched. The tests involving this MessageReader are passing. 

## How I Tested These Changes
Existing tests should pass.

## Changelog [New | Bug | Docs]

> Replace this message with a changelog entry, or `NOCHANGELOG`

2024-08-30 14:29 UTC, danielgafni commented
* **#24098** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24098?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @danielgafni and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-30 14:49 UTC, danielgafni commented
hey @alangenfeld, would you be able to take a look? the PR is far from being ready, I would just like to hear your thoughts on the overall idea

2024-08-30 15:39 UTC, alangenfeld reviewed
My initial reaction to seeing this is that i think the bool toggle to flip whether `read_messages` is started in `open_pipes_session` introduces significant variability in behavior that is unfortunate.

The place my head goes is 
* keeping it so that `read_messages` always starts with the session 
* something like a thread is started to do the message reading, but it is blocked on receiving some information from the launch call to proceed to actually consuming messages
* we would add some way for that thread to listen for that new information to arrive, maybe something like thread safe "session state" that can be set and listened to

2024-08-30 17:25 UTC, danielgafni commented
I like what you're saying, it would also address another issue I have with the current design - the requirement to handle threading in individual implementations instead of providing a shared interface for doing this. 

How about something like this? 

```python
class MyMessageReader(PipesMessageReader):
    def read_location_known(self, extra_params: PipesParams) -> bool:
        # some logic to check if we have enough information from self + extra runtime params 

# thread running .read_messages
def read_messages():
    while not message_reader.read_location_known(self.shared_State.extra_params):
        sleep(0.05)

    message_reader.read_messages(handler, extra_params)

# inside PipesClient
with open_pipes_session() as session:
    response = ...  # launch external process
    session.update_params({"log_stream": response["log_stream"]})
    block_until_complete(response)
    
...

2024-08-30 18:00 UTC, alangenfeld commented
Yep, think were on the same page - my personal bias would be a more open ended `on_shared_state_change` method instead of the more prescriptive `read_location_known` setup. I imagine the `on_shared_state_change` fn would set an `Event`/ `Condition` that the thread would be waiting on before it then proceeds to poll logs.

We have this `on_opened` lifecycle method 
https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/_core/pipes/client.py#L165-L171
that is used to start log readers when the opened message comes through 
https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/_core/pipes/utils.py#L372-L389
which is in that sort of direction. 

See what feels best to you getting an actual implementation sorted out

2024-09-03 11:25 UTC, schrockn commented on python_modules/libraries/dagster-aws/dagster_aws/pipes/message_readers.py
> +        assert extra_params is not None, "extra_params must be provided."
we typically use check.invariant to check business logic like this as `assert` can be compiled out by a user

2024-09-03 11:27 UTC, schrockn commented on python_modules/dagster/dagster/_core/pipes/client.py
> +    def read_messages(
fwiw read_messages also is not really an accurate name as this point. it more instigates a reading process no?

2024-09-03 11:27 UTC, schrockn requested changes
Just queue management since you are planning changes.

2024-09-12 15:43 UTC, danielgafni commented
So, I was working on this today for a while only to discover that a near exact copy of what I was thinking about was already implemented by @smackesey!

I was a little surprised to find this logic in [PipesBlobStoreMessageReader](https://github.com/dagster-io/dagster/blob/c2a9c47cf98870dc87b0ce96a5e859afbc5e3938/python_modules/dagster/dagster/_core/pipes/utils.py#L239) and not in `PipesMessageReader`. I think that's why I haven't discovered this code earlier - I haven't really been looking into `PipesBlobStoreMessageReader`. 

Actually, the implementation of `PipesBlobStoreMessageReader` seems to be completely location-agnostic. I think it can be renamed to something like `PipesThreaderMessageReader` to emphasize on this. 

It's so general that I believe that most `PipesMessageReader`s could be replaced by it. 

The actual logs reading logic should go inside various [PipesLogReader](https://github.com/dagster-io/dagster/blob/c2a9c47cf98870dc87b0ce96a5e859afbc5e3938/python_modules/dagster/dagster/_core/pipes/utils.py#L431) implementations, which is a far more simple task, because all the threading logic is done inside `PipesBlobStoreMessageReader/PipesThreaderMessageReader`. 

@schrockn @alangenfeld @smackesey what do you think about renaming `PipesBlobStoreMessageReader` -> `PipesThreaderMessageReader` and reusing it everywhere (when possible)? 

@smackesey the only questions I have regarding your implementation is the following: `PipesBlobStoreMessageReader.on_opened` is only called after the external process has been started, so `opened_payload` can't be used to set parameters which determine the read location (for cases when read location is only know after the external process has been started). 

Therefore, the only real modification to the current `PipesBlobStoreMessageReader` code would be adding a third source of `log_params` which can be set manually. 

Am I thinking correct about this?

2024-09-13 12:51 UTC, closed without merging