Add kinds parameter to AssetSpec
dagster-io/dagster pull request #24154
Opened 2024-09-02 16:18 UTC by benpankow

## Summary

Introduces a `kinds` parameter to `AssetSpec`, sugar which converts immediately into the kind tags introduced in #23779.

## Test Plan

Unit tests.

2024-09-02 16:18 UTC, benpankow commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24154?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#24154** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24154?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#23779** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23779?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#23826](https://github.com/dagster-io/dagster/pull/23826) <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/23826?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @benpankow and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-03 11:22 UTC, schrockn requested changes
I think you need to restack this one

2024-09-04 16:02 UTC, schrockn commented
Thanks for separating this out. @PedramNavid would love for you to weigh in how to introduce something like this from the community eng perspective in terms of docs and community rollout. 

cc: @brandonphillips this is the sort of change that people will like a lot, especially when combined with all the kinds that @braunjj has added recently.

2024-09-30 13:42 UTC, schrockn approved these changes
I'm happy with the code here so unblocking. However I still think this is an opportunity to get spark some joy with low cost (alongside showcasing all the kinds available). So just want to make sure this is coordinated with product (@elementljarredc) and community eng

2024-10-01 05:29 UTC, PedramNavid commented
> I'm happy with the code here so unblocking. However I still think this is an opportunity to get spark some joy with low cost (alongside showcasing all the kinds available). So just want to make sure this is coordinated with product (@elementljarredc) and community eng

@benpankow once you've got this merged, let us know and we can find a way to showcase this.

2024-10-01 16:36 UTC, merged