WIP fix: Prevent job hang when Pod exits before init
dagster-io/dagster pull request #24280
Opened 2024-09-06 02:46 UTC by MattyKuzyk

## Summary & Motivation
This is meant to address https://github.com/dagster-io/dagster/issues/22453

Previously, if a pod was Evicted by the Kubelet or force deleted before initialization was finished, the `wait_for_pod` function would simply wait forever, forcing us to kill the job.

To solve this, we added a wait timeout loop specifically for the initial pod creation. As soon as the pod is "seen" for the first time by the Kubernetes API, we break out of that loop and continue to the main logic loop of waiting for pod readiness.

If at any point in that second loop the pod no longer exists, we know that it was unexpectedly deleted, and thus we need to raise an error so that the job doesn't hang indefinitely.

## How I Tested These Changes
- Added unit tests and 
- Ran successful jobs with these changes
- Killed pod on startup and confirmed that an error was raised, causing Dagster to retry the pod
## Changelog

Insert changelog entry or "NOCHANGELOG" here.

- [ ] `NEW` _(added new feature or capability)_
- [x] `BUGFIX` _(Fixed job hang when Pod exits before init)_
- [ ] `DOCS` _(added or updated documentation)_

2024-09-06 05:09 UTC, MattyKuzyk commented
Is there anything wrong with migrating to fstrings? I noticed their use is rampant elsewhere in the codebase so I assume it's fine.

2024-09-06 19:28 UTC, yuhan commented
@smackesey @danielgafni can you take a look?

2024-09-06 19:46 UTC, smackesey commented
@yuhan My k8s is weak, I think I'm not the right person to review this

2024-09-06 19:50 UTC, yuhan commented
adding @gibsondan (who recently made changes to k8s pipes) @alangenfeld (who built k8s pipes orginally)

2024-09-07 21:05 UTC, danielgafni requested changes
Amazing job! 

The logic seems correct to me.

Asked for a few small changes

2024-09-08 02:46 UTC, MattyKuzyk commented on python_modules/libraries/dagster-k8s/dagster_k8s/client.py
> +            wait_initial_timeout (numeric, optional): Timeout after which to give up and raise exception
Done

2024-09-08 02:46 UTC, MattyKuzyk commented on python_modules/libraries/dagster-k8s/dagster_k8s/client.py
> +                raise DagsterK8sError("Pod was unexpectedly killed")
Done

2024-09-08 20:59 UTC, danielgafni commented
@MattyKuzyk could you please run `make ruff`? Otherwise looking good!

2024-09-09 00:57 UTC, MattyKuzyk commented
Ran `make ruff`, should be good to go.

2024-09-09 11:15 UTC, danielgafni approved these changes
LGTM unless @alangenfeld has some comments

2024-09-10 14:50 UTC, alangenfeld commented
I trust y'all - not seeing any issues doing a quick skim

2024-09-10 15:20 UTC, merged