[definition-tags] Add new `run_tags` param to JobDefinition and associated constructs
dagster-io/dagster pull request #24379
Opened 2024-09-10 21:36 UTC by smackesey

## Summary & Motivation

## How I Tested These Changes

## Changelog

Insert changelog entry or "NOCHANGELOG" here.

- [ ] `NEW` _(added new feature or capability)_
- [ ] `BUGFIX` _(fixed a bug)_
- [ ] `DOCS` _(added or updated documentation)_

2024-09-10 21:36 UTC, smackesey commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24379?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#24379** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24379?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#24378** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24378?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#24377** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24377?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @smackesey and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-16 16:04 UTC, smackesey commented on examples/docs_snippets/docs_snippets_tests/deploying_tests/test_monitoring_daemon_examples.py
> -    assert asset_job.tags[MAX_RUNTIME_SECONDS_TAG] == 10
This change is just from adding tag normalization to `UnresolvedAssetJobDefinition` (where it should've been already anyway).

2024-09-23 13:57 UTC, schrockn commented on python_modules/dagster/dagster/_core/definitions/graph_definition.py
> +        x = JobDefinition.dagster_internal_init(
rm

2024-09-23 14:00 UTC, schrockn requested changes
I think it is important to document and test the cases where a sensor or schedule points to a job and emits a `RunRequest` along side the different combinations and `run_tags` and `tags`.

2024-09-25 19:04 UTC, smackesey commented
>I think it is important to document and test the cases where a sensor or schedule points to a job and emits a RunRequest along side the different combinations and run_tags and tags.

Good call, those tests have been added.

2024-09-27 18:50 UTC, schrockn approved these changes
Great thanks for pushing this through

2024-09-27 19:01 UTC, merged