[dagster-airlift] multi-task mapping
dagster-io/dagster pull request #24464
Opened 2024-09-12 23:20 UTC by dpeng817

## Summary & Motivation

## How I Tested These Changes

## Changelog

Insert changelog entry or "NOCHANGELOG" here.

- [ ] `NEW` _(added new feature or capability)_
- [ ] `BUGFIX` _(fixed a bug)_
- [ ] `DOCS` _(added or updated documentation)_

2024-09-12 23:20 UTC, dpeng817 commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24464?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#24464** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24464?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#24447** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24447?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#24277** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24277?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#24321** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24321?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dpeng817 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-13 13:22 UTC, schrockn commented on examples/experimental/dagster-airlift/dagster_airlift/constants.py
> +DAG_AND_TASK_ID_METADATA_KEY = "airlift/dag_and_task_ids"
In a follow up, let's change the prefix here to be `dagster-airlift`, the name of the publish pypi package, as that provides a convenient way to namespace tags and metadata in an enforceable way.

2024-09-13 14:58 UTC, schrockn reviewed
Let's come up with a noun for (dag_id, task_id) so that we can refer to lists of them.

I'm also skeptical of `RefToDefs` and `SharedSentinel` but I think we need motivating examples to iterate on it.

2024-09-13 17:51 UTC, dpeng817 commented
@schrockn potential nouns for dag and task id:
`DST (dag scoped task)`
`dagtask`
`coupling`

2024-09-16 16:52 UTC, schrockn commented on examples/experimental/dagster-airlift/dagster_airlift/constants.py
> +AIRFLOW_COUPLING_METADATA_KEY = "airlift/couplings"
Coupling a little odd (and has some understones)

2024-09-16 16:52 UTC, schrockn commented on examples/experimental/dagster-airlift/dagster_airlift/constants.py
> +AirflowCoupling = Tuple[str, str]
Definitely want something with named properties.

2024-09-16 16:55 UTC, schrockn commented on examples/experimental/dagster-airlift/dagster_airlift/core/dag_defs.py
> +    def to_defs(self) -> Definitions:
Need docblock or example usage to understand this

2024-09-16 16:58 UTC, schrockn commented on examples/experimental/dagster-airlift/dagster_airlift/core/defs_from_airflow.py
> +    dag_defs_list: List[Union[DagDefs, Definitions]] = [],
never default to `[]` https://docs.python-guide.org/writing/gotchas/

2024-09-16 16:59 UTC, schrockn commented on examples/experimental/dagster-airlift/dagster_airlift/core/defs_from_airflow.py
> +    dag_defs_list: List[Union[DagDefs, Definitions]] = [],
Seems like we should force the caller to merge all the DagDefs into `Definitions` or _only_ take Dag Defs. This interemediate is not satisfying.

2024-09-16 17:00 UTC, schrockn requested changes
We're going to need to talk some of this through. This will definitely have a bunch of downstream consequencs.

2024-09-18 17:36 UTC, closed without merging