[dagster-airlift][rfc] readme with proxying language
dagster-io/dagster pull request #24610
Opened 2024-09-19 20:53 UTC by dpeng817

## Summary & Motivation

## How I Tested These Changes

## Changelog

Insert changelog entry or "NOCHANGELOG" here.

- [ ] `NEW` _(added new feature or capability)_
- [ ] `BUGFIX` _(fixed a bug)_
- [ ] `DOCS` _(added or updated documentation)_

2024-09-19 20:53 UTC, dpeng817 commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24610?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#24610** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24610?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#24569** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24569?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#24556** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24556?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#24540** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24540?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dpeng817 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-20 15:01 UTC, schrockn commented on examples/experimental/dagster-airlift/examples/tutorial-example/README.md
> +## Proxying to Assets
So to be clear I still think we should describe this as "Migrating to Assets". Proxying is our _tool_ for facilitating the process.

2024-09-20 15:02 UTC, schrockn commented on examples/experimental/dagster-airlift/examples/tutorial-example/README.md
> +    proxied: False
I think this is great and makes it much more clear what is going on. This is tracking a specific technical behavior, not arbitrary metadata for bookkeeping.

2024-09-20 15:03 UTC, schrockn requested changes
Inline comments

2024-09-26 18:36 UTC, closed without merging