Fix dbt global config command
dagster-io/dagster pull request #24615
Opened 2024-09-19 23:07 UTC by clairelin135

## Summary & Motivation

## How I Tested These Changes

## Changelog

Insert changelog entry or "NOCHANGELOG" here.

- [ ] `NEW` _(added new feature or capability)_
- [ ] `BUGFIX` _(fixed a bug)_
- [ ] `DOCS` _(added or updated documentation)_

2024-09-19 23:08 UTC, clairelin135 commented
* **#24615** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24615?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @clairelin135 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-19 23:41 UTC, rexledesma requested changes
From dbt’s documentation:

> If a CLI option is supported by specific commands, rather than supported by all commands ("global"), it is generally not considered to be a "flag".

—full-refresh is not supported by all commands (e.g. dbt parse). So it shouldn’t even be a global config in the first place.

We should just clarify that the global_config_flags accept anything shown by dbt —help, to clarify the incorrect dbt docs.

2024-09-24 19:54 UTC, clairelin135 commented
Makes sense, agree with that update.

2024-09-24 20:00 UTC, rexledesma approved these changes

2024-09-24 20:19 UTC, merged