[dagster-embedded-elt] Include entire error message when failing to fetch Sling metadata
dagster-io/dagster pull request #24633
Opened 2024-09-20 19:53 UTC by benpankow

## Summary & Motivation

## How I Tested These Changes

## Changelog

Insert changelog entry or "NOCHANGELOG" here.

- [ ] `NEW` _(added new feature or capability)_
- [ ] `BUGFIX` _(fixed a bug)_
- [ ] `DOCS` _(added or updated documentation)_

2024-09-20 19:53 UTC, benpankow commented
* **#24633** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24633?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @benpankow and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-20 23:14 UTC, rexledesma requested changes

2024-09-20 23:14 UTC, rexledesma commented on python_modules/libraries/dagster-embedded-elt/dagster_embedded_elt/sling/sling_event_iterator.py
> +                "Failed to fetch row count for stream %s\nException: {e}",
Use f string?

2024-09-27 15:59 UTC, rexledesma approved these changes

2024-09-27 16:50 UTC, merged