[dagster-airlift] support time-window partitioned assets
dagster-io/dagster pull request #24773
Opened 2024-09-25 22:00 UTC by dpeng817

## Summary & Motivation

## How I Tested These Changes

## Changelog

Insert changelog entry or "NOCHANGELOG" here.

- [ ] `NEW` _(added new feature or capability)_
- [ ] `BUGFIX` _(fixed a bug)_
- [ ] `DOCS` _(added or updated documentation)_

2024-09-25 22:00 UTC, dpeng817 commented
* **#24773** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24773?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dpeng817 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-26 16:31 UTC, schrockn commented on examples/experimental/dagster-airlift/dagster_airlift/core/partition_utils.py
> +    return partitions_def.get_partition_key_for_timestamp(logical_date.timestamp())
we are definitely going to need to make this pluggable at some level

2024-09-26 16:32 UTC, schrockn submitted a review, later dismissed
Makes sense overall. I think it is going to be important to at least hypothesize what the user-pluggability story is going to be as users will want complete control over the format of the partition keys in the general case.

2024-09-26 16:46 UTC, schrockn commented on examples/experimental/dagster-airlift/dagster_airlift/core/partition_utils.py
> +    return partitions_def.get_partition_key_for_timestamp(logical_date.timestamp())
Yeah would like to see that downstack PR before stamping this

2024-09-26 17:14 UTC, dpeng817 commented
see https://github.com/dagster-io/dagster/pull/24807 @schrockn

2024-09-30 13:45 UTC, schrockn commented on examples/experimental/dagster-airlift/dagster_airlift/core/partition_utils.py
> +    logical_date = task_instance.logical_datetime
when do we use the name "logical" versus "effective"?

2024-09-30 13:46 UTC, schrockn commented on examples/experimental/dagster-airlift/dagster_airlift/core/airflow_instance.py
> +        return datetime.datetime.fromisoformat(logical_date_str)
oh I see this is airflow terminology

2024-09-30 13:48 UTC, schrockn commented on examples/experimental/dagster-airlift/dagster_airlift/core/partition_utils.py
> +    logical_date = task_instance.logical_datetime
To make this super clear, I think we should prefix local variables that store airflow's concept of date with `airflow_`. It is very easy IMO to get all the different notions of time confused in this function. Let's do a readability pass.

2024-09-30 13:49 UTC, schrockn requested changes
Let's do a pass to make sure we don't confuse the different notions of time floating around here.

2024-09-30 22:31 UTC, closed without merging