Sidecar Container Support
dagster-io/dagster pull request #24834
Opened 2024-09-27 00:18 UTC by tdipadova3rd

## Summary & Motivation

This PR adds support for sidecar containers for all Dagster pods, for versions of K8s before and after 1.29 ([Native Sidecars](https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/)).

Google recommends using Cloud SQL Auth Proxy to connect to Cloud SQL from Kubernetes. The proxy is deployed as a sidecar container, allowing application pods to connect to PostgreSQL as localhost while the proxy handles authentication and encryption over private IP. There is a [discussion item open](https://github.com/dagster-io/dagster/discussions/9086) requesting support for Cloud SQL Auth Proxy in self-hosted Dagster.

## How I Tested These Changes

I tested these changes by deploying Dagster on two GKE clusters, one running K8s 1.28 and one running K8s 1.30. Each deployment used the Cloud SQL Auth Proxy to connect to GCP Cloud SQL for the Webserver, Daemon, and Migrate Job. For K8s before 1.29, I use the DefaultRunLauncher and add the Cloud SQL Auth Proxy as a sidecar to the User Code Location. For K8s 1.29+, I use the K8s Run Launcher with a [Native Sidecar](https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/).

## Changelog

Insert changelog entry or "NOCHANGELOG" here.

- [x] `NEW` _(added new feature or capability)_
- [ ] `BUGFIX` _(fixed a bug)_
- [ ] `DOCS` _(added or updated documentation)_

2024-09-30 21:00 UTC, mlarose reviewed
Hi @tdipadova3rd 

Thank you very much for this contribution.

> For versions before 1.29, you can deploy Dagster with Cloud SQL Auth Proxy using a few custom commands. For these versions, you cannot use the K8sRunLauncher, instead you need to configure deployments to use the DefaultRunLauncher, which runs Dagster runs as new processes in the Code Location pod.

That's a quite severe limitation and, combined with the other workarounds (such as pgIsReadyCommandOverride and customMigrateCommand with arbitrary sleeps), I think the tradeoffs and potential land mines (seldomly hitting those timeouts leading to hard to debug failures) introduced to support <1.29 may not be worthwhile. How would you feel about dropping that from this PR?

2024-10-09 20:40 UTC, tdipadova3rd commented
@mlarose Thank you for the review! I've removed support for K8s versions <1.28 and I've renamed `extraInitContainers` to `extraPrependedInitContainers` where appropriate. I've deployed and tested these changes in my clusters. Please let me know if there's any other changes you'd like.

2024-10-10 19:16 UTC, mlarose commented
@gibsondan - this one looks good to me but i'd appreciate if you take a glance here.

2024-10-10 19:22 UTC, mlarose commented
> @mlarose Thank you for the review! I've removed support for K8s versions <1.29 and I've renamed `extraInitContainers` to `extraPrependedInitContainers` where appropriate. I've deployed and tested these changes in my clusters. Please let me know if there's any other changes you'd like.

@tdipadova3rd my understanding is you don't need the extraContainers anymore to support 1.29 sidecars. I suppose it's ok leave that feature there, however comments and the PR description still pointing to supporting that are a bit confusing.

2024-10-10 19:30 UTC, mlarose commented on helm/dagster/values.yaml
> +  # Extra init containers are started **before** the check-db-ready init container.
Unless you are reading the helm's chart implementation, which most users won't, the `check-db-ready` is unknown to readers of this configuration file.

Perhaps I'd wordsmith this as "Extra init containers are started **before** the connection to the database is tested."

2024-10-10 19:31 UTC, mlarose commented on helm/dagster/values.yaml
> +  # For K8s versions after 1.29, prefer using initContainers instead. See:
```suggestion
  # For K8s versions after 1.29, prefer using initContainers to use native sidecars instead. See:
```

2024-10-10 19:32 UTC, mlarose commented on helm/dagster/values.yaml
> +  # Extra init containers are started **before** the check-db-ready init container.
see other comment

2024-10-10 19:37 UTC, gibsondan commented
Hey @tdipadova3rd - there are a couple of formatting errors that our CI picked up as well: https://buildkite.com/dagster/unit-tests/builds/1055#019277e0-1939-46cc-9123-a1b97cd2bfc9 - you should be able to run it locally via "make ruff" once they're fixed to confirm so you don't have to wait for us to unblock it again.

2024-12-16 22:56 UTC, gibsondan requested changes
this might require a rebase now that a couple of months have passed. Still open to landing this once it passes CI!

2025-01-11 01:40 UTC, closed without merging