Basic task-based peering working
dagster-io/dagster pull request #24852
Opened 2024-09-27 18:37 UTC by schrockn

## Summary & Motivation

## How I Tested These Changes

## Changelog

Insert changelog entry or "NOCHANGELOG" here.

- [ ] `NEW` _(added new feature or capability)_
- [ ] `BUGFIX` _(fixed a bug)_
- [ ] `DOCS` _(added or updated documentation)_

2024-09-27 18:37 UTC, schrockn commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24852?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#24852** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24852?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#24850** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24850?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @schrockn and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-27 22:32 UTC, dpeng817 commented on examples/experimental/dagster-airlift/dagster_airlift/core/airflow_defs_data.py
> +    def construct_automapped_dag_assets_def(self) -> Definitions:
misleading name

2024-09-27 22:40 UTC, dpeng817 requested changes
handling of dag asset deps

2024-09-27 22:40 UTC, dpeng817 commented on examples/experimental/dagster-airlift/dagster_airlift/core/airflow_defs_data.py
> +        return Definitions.merge(Definitions(assets=specs), self.construct_dag_assets_defs())
[1] we need to link the leaf tasks to the dag asset that we create

2024-09-27 22:40 UTC, dpeng817 commented on examples/experimental/dagster-airlift/dagster_airlift_tests/unit_tests/core_tests/test_load_defs.py
> +    assert specs[dag1_standalone].deps == []
[1] I'd expect some assertions around the full dag asset as well, namely that it has a dep on all of these

2024-09-27 22:43 UTC, dpeng817 approved these changes
looks good outside of dag deps. But that's handled in a downstream

2024-09-30 13:52 UTC, schrockn commented
### Merge activity

* **Sep 30, 9:52 AM EDT**: @schrockn started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/24852).

2024-09-30 13:59 UTC, merged