Explicitly error if auto_materialize: use_sensors is set to False, but AutomationConditionSensorDefinitions are found
dagster-io/dagster pull request #24911
Opened 2024-09-30 19:42 UTC by OwenKephart

## Summary & Motivation

As title. This is an invalid state, and the previous behavior would be to ignore this sensor and continue using the daemon, which is very confusing.

Updated this so that we will error if we find ourselves in this state, informing users of the cause and the way to fix it (which should always just be to remove that instance configuration).

## How I Tested These Changes

Unit tests, confirmed that no existing organizations are in this state.

## Changelog

If the legacy `auto_materialize: use_sensors` instance configuration value is overridden to be `False`, and any `AutomationConditionSensorDefinitions` are defined, this will now raise an error rather than silently ignoring the sensor.

- [ ] `NEW` _(added new feature or capability)_
- [x] `BUGFIX` _(fixed a bug)_
- [ ] `DOCS` _(added or updated documentation)_

2024-09-30 19:42 UTC, OwenKephart commented
* **#24911** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/24911?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @OwenKephart and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-01 13:26 UTC, gibsondan reviewed
how does this error manifest in cloud?

2024-10-02 13:46 UTC, gibsondan requested changes
my fear is that this would not present in a user visible way in cloud, I think the deployment for the specific code location deploy adding the sensor would need to fail in some way in order for this to show up in CI/CD (which has some tradeoffs too since it would break their whole code location, as would this solution)

Ideally there would be some way to display this invalid state prominently somewhere in the UI without grinding everything to a halt but appreciate that that is a lot of work

I think @smackesey has run into similar challenges with the "you have multiple assets with the same name" error state (although that one is even trickier since it requires looking at multiple code locations at once, at least this one the error state is limited to a particular code location

2024-11-15 16:58 UTC, OwenKephart commented
closing this in favor of a banner-based approach

2024-11-15 16:58 UTC, closed without merging