[dagster-airlift] Assets forward tutorial
dagster-io/dagster pull request #25193
Opened 2024-10-10 18:02 UTC by dpeng817

## Summary & Motivation

## How I Tested These Changes

## Changelog

> Insert changelog entry or delete this section.

2024-10-10 18:03 UTC, dpeng817 commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25193?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#25193** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25193?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#25168** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25168?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25160** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25160?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25159** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25159?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25158** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25158?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25139** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25139?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25138** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25138?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25127** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25127?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#25128](https://github.com/dagster-io/dagster/pull/25128) <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25128?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* **#25126** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25126?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25125** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25125?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25124** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25124?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25120** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25120?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dpeng817 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-14 14:44 UTC, schrockn commented on examples/experimental/dagster-airlift/examples/tutorial-example/README.md
> +def rebuild_customer_list_assets() -> Sequence[Union[AssetsDefinition, AssetSpec]]:
Union type hints are rough. Not sure we have better alternative.

2024-10-14 14:45 UTC, schrockn requested changes
Unless necessary for tests, I don't think we should have `rebuild_customer_list_assets` as separate functions. Would rather have those inlined.

2024-10-14 15:57 UTC, dpeng817 commented
Yea, I don't think it's necessary anymore since we only have one top-level definitions object now. Before it would induce multiple to inline them.

2024-10-14 17:25 UTC, schrockn approved these changes

2024-10-14 20:24 UTC, dpeng817 commented on examples/experimental/dagster-airlift/examples/tutorial-example/README.md
> +mapped_assets = assets_with_task_mappings(
I think it makes things a bit more clear. I tend to favor smaller variable declarations over one large nested declaration for tutorial code.

2024-10-14 20:27 UTC, schrockn commented on examples/experimental/dagster-airlift/examples/tutorial-example/README.md
> +mapped_assets = assets_with_task_mappings(
ok np. I don't feel strongly either way!

2024-10-14 20:58 UTC, merged