[dagster-airlift] Make proxy operator pluggable
dagster-io/dagster pull request #25205
Opened 2024-10-10 23:10 UTC by dpeng817

## Summary & Motivation

## How I Tested These Changes

## Changelog

> Insert changelog entry or delete this section.

2024-10-10 23:10 UTC, dpeng817 commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25205?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#25205** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25205?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#25193** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25193?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25168** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25168?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25160** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25160?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25159** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25159?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25158** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25158?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25139** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25139?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25138** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25138?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25127** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25127?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#25128](https://github.com/dagster-io/dagster/pull/25128) <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25128?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* **#25126** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25126?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25125** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25125?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25124** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25124?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25120** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25120?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dpeng817 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-14 16:23 UTC, schrockn commented on examples/experimental/dagster-airlift/dagster_airlift/in_airflow/proxying_fn.py
> +    ] = None,
`build_task_fn`

And then we can avoid having to export `build_dagster_task` by instead having `BaseProxyTaskToDagsterOperator` implement a `build_from_task` `@classmethod` that the user can override.

2024-10-14 16:23 UTC, schrockn requested changes
suggestion to avoid public API

2024-10-14 16:28 UTC, schrockn commented on examples/experimental/dagster-airlift/examples/tutorial-example/tutorial_example/custom_operator_examples/custom_proxy.py
> +    operator_construction_callback=lambda task: build_dagster_task(
`build_from_task_fn= CustomProxyToDagsterOperator.build_from_task`

```python
class BaseProxyWhatever:

   @classmethod
   def build_from_task(cls, task):
      return build_dagster_task(task, cls)

```

2024-10-15 16:46 UTC, schrockn commented on examples/experimental/dagster-airlift/dagster_airlift/in_airflow/task_proxy_operator.py
> +    operator_overrides: Optional[Mapping[str, Any]] = None,
what's `operator_overrides`?

2024-10-15 16:46 UTC, schrockn requested changes
What is operator overrides?

2024-10-15 18:57 UTC, schrockn approved these changes

2024-10-15 19:59 UTC, merged