Make AutomationCondition evaluate optionally async
dagster-io/dagster pull request #25238
Opened 2024-10-11 20:58 UTC by briantu

## Summary & Motivation

## How I Tested These Changes

## Changelog

Insert changelog entry or "NOCHANGELOG" here.

- [ ] `NEW` _(added new feature or capability)_
- [ ] `BUGFIX` _(fixed a bug)_
- [ ] `DOCS` _(added or updated documentation)_

2024-10-11 20:59 UTC, briantu commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25238?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#25238** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25238?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#25014** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25014?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @briantu and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-11 21:06 UTC, OwenKephart requested changes

2024-10-11 21:06 UTC, OwenKephart commented on python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/boolean_operators.py
> +            child_result = await child_context.evaluate_async()
we don't use the child_context, so this and the above could be a one liner

2024-10-11 21:06 UTC, OwenKephart commented on python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/boolean_operators.py
> +            child_result = await child_context.evaluate_async()
see above

2024-10-11 21:06 UTC, OwenKephart commented on python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/boolean_operators.py
> +        child_result = await child_context.evaluate_async()
see above

2024-10-11 21:06 UTC, OwenKephart commented on python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/check_operators.py
> +            check_result = await check_condition.evaluate(
see above comment, this is also asyncio.gatherable I believe

2024-10-11 21:06 UTC, OwenKephart commented on python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/check_operators.py
> +            check_result = await check_condition.evaluate(
etc., you get the point

2024-10-11 21:06 UTC, OwenKephart commented on python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/dep_operators.py
> +            dep_result = await dep_condition.evaluate(
see above

2024-10-11 21:37 UTC, OwenKephart approved these changes
note comment, otherwise this is looking great so far!

2024-10-11 21:37 UTC, OwenKephart commented on python_modules/dagster/dagster/_core/definitions/declarative_automation/operators/since_operator.py
> +        trigger_result = await context.for_child_condition(
I'll be annoying and say that this and reset_result can be executed concurrently, so those are also gatherable as well

2024-10-22 19:44 UTC, OwenKephart approved these changes

2024-10-22 22:08 UTC, briantu commented
### Merge activity

* **Oct 22, 6:08 PM EDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/25238).

2024-10-22 22:19 UTC, merged