[dagster-airlift] Support dag-level overrides in builder
dagster-io/dagster pull request #25243
Opened 2024-10-11 23:06 UTC by dpeng817

## Summary & Motivation

## How I Tested These Changes

## Changelog

> Insert changelog entry or delete this section.

2024-10-11 23:07 UTC, dpeng817 commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25243?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#25205** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25205?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25193** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25193?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25168** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25168?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25160** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25160?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25159** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25159?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25158** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25158?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25243** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25243?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#25242** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25242?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dpeng817 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-14 14:47 UTC, schrockn commented on examples/experimental/dagster-airlift/dagster_airlift/core/airflow_defs_data.py
> +    def peered_dag_asset_keys_by_handle(self) -> Mapping[DagHandle, AbstractSet[AssetKey]]:
`by_dag_handle` for clarity IMO

2024-10-14 14:50 UTC, schrockn commented on examples/experimental/dagster-airlift/dagster_airlift/core/sensor/sensor_builder.py
> +    # If there is a dagster run for this dag, we don't need to synthesize materializations for mapped dag assets.
The double negative in the comment makes this a little hard to follow.

# No dagster runs means that the computation that materializes the asset was not proxied to Dagster. Therefore we are going to emit synthetic materializations based on the airflow executoion data.

2024-10-14 14:57 UTC, schrockn commented on examples/experimental/dagster-airlift/dagster_airlift/core/serialization/compute.py
> +
this naming is confusing alongside `asset_keys_in_dag_by_id` IMO. `asset_keys_by_dag` should have a more specific name to indicate only contains DAG to asset mappings

2024-10-14 14:58 UTC, schrockn commented on examples/experimental/dagster-airlift/dagster_airlift/core/serialization/compute.py
> +
`asset_keys_by_mapped_dag_id`?

2024-10-14 14:59 UTC, schrockn commented on examples/experimental/dagster-airlift/dagster_airlift/core/utils.py
> +    return set(dag_handles)
nit: could be set comprehension

2024-10-14 15:00 UTC, schrockn commented on examples/experimental/dagster-airlift/dagster_airlift/core/serialization/compute.py
> +        return [spec for spec in self.asset_specs if is_dag_mapped_asset_spec(spec)]
`mapped_dag_asset_specs`?

2024-10-14 15:01 UTC, schrockn requested changes
I think we need a round of naming consistency pass here around "mapped task" and "mapped dag"

2024-10-14 15:57 UTC, schrockn commented on examples/experimental/dagster-airlift/dagster_airlift/core/serialization/compute.py
> +    def mapped_asset_keys_by_dag_id(self) -> Dict[str, Set[AssetKey]]:
`asset_keys_by_mapped_dag_id` I think it more accurate?

2024-10-14 15:57 UTC, schrockn commented on examples/experimental/dagster-airlift/dagster_airlift/core/serialization/compute.py
> +    def mapped_asset_keys_by_task(self) -> Dict[str, Dict[str, Set[AssetKey]]]:
`asset_keys_by_mapped_task_id`?

2024-10-14 15:59 UTC, schrockn approved these changes
Please heed final naming suggestion!

2024-10-14 20:00 UTC, merged