Add `executed_with_root_target` condition to handle partial runs / failures
dagster-io/dagster pull request #25253
Opened 2024-10-14 17:00 UTC by OwenKephart

## Summary & Motivation

Resolves: https://github.com/dagster-io/dagster/issues/24389

To put it simply, this ensures the `any_deps_updated` condition does not "count" an update from a parent if the run that materialized that parent also planned to materialize the child.

This guards against a variety of situations where a run can be launched with the intention of updating many assets, but fail to do so for whatever reason (intentional skip, failure event). In those cases, the assumption is that the child should NOT be attempted again (even though the parent did successfully materialize).

This is a fairly niche implementation detail that users should not have to think about when crafting their own policies.

## How I Tested These Changes

I added a parameterized test that failed before this change (for the skip and fail cases) and passes now.

## Changelog

Fixed an issue with `AutomationCondition.eager()` that could cause it to attempt to launch a second attempt of an asset in cases where it was skipped or failed during a run where one of its parents successfully materialized.

2024-10-14 17:00 UTC, OwenKephart commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25253?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#25253** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25253?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#25215** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25215?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#25204](https://github.com/dagster-io/dagster/pull/25204) <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25204?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* **#25214** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25214?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25211** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25211?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25210** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25210?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25203** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25203?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25190** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25190?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25187** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25187?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25186** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25186?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25184** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25184?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25171** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25171?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25170** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25170?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @OwenKephart and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-16 00:14 UTC, schrockn commented on python_modules/dagster/dagster/_core/asset_graph_view/asset_graph_view.py
> +    def _compute_latest_check_run_executed_with_target(
Fact that these two implementations are so different is brutal

2024-10-16 00:15 UTC, schrockn requested changes
Are there performance implications of this given that it is in the `eager` condition and ends up invoking `expensively_compute_partition_keys`? Are we saved by `latest_time_window` here?

2024-10-17 19:49 UTC, OwenKephart commented
We're actually saved by the fact that this is and'd together with the `newly_updated` condition. So we only check this on the exact tick that a parent updates, which pretty severely caps the number of total partitions we might be dealing with here

2024-10-22 11:34 UTC, schrockn commented on python_modules/dagster/dagster/_core/definitions/declarative_automation/automation_condition.py
> +                    & ~AutomationCondition.executed_with_root_target()
Can you make the comment about perf you made in the PR discussion as a comment here.

2024-10-22 11:35 UTC, schrockn approved these changes

2024-10-22 16:50 UTC, OwenKephart commented
### Merge activity

* **Oct 22, 12:50 PM EDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/25253).

2024-10-22 17:02 UTC, merged