[asset-graph-view] Make deserializing subsets safer
dagster-io/dagster pull request #25340
Opened 2024-10-17 16:04 UTC by OwenKephart

## Summary & Motivation

As title. This guards against situations in which an asset is completely removed from the graph and we try to get an EntitySubset from a SerializedEntitySubset.

## How I Tested These Changes

## Changelog

NOCHANGELOG

2024-10-17 16:04 UTC, OwenKephart commented
* **#25340** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25340?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @OwenKephart and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-17 17:08 UTC, schrockn requested changes
Makes sense. This seems like the type of change that should include a repro test.

2024-10-22 11:33 UTC, schrockn approved these changes

2024-10-22 11:33 UTC, schrockn approved these changes
[![yaytests](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/wS38mdcdU6aAeJobBdry/ece75c18-84d5-4630-9bef-f2d18e3c554a/yaytest.gif)](https://app.graphite.dev//settings/meme-library?org=dagster-io)

2024-10-22 16:39 UTC, OwenKephart commented
### Merge activity

* **Oct 22, 12:39 PM EDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/25340).

2024-10-22 16:39 UTC, merged