[dagster-airlift] Fixes for demo
dagster-io/dagster pull request #25358
Opened 2024-10-18 04:59 UTC by dpeng817

## Summary & Motivation

## How I Tested These Changes

## Changelog

> Insert changelog entry or delete this section.

2024-10-18 05:00 UTC, dpeng817 commented
* **#25358** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25358?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dpeng817 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-18 16:48 UTC, schrockn requested changes
Per discussion, the airflow tag is ambiguous now that we aren't querying the proxying state from Airflow. Instead we can just add an airlift tag.

2024-10-18 20:07 UTC, schrockn commented on js_modules/dagster-ui/packages/ui-core/src/graph/OpTags.tsx
> +    content: 'Airlift Mapped',
How about just "Mapped"

2024-10-18 20:37 UTC, dpeng817 commented on js_modules/dagster-ui/packages/ui-core/src/graph/OpTags.tsx
> +    content: 'Airlift Mapped',
Fine with that

2024-10-22 11:22 UTC, schrockn commented on examples/experimental/dagster-airlift/dagster_airlift/core/serialization/defs_construction.py
> +    tags = {**spec.tags, **airlift_mapped_kind_dict()}
local variable seems unnecessary

2024-10-22 11:24 UTC, schrockn commented on examples/experimental/dagster-airlift/dagster_airlift/core/serialization/defs_construction.py
> +        tags=tags,
use functions added in #25094?

2024-10-22 11:24 UTC, schrockn commented on examples/experimental/dagster-airlift/dagster_airlift/core/serialization/defs_construction.py
> +            tags={**airflow_kind_dict(), f"{KIND_PREFIX}dag": ""},
use kinds argument?

2024-10-22 11:25 UTC, schrockn approved these changes
Cool. Had minor suggestions.

2024-10-22 16:33 UTC, dpeng817 commented
### Merge activity

* **Oct 22, 9:33 AM PDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/25358).

2024-10-22 16:33 UTC, merged

2024-10-22 16:34 UTC, dpeng817 commented on examples/experimental/dagster-airlift/dagster_airlift/core/serialization/defs_construction.py
> +        tags=tags,
whoops. I'll do this in a follow up

2024-10-22 16:34 UTC, dpeng817 commented on examples/experimental/dagster-airlift/dagster_airlift/core/serialization/defs_construction.py
> +            tags={**airflow_kind_dict(), f"{KIND_PREFIX}dag": ""},
similarly forces us to bump pin