[RFC] make docker termination timeout configurable
dagster-io/dagster pull request #25365
Opened 2024-10-18 13:00 UTC by sryza

## Summary & Motivation

Not a part of the codebase I am super familiar with, but makes it possible to configure the timeout when canceling a run launched by the docker run launcher.

A couple questions:
- Does it make sense to set a termination timeout on the docker executor?
- If so, is there somewhere that we test step termination

## How I Tested These Changes

## Changelog

> Insert changelog entry or delete this section.

2024-10-18 13:07 UTC, gibsondan commented
I see a stop_timeout argument referenced here too that could in theory be
set at run launch time?
https://docker-py.readthedocs.io/en/stable/api.html

But am unsure if the higher level api that we are using to create the
container gives us access to that lower level api parameter

On Fri, Oct 18, 2024 at 9:01 AM Sandy Ryza ***@***.***> wrote:

> @sryza <https://github.com/sryza> requested your review on: #25365
> <https://github.com/dagster-io/dagster/pull/25365> [RFC] make docker
> termination timeout configurable.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dagster-io/dagster/pull/25365#event-14720396697>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACAPJC44TOQPGBQDU75PJ4TZ4EBAXAVCNFSM6AAAAABQF5ALEKVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJUG4ZDAMZZGY3DSNY>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2024-10-18 13:18 UTC, gibsondan commented
I think it’s possible that container_kwargs.stop_timeout will work already
for this with no code changes required?

On Fri, Oct 18, 2024 at 9:08 AM gibsondan ***@***.***> wrote:

> I see a stop_timeout argument referenced here too that could in theory be
> set at run launch time?
> https://docker-py.readthedocs.io/en/stable/api.html
>
> But am unsure if the higher level api that we are using to create the
> container gives us access to that lower level api parameter
>
> On Fri, Oct 18, 2024 at 9:01 AM Sandy Ryza ***@***.***> wrote:
>
> > @sryza <https://github.com/sryza> requested your review on: #25365
> > <https://github.com/dagster-io/dagster/pull/25365> [RFC] make docker
> > termination timeout configurable.
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <https://github.com/dagster-io/dagster/pull/25365#event-14720396697>,
> or
> > unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/ACAPJC44TOQPGBQDU75PJ4TZ4EBAXAVCNFSM6AAAAABQF5ALEKVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJUG4ZDAMZZGY3DSNY>
>
> > .
> > You are receiving this because your review was requested.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dagster-io/dagster/pull/25365#issuecomment-2422439189>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACAPJCYKV4RR4S73HVBRH2TZ4EB3VAVCNFSM6AAAAABQF5ALEKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMRSGQZTSMJYHE>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2024-10-22 13:25 UTC, gibsondan requested changes
humbly suggesting https://github.com/dagster-io/dagster/pull/25423 as an alternate solution here

2024-10-28 14:55 UTC, sryza commented
@gibsondan makes sense to me!

2024-10-28 14:55 UTC, closed without merging