[utils] add supersession warning and decorator
dagster-io/dagster pull request #25363
Opened 2024-10-18 10:26 UTC by danielgafni

## Summary & Motivation

## How I Tested These Changes

## Changelog

> Insert changelog entry or delete this section.

2024-10-18 10:26 UTC, danielgafni commented
* **#25335** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25335?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25362** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25362?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25363** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25363?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @danielgafni and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-18 10:35 UTC, danielgafni commented on python_modules/dagster/dagster/_utils/warnings.py
> +        f"{subject} is superseeded and it's usage is discouraged."
Thanks :robot:

2024-10-18 13:50 UTC, cmpadden requested changes
Overall looks good.

@danielgafni some pyright errors:
```
[2024-10-18T11:29:26Z] Creating temporary pyright config file at pyrightconfig-alt-1.json
[2024-10-18T11:29:26Z] Running pyright for environment `alt-1`...
[2024-10-18T11:29:26Z]   pyright --project=pyrightconfig-alt-1.json --outputjson --level=warning --warnings
[2024-10-18T11:29:39Z] Creating temporary pyright config file at pyrightconfig-master.json
[2024-10-18T11:29:39Z] Running pyright for environment `master`...
[2024-10-18T11:29:39Z]   pyright --project=pyrightconfig-master.json --outputjson --level=warning --warnings
[2024-10-18T11:33:45Z]
[2024-10-18T11:33:45Z] /workdir/docs/sphinx/_ext/dagster-sphinx/dagster_sphinx/__init__.py:
[2024-10-18T11:33:45Z]   127:32: Argument of type "SupersededInfo" cannot be assigned to parameter "info" of type "DeprecatedInfo | ExperimentalInfo" in function "inject_object_flag"
[2024-10-18T11:33:45Z]   Type "SupersededInfo" is not assignable to type "DeprecatedInfo | ExperimentalInfo"
[2024-10-18T11:33:45Z]     "SupersededInfo" is not assignable to "DeprecatedInfo"
[2024-10-18T11:33:45Z]     "SupersededInfo" is not assignable to "ExperimentalInfo" (reportArgumentType)
[2024-10-18T11:33:45Z]
[2024-10-18T11:33:45Z] pyright 1.1.379
[2024-10-18T11:33:45Z] Finished in 252.57600000000002 seconds
```

2024-10-18 22:18 UTC, danielgafni commented
@cmpadden I believe this error is from the upstack PR. This should be good to approve.

2024-10-21 20:04 UTC, cmpadden approved these changes

2024-10-21 20:06 UTC, danielgafni commented
### Merge activity

* **Oct 21, 4:06 PM EDT**: [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/25363) rebased this pull request as part of a merge.

2024-10-21 20:06 UTC, merged