[dagster-powerbi] Update Power BI documentation to showcase new API patterns
dagster-io/dagster pull request #25468
Opened 2024-10-23 19:49 UTC by benpankow

## Summary

Updates our Power BI docs to incorporate the new specs-building pattern, norm of passing the resource to `Definitions`, and the new pattern for building executable asset definitions.

2024-10-23 19:50 UTC, benpankow commented
* **#25468** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25468?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @benpankow and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-23 20:29 UTC, cmpadden requested changes
Overall looks great--just a few broken links possibly due to a needed `make apidoc-build`.

2024-10-23 20:29 UTC, cmpadden commented on docs/content/integrations/powerbi.mdx
> +Dagster can automatically load all semantic models, data sources, reports, and dashboards from your Power BI workspace as asset specs. Call the <PyObject module="dagster_powerbi" method="load_powerbi
`load_powerbi_asset_specs` link does not work; if this is new make sure to run `make apidoc-build`.

<img width="315" alt="image" src="https://github.com/user-attachments/assets/5d5db40d-4bf5-4b4c-938e-dee6f674af0e">

2024-10-23 20:29 UTC, cmpadden commented on docs/content/integrations/powerbi.mdx
> +Dagster's default behavior is to pull in representations of Power BI semantic models as external assets, which appear in the asset graph but can't be materialized. However, you can build executable a
Broken link for this one too

2024-10-30 20:37 UTC, cmpadden approved these changes
The passing of `specs` to the `assets` Definitions parameter still feels odd to me.

And the amount of boilerplate required to filter executable / non-executable assets is a bit much for end-users. But I'm liking the direction that these things are moving, and I suspect we'll be able to reduce the API surface over time.

Thanks for all the great work, and making sure docs are included @benpankow .

2024-10-31 16:11 UTC, merged