always fetch storage_ids by partition for latest materializations call
dagster-io/dagster pull request #25511
Opened 2024-10-24 18:49 UTC by prha

## Summary & Motivation

## How I Tested These Changes

## Changelog

> Insert changelog entry or delete this section.

2024-10-24 18:50 UTC, prha commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25511?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#25511** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25511?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#25510** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25510?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @prha and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-25 02:14 UTC, gibsondan requested changes
one small thing - little worried about the 'fetch every asset partition' case and i think we could leave out passing in the filter for that case? otherwise looks good

2024-10-25 02:14 UTC, gibsondan commented on python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
> -            }
the change being made in this PR seems like a big improvement for the case where you pass in 1001 partitions and there are 10000 partitions - we were fetching a bunch of materializations before in that case that we then just threw out and didn't use right?

2024-10-25 02:14 UTC, gibsondan commented on python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
> +                    set(partitions),
do we need to pass this in the partitions set if partitions is None (i.e. we want all partitions)? I think we don't, right? I could imagine it being slower to add the filter that lists every single partition for that case

2024-10-25 17:51 UTC, prha commented
@gibsondan there's also an argument to be made that in the case partitions is `None`, we'll want to paginate through the known set of partitions in chunks of 1000...

2024-10-27 15:32 UTC, gibsondan approved these changes
re: paginating in chunks i could see that too, i guess we are trading off timing out the whole request potentially vs. timing out an individual query - could also see the argument for eventually disallowing the query_all_partitions case and requiring callsites to paginate, that might be better than paginating for them within the body of the resolver

2024-10-27 15:32 UTC, gibsondan commented on python_modules/dagster-graphql/dagster_graphql/schema/asset_graph.py
> +            get_partition(event): event for event in events_for_partitions
i don't think get_partition needs to be a lambda anymore now that it is only used in one path

2024-10-28 17:10 UTC, merged