[dagster-airlift] Observe stage
dagster-io/dagster pull request #25820
Opened 2024-11-08 20:20 UTC by dpeng817

## Summary & Motivation

## How I Tested These Changes

## Changelog

> Insert changelog entry or delete this section.

2024-11-08 20:20 UTC, dpeng817 commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25820?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#25821** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25821?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25820** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25820?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#25819** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25819?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25816** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25816?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25815** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25815?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#25814** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25814?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dpeng817 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-11-11 15:37 UTC, cmpadden requested changes
Overall looks good--couple of nits.

2024-11-11 15:37 UTC, cmpadden commented on docs/content/integrations/airlift/tutorial/observe.mdx
> +_Note: There will be some delay between task completion and assets materializing in Dagster, managed by the sensor. This sensor runs every 30 seconds by default (you can reduce down to one second via
```suggestion
_Note: There will be some delay between task completion and assets materializing in Dagster, managed by the sensor. This sensor runs every 30 seconds by default (you can reduce down to one second via the `minimum_interval_seconds` argument to `sensor`)._
```

rm repetition

2024-11-11 15:37 UTC, cmpadden commented on docs/content/integrations/airlift/tutorial/observe.mdx
> +If your assets represent a time-partitioned data source, Airlift can automatically associate your materializations to the relevant partitions. In the case of `rebuild_customers_list`, data is daily p
```suggestion
If your Airflow tasks produce time-partitioned assets, Airlift can automatically associate your materializations to the relevant partitions. In the case of `rebuild_customers_list`, data is daily partitioned in each created table, and and the Airflow DAG runs on a `@daily` cron schedule. We can likewise add a `DailyPartitionsDefinition` to each of our assets.
```

Tried to clarify that this time based partitioning comes from Airflow, and we're mapping it to DailyPartitionsDefinition.

2024-11-12 18:27 UTC, cmpadden approved these changes

2024-11-12 18:34 UTC, merged