Fixed sensor returning all keys instead of latest keys
dagster-io/dagster pull request #25891
Opened 2024-11-13 00:29 UTC by kevSweet

## Summary & Motivation
Related to this issue: [https://github.com/dagster-io/dagster/issues/25890](url)

2024-11-21 18:34 UTC, maximearmstrong requested changes

2024-11-21 18:34 UTC, maximearmstrong commented on python_modules/libraries/dagster-aws/dagster_aws/s3/sensor.py
> +        return []
Could we add a comment to describe what is happening and a test in `dagster_was_test/s3_tests/test_s3_sensor.py`?

2025-01-08 21:19 UTC, garethbrickman commented
@kevSweet Just a ping in case you missed the above ^

2025-04-25 13:55 UTC, garethbrickman commented
Closing in favor of https://github.com/dagster-io/dagster/pull/29539

2025-04-25 13:55 UTC, closed without merging