Move replace_attributes, merge_attributes onto AssetSpec, publicise
dagster-io/dagster pull request #25941
Opened 2024-11-14 23:57 UTC by benpankow

## Summary

Now that they've baked for a little bit, moves the `replace_attributes` and `merge_attributes` utilities directly onto `AssetSpec`, and marks them public.

## How I Tested These Changes

Update unit test.

## Changelog

> Introduced AssetSpec.replace_attributes and AssetSpec.merge_attributes to easily alter properties of an asset spec.

2024-11-14 23:58 UTC, benpankow commented
* **#25941** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25941?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/25941?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `master`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-11-15 17:08 UTC, OwenKephart requested changes
generally supportive, just want to be careful about old params

2024-11-15 17:08 UTC, OwenKephart commented on python_modules/dagster/dagster/_core/definitions/asset_spec.py
> +        freshness_policy: Optional[FreshnessPolicy] = ...,
can we remove freshness_policy and automation_condition to avoid needing to go through a deprecation cycle on them?

2024-11-20 16:39 UTC, benpankow commented
> My only question before we introduce this is how we handle specs and `AssetsDefinitions` uniformly. Ideally we would have a one liner for that.

I can think of a couple options:

1. Rename these methods to `replace_spec_attributes`, `merge_spec_attributes` and also define them on `AssetsDefinition`. This leaves us with very nice behavior in comprehensions:

```python
my_specs_and_defs = ...

my_updated_specs_and_defs = [
  asset.replace_spec_attributes(owner="ben@dagsterlabs.com")
  for asset in my_specs_and_defs
]
```

2. Retain & publicize standalone methods which can operate on both specs and definitions, e.g. `dg.replace_spec_attributes`, `dg.merge_spec_attributes`. Under the hood, they just call `spec.replace_attributes(...)` or `def.map_specs(lambda spec: spec.replace_attributes(...))`


```python
my_specs_and_defs = ...

my_updated_specs_and_defs = [
  dg.replace_spec_attributes(asset, owner="ben@dagsterlabs.com")
  for asset in my_specs_and_defs
]

# Can still call directly on specs
my_spec = ...
my_spec = my_spec.replace_attributes(...)
```

3. No change, use ternary in comprehension:

```python
my_specs_and_defs = ...

my_updated_specs_and_defs = [
  asset.replace_attributes(owner="ben@dagsterlabs.com")
  for asset in my_specs_and_defs
  if isinstance(asset, AssetSpec)
  else
  asset.map_specs(lambda spec: spec.replace_attributes(owner="ben@dagsterlabs.com")
]
```

2024-11-20 17:31 UTC, benpankow commented
Yeah, maybe we want something like

```python
def map_specs(collection: Sequence[Union[AssetsDefinition, AssetSpec]], fn: Callable[[AssetSpec], AssetSpec]) -> Sequence[Union[AssetsDefinition, AssetSpec]]):
  return [x.map_specs(fn) for x in collection if isinstance(x, AssetsDefinition) else fn(x)]

my_specs_and_defs = ...

my_predicate: Callable[[AssetSpec], bool] = ...

my_updated_specs_and_defs = dg.map_specs(my_specs_and_defs, lambda spec: spec.replace_attributes(owner="ben@dagsterlabs.com") if my_predicate(spec) else spec)
```

2024-11-20 17:50 UTC, dpeng817 commented
I find myself more convinced by `map_specs` than `AssetsDefinition.replace_attributes` - to our discussion in product review, I think `replace_attributes` on `AssetsDefinition` seems overly specified. We're wrapping a primitive with `map_specs`, true, but I don't think it actually removes any of the flexibility of that primitive.

The problem; I think we'll unfortunately end up with a combinatorial explosion of these for every kind of spec. IE; `map_check_specs`. I think that's preferable to the alternative though of forcing users to encounter this awkwardness.

2024-11-22 20:39 UTC, schrockn submitted a review, later dismissed
Let's do a standalone function `map_asset_specs` 👍🏻

2024-11-23 00:12 UTC, benpankow commented
Introduced in #26109

2024-11-23 02:18 UTC, schrockn approved these changes

2024-11-25 17:52 UTC, merged