[asset selection] Introduce AssetSelection.to_selection.str
dagster-io/dagster pull request #26047
Opened 2024-11-20 20:10 UTC by benpankow

## Summary

On the backend, `AssetSelection` is a nice serializable representation of an asset selection, which we might generate through a few methods:

- From an Antlr asset selection string
- From a set of frontend filters, saved in a catalog view
- Potentially from snapshotted user code, though we don't do this right now

We don't have a good way to convert this selection back into a user-readable Antlr string. There are a few possible solutions here:

- Save the user-specified Antlr string alongside a selection. This seems like a promising approach when the initial source of truth is an Antlr string.
- Generate an Antlr string. This is the approach we'll need if the source of truth is user code or frontend filters where no Antlr string previously existed.

This PR introduces a `to_selection_str()` method on `AssetSelection` subclasses, which output a valid Antlr string representing that selection:

- The string must be parsed into an identical AssetSelection
- The string may not identically match the original Antlr string, if one exists

## Test Plan

New tests which
1. Ensure that Antlr strings can be converted to selections, back into strings, and back into a matching selection
2. Ensure that we have all Antlr literals under test, a rough proxy for ensuring we have full coverage of the grammar

2024-11-20 20:10 UTC, benpankow commented
* **#26047** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26047?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26047?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `master`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-11-21 20:33 UTC, briantu requested changes
Just one comment, otherwise lgtm!

2024-11-22 00:37 UTC, benpankow commented on python_modules/dagster/dagster/_core/definitions/asset_selection.py
> +            return f"{base} - ({child})"
Thanks, good catch

2024-11-22 06:50 UTC, salazarm reviewed
hmm not familiar with this code but I don't see any parenthetical grouping anywhere?

2024-11-22 17:03 UTC, merged