[components] Add ability to load a component using config
dagster-io/dagster pull request #26148
Opened 2024-11-26 18:20 UTC by OwenKephart

## Summary & Motivation

This adds a separate construction path for Components, which takes a dictionary of config that conforms to the class's config schema.

Because there's no generalized way to auto-generate a config schema or a conversion function, I think we'll end up relying in most cases on users subclassing an iniital simple implementation that just allows for some configured specs and maybe some unstrctured params, hence the AssetsComponent.

## How I Tested These Changes

## Changelog

> Insert changelog entry or delete this section.

2024-11-26 18:21 UTC, OwenKephart commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26148?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#26149** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26149?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26148** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26148?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26148?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#26143** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26143?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26104** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26104?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-11-26 18:48 UTC, schrockn requested changes
for discussion

2024-11-27 02:18 UTC, OwenKephart commented on python_modules/dagster/dagster/_components/__init__.py
> +        )
exactly yep

2024-11-27 02:20 UTC, OwenKephart commented on python_modules/dagster/dagster/_components/__init__.py
> +
totally agree, in a vacuum config feels natural but we'll have to come up with something else.

we could just call this method from_dict(), but certainly we will need some name for "blob of 'configuration' that determines properties of your components". Maybe some riff on "properties"?

2024-11-27 14:24 UTC, schrockn commented on python_modules/dagster/dagster/_components/__init__.py
> +    def from_config(cls, path: Path, config: Mapping[str, Any]) -> Self: ...
Config --> component params

2024-11-27 14:25 UTC, schrockn commented on python_modules/dagster/dagster/_components/__init__.py
> +class AssetSpecsModel(BaseModel):
eliminate pluralized. let's do lists

2024-11-27 14:26 UTC, schrockn requested changes
Enough for a spin

2024-11-27 15:50 UTC, schrockn approved these changes
Cool. Update PR summary and description.

2024-11-27 16:58 UTC, OwenKephart commented
### Merge activity

* **Nov 27, 11:58 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/26148).

2024-11-27 17:04 UTC, merged