[components] Add ability to load directly from path
dagster-io/dagster pull request #26150
Opened 2024-11-26 18:21 UTC by OwenKephart

## Summary & Motivation

This allows us to use the config loading system to load components from a path directly. All `defs.yaml` files conform to the same schema of:

```yaml

component_type: <component type>

config: <component-specific config>

```

## How I Tested These Changes

## Changelog

NOCHANGELOG

2024-11-26 18:21 UTC, OwenKephart commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26150?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#26150** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26150?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26150?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#26149** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26149?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26148** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26148?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26143** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26143?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26104** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26104?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-11-27 16:05 UTC, schrockn commented on python_modules/dagster/dagster_tests/components_tests/code_locations/python_script_location/scripts/defs.yml
> +      - key: override_key
Now that I see this I think it is important to restructure this schema to have an `asset_specs` key.

```yaml
component_type: collection
component_params:
  component_type: python_script
  components:
    script_one:
       assets:
          - key: a
          - key: b
             deps: [up1, up2]
    script_three:
       assets:
           - key: override_key
```

2024-11-27 16:05 UTC, schrockn requested changes
enough to do a spin

2024-11-27 17:46 UTC, schrockn approved these changes

2024-11-27 17:47 UTC, OwenKephart commented
### Merge activity

* **Nov 27, 12:47 PM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/26150).

2024-11-27 17:47 UTC, merged