[components] dg list
dagster-io/dagster pull request #26188
Opened 2024-11-28 00:38 UTC by smackesey

## Summary & Motivation

## How I Tested These Changes

## Changelog

> Insert changelog entry or delete this section.

2024-11-28 00:38 UTC, smackesey commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26188?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#26188** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26188?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26188?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#26176** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26176?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26185** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26185?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26178** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26178?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26175** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26175?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26166** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26166?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-10 14:36 UTC, schrockn commented on python_modules/libraries/dg-cli/dg_cli/cli/list.py
> +@click.group(name="generate")
looks real

2024-12-10 14:36 UTC, schrockn commented on python_modules/libraries/dg-cli/dg_cli/cli/list.py
> +    """List registered Dagster component types."""
legit

2024-12-10 14:37 UTC, schrockn requested changes
graphite reviewer bugs look real

2024-12-10 15:40 UTC, schrockn approved these changes

2024-12-10 15:42 UTC, smackesey commented on python_modules/libraries/dg-cli/dg_cli/cli/list.py
> +    for component_type in context.list_code_locations():
it's already fixed that's outdated

2024-12-10 15:42 UTC, merged