[components] Add @global_component decorator to register globally available components
dagster-io/dagster pull request #26185
Opened 2024-11-27 22:16 UTC by smackesey

## Summary & Motivation

## How I Tested These Changes

## Changelog

> Insert changelog entry or delete this section.

2024-11-27 22:16 UTC, smackesey commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26185?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#26176** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26176?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26185** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26185?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26185?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#26178** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26178?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26175** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26175?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26166** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26166?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-11-28 01:26 UTC, smackesey commented
>What is the motivating use case?

1. Supports development. We can experiment with new components by just plopping them in `dagster._components.impls` and slapping `@global_component` on them, they will then be available to `dg generate`.
2. When we release this feature we may wish to provide some basic components built in to Dagster, this is how we can expose them.

2024-11-28 12:36 UTC, schrockn requested changes
I think we should see if it avoid requiring this for now. Requiring module name at all times might actually teach the user how the system works. Let's discuss next week.

2024-12-12 12:52 UTC, smackesey commented
Closed because we have developed a different approach to registration/naming.

2024-12-12 12:52 UTC, closed without merging