Retry ECS START_TIMEOUT from run monitoring
dagster-io/dagster pull request #26183
Opened 2024-11-27 21:53 UTC by Zan-L

## Summary & Motivation
About 1% of ECS tasks fail to start. This change allows those unresponsive tasks to be retried from the run monitoring.

## How I Tested These Changes
N/A

## Changelog
- Implement `resume_run()` for ECS Run Launcher (by simply copying the `launch_run()` logic)
- Modify `monitor_starting_run()` to consider retries
- Pass `BaseWorkspaceRequestContext` from `execute_run_monitoring_iteration()` to `monitor_starting_run()`

2024-12-06 14:52 UTC, gibsondan requested changes
Hi @Zan-L - thank you for sending this out!

The goal of this change makes sense to me - I'd like to propose that we use a different way of detecting whether or not the run has failed based on some existing logic that actually already exists on the EcsRunLauncher for detecting transient startup failures, that we just haven't yet gotten around to integrating with the run monitoring daemon yet: https://github.com/dagster-io/dagster/blob/adadb8b8019333fd58813432fa472fb7fdf0d5a0/python_modules/libraries/dagster-aws/dagster_aws/ecs/launcher.py#L907

If the way this logic worked was instead:
- check the run worker health for all starting runs (similar to how we check the run worker health for all started runs),
- if the run worker status has a status FAILED and the transient flag is true, re-launch it
- (this is optional, but I think would also be a great additional change) - if the run worker has status failed and the transient flag is not True, fail or terminate it, something like this:
```
                if not run.is_finished:  # don't report failure if it's already been reported
                    message = f"{Detected that run worker failed" + (
                        f": {run_worker_status.message}" if run_worker_status.message else "."
                    )

                    if run.status == DagsterRunStatus.CANCELING:
                        instance.report_run_canceled(run, message)
                    else:
                        instance.report_run_failed(run, message)
```

This will allow you to get the behavior you want earlier, without having to wait for the run to time out (and will also prevent it from retrying unneccesarily in cases where it timed out for other, non-transient reasons)

I am also going to check with the team about whether it makes sense to build this on the experimental run_monitoring_max_resume_run_attempts feature or if this should be its own separate thing (this is less complicated than the exiting "resume crashed runs" feature since it doesn't need to worry about any steps having started on the run that might need to be resumed - you could call launch_run and not resume_run and get the same results) - I will get back to you on that.

2024-12-06 14:54 UTC, gibsondan commented
Finally I think we are definitely going to want some automated testing before landing this, but we can also sort that out once we have finalized the overall strategy.

2024-12-06 16:20 UTC, Zan-L commented
@gibsondan Thank you for following up! I actually saw that code piece for `_is_transient_startup_failure()` but it seemed unfinished with nothing calling it yet.

> This will allow you to get the behavior you want earlier, without having to wait for the run to time out

I think you meant that I didn't need to wait for `run start timeout` from run monitoring, but the alternative solution only introduces a separate timeout in addition to the one in run monitoring as the following line indicated:
https://github.com/dagster-io/dagster/blob/adadb8b8019333fd58813432fa472fb7fdf0d5a0/python_modules/libraries/dagster-aws/dagster_aws/ecs/launcher.py#L823

Please consider if that additional timeout is necessary.

At last, it seems almost all reasons in `_is_transient_stop_reason()` are related to timeouts. Of the three kinds of `CheckRunHealthResult` returned from `check_run_worker_health()`, only `_is_transient_startup_failure()` is actionable. Does it imply that all the efforts to implement worker health check just lead to retrying those time out at startup? If that's the case, my solution would be much simpler.

I may have limited understanding so forgive me if my ideas are wrong. Always happy to see it is being worked on!

2024-12-06 16:25 UTC, gibsondan commented
@Zan-L that's true that it's a timeout that's triggering the failure, but the timeout is from an error message returned from the ECS API rather than a configuration option in dagster, so its in a better position to be the source of truth for the failure - it's more or less as soon as ECS gives us the information that we can use to know that it failed.

There can be other reasons that a run worker failed, for example the code crashing - but those are the failures that we've identified as being returned from the ECS API due to transient issues with the ECS service that are outside of the user's control.

2024-12-06 16:46 UTC, Zan-L commented
Thank you for the clarification! The only concern I have left is that ECS may be unresponsive and thus not returning anything, which is what my solution aims to solve. If the health check mechanism covers that it would be great.

2024-12-06 16:48 UTC, gibsondan commented
I also just want to mention that there are some existing features that can help in this general case of 'run failed to start up and you want it to still execute' - specifically run retries, which can also be configured to only fire when they happen due to 'system' errors like this one: https://docs.dagster.io/deployment/run-retries#combining-op-and-run-retries

The main difference there is that it will create a new run instead of re-using the existing one, but that might not be a big deal here since no events have actually fired in the run yet?

2024-12-07 01:29 UTC, Zan-L commented
That's a nice feature I did not notice, Thanks! But the new run does introduce a bit of inconvenience - failure sensor would be triggered for every retry. I'll see if there's any workaround. Thanks again!

2024-12-07 13:26 UTC, gibsondan commented
We actually just added a “dagster/will_retry” tag in the release this week
that you could use to filter out runs from your run failure sensor that are
about to be automatically retried.

On Fri, Dec 6, 2024 at 7:30 PM Zan-L ***@***.***> wrote:

> That's a nice feature I did not notice, Thanks! But the new run does
> introduce a bit of inconvenience - failure sensor would be triggered for
> every retry. I'll see if there's any workaround. Thanks again!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dagster-io/dagster/pull/26183#issuecomment-2524744235>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACAPJC5MOQ4LTSGNMLO7JAD2EJFSJAVCNFSM6AAAAABSTZEBY2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKMRUG42DIMRTGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-12-07 19:30 UTC, Zan-L commented
That basically solved the problem in a more elegant way. I agree that retry mechanisms are spread across and really like to see the work on centralizing it. Thank you for letting me know! Now I can do things like this in the run failure sensor to retry just the error I want:
```python
if context.dagster_run.tags.get('dagster/will_retry') == 'true':
    if email_body.startswith('ECS task failed to start up'):
        context.instance.delete_run(context.dagster_run.run_id)
        return
    else:
        if new_run_id := context.dagster_run.tags.get('dagster/auto_retry_run_id'):
            context.instance.run_launcher.terminate(new_run_id)
            context.instance.delete_run(new_run_id)
```
Which is clean enough. Feel free to close this pull request.

One more thing though, as I was browsing through the code for auto retrying backfilled runs, I noticed that the current logic for determining whether a backfill has completed may still be flawed for assets with optional output, because only materialized and failed runs are considered complete:
https://github.com/dagster-io/dagster/blob/701562db5b21256ef6a409ce160ca9c7a1444cd6/python_modules/dagster/dagster/_core/execution/asset_backfill.py#L177-L182
This causes backfills to be stuck in `in progress` state if there is one partition that did not return output and also causes the Automation Condition backfill_in_progress() to always evaluate to true, blocking future automation. 

How about changing the logic from getting all that is materialized to all that has `RUN_SUCCESS` events for this function?
https://github.com/dagster-io/dagster/blob/701562db5b21256ef6a409ce160ca9c7a1444cd6/python_modules/dagster/dagster/_core/execution/asset_backfill.py#L1301

2025-01-08 12:13 UTC, closed without merging