[dagster-airbyte] Scaffold DagsterAirbyteTranslator for rework
dagster-io/dagster pull request #26205
Opened 2024-11-28 21:11 UTC by maximearmstrong

## Summary & Motivation

## How I Tested These Changes

## Changelog

> Insert changelog entry or delete this section.

2024-11-28 21:11 UTC, maximearmstrong commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26205?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#26205** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26205?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26205?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#26204** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26204?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-03 19:26 UTC, dpeng817 commented
I'm assuming the upstack is meant to be non-draft as well?

2024-12-03 19:35 UTC, dpeng817 requested changes
I think this needs to wait on approval on downstreams since this PR doesn't have full context. Removing from my queue for now.

2024-12-05 18:09 UTC, dpeng817 approved these changes

2024-12-05 21:16 UTC, merged