move op concurrency key as top-level definition arg
dagster-io/dagster pull request #26256
Opened 2024-12-03 20:53 UTC by prha

## Summary & Motivation
Tags are a bad mechanism for specifying concurrency controls.  Adds a top-level argument `concurrency_key` to asset/op definitions to replace the use of op tags to specify concurrency conditions.

This provides more cues for what you can place concurrency limits on (e.g. op defs not graph defs, asset defs not asset specs)

## How I Tested These Changes
BK

## Changelog
Adds a top-level argument `concurrency_key` to asset/op definitions to replace the use of op tags to specify concurrency conditions.

2024-12-11 23:41 UTC, schrockn submitted a review, later dismissed
So before we move forward with this I think we need to have a naming session of concurrency group versus pool versus something else. Important decision with long term ramifications.

2024-12-13 17:47 UTC, prha commented
* **#26458** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26458?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26256** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26256?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26256?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `master`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2025-01-09 16:57 UTC, schrockn requested changes
How about we introduce it as "hidden" for name (e.g. just in `kwargs`) so people don't start using it before we are ready?

2025-01-09 16:59 UTC, schrockn commented
Also are we going to add `PoolDefinition` somewhere if we want to attach metadata or other structured information?

2025-01-09 21:23 UTC, prha commented
Discussed offline, but putting here for posterity:

I don't have plans to add `PoolDefinition`, because that automatically ties pools to a code location, and we specifically want pools to be a concept governing across code locations.  If we come up with a richer API at the deployment layer, pools would be a great use case for it.

2025-01-10 01:18 UTC, prha commented
Instead of hiding the pool arg in kwarg, just issued a `preview_warning` which I will remove once this is ready to go in `1.10.0`

2025-01-15 00:51 UTC, OwenKephart requested changes
minor comments

2025-01-15 00:51 UTC, OwenKephart commented on python_modules/dagster/dagster/_core/definitions/graph_definition.py
> +    def pools(self) -> set[str]:
nit: prefer `from collections.abc import Set`

2025-01-15 00:51 UTC, OwenKephart commented on python_modules/dagster/dagster/_core/definitions/node_definition.py
> +    def pools(self) -> set[str]: ...
see above

2025-01-15 00:51 UTC, OwenKephart commented on python_modules/dagster/dagster/_core/definitions/op_definition.py
> +        """Optional[str]: The concurrency group for this op."""
nit: should the docstring say pool instead of group?

2025-01-15 00:51 UTC, OwenKephart commented on python_modules/dagster/dagster/_core/execution/plan/active.py
> +                pool = cast(str, step.pool)
nit: pre-existing, but should this be a check.str() instead of a cast?

2025-01-15 00:51 UTC, OwenKephart commented on python_modules/dagster/dagster/_core/snap/node.py
> +    pools: set[str]
see above

2025-01-15 00:51 UTC, OwenKephart commented on python_modules/dagster/dagster/_core/snap/node.py
> +@record_custom
why does this now need to be custom? does the backcompat not work if pool is just `pool: Optional[str] = None`?

2025-01-16 00:01 UTC, prha commented on python_modules/dagster/dagster/_core/definitions/graph_definition.py
> +    def pools(self) -> set[str]:
is that everyone's preference?  the incidence of `set` is like 4x the count of `Set`:

```
(dagster) ➜  dagster git:(prha/asset_op_concurrency_key) s '\bset\[' | wc
     423    2458   58005
(dagster) ➜  dagster git:(prha/asset_op_concurrency_key) s '\bSet\[' | wc
      99     773   15437
```

2025-01-16 23:50 UTC, OwenKephart commented on python_modules/dagster/dagster/_core/definitions/graph_definition.py
> +    def pools(self) -> set[str]:
for typing yeah -- I imagine almost all of those lower case `set`s are at runtime

until recently this was `from typing import AbstractSet`, `from collections.abc import Set` is the same thing but is now preferred by our linter -- this marks the return value as immutable, which has some value, but just in general I haven't seen `set[x]` used as a return type anywhere else in the code so we should be consistent

2025-01-16 23:51 UTC, OwenKephart approved these changes
approving but I do think the return types should be Set[str] instead of set[str]

2025-01-16 23:52 UTC, OwenKephart commented on python_modules/dagster/dagster/_core/snap/node.py
> +class OpDefSnap(IHaveNew):
why IHaveNew here?

2025-01-21 19:52 UTC, merged