[components] Add --editable-dagster-root to dg generate code-location
dagster-io/dagster pull request #26295
Opened 2024-12-05 18:59 UTC by smackesey

## Summary & Motivation

## How I Tested These Changes

## Changelog

> Insert changelog entry or delete this section.

2024-12-05 18:59 UTC, smackesey commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26295?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#26295** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26295?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26295?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#26293** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26293?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-06 18:01 UTC, schrockn commented
We could hide it if DAGSTER_GIT_REPO_DIR is not defined

2024-12-06 18:01 UTC, schrockn requested changes
I think this needs to be restack. It showing all the library moves

2024-12-09 23:22 UTC, smackesey commented
>We could hide it if DAGSTER_GIT_REPO_DIR is not defined

This might be a better long-term solution but I'd rather not right now to keep thing simple. Could get confusing in tests that are manipulating the environment in-process, while the CLI gets defined once at import time.

2024-12-09 23:37 UTC, OwenKephart approved these changes

2024-12-10 02:01 UTC, merged