Optional check db ready
dagster-io/dagster pull request #26343
Opened 2024-12-09 05:10 UTC by easontm

## Summary & Motivation

Address #26311 and #26284 (duplicate issues)

## How I Tested These Changes

1. Wrote some tests
2. Installed the chart to minikube with
```
helm install dagster . --set dagsterWebserver.image.tag=latest --set dagsterDaemon.image.tag=latest --set pipelineRun.image.tag=latest --set dagsterWebserver.checkDbReadyInitContainer=true
```
And observed the initContainers present. Then ran it again with `false`
```
helm install dagster . --set dagsterWebserver.image.tag=latest --set dagsterDaemon.image.tag=latest --set pipelineRun.image.tag=latest --set dagsterWebserver.checkDbReadyInitContainer=false
```
And observed the initContainers absent.

## Changelog

- Added flag `checkDbReadyInitContainer` to optionally disable db check initContainer.

2024-12-09 14:01 UTC, easontm commented on helm/dagster/schema/schema_tests/test_celery_queues.py
> +    assert daemon_deployment.spec.template.spec.init_containers is None or "check-db-ready" not in [
The first `is None` check is not strictly necessary for all tests, but default templates have initContainers and some don't. The shortcircuit makes it so the tests which _do_ have an initContainer by default will not start failing if that container is removed.

2024-12-13 14:10 UTC, cmpadden commented
Hey @gibsondan, these changes look reasonable and well enough tested to me.

Do you know who would be best to give the final sign off, saw you in the git blame a bit, but there were a lot of people in there.

2024-12-13 18:01 UTC, gibsondan requested changes
Hi @easontm - thank you for adding this and for the thorough tests. I have one last request for you related to said thorough tests - can you add a case where the value is not explicitly set? I think it's important that we capture that nothing has changed if the user has not explciitly overridden the value and is relying on it being set to true in the default templated values.yaml (so that we know the check won't be inadvertently disabled).

For example, if you had accidentally left out something in the values.yaml (or somebody accidentally removed it in the future) it would be good if a test started failing.

Other than that hopefully relatively quick change this looks great to me.

2024-12-14 03:02 UTC, easontm commented on helm/dagster/schema/schema_tests/test_celery_queues.py
> +            ),
Added! I verified by replacing `true` with `~` in the `values.yaml` file to intentionally break the test and it failed as it should.

2024-12-14 04:07 UTC, gibsondan approved these changes
thanks!

2024-12-14 04:07 UTC, merged