[components] Improve docstrings and clean up code in dagster-dg
dagster-io/dagster pull request #26406
Opened 2024-12-11 15:55 UTC by smackesey

## Summary & Motivation

## How I Tested These Changes

## Changelog

> Insert changelog entry or delete this section.

2024-12-11 15:55 UTC, smackesey commented
* **#26406** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26406?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26406?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `master`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-11 23:47 UTC, schrockn requested changes
For "project" versus "directory"

2024-12-11 23:47 UTC, schrockn commented on python_modules/libraries/dagster-dg/dagster_dg/cli/generate.py
> +    structure:
So we are going to have to workshop the use of term "project" especially as it pertains to deployment versus code locations.

2024-12-11 23:47 UTC, schrockn commented on python_modules/libraries/dagster-dg/dagster_dg/cli/generate.py
> +    structure:
Let's just refer to them as "directories" for now to avoid the project lingo, which I think has a lot of implications.

2024-12-12 00:33 UTC, schrockn approved these changes

2024-12-12 01:10 UTC, merged