[ui] Reject throttleLatest promise with a string instead of an Error
dagster-io/dagster pull request #26452
Opened 2024-12-12 19:30 UTC by hellendag

## Summary & Motivation

## How I Tested These Changes

## Changelog

> Insert changelog entry or delete this section.

2024-12-12 19:30 UTC, hellendag commented
* **#26452** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26452?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26452?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `master`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-13 12:43 UTC, salazarm commented
I think the actual issue is that the promise rejection was uncaught.

2024-12-13 12:43 UTC, salazarm requested changes
Can you confirm that the existing code still causes a DD error because I had landed a change to catch the promise error to stop DD from reporting it and curious if that worked or not (it didnt make it into the release).

2024-12-13 16:35 UTC, hellendag commented
Rejection catch should handle this as noted, closing.

2024-12-13 16:35 UTC, closed without merging