[components] Expose generation CLI params in dagster-dg
dagster-io/dagster pull request #26478
Opened 2024-12-13 17:51 UTC by smackesey

## Summary & Motivation

## How I Tested These Changes

## Changelog

> Insert changelog entry or delete this section.

2024-12-18 13:27 UTC, schrockn requested changes
I don't think it is viable to dump the user-defined options into the namespace as our own cmdline options.

This will mean we can never add cmdline options without potentially breaking user-defined components.

2024-12-18 13:42 UTC, smackesey commented
>This will mean we can never add cmdline options without potentially breaking user-defined components.

Options can be added at multiple levels of the command hierarchy, which is how this already works. For example:

```
dg --clear-cache generate component dagster_components.dbt_project USER_OPTIONS...
```

I think it makes sense to provide the final subcommand namespace as user-zone. Any options we want to add that would apply to _all_ component typse could be added to the `dg generate component` namespace where they would not collide with user options:

```
dg generate component --our-new-option dagster_components USER_OPTIONS...
```

>I don't think it is viable to dump the user-defined options into the namespace as our own cmdline options.

What is the alternative you're suggesting? Keep the user params behind `--`? Feels like kinda awkward DX to me.

2024-12-18 13:44 UTC, schrockn commented
Ah the "generic" option go before the component type, and the user-defined arguments go over the component type?

2024-12-18 13:45 UTC, smackesey commented
>Ah the "generic" option go before the component type, and the user-defined arguments go over the component type?

yes

2024-12-19 14:01 UTC, smackesey commented
@schrockn This has been stacked on the help string reformatting PR and the summary was updated with what the help string now looks like.

2024-12-19 14:27 UTC, schrockn reviewed
Could we make it:


```
$ dg generate component dagster_components.dbt_project --help

Usage: dg [DG_OPTIONS] generate component dagster_components.dbt_project [COMPONENT_OPTIONS] COMPONENT_NAME

Options (dagster_components.dbt_project):
  --json-params TEXT   JSON string of component parameters.
  --init BOOLEAN       init
  --project-path TEXT  project_path
  -h, --help           Show this message and exit.

Options (dg):
  --builtin-component-lib TEXT  Specify a builitin component library to use.
  --verbose                     Enable verbose output for debugging.
  --disable-cache               Disable caching of component registry data.
  --clear-cache                 Clear the cache before running the command.
  --cache-dir PATH              Specify a directory to use for the cache.
```

2024-12-19 14:29 UTC, schrockn approved these changes
Make sense. Consider suggestions to the help string.

2024-12-19 14:50 UTC, smackesey commented
@schrockn re your help string suggestions, I have some thoughts but let's discuss in standup and I can implement any changes in a followup

2024-12-19 15:24 UTC, merged