Simplify module asset loader code path
dagster-io/dagster pull request #26484
Opened 2024-12-13 20:24 UTC by dpeng817

## Summary & Motivation

## How I Tested These Changes

## Changelog

> Insert changelog entry or delete this section.

2024-12-13 20:24 UTC, dpeng817 commented
* **#26484** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26484?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26484?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `master`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-14 00:19 UTC, OwenKephart approved these changes
soooo much better

2024-12-14 00:19 UTC, OwenKephart commented on python_modules/dagster/dagster/_core/definitions/load_assets_from_modules.py
> +    def cacheables(self) -> Sequence[CacheableAssetsDefinition]:
let's spend the keystrokes on this name and call in `cacheable_assets_defs`

2024-12-14 00:19 UTC, OwenKephart commented on python_modules/dagster/dagster/_core/definitions/load_assets_from_modules.py
>              A tuple containing a list of assets, a list of source assets, and a list of
<!--__GRAPHITE_HTML_TAG_START__--><i class='graphite__hidden'>[Re: line +144]<br/><br/></i>

<!--__GRAPHITE_HTML_TAG_END__-->lol i guess remove that<!--__GRAPHITE_HTML_TAG_START__--><span class='graphite__hidden'><br/><br/>See this comment inline on <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26484?utm_source=unchanged-line-comment">Graphite</a>.</span>

<!--__GRAPHITE_HTML_TAG_END__-->

2024-12-14 00:19 UTC, OwenKephart commented on python_modules/dagster/dagster/_core/definitions/load_assets_from_modules.py
> +                    f"Asset key {key.to_user_string()} is defined multiple times. Definitions found in modules: {', '.join(set(self.module_name_by_id[id(asset_object)]
not critical (this is pre-existing thing), but one possibility here is for the asset to be defined twice in the same module, at which point this error message wouldn't be as helpful

wondering if in the case that the len(modules) == 1, we could print out the reprs of the individual objects or something.

feel free to ignore tho

2024-12-14 00:35 UTC, schrockn requested changes
I think we can do better here and simplify it further having `assets_from_modules` returning to a `List[AssetsDefinitions]` which will simplify all of this even more.

2024-12-14 00:38 UTC, OwenKephart commented
> I think we can do better here and simplify it further having `assets_from_modules` returning to a `List[AssetsDefinitions]` which will simplify all of this even more.

@schrockn this function is (somewhat tragically) part of the public API so we can't change the type signature

2024-12-14 00:42 UTC, schrockn commented
Ah yeah you are right. I was thinking that in our code it would be likely be backwards compatible change to go from 

`Sequence[Union[AssetsDefinition, SourceAsset, CacheableAssetsDefinition]]` to `Sequence[AssetsDefinition]` but that is only true if you don't do much processing in getting all those definitions and passing them to `Definitions`.

The only way out is through components.

2024-12-14 00:43 UTC, schrockn approved these changes

2024-12-18 18:38 UTC, merged