[dagster-embedded-elt] Expose dlt and sling extras
dagster-io/dagster pull request #26497
Opened 2024-12-13 23:40 UTC by deepyaman

## Summary & Motivation

As a user, I don't unnecessarily want to install Sling if I'm only using dlt and vice versa.

## How I Tested These Changes

## Changelog

> dlt and Sling are now extra requirements of the `dagster-embedded-elt` package; to include them, install `dagster-embedded-elt[dlt]` or `dagster-embedded-elt[sling]`, respectively.

2024-12-14 00:23 UTC, OwenKephart commented
@cmpadden @PedramNavid do either of you recall why we didn't do it this way to begin with? I remember there was some discussion about having embedded-elt be its own package vs. having dagster-sling and dagster-dlt, wondering if there's some context missing there

2024-12-14 00:49 UTC, PedramNavid commented
Can’t think of any reason why we wouldn’t do this. Will this be a breaking change?

2024-12-14 01:11 UTC, OwenKephart requested changes
discussed offline: this would unfortunately be a breaking change

2024-12-16 14:23 UTC, zilto commented
As a user, I was about to open a issue for the same reason.

## Inconvenience
- The pypi target `dagster-embbed-elt` doesn't follow the integration convention and I had to go through the docs to find it ("embbed elt" could be obscure terms for users)
- I don't want to install `sling` or depend on it. The Python install seems small, but it seems to [require a binary that's about 50Mb](https://github.com/slingdata-io/sling-cli/releases/), which might matter on AWS lambdas and such.
- The Python imports `dagster_embedded_elt` may be more obvious with `dagster_sling` and `dagster_dlt`

## Potential solution
There seems to be two-fold for backwards compatibility:
- **pypi**: create pypi targets `dagster-dlt` and `dagster-sling` while keeping `dagster-embbed-elt`
- **python modules**: Could have a `dagster-dlt` namespace that imports  `dagster_embbed_elt.dlt`

2024-12-16 17:07 UTC, OwenKephart commented
Hi @zilto ! Thanks for weighing in here -- we're currently planning on segmenting these libraries out essentially as you describe, although we'll likely just port the code for each integration into the new libraries and keep `dagster-embedded-elt` as a thin backcompat layer with dependencies on `dagster-sling` and `dagster-dlt` (rather than vice-versa)

2024-12-16 18:30 UTC, closed without merging