[components] Add dagster-dg global config and AppContext
dagster-io/dagster pull request #26516
Opened 2024-12-16 13:33 UTC by smackesey

## Summary & Motivation

Add a global `AppContext` and `DgConfig` object in `dagster-dg`. The purpose of these abstractions is to capture global configuration and pass it throughout the system. Global configuration is supported via top-level options passed to `dg` on the command line.

`AppContext` may appear premature in this PR, since it just wraps `DgConfig`. Upstack we add the cache to it.

## How I Tested These Changes

Unit tests.

2024-12-16 13:33 UTC, smackesey commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26516?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#26517** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26517?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26516** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26516?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26516?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#26512** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26512?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-16 15:53 UTC, schrockn requested changes
q mgmt as this will change based on what happens downstack

2024-12-17 18:53 UTC, schrockn commented on python_modules/libraries/dagster-dg/dagster_dg/context.py
> +class AppContext:
Can we make this a more specific class name? `AppContext` super general

2024-12-17 18:53 UTC, schrockn commented on python_modules/libraries/dagster-dg/dagster_dg/context.py
> +class AppContext:
whoa graphite

2024-12-17 18:54 UTC, schrockn approved these changes
would like a better name for `AppContext`

2024-12-17 20:46 UTC, merged