AssetMaterialization: allow to pass str, date or datetime
dagster-io/dagster pull request #26511
Opened 2024-12-15 10:07 UTC by Gw1p

## Summary & Motivation

Extend AssetMaterialization constructor to initialize `partition` using datetime.date and datetime.datetime (use `.isoformat()` in such case).

## How I Tested These Changes

In my local Dagster, materialized assets with str, datetime.date, datetime.datetime and tested that I get an error with another type.

I'm happy to look into adding a test.

## Changelog

> Allow constructing AssetMaterialization with `datetime.date` or `datetime.datetime` as partition. If passed, they will be iso-formatted so datetime.date becomes `YYYY-MM-DD` and  datetime.datetime becomes `YYYY-MM-DDTHH:MM:SS.ffffff` (if microsecond is not 0) or `YYYY-MM-DDTHH:MM:SS` otherwise.

2024-12-16 19:57 UTC, jamiedemaria reviewed
This seems like a fine change to me, but i'm not sure if there is a reason we only have allowed strings up to this point. @clairelin135 and @dpeng817 you're the most recent authors on this part of the code, do you have any additional context to add?

Would also like to see some tests for this before merging. https://github.com/dagster-io/dagster/blob/279d44aa2f325f2d2a883807da6f29bf3a2b10e1/python_modules/dagster/dagster_tests/asset_defs_tests/test_partitioned_assets.py would be a good spot to add them

2024-12-16 20:20 UTC, dpeng817 commented
I sympathize with the desire to have a convenient way of getting the partition key for an asset, but I don't love this approach. `AssetMaterialization` is a pretty core abstraction, and ultimately we expect all partition keys to be resolvable to strings. I think there's a ton of code paths that would break if partition_key was all of a sudden not necessarily a string.

Furthermore, the mapping of a datetime to a partition key depends on the actual partition definition of the asset, and in the constructor of an assetmaterialization we don't have access to that information (and I don't think we want to need access to that information). I think what you actually want to do is something like this:
```python
import dagster as dg
from datetime import datetime
MY_TIME_WINDOW_PARTITIONS_DEF = dg.DailyPartitionsDefinition(...)

my_datetime = datetime(...)

MY_TIME_WINDOW_PARTITIONS_DEF.get_partition_key(my_datetime)
```

the question is; what happens if the partition key does not align directly with the given datetime? Should we error? 

Basically, i think what we really want here are better utilities for going from a given datetime to the relevant partition key.

2024-12-16 20:21 UTC, dpeng817 requested changes
Left a lengthy comment, really appreciate you taking the time to write up this PR but I worry this isn't the right approach.

2024-12-17 21:30 UTC, Gw1p commented
> I sympathize with the desire to have a convenient way of getting the partition key for an asset, but I don't love this approach. `AssetMaterialization` is a pretty core abstraction, and ultimately we expect all partition keys to be resolvable to strings. I think there's a ton of code paths that would break if partition_key was all of a sudden not necessarily a string.
> 
> Furthermore, the mapping of a datetime to a partition key depends on the actual partition definition of the asset, and in the constructor of an assetmaterialization we don't have access to that information (and I don't think we want to need access to that information). I think what you actually want to do is something like this:
> 
> ```python
> import dagster as dg
> from datetime import datetime
> MY_TIME_WINDOW_PARTITIONS_DEF = dg.DailyPartitionsDefinition(...)
> 
> my_datetime = datetime(...)
> 
> MY_TIME_WINDOW_PARTITIONS_DEF.get_partition_key(my_datetime)
> ```
> 
> the question is; what happens if the partition key does not align directly with the given datetime? Should we error?
> 
> Basically, i think what we really want here are better utilities for going from a given datetime to the relevant partition key, given a partitionsdefinition.

Makes sense. I'm happy to work on utils to derive partition from partition definition, that seems like a nicer approach.

I'm leaving for the Christmas holidays but will get on it when I return in 2 weeks.

2025-01-09 20:24 UTC, Gw1p commented
> I sympathize with the desire to have a convenient way of getting the partition key for an asset, but I don't love this approach. `AssetMaterialization` is a pretty core abstraction, and ultimately we expect all partition keys to be resolvable to strings. I think there's a ton of code paths that would break if partition_key was all of a sudden not necessarily a string.
> 
> Furthermore, the mapping of a datetime to a partition key depends on the actual partition definition of the asset, and in the constructor of an assetmaterialization we don't have access to that information (and I don't think we want to need access to that information). I think what you actually want to do is something like this:
> 
> ```python
> import dagster as dg
> from datetime import datetime
> MY_TIME_WINDOW_PARTITIONS_DEF = dg.DailyPartitionsDefinition(...)
> 
> my_datetime = datetime(...)
> 
> MY_TIME_WINDOW_PARTITIONS_DEF.get_partition_key(my_datetime)
> ```
> 
> the question is; what happens if the partition key does not align directly with the given datetime? Should we error?
> 
> Basically, i think what we really want here are better utilities for going from a given datetime to the relevant partition key, given a partitionsdefinition.

@dpeng817 I've implemented the suggested changes. Let me know what you think about this approach!

2025-01-14 21:41 UTC, dpeng817 approved these changes
Okay nice. Thanks for the additional test.

2025-01-14 21:42 UTC, dpeng817 commented
@Gw1p this just needs a rebase, and I'll merge it. Thanks for your contribution!

2025-01-16 18:09 UTC, Gw1p commented
Had a pyright failure. Should be fixed.

2025-01-16 18:29 UTC, merged