Make asset check coercion explicit in with_attributes
dagster-io/dagster pull request #26529
Opened 2024-12-16 22:49 UTC by dpeng817

## Summary & Motivation

## How I Tested These Changes

## Changelog

> Insert changelog entry or delete this section.

2024-12-16 22:49 UTC, dpeng817 commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26529?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#26529** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26529?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26529?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#26527** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26527?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26524** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26524?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26514** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26514?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26498** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26498?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26484** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26484?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26494** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26494?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-17 22:33 UTC, OwenKephart requested changes
comment -- I adding the additional argument in a vacuum is reasonable (although might not be worth the additional complexity), but changing the behavior of the existing argument is likely a no-go

2024-12-17 22:33 UTC, OwenKephart commented on python_modules/dagster/dagster/_core/definitions/assets.py
> +            output_check_key_replacements.get(key, key) for key in self.check_keys
so I think this is a breaking behavior change that has the potential to actually cause issues -- one good thing about the old implementation was that  if you're replacing the key of an asset, then you almost certainly need to change the key of any checks referencing that asset.

even though that is implicit and weird, I think it's easy for someone to end up relying on that behavior

2024-12-18 20:43 UTC, OwenKephart approved these changes
assuming all the tests pass after this change, I'm in. I'm just vaguely concerned / anticipate that there will be some oddball situation that these did need to be separate arguments (which would show up in the tests)

2024-12-19 16:15 UTC, merged