Consolidate cacheable methods
dagster-io/dagster pull request #26531
Opened 2024-12-16 23:21 UTC by dpeng817

## Summary & Motivation

## How I Tested These Changes

## Changelog

> Insert changelog entry or delete this section.

2024-12-16 23:21 UTC, dpeng817 commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26531?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#26531** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26531?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26531?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#26529** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26529?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26527** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26527?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26524** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26524?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26514** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26514?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26498** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26498?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26484** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26484?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26494** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26494?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-18 16:43 UTC, OwenKephart approved these changes
Note comments

2024-12-18 16:43 UTC, OwenKephart commented on python_modules/dagster/dagster/_core/definitions/load_assets_from_modules.py
> -def _spec_mapper_disallow_group_override(
why is this no longer necessary?

2024-12-18 16:43 UTC, OwenKephart commented on python_modules/dagster/dagster/_core/definitions/asset_spec.py
> +        **kwargs,
kwargs -> _kwargs

2024-12-18 16:49 UTC, OwenKephart requested changes
ok actually looking upstack at this, I'm getting cold feet on this approach -- there's currently only a single place where we need to do this, and it's not clear to me that separating out this logic actually results in a better outcome.

I think it's easy to come across this with_attributes() method by accident as a user, even if it's not technically public, and the fact that it takes arbitrary kwargs makes seem like it can do things that it can't

I'd rather one large ugly function that's just `def with_attributes(asset: Union[...], ...)` than spread out the ugliness across each of the individual classes

2024-12-19 01:06 UTC, dpeng817 reviewed
Giving up on this for now. I think there's still potential with the idea, but it's actually quite tricky to build up a big function, since we need to figure out holistically across all asset keys which to replace when adding the key prefix.
If we don't include asset prefixes,  I think we end up leaving out a lot of the complexity, so probs not worth

2024-12-19 01:06 UTC, closed without merging