Genericize object list utils
dagster-io/dagster pull request #26535
Opened 2024-12-17 00:25 UTC by dpeng817

## Summary & Motivation

## How I Tested These Changes

## Changelog

> Insert changelog entry or delete this section.

2024-12-17 00:25 UTC, dpeng817 commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26535?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#26535** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26535?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26535?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#26534** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26534?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26533** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26533?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26532** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26532?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26531** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26531?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26529** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26529?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26527** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26527?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26524** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26524?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26514** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26514?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26498** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26498?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26484** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26484?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26494** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26494?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-18 16:53 UTC, OwenKephart requested changes
I like the direction, just think we should update the names

2024-12-18 16:53 UTC, OwenKephart commented on python_modules/dagster/dagster/_core/definitions/module_loaders/utils.py
> +LoadableAssetObject = Union[AssetsDefinition, AssetSpec, SourceAsset, CacheableAssetsDefinition]
I think `Object` -> `Def` in all of these names would make more sense

2024-12-18 16:53 UTC, OwenKephart commented on python_modules/dagster/dagster/_core/definitions/module_loaders/object_list.py
> +    def flat_object_list(self) -> Sequence[LoadableDagsterObject]:
e.g.

```python
def dlat_defs_list(self) -> Sequence[LoadableDagsterDef]:
```

2024-12-19 01:46 UTC, dpeng817 reviewed
@OwenKephart so I'd like to push back for the asset case; it's very hard to reason about assets since there is `AssetsDefinition`, `SourceAsset` and `AssetSpec`, and those can all have the same values. I think that that `SourceAsset` and `AssetSpec` falling into a defs_list is a bit strange, but maybe that's saying more about the naming of those APIs than anything else.

I don't feel that strongly about it but I'd request that if you really want the name change that we do it in a follow up; turns into an absolutely nightmarish rebase (changes like every line of the object_list.py file)

2024-12-19 06:27 UTC, yuhan commented
I do like `Def` better than `Object` simply because `Object` would be new noun.

But this isn't extremely publicly facing and we are in a release freeze zone, so I think landing + follow up for name changes is reasonable. (you have my verbal stamp. i will let owen approve in case of any strong reason not to)

2024-12-19 14:42 UTC, OwenKephart requested changes
Requesting changes in re: the naming change discussion in the PR above.

If we're aligned on those changes, happy to approve this PR and let you do the refactor stacked on top or wherever's convenient

2024-12-19 16:12 UTC, OwenKephart approved these changes

2024-12-19 16:54 UTC, merged