[dagster-databricks] Fix Cluster Drive Log Root Error when no extras provided for pipe
dagster-io/dagster pull request #26592
Opened 2024-12-19 14:01 UTC by GBBBAS

## Summary & Motivation
Addresses bug #26434 where an error is thrown for any Databricks Pipes where extras have not been provided for the pipe. 

Update checks if extras is available in params first to prevent the bug from being thrown

## How I Tested These Changes

## Changelog

> Insert changelog entry or delete this section.

2024-12-19 21:45 UTC, jamiedemaria reviewed
seems reasonable to me. Just want to get @danielgafni 's sign off in case there is an underlying issue here where `extras` isn't getting set when we expect it to be set

2024-12-19 23:23 UTC, jamiedemaria commented
In the meantime, @GBBBAS can you run `make ruff` and push the changes? That will get CI passing

2024-12-20 14:51 UTC, danielgafni approved these changes
Thanks!

2024-12-20 16:26 UTC, jamiedemaria requested changes
Requesting changes to rerun `make ruff` so that this doesn't get accidentally merged until thenn

2025-01-08 21:36 UTC, garethbrickman commented
@GBBBAS just a reminder to please run `make ruff` and push the formatting changes

2025-01-09 09:06 UTC, GBBBAS commented
> @GBBBAS just a reminder to please run `make ruff` and push the formatting changes

Done and pushed the commit

2025-01-09 14:10 UTC, merged