[core-api][experimental] `custom_path_fs_io_manager`
dagster-io/dagster pull request #26679
Opened 2024-12-23 18:27 UTC by OwenKephart

## Summary & Motivation

decision: experimental -> public
reason: doubt many people are using this, but it has existed for many many years and there is no reason for us to remove support for it
docs exist: yes (api only, which is ok)

## How I Tested These Changes

## Changelog

> Insert changelog entry or delete this section.

2024-12-23 18:28 UTC, OwenKephart commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26679?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#26683** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26683?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26682** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26682?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26681** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26681?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26680** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26680?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26679** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26679?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26679?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#26678** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26678?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-26 19:14 UTC, yuhan commented
This is the old resource pattern tho. should we mark it deprecated instead? it's successor is `CustomPathPickledObjectFilesystemIOManager`, but we don't really expose it and it'is also an ugly name.

2024-12-26 19:14 UTC, yuhan requested changes
request changes just to keep track of the statuses

2025-01-18 00:36 UTC, OwenKephart commented
updated to superseded with a reference to the newer pattern

2025-02-05 13:57 UTC, maximearmstrong approved these changes

2025-02-06 21:52 UTC, merged