[core-api][experimental] direct resource passing
dagster-io/dagster pull request #26688
Opened 2024-12-23 18:28 UTC by OwenKephart

## Summary & Motivation

decision: experimental -> public (could be convinced otherwise)
reason: this has existed for a long time, and even if it isn't directly recommended in most cases at the moment, we're moving to a world where more locally-scoped resource definitions are the norm and so this seems fair to support.
docs exist: api only

## How I Tested These Changes

## Changelog

> Insert changelog entry or delete this section.

2024-12-23 18:28 UTC, OwenKephart commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26688?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#26689** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26689?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26688** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26688?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26688?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#26687** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26687?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26686** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26686?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26685** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26685?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26684** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26684?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26683** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26683?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26682** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26682?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26681** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26681?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26680** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26680?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26679** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26679?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26678** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26678?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-26 21:53 UTC, yuhan commented
adding @dpeng817 to this one. i'm a little indifferent to GA vs not, so want second opinions here.

if we do end up making it public, i think we'll need to add docstring for resource_defs and io_manager_defs. not seeing them currently

2025-01-02 16:51 UTC, dpeng817 requested changes
I actually disagree with this.

I don't think we document direct resource passing _anywhere_ outside of api docs, and it has known problems (specifically key collisions). There might be a few places we use it internally, but in general I think it doesn't fit with how the framework has evolved (you specify resources at the op level but assets at the spec level).

I think if we wanted to make it truly public we would at the very least need to resolve the key collisions problem (having scoped resources be a true concept within dagster) but that's unlikely to be prioritized any time soon.

2025-01-18 00:09 UTC, OwenKephart commented
@dpeng817 i'm convinced -- updated

2025-02-06 21:54 UTC, merged