[core-apis][experimental] observable_source_asset, multi_observable_source_asset
dagster-io/dagster pull request #26706
Opened 2024-12-23 18:37 UTC by OwenKephart

## Summary & Motivation

decision: experimental -> beta
reason: we have aspirations of simplifying the ways in which we define asset observation computations, let's leave the option value open to change names on these APIs
docs exist: n/a

## How I Tested These Changes

## Changelog

> Insert changelog entry or delete this section.

2024-12-23 18:38 UTC, OwenKephart commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26706?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#26710** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26710?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26709** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26709?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26708** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26708?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26707** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26707?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26706** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26706?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26706?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#26705** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26705?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26704** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26704?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26703** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26703?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26702** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26702?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26701** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26701?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26700** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26700?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26699** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26699?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26698** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26698?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26697** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26697?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26696** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26696?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26695** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26695?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26694** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26694?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26693** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26693?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26692** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26692?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26691** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26691?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26690** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26690?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26689** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26689?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26688** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26688?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26687** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26687?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26686** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26686?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26685** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26685?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26684** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26684?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26683** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26683?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26682** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26682?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26681** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26681?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26680** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26680?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/>< [...]

2024-12-26 22:18 UTC, yuhan requested changes
i know this has existed for years, but given this feels inconsistent with the rest of surface areas, i wonder if we could boldly mark this as Preview?

opinion not strongly held. open to push back.

2024-12-26 23:02 UTC, schrockn commented
Agree with yuhan. We need to replace source asset with external asset language and this is an oversight, so Beta doesn't really communicate this accurately.

2025-02-06 23:23 UTC, yuhan approved these changes
left comment in BUILD-601.

agree it's a fair assessment to keep it in beta

2025-02-07 18:56 UTC, schrockn approved these changes
Ok I buy it

2025-02-07 23:19 UTC, merged