[core-api][experimental] `Definitions.merge`
dagster-io/dagster pull request #26704
Opened 2024-12-23 18:37 UTC by OwenKephart

## Summary & Motivation

decision: experimental -> GA
reason: we are leaning heavily on this behavior in components-land, and generally see this as a good tool when organizing a code location. we should formally endorse it
docs exist: no (will likely need to create some sort of guide along the lines of "organizing code locations", which would reference this)

## How I Tested These Changes

## Changelog

> Insert changelog entry or delete this section.

2024-12-26 22:15 UTC, yuhan approved these changes
approving for the decision, but i think docs is pretty important for this one.

2024-12-26 23:01 UTC, schrockn commented
This one I am not totally sold on yet since components might in fact *hide* this forever since it called on the user's behalf.

2025-01-02 18:52 UTC, schrockn requested changes
I want to discuss this one as I'm not sure we want to support it forever with components coming

2025-02-05 13:56 UTC, maximearmstrong commented
> I want to discuss this one as I'm not sure we want to support it forever with components coming

@schrockn Do you think the beta stage would make more sense? Would we deprecate/delete this when components are around, or would users leverage `Definitions.merge` in custom code?

2025-02-05 15:54 UTC, schrockn commented
We are going to need to support something like it so let's move forward with exposing it.

2025-02-05 17:40 UTC, maximearmstrong approved these changes

2025-02-06 21:53 UTC, merged