[dagster-looker] Use Looker API translator instance in spec loader and state-backed defs
dagster-io/dagster pull request #26743
Opened 2024-12-27 19:56 UTC by maximearmstrong

## Summary & Motivation

## How I Tested These Changes

## Changelog

> Insert changelog entry or delete this section.

2024-12-27 19:56 UTC, maximearmstrong commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26743?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#26744** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26744?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26743** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26743?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26743?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#26742** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26742?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-31 13:37 UTC, OwenKephart requested changes
Because this is a breaking change, we'd need to wait for dagster 1.10 in order to merge this.

I think the better option here is to make the type `Union[DagsterLookerApiTranslator, Type[DagsterLookerApiTranslator]]`, and emit a deprecation warning if a Type is passed in

Edit: looks like a lot of the related PRs also have breaking changes, so maybe the plan was already to just wait for 1.10 to merge them all, is that right?

2025-01-02 15:55 UTC, schrockn commented
It wouldn't be that hard to do what @OwenKephart suggested right? 

Even though we are "allowed" to do breaking changes if a relatively low effort option is available we should do that, especially on a feature we have discussed so publicly/

2025-01-02 16:37 UTC, maximearmstrong commented
> It wouldn't be that hard to do what @OwenKephart suggested right?
>
> Even though we are "allowed" to do breaking changes if a relatively low effort option is available we should do that, especially on a feature we have discussed so publicly.

That makes sense - I thought avoiding a deprecation cycle for an experimental feature would have been the best, but I see the value in emitting the warning. I can go ahead and make the update.

2025-01-02 18:57 UTC, schrockn approved these changes
Would like a test to test the deprecation warning (on the power BI one as well) but will not block

2025-01-02 20:12 UTC, maximearmstrong commented
> Would like a test to test the deprecation warning (on the power BI one as well) but will not block

Updated for Power BI, Tableau and Looker

2025-01-02 20:16 UTC, merged