[components] Use AssetAttributesModel instead of DbtTranslatorParams
dagster-io/dagster pull request #26768
Opened 2024-12-31 17:49 UTC by OwenKephart

## Summary & Motivation

This converts to using the AssetAttributesModel inside the translator. This is nice because it reduces duplicated code (e.g. the AssetKey.from_user_string() conversion), and in general having fewer distinct types flying around is good. (note: the `group_name` key was erroneously called just `group` before, this is something that we now no longer need to worry about)

Unfortunately, the translator code is still a mess on account of not having a unified `get_asset_spec()` method, meaning we have to implement a bunch of individual fns. However, once that's implemented, the translator can become as simple as:

```python

class XComponentTranslator(XTranslator):

    def __init__(self, params: AssetAttributes, resolver): ...

    def get_asset_spec(self, x: ...) -> AssetSpec:
        base_spec = super().get_asset_spec(x)
        rendered_props = params.get_rendered_properties(resolver.with_context(x=x))
        return base_spec.replace_attributes(**rendered_props)

```

## How I Tested These Changes

## Changelog

NOCHANGELOG

2024-12-31 17:50 UTC, OwenKephart commented
* **#26650** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26650?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#26768** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26768?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26768?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `master`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-31 17:50 UTC, OwenKephart commented on python_modules/libraries/dagster-components/dagster_components/core/component_rendering.py
> +
this is easier to override on a per-key basis

2024-12-31 23:22 UTC, schrockn commented on python_modules/libraries/dagster-components/dagster_components/core/dsl_schema.py
> +
this seems super gross and instead there should more structured and well-typed way of doing this (like a callback attached to `RenderingMetadata`)

2024-12-31 23:24 UTC, schrockn requested changes
Not a fan of `render_property` specifically

2025-01-07 02:18 UTC, schrockn commented on python_modules/libraries/dagster-components/dagster_components/core/dsl_schema.py
> +    return AssetKey.from_user_string(rendered) if rendered else None
yeah this is what I think the structure should be, but if we call this "resovling" rather than "rendering" this should be called a resolver

2025-01-07 02:19 UTC, schrockn commented on python_modules/libraries/dagster-components/dagster_components/lib/dbt_project.py
> +        self, attribute: str, dbt_resource_props: Mapping[str, Any], default_method
How about we type attribute as `Literal["key", "group_name", "tags", "automationc_condition"]` or what ever other ones I am missing?

2025-01-07 02:20 UTC, schrockn approved these changes
Please consider typehinting as literal!

2025-01-07 19:17 UTC, OwenKephart commented
### Merge activity

* **Jan 7, 2:17 PM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/26768).

2025-01-07 19:19 UTC, merged