[single-grpc-server] introduce a heartbeat to proxy server
dagster-io/dagster pull request #26777
Opened 2024-12-31 21:07 UTC by dpeng817

## Summary & Motivation

## How I Tested These Changes

## Changelog

> Insert changelog entry or delete this section.

2024-12-31 21:07 UTC, dpeng817 commented
* **#26777** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26777?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/26777?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `master`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2025-01-02 20:28 UTC, dpeng817 commented on python_modules/dagster/dagster/_grpc/proxy_server.py
> +            self._client_heartbeat_shutdown_event = threading.Event()
rename these properties because now it's confusing that there's a client and server heartbeat thread

2025-01-02 22:40 UTC, gibsondan requested changes
this makes sense but there is one important change to the default behavior here that I think explains the test failures

2025-01-02 22:40 UTC, gibsondan commented on python_modules/dagster/dagster/_cli/code_server.py
> +)
this should default to off (like dagster api grpc does) - we still want to support the existing use case of users running their own grpc servers, not dagster dev managing it, in which case there will not be a heartbeat - changing the default behavior here would break that use case

2025-01-02 22:40 UTC, gibsondan commented on python_modules/dagster/dagster/_grpc/proxy_server.py
> +        self.__server_heartbeat_thread.start()
we should still join() this thread on cleanup / shutdown (even though its a daemon thread, still good to do cleanup)

2025-01-02 22:40 UTC, gibsondan commented on python_modules/dagster/dagster/_grpc/proxy_server.py
>          # In case ShutdownServer was not called
clean up the server one here too

2025-01-02 22:41 UTC, gibsondan reviewed
you may want to keep the separate boolean argument (it will typically only be set by us anyway in dagster dev) or make the default 0 and have that mean no heartbeat

2025-01-06 14:56 UTC, gibsondan commented on python_modules/dagster/dagster/_cli/code_server.py
> +    help="How long to wait for a heartbeat from the caller before timing out. Defaults to 30 seconds.",
maybe worth clarifying here that this only comes into play if --heartbeat is set

2025-01-06 14:56 UTC, gibsondan commented on python_modules/dagster/dagster/_grpc/proxy_server.py
>          # In case ShutdownServer was not called
@dpeng817 did you see this one? you want something like this with the server heartbeat thread I think: https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/_grpc/server.py#L462-L463

2025-01-06 14:56 UTC, gibsondan commented on python_modules/dagster/dagster_tests/general_tests/grpc_tests/test_persistent.py
> +def test_server_heartbeat_timeout_code_server_cli() -> None:
looks like this new test is failing in CI?

2025-01-06 18:35 UTC, dpeng817 commented on python_modules/dagster/dagster_tests/general_tests/grpc_tests/test_persistent.py
> +def test_server_heartbeat_timeout_code_server_cli() -> None:
hmm weird. Passed for me locally.

2025-01-07 05:20 UTC, dpeng817 commented on python_modules/dagster/dagster/_grpc/proxy_server.py
>          # In case ShutdownServer was not called
agh sorry for the miss. that totally makes sense.

2025-01-07 05:23 UTC, dpeng817 commented on python_modules/dagster/dagster/_grpc/proxy_server.py
>          # In case ShutdownServer was not called
Added a join to `cleanup`. We don't need to add one to `ReloadCode` though right? We only need to clean up the original client heartbeat thread there since we're polling a new underlying grpc server?

2025-01-07 21:57 UTC, gibsondan commented on python_modules/dagster/dagster/_grpc/proxy_server.py
>          # In case ShutdownServer was not called
that's right, since we're not swapping out the server thread we should not need to join it

2025-01-07 22:02 UTC, gibsondan approved these changes

2025-01-07 22:02 UTC, gibsondan commented on python_modules/dagster/dagster/_grpc/proxy_server.py
>          self._shutdown_once_executions_finish_event.set()
as you noted earlier, add

```
self._grpc_server_registry.shutdown_all_processes()
```

here

2025-01-07 22:02 UTC, gibsondan commented on python_modules/dagster/dagster/_grpc/proxy_server.py
>          return self._query("Heartbeat", request, context)
I'm pretty sure we do not need to pass this one through like the others right? since its a different heartbeat? (the proxy server already sends heartbeats to its child code servers)

2025-01-07 22:24 UTC, dpeng817 commented on python_modules/dagster/dagster/_grpc/proxy_server.py
>          return self._query("Heartbeat", request, context)
ah - yea that's a good point. we should be able to avoid the additional send.

2025-01-16 17:27 UTC, merged