Allow dagster-ge solid factory to work with arbitrary types
dagster-io/dagster pull request #2921
Opened 2020-09-15 16:06 UTC by sd2k

Closes #2910.

2020-09-15 16:16 UTC, sd2k commented
The main thing I'm uncertain of here is what to name things, and what the default arguments to `batch_kwargs` should be. 

Currently the defaults work for both a `pandas.DataFrame` and a `pyspark.sql.DataFrame`, where `batch_kwargs` expects a `dataset` field. However, for a [SQLAlchemy source it expects to have very different fields](https://docs.greatexpectations.io/en/latest/guides/how_to_guides/creating_batches/how_to_load_a_database_table_view_or_query_result_as_a_batch.html).

This also makes me wonder what the real name for the solid's `InputDefinition` should be, since it's clearly not a `dataset` in all cases. I'm not really clued up enough on Great Expectation's naming conventions here, plus it sounds like they may be [changing some names soon](https://docs.greatexpectations.io/en/0.12.0/reference/core_concepts.html).

Anyway, happy to take suggestions!

2020-10-05 20:20 UTC, mgasner requested changes
This looks great, sorry it took so long to review. I'm requesting changes only because I think we need to rebase before merge, and also to bring the docstring in line with the function signature.

2020-10-05 20:20 UTC, mgasner commented on python_modules/libraries/dagster-ge/dagster_ge/factory.py
> +        extra_batch_kwargs (Optional[dict]): any extra key-value pairs to be included in
doesn't match the function signature

2020-10-05 20:20 UTC, mgasner commented on python_modules/libraries/dagster-ge/dagster_ge/factory.py
> +        final_batch_kwargs["datasource"] = datasource_name
it may make sense to check for the presence of the key `'datasource'` in `batch_kwargs` and warn/log if it is present

2020-10-06 08:04 UTC, sd2k commented
Thanks @mgasner, I've rebased and made those requested changes.

2020-10-06 13:59 UTC, mgasner commented
Great, I think the test failures we're seeing are unrelated and will be fixed by other work

2020-10-07 16:40 UTC, merged