Preserved the original function wrapped by @solid.
dagster-io/dagster pull request #3340
Opened 2020-12-04 22:55 UTC by JBrVJxsc

### Summary
The PR will preserve a reference to the original function that got wrapped by @solid.

### Background
Currently, Dagster does not support async functions & generators, and it is not in the roadmap in the near future (a quarter). For adopters (like me) who are trying to convert their existing asyncio func & gen into solids, the closest they can do is to implement their own executors and deal with the async func & gen within the executor. However, they do not have access to the original functions as all functions will be wrapped into a general generator. As a result, besides implementing a new executor, they also need to make another version of @solid decorator, which is really cumbersome.

### Solution
The easiest way to resolve this is to preserve a reference to the original function, and this adds more flexibility for the customized executor, not only for the async case I mentioned above but also potentially other use cases.

2020-12-04 23:21 UTC, alangenfeld requested changes
I would like to see some tests included that demonstrates that this works and how it could be used

2020-12-04 23:21 UTC, alangenfeld commented on python_modules/dagster/dagster/core/definitions/decorators/solid.py
> +        self._fn = fn
its not clear how this is useful since the `_Solid` instances are just temporary and this information is not making it in to the `SolidDefinition`

2021-07-08 14:29 UTC, alangenfeld commented
the original function is now preserved on @solid

2021-07-08 14:29 UTC, closed without merging

2021-07-11 03:38 UTC, JBrVJxsc commented
@alangenfeld sorry, could you point me to the place where the original function got preserved? I don't see it from the code ...

2021-07-12 17:02 UTC, alangenfeld commented
https://github.com/dagster-io/dagster/commit/0bf00b9c0421c512372aba9fa0bbefa0235e9509