Add default-container-resources LimitRange example
dagster-io/dagster pull request #3522
Opened 2021-01-09 22:29 UTC by mrdavidlaing

Adds an example extraManifests: showing how to add a a LimitRange object that sets default container resource requests and limits.

Addresses #3483

2021-01-09 23:31 UTC, mrdavidlaing commented
@chenbobby Could you review this when you get a chance.  Thanks!

2021-01-09 23:44 UTC, chenbobby approved these changes
Looks great, @mrdavidlaing! The additional notes in the comment are also very clear and helpful 👍

as a sidenote, we're considering some changes in the future that would allow k8s config to pass through to pipelines+solids without using the `tags={...}` method, which is currently schemaless and thus error-prone. not blocking for this PR tho 😄

2021-01-10 00:26 UTC, chenbobby requested changes
Our buildkite linter failed due to some indentation issues. I left a comment that points out a fix.

2021-01-10 00:26 UTC, chenbobby commented on helm/dagster/values.yaml
> +##- apiVersion: v1
Oops! our linter failed because lines 624-636 are not indented properly. adding a 2-space indent to these lines would fix it

2021-01-10 23:32 UTC, chenbobby approved these changes

2021-01-10 23:33 UTC, merged