Add support for datetime64[ns, UTC] via PandasColumn.datetime_column(..., utc=True)
dagster-io/dagster pull request #4117
Opened 2021-05-01 19:11 UTC by mrdavidlaing

From [#dagster-support thread](https://dagster.slack.com/archives/C01U954MEER/p1618916606441300):

> @mrdavidling:
> I have a PandasColumn.datetime_column that I'd like to constrain to only contain dates in UTC.
> Is this possible?
> Currently, if I define the column like this:
> `PandasColumn.datetime_column("at_date", non_nullable=True, is_required=True)`
and pass it a dataframe with a the column of type `datetime64[ns, UTC]` (from `pandas.to_datetime(my_dates, utc=True)` ) I get the following error:
> `Warning! Type check failed. Violated "ColumnDTypeInSetConstraint" for column "at_date" - Column dtype must be in the following set {'datetime64[ns]'}.. DTypes received: datetime64[ns, UTC]`
>Which is pretty much the exact opposite of the constraint I'm trying to place on the column :slightly_smiling_face:
>
>@catherinewu:
>Hi @mrdavidlaing :wave: that change would be very appreciated! feel free to tag me in the PR

## Summary
Extends the `PandasColumn.datetime_column()` with a `utc` flag (defaulted to `False` to preserve existing behaviour).

When `utc=True` the column must have values with a UTC timezone

## Test Plan

Added [`test_datetime_column_utc_ok()`](https://github.com/dagster-io/dagster/compare/master...mrdavidlaing:pandas_column_datetime_utc?expand=1#diff-d4b6c9483e6fafec33f7ca6da99ae5fbee7a8f541bd9152433765a71dcaecd9aR150) to unit test suite

## Checklist
- [x] My change requires a change to the documentation and I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

2021-05-01 19:13 UTC, mrdavidlaing commented
@catherinewu Am I correct in assuming that adding [docstring documentation](https://github.com/dagster-io/dagster/pull/4117/commits/612dc313421b2af7cb0f4563e7a82387bc8e388a#diff-740ad5c61a9defb2567455817293b56d80a78b0da490b46a9c56855efb547d40R278-R279) will automatically update the [published docs for the method](https://docs.dagster.io/_apidocs/libraries/dagster-pandas#dagster_pandas.PandasColumn) ?

Or is there somewhere else I need to change to update the docs?

2021-05-03 16:29 UTC, catherinewu requested changes
Looks good so far!

2021-05-03 16:29 UTC, catherinewu commented on python_modules/libraries/dagster-pandas/dagster_pandas/validation.py
> +            utc (Optional[bool]): Flag indicating whether datetime should have UTC timezone
could we allow users to specify any tz_localize compatible timezone?

2021-05-03 16:30 UTC, catherinewu commented
Thank you for the PR @mrdavidlaing! Yup, the docs are created during the release process each week and you don't need to change anything in the diff for that.

I think you may need to run `make isort` and `make black` for some formatting issue. (the py3.8 errors seem to be flakes :/)

2021-05-05 10:42 UTC, mrdavidlaing commented
@catherinewu Updated as suggested.

Could you take another look please.

2021-05-09 13:48 UTC, mrdavidlaing commented
This PR should resolve #3365

2021-05-09 14:18 UTC, mrdavidlaing commented
@catherinewu Finally got the `black` tests to pass :)

Could you re-check (and hopefully merge?)

2021-05-13 16:25 UTC, alangenfeld commented
some lint and test failures incase you missed it

2021-05-13 17:41 UTC, mrdavidlaing commented
Hmm.  I was positive that all was green when I checked on https://github.com/dagster-io/dagster/pull/4117#issuecomment-835816499.

Trying again...

2021-05-14 16:13 UTC, mrdavidlaing commented
@alangenfeld I'm not sure why when I rebased my branch on dagster/master all these additional commits showed up in this PR.

Would you prefer if I make a "clean" branch and create a new PR?

2021-05-16 13:57 UTC, mrdavidlaing commented
@alangenfeld / @catherinewu I think I have all the tests / linting passing now - its just the `
Vercel — Authorization required to deploy.` check that is failing to pass.

Could you recheck & if all is good merge.

Thanks!

2021-05-17 10:05 UTC, mrdavidlaing commented
Aha - looks like it takes much longer for the buildkite test run to trigger/complete.  Pushed a new change to address the pylint issue

2021-05-17 13:24 UTC, mrdavidlaing commented
@alangenfeld / @catherinewu - its been ~3 hours since I pushed 670331b; yet the buildkite tests still don't seem to have triggered.

Is there a manual step you (or I) need to invoke to get them to run?

2021-05-17 14:51 UTC, alangenfeld commented
Yea @mrdavidlaing sorry I didn't explain sooner - the buildkite run is manually triggered at the moment which I acknowledge is a suboptimal experience for external contribution.

2021-05-17 15:14 UTC, merged

2021-05-17 15:15 UTC, alangenfeld commented
thanks for the PR (and your patience) 😄

2021-05-17 15:26 UTC, mrdavidlaing commented
🥳  Thanks for helping me get it merged :)