dagster-k8s: make k8s_run_executor to inherit launcher config
dagster-io/dagster pull request #4331
Opened 2021-07-01 13:24 UTC by seruman

## Summary
As pointed in #4317, `k8s_run_executor` would not inherit `K8sRunLauncher` config defined in Dagster instance/config.

With changes proposed, `k8_run_executor` extracts `DagsterK8sJobConfig` values from launcher and uses them by default. This eliminates re-defining `namespace`, `env_config_maps`, `service_account_name` or any other job config again for executor.

## Test Plan
I've yet to find automated tests for `dagster-k8s` therefore unable to prodive any.

Tested #4317 with building two container images;
* `dagster-k8s`: Base Dagster image built with `dagster-image` tool from fork. Used in `daemon` and `dagit` pods.
	* `dagster-image build --name dagster-k8s-editable --dagster-version 0.11.4 -v 3.7.8`
* `dagster-poc`: User code deployment image, built on top of `dagster-k8s` above. 
	* Dockerfile:
	```Dockerfile
	FROM bigdata/dagster-k8s-editable

	RUN apt-get update -yqq && apt-get install -yqq cron
	ADD . /opt/pipelines
	RUN pip install /pipelines
	```

* `dagster-run-*` pod:
```yaml
spec:
  containers:
  - args:
    - dagster
    - api
    - execute_run
    # ...
    env:
    - name: DAGSTER_HOME
      value: /opt/dagster/dagster_home
    - name: DAGSTER_PG_PASSWORD
      valueFrom:
        secretKeyRef:
          key: postgresql-password
          name: dagster-postgresql-secret
    envFrom:
    - configMapRef:
        name: dagster-pipeline-env
    - configMapRef:
        name: aws-localstack
    image: dagster-poc:latest
    imagePullPolicy: Never
    name: dagster-run-b839de7e-ef24-40c3-8832-2f71df129370
    volumeMounts:
    - mountPath: /opt/dagster/dagster_home/dagster.yaml
      name: dagster-instance
      subPath: dagster.yaml
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: dagster-token-xxmm5
      readOnly: true
  volumes:
  - configMap:
      defaultMode: 420
      name: dagster-instance
    name: dagster-instance
  - name: dagster-token-xxmm5
    secret:
      defaultMode: 420
      secretName: dagster-token-xxmm5
```

* One of the `dagster-run*` pods:
```yaml
spec:
  containers:
  - args:
    - dagster
    - api
    - execute_step
    # ...
    env:
    - name: DAGSTER_HOME
      value: /opt/dagster/dagster_home
    - name: DAGSTER_PG_PASSWORD
      valueFrom:
        secretKeyRef:
          key: postgresql-password
          name: dagster-postgresql-secret
    envFrom:
    - configMapRef:
        name: dagster-pipeline-env
    - configMapRef:
        name: aws-localstack
    image: dagster-poc:latest
    imagePullPolicy: IfNotPresent
    name: dagster-job-eceeceeda4d1e5af8591b0e565c178e2
    volumeMounts:
    - mountPath: /opt/dagster/dagster_home/dagster.yaml
      name: dagster-instance
      subPath: dagster.yaml
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: dagster-token-xxmm5
      readOnly: true
  volumes:
  - configMap:
      defaultMode: 420
      name: dagster-instance
    name: dagster-instance
  - name: dagster-token-xxmm5
    secret:
      defaultMode: 420
      secretName: dagster-token-xxmm5
```

## Checklist

- [x] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2021-07-01 13:28 UTC, seruman commented on python_modules/libraries/dagster-k8s/dagster_k8s/executor.py
> +    }
I'm not quite comfortable with this one, was not sure if there should be a check like the one in; https://github.com/dagster-io/dagster/blob/fc94a35176bf412c72f3fc90e1f6d75a4cb86aa1/python_modules/libraries/dagster-celery-k8s/dagster_celery_k8s/executor.py#L112-L116

2021-07-28 13:52 UTC, johannkm requested changes
Hi @seruman- thanks for putting this up! Apologies for not noticing earlier, but we have a duplicate change in https://dagster.phacility.com/D9078

It looks like you went with slightly different behaviors which I think are a little interesting- for example concatenating the env secrets. That does seem like something that would actually be desired behavior pretty often, but I'm also hesitant to make that assumption. Curious to hear your thoughts!

Re: dagster-k8s testing- for future reference, most of the test coverage is in our integration tests- integration_tests/test_suites/k8s-integration-test-suite/test_executor.py. We definitely should improve our unit testing here

2021-08-01 16:36 UTC, seruman commented
> Hi @seruman- thanks for putting this up! Apologies for not noticing earlier, but we have a duplicate change in [dagster.phacility.com/D9078](https://dagster.phacility.com/D9078)
> 
> It looks like you went with slightly different behaviors which I think are a little interesting- for example concatenating the env secrets. That does seem like something that would actually be desired behavior pretty often, but I'm also hesitant to make that assumption. Curious to hear your thoughts!
> 
> Re: dagster-k8s testing- for future reference, most of the test coverage is in our integration tests- integration_tests/test_suites/k8s-integration-test-suite/test_executor.py. We definitely should improve our unit testing here

Hi @johannkm, that's great to see it implemented. The though behind concatenating the config maps and secrets was to enable pipeline authors to provide custom ones. Launcher could provide configs/secrets required or common for all pipelines; like AWS credentials or database/warehouse secrets. By combining them with user provided ones, pipeline authors could specify pipeline specific config/secrets without redefining common ones.

I can close this PR in favor of https://github.com/dagster-io/dagster/commit/4ccdbb18c4933f5d77ee56123810563b6723f127.

2021-08-01 16:56 UTC, gibsondan commented
Hi @seruman - I totally agree with the reasoning behind concatenation, we'll go ahead and make that change this week as well.

2021-08-02 18:50 UTC, johannkm commented
Closing for https://github.com/dagster-io/dagster/commit/4ccdbb18c4933f5d77ee56123810563b6723f127

2021-08-02 18:50 UTC, closed without merging