Allow int execution_time for dbt type
dagster-io/dagster pull request #4332
Opened 2021-07-01 21:15 UTC by dehume-drizly

## Summary
Allow the dbt solids fail when there are downstream models that are skipped. This is because the `execution_time` for those models is 0 which is an int rather than a float. Allow for int or float in the dbt types.
```
dagster.check.ElementCheckError: Value 0 from key execution_time is not a <class 'float'>. Dict: {'status': 'skipped', 'timing': [], 'thread_id': 'Thread-9', 'execution_time': 0, 'message': None, 'adapter_response': {}, 'unique_id': 'model.model.model_name’}
```

## Test Plan
Include an additional mocked test type

## Checklist

- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2021-07-08 16:51 UTC, dpeng817 requested changes
It seems like what we really want is for 0-valued ints to be converted to float. The approach detailed here seems like a workaround that could have more far-reaching implications.

Requesting changes for an approach that gates ints, and converts to floats.

2021-07-08 16:51 UTC, dpeng817 commented on python_modules/libraries/dagster-dbt/dagster_dbt/types.py
> +        execution_time = d["execution_time"]
nit: we should still check here; can check multiple types by doing `check.inst_param(d["execution_time"], "execution_time", (int, float))`.

2021-07-13 15:22 UTC, dehume-drizly commented
Does this implementation work? Switched converting the execution time to float.

2021-07-13 16:34 UTC, dpeng817 approved these changes
LGTM, just take a look at the nit for the comment. Thanks for doing this!

2021-07-13 16:34 UTC, dpeng817 commented on python_modules/libraries/dagster-dbt/dagster_dbt/types.py
> +        execution_time (Union[float,int]): The execution duration (in seconds) of the dbt node (model).
Nit: this should actually always be float since we convert it before we construct the namedtuple.

2021-07-14 14:45 UTC, dehume-drizly commented
Actually. Looking at the changes to the dbt type since the dbt refactor. I don't think my PR is relevant anymore. It might be worth adding the additional test case for when execution time is an int. But otherwise I think this can just be closed

2021-07-14 14:45 UTC, closed without merging