Fix dagit tests when run from a release branch
dagster-io/dagster pull request #4975
Opened 2021-09-30 21:43 UTC by gibsondan

Summary: These are only dev in master

Test plan: BK, push to release branch

## Summary

## Test Plan

## Checklist

- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2021-09-30 22:03 UTC, prha requested changes, later dismissed

2021-09-30 22:03 UTC, prha commented on python_modules/dagit/dagit_tests/starlette/test_app.py
> +        "dagit_version": dagster_version,
I think you want:
```
   "dagit_version": dagit_version,
   "dagster_version": dagster_version,
   "dagster_graphql_version": dagster_graphql_version,
```

2021-09-30 22:07 UTC, gibsondan commented
good point. snuck in one more tiny fix that was failing in the RC

2021-09-30 22:51 UTC, prha commented on .buildkite/dagster-buildkite/dagster_buildkite/steps/dagster.py
> +            "-e python_modules/automation",
either repeat `pip install` or make a single command?

2021-10-01 01:55 UTC, gibsondan commented on .buildkite/dagster-buildkite/dagster_buildkite/steps/dagster.py
> +            "-e python_modules/automation",
done

2021-10-01 15:14 UTC, prha approved these changes

2021-10-01 18:01 UTC, merged