Helm ingress template compatible with k8s v1.22
dagster-io/dagster pull request #5476
Opened 2021-10-30 02:42 UTC by wkeifenheim

## Summary

As of Kubernetes v1.22 the Ingress API no longer supports the `extensions/v1beta1` spec ([ref](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22)). With the `networking.k8s.io/v1` API version being available since k8s v1.19, and that being the oldest version I can deploy against in GCP, I decided to future-proof as much as I could and see what it takes to support Ingress on k8s v1.19+ with the Helm chart.

I have added additional templating to produce the newer Ingress YAML when the deployment target is running k8s 1.19 or later.

When trying deployment with this new template, I made the bare minimum changes to `values`.
```yaml
ingress:
  enabled: true

  annotations: {}

  # Specify ingressClassName for Kubernetes >= 1.19
  ingressClassName: "nginx"

  dagit:
    # Ingress hostname for Dagit e.g. dagit.mycompany.com
    # This variable allows customizing the route pattern in the ingress. Some
    # ingress controllers may only support "/", whereas some may need "/*".
    # NOTE: Dagit doesn't yet support hosting on a path, e.g. mycompany.com/dagit.
    path: "/"
    # pathType is only for k8s >= 1.19
    pathType: Prefix
    # NOTE: do NOT keep trailing slash. For root configuration, set as empty string
    # See: https://github.com/dagster-io/dagster/issues/2073
    host: "dagit.wkk8s.dev"
```

**_If there is a plan is to drop support for k8s versions before 1.19, the ingress template could then drop all of the `$apiIsStable` complexity._**

## Test Plan

1. Ran `helm lint` -> no issues found.
2. Ran the unmodified `test_ingress.py` tests -> all passed.
2. Updated the Helm template `model` of `test_ingress.py` to use `V1Ingress` -> tests continue to pass.
3. Created local clusters (minikube) with k8s versions `1.19.16`, `,1.21.6`, and `1.22.2` and deployed (Dagster v0.13.2) using the updated Helm chart and the `values` specified in the summary above. I configured Ingress for Dagit using nginx in all cases. Using Dagit in the browser and executing the `single_pod_job` example graph worked in all cases.

Attempted to start a cluster with K8s ~1.15 since the chart states it supports `>=1.15` however these attempts failed. Before spending more time attempting to spin up older K8s versions, I figured I would start this PR process and get feedback on additional testing requirements.

## Checklist

- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2021-12-22 18:59 UTC, rexledesma requested changes
This kubernetes compatability problem looks pretty well known - could we deal with it in a similar way to https://github.com/airflow-helm/charts/blob/main/charts/airflow/values.yaml#L1176-L1180?

Rather than inferring the user's kubernetes version (which results in some gnarly helper templates), we should have the ingress version as an input in `values.yaml`. Then, we can fork the ingress using that value.

2021-12-22 20:49 UTC, wkeifenheim commented
@rexledesma Totally agree that the templating **is** gnarly in this PR. I had looked at a few different Helm templates from popular applications when coming up with what I did, and before that I have never touched Helm templates or even `go` before.

More so than the value set for `apiVersion`, the `-path` fields are more nightmarish to template. I got to place that appears to work, but I hesitated to refine it more before knowing if k8s 1.15~1.18 will continue to be supported.

I am not sure which Helm charts for Airflow are actually out in the wild, but what I referenced in the PR code has been updated more recently and is a different repo than what you linked. [In this repository](https://github.com/apache/airflow/blob/main/chart/templates/webserver/webserver-ingress.yaml) Airflow are following the `apiIsStable` pattern and inferring the k8s deployment version at the time of deploy.

2021-12-29 18:02 UTC, AndreaGiardini commented
One this worth mentioning: K8s version 1.18-1.19 are already EOL

Is it even worth having this conditional? 
Maybe we should just upgrade to `networking.k8s.io/v1` and make this chart compatible only with k8s > 1.19 ?

2021-12-29 18:21 UTC, wkeifenheim commented
> Maybe we should just upgrade to networking.k8s.io/v1 and make this chart compatible only with k8s > 1.19 ?

I would support that decision, it is suggested in the PR description :)

Probably worth clarifying, when I have mentioned support I mean support _by Elementl_. The Kubernetes versions themselves being EOL is certainly a good reason to make the switch to >= 1.19.

2021-12-30 04:40 UTC, rexledesma commented
Although the Kubernetes versions <1.19 are indeed EOL (see https://endoflife.date/kubernetes), a better gauge of the minimum version we should support should come from the EOL for the versions on managed cloud services like EKS, GKE, and AKE, as these are the common interfaces through which a user would provision a Kubernetes cluster. I will feel more confident bumping the supported version once this occurs for the major cloud providers.

From the [EKS](https://endoflife.date/amazon-eks) and [GKE](https://endoflife.date/google-kubernetes-engine) EOL calendar, 1.18 support will end by March 2022 for these two providers. [AKS](https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar) is already EOL for 1.19, we are good on that front.

Until then, we should maintain compatibility with < 1.18 - hope that makes sense to you all!

2021-12-30 18:09 UTC, rexledesma commented
@wkeifenheim whichever is more convenient for you!

2022-01-03 15:12 UTC, wkeifenheim commented
@rexledesma I lean towards closing this PR and starting a new one. I'll post a bit more on the associated issue ticket, but tldr I started on the new approach over the weekend.

2022-01-03 15:12 UTC, closed without merging