Wrap error raised in `handle_output` of IO Manager in user_code_error_boundary
dagster-io/dagster pull request #5624
Opened 2021-11-11 20:51 UTC by clairelin135

This PR fixes #4508 by catching exceptions that occur in the `handle_output()` method of an IO manager before outputs are yielded. Previously, only errors raised after an output was yielded would be wrapped in `user_code_error_boundary`. 

Screenshot of behavior after fix:
![Screen Shot 2021-11-11 at 11 40 16 AM](https://user-images.githubusercontent.com/29110579/141366538-31b90f64-fa52-4ecb-aace-644c8fc043b4.png)

2021-11-12 22:11 UTC, sryza reviewed
I've seen this issue occur outside of `handle_output` as well. E.g. here's an example of a bunch of framework frames being included in an error from an op compute function: https://demo.elementl.show/instance/runs/d9ed8802-e43b-43ec-9e4d-3754cc0b1996?logKey=id_range_for_time. I wonder if it's a problem that could solve inside `iterate_with_context`?

Either way, it seems like this diff is replacing `solid_execution_error_boundary` with `user_code_error_boundary`, and that could have some consequences?

Also, I have a vague recollection that @OwenKephart has worked with some of the subtleties of this code. Owen, is that right? Mind taking a look?

2021-11-19 17:58 UTC, OwenKephart requested changes

2021-11-19 17:58 UTC, OwenKephart commented on python_modules/dagster/dagster/core/execution/plan/execute_step.py
> -    handle_output_res = output_manager.handle_output(output_context, output.value)
also I hate github because I wrote this comment like 4 days ago but I forgot to hit the "finish review" button so it didn't show up

2021-11-23 19:25 UTC, clairelin135 commented on python_modules/dagster/dagster/core/execution/plan/execute_step.py
> -    handle_output_res = output_manager.handle_output(output_context, output.value)
@OwenKephart Thanks for explaining all of this! Makes sense, I followed what you said above and wrapped the `handle_output` function in a generator

2021-11-23 19:30 UTC, OwenKephart approved these changes
looks great! you should add a comment explaining what's going on here because it's a little complicated but other than that this is good to go

2021-11-23 21:30 UTC, merged