Remove unused workspace gql query
dagster-io/dagster pull request #5666
Opened 2021-11-15 22:43 UTC by johannkm

## Summary

## Test Plan

## Checklist

- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2021-11-15 22:43 UTC, johannkm commented
Current dependencies on/for this PR:
* master
  * **PR #5666**  (this PR)

This comment was auto-generated by [Graphite](https://graphite.dev?utm_source=gh) and will continue to be automatically updated while this PR remains open.

2021-11-16 17:14 UTC, hellendag commented
Don't forget to run `yarn generate-graphql`.

2021-11-16 17:15 UTC, hellendag requested changes
Looks good, just the GraphQL type generation issue. Back to your queue :)

2021-11-18 19:29 UTC, hellendag approved these changes

2021-11-18 22:08 UTC, merged