Dynamic Output Bite-Sized Example
dagster-io/dagster pull request #5822
Opened 2021-11-30 00:08 UTC by clairelin135

2021-11-30 21:16 UTC, dpeng817 reviewed
Would there be any commentary to accompany this, or would this just exist independently? Motivation in general is a really difficult thing to get across for simple example type jobs, but I think if this is meant to be standalone we could do a better job explaining decisions, maybe via comments?

2021-12-02 00:38 UTC, yuhan reviewed
thanks for putting this together! i think it's a great skeleton to start with. the next iteration is to make the "why" more compelling.

2021-12-02 00:38 UTC, yuhan commented on examples/bite_sized/dynamic_output.py
> +from bite_sized.conditional_branching import DataframeToCSVIOManager
the idea i had in mind was to make every single example to be standalone so users can just look at one repo/job at a time and be able to execute runs just using that example. wonder how you feel about this idea?
see more discussions on https://github.com/dagster-io/dagster/pull/5787

2021-12-02 00:38 UTC, yuhan commented on examples/bite_sized/dynamic_output.py
> +    return pd.concat(articles)
would be great to have some more parsing logics here to make "why" to use the dynamic out stronger.

the current job shape imo could be simplified to a single op that fetch the df and store per-category in csv's a for loop, i.e. it's a bit less convincing why i need to have two ops and dynamic out at the first place.

2022-01-21 01:19 UTC, yuhan requested changes
queue management: also, i may commandeer it some time next week!

2024-10-01 17:23 UTC, PedramNavid commented
> queue management: also, i may commandeer it some time next week!

you sure about that?

2025-04-21 19:39 UTC, closed without merging