Background step cancellation thread
dagster-io/dagster pull request #5914
Opened 2021-12-09 02:16 UTC by johannkm

## Summary

## Test Plan

## Checklist

- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2021-12-09 02:16 UTC, johannkm commented
Current dependencies on/for this PR:
* master
  * **PR #5914**  (this PR)

This comment was auto-generated by [Graphite](https://graphite.dev?utm_source=gh) and will continue to be automatically updated while this PR remains open.

2021-12-09 16:06 UTC, alangenfeld commented on python_modules/dagster/dagster/cli/api.py
> +                            )
not enough information to disambiguate

2021-12-17 20:03 UTC, alangenfeld requested changes
See inline comments

2021-12-17 20:03 UTC, alangenfeld commented on python_modules/dagster/dagster/grpc/types.py
> +        "retry_mode known_state should_verify_step should_start_background_cancellation_thread",
`should_start_background_cancellation_thread` is very current-impl specific. I think from the API perspective the difference is between the run worker being responsible or this step worker being responsible for itself 
riffing:
`self_managed_cancellation: bool`
`cancellation_source: external (default) | self`

2021-12-17 20:03 UTC, alangenfeld commented on python_modules/dagster/dagster/cli/api.py
> +                    buff.append(serialize_dagster_namedtuple(event))
nit: refactor maybe - nesting getting deep

2021-12-17 20:03 UTC, alangenfeld commented on python_modules/dagster/dagster/cli/api.py
> +                            )
this is attributed to the run not the specific step this is happening in

2021-12-17 20:34 UTC, alangenfeld approved these changes
🙏

2021-12-17 20:36 UTC, alangenfeld commented
this should be put under test right?

at least update the PR summary / test plan with how you tested this

2022-01-27 17:48 UTC, closed without merging