Error when a solid/op is invoked within another solid/op
dagster-io/dagster pull request #6089
Opened 2022-01-03 18:38 UTC by dpeng817

Right now, we kind of let people blindly invoke ops/solids within other ops/solids. This leads to misunderstandings with our composition DSL, and hinders ramp-up with dagster. 

This PR hard-errors when performing this type of invocation, and points people to the relevant documentation. Technically, this is a breaking change, but it's a breaking change for undefined behavior.

2022-01-03 18:42 UTC, schrockn commented
We should have a method for direct invocation if we make this change. e.g. `some_op.invoke(context, arg1)`

2022-01-03 19:25 UTC, dpeng817 commented
> We should have a method for direct invocation if we make this change. e.g. some_op.invoke(context, arg1)

@schrockn do you mean in the general case, moving direct invocation to the `.invoke(...)` method? Or making `.invoke(...)` have the same behavior as direct invocation so that folks who for some reason want to directly invoke within their ops can do so

2022-01-03 19:34 UTC, schrockn commented
"Or making .invoke(...) have the same behavior as direct invocation so that folks who for some reason want to directly invoke within their ops can do so"

^--- This exactly. Have the *ability* to do direct invocation in the cases where this PR is making it a hard error.

2022-01-04 19:02 UTC, alangenfeld commented
I remember discussing this in person at some point and I think we had an argument for why hard error wasn't the way to go. Wish I could remember the details. 

Does anyone have strong opinions on error vs warn here? I soft lean towards warn instead of error - assuming the warning would actually show up somewhere useful. I guess it would have to fire an event log warning to be visible.

2022-01-06 19:12 UTC, dpeng817 commented
cc @alangenfeld @schrockn My take is that invocation within ops is a quite advanced / niche use case. Invoking an op within another op is using dagster in a way that wasn't intended, which means one of two things to me:
1. You are very familiar with Dagster, understand the graph DSL and are stretching the abstractions to suit your needs. For these folks, `.invoke()` should work fine.
2. You don't understand Dagster, and think you're building out a DAG by invoking ops within other ops. For these folks, probably don't want to be invoking ops within other ops and we should turn these folks away from that path. 
TL;dr, I think it's a workflow that is fine to support, but we should make sure that users are actively aware of the behavior that they are opting into, which is what makes a `.invoke()` method attractive.

2022-01-07 21:06 UTC, dpeng817 commented on python_modules/dagster/dagster_tests/core_tests/test_solid_invocation.py
> +    from dagster.core.definitions.composition import (  # pylint: disable=unused-import
I have no idea why this fixes test failures

2022-01-18 19:09 UTC, alangenfeld requested changes
alright looks like hard error is the way to go - lets just ensure `invoke` is actually discoverable

2022-01-18 19:09 UTC, alangenfeld commented on python_modules/dagster/dagster/core/definitions/solid_definition.py
> +    def invoke(self, *args, **kwargs) -> Any:
doc block

2022-01-18 19:09 UTC, alangenfeld commented on python_modules/dagster/dagster/core/definitions/solid_definition.py
> +            )
This should probably mention `invoke` method explicitly or how else would one discover it? Maybe update the linked docs as well with a section 

A little worried about this deep link breaking over time - not sure best way to defend against that.

2022-01-26 17:19 UTC, dpeng817 commented
Closing for now until I have time to revisit

2022-01-26 17:19 UTC, closed without merging