Allow run_id to be referenced from resources when invoking
dagster-io/dagster pull request #6094
Opened 2022-01-03 22:12 UTC by dpeng817

Relevant to https://github.com/dagster-io/dagster/issues/6091

2022-01-04 19:28 UTC, alangenfeld commented on python_modules/dagster/dagster/core/execution/context/invocation.py
> +        run_id: str,
if were going to add this, should we just take the run object instead here? [1]

2022-01-04 19:35 UTC, alangenfeld commented
Should we be more thorough and have a sibling to `InitResourceContext` that is for direct invocation similar to the set up for the solid contexts? Im not sure how much that actually helps, but the `pipeline_run` comments on `build_resources` don't feel great.

The other thing we could do is just thread the `EPHEMERAL` through and not mess with the public API yet

2022-01-05 16:48 UTC, alangenfeld requested changes
to your queue for thoughts

2022-01-26 17:19 UTC, dpeng817 commented
Closing for now until I have time to revisit

2022-01-26 17:19 UTC, closed without merging