[docs] details on mapping dynamic outputs
dagster-io/dagster pull request #6140
Opened 2022-01-07 16:23 UTC by alangenfeld

## Test Plan

read the docs

2022-01-07 16:23 UTC, alangenfeld commented
Current dependencies on/for this PR:
* master
  * **PR #6140**  (this PR)

This comment was auto-generated by [Graphite](https://graphite.dev?utm_source=gh).

2022-01-07 16:24 UTC, alangenfeld reviewed
This level of detail felt excessive for the concepts page so here felt like the right place to me.

Very open to feedback on wording and placement for this.

2022-01-07 18:45 UTC, dpeng817 requested changes
Generally looks good, I think there just need to be a few more code snippets

2022-01-07 18:45 UTC, dpeng817 commented on docs/sphinx/sections/api/apidocs/dynamic.rst
> +To establish dependencies on a dynamic output in a composition function like :py:class:`job` or :py:class:`graph`, the ``map`` function is used on the object representing the dynamic output. `map` ta
like :py:class:`job` or :py:class:`graph` -> like ones _decorated_ by ...

2022-01-07 18:45 UTC, dpeng817 commented on docs/sphinx/sections/api/apidocs/dynamic.rst
> +To establish dependencies on a dynamic output in a composition function like :py:class:`job` or :py:class:`graph`, the ``map`` function is used on the object representing the dynamic output. `map` ta
I also find this statement generally hard to follow without an accompanying code snippet. I think the below snippets somewhat alleviate this, but I think a snippet showing a simple mapping in action would be helpful.

2022-01-07 18:45 UTC, dpeng817 commented on docs/sphinx/sections/api/apidocs/dynamic.rst
> +        do_stuff(b_values.collect())
maybe also show namedtuple access of outputs here. While it's shown in the next code snippet, I don't think it's entirely clear

2022-01-22 00:20 UTC, yuhan reviewed
I think this level of details is worth including in https://docs.dagster.io/concepts/ops-jobs-graphs/jobs-graphs because 
1. rst is hard to maintain, as we don't have tests set up for bad links.
2. code snippets aren't under tests which means they could get outdated and confuse readers.
3. although i can't think of a perfect concept page for this info to fit it, i think it's more of the concept info hierarchy problem, so we should maybe re-org the giant Jobs&Graphs a bit. i could imagine we start to expand details for other graph shapes like conditional branching and fan in. (and i like this direction a lot!)


we could expand the [Dynamic Mapping & Collect example](https://docs.dagster.io/concepts/ops-jobs-graphs/jobs-graphs#dynamic-mapping--collect) or move it to somewhere like <img height="371" alt="Screen Shot 2022-01-21 at 4 16 11 PM" src="https://user-images.githubusercontent.com/4531914/150615943-12dfff05-9aa3-46ce-a943-b1a30bf848e0.png">

2022-01-31 21:24 UTC, yuhan submitted a review, later dismissed
q management

2022-02-25 21:37 UTC, alangenfeld reviewed
good push back on the initial pass on this - I think this direction is much better

2022-02-26 00:42 UTC, yuhan commented
content looks great. could we add tests for the code snippets, e.g. make sure the jobs can run properly at minimum?

2022-03-03 21:39 UTC, yuhan approved these changes

2022-03-04 22:54 UTC, merged