add batch loaders to GraphenePipeline
dagster-io/dagster pull request #6207
Opened 2022-01-13 19:58 UTC by prha

This should enable batching of runs at the repository level, making use of the new `RunBatchLimit` argument to `get_runs` / `get_run_records`.

## Test Plan
BK

2022-01-14 16:13 UTC, alangenfeld commented
you get any measurements on this?

2022-01-14 18:25 UTC, prha commented
Results are promising...

Before:
![Screen Shot 2022-01-14 at 10 24 01 AM](https://user-images.githubusercontent.com/1040172/149566114-31d4edc5-f09e-403c-90f4-d953c6b52500.png)

After:
![Screen Shot 2022-01-14 at 10 24 07 AM](https://user-images.githubusercontent.com/1040172/149566142-dcec2834-a6af-407c-a80f-a685686e168b.png)

2022-01-20 23:31 UTC, alangenfeld requested changes
I'm on board with this - the perf wins are worth the complexity. 

Back to you to polish this up just a bit with typing, comments, and ideally some tests. Maybe some regression protection to verify that certain graphql queries only result in N instance calls via `traced`

2022-01-20 23:31 UTC, alangenfeld commented on python_modules/dagster-graphql/dagster_graphql/implementation/loader.py
> +        self._data = {}
typing for this for example i think would be really useful for understanding this beast

2022-01-26 20:19 UTC, alangenfeld approved these changes

2022-01-26 20:19 UTC, alangenfeld commented on python_modules/dagster-graphql/dagster_graphql_tests/graphql/test_sensors.py
> +    assert counts.get("DagsterInstance.all_stored_job_state") == 1
nit: clarifying comments on these tests maybe helpful

2022-01-26 21:45 UTC, merged