[software-defined-assets] Enable inter-asset dependencies
dagster-io/dagster pull request #6307
Opened 2022-01-21 23:44 UTC by OwenKephart

This diff makes it possible to have a multi_asset in which some of the assets inside the multi_asset depend on other assets inside the same multi_asset.

To go along with this change, we also add in extra information to the ExternalAssetNode object, specifically the description of each output. While this isn't strictly necessary for the change, this is useful because otherwise the only description we can source for a given asset comes from the Op itself (which may have a one to many relationship with assets).

2022-01-25 00:12 UTC, clairelin135 reviewed
This looks good to me as long as we handle the case that an input and output may share the same name but refer to different assets.

2022-01-25 17:23 UTC, OwenKephart commented on python_modules/dagster/dagster/core/definitions/output.py
> +    def in_deps(self) -> Sequence[str]:
yep very true

2022-01-25 17:58 UTC, alangenfeld reviewed
I can understand how we iterated our selves here, but as the complexity of SDA increases this approach of bolting on top level properties to existing objects is unsustainable. There has to be a better way to model these things.

2022-01-25 17:58 UTC, alangenfeld commented on python_modules/dagster/dagster/core/host_representation/external_data.py
> +    namedtuple("_ExternalAssetDependency", "upstream_asset_key input_name output_name")
nit: these should all be typing.NamedTuple

2022-01-25 17:58 UTC, alangenfeld commented on python_modules/dagster/dagster/core/definitions/output.py
> +    @property
ya this feels really bad to me on first glance, these being terse and undocumented certainly doesn't help.

2022-01-25 17:58 UTC, alangenfeld commented on python_modules/dagster/dagster/core/definitions/output.py
> +        asset_partitions_def=None,
these two args feel odd next to each other, this def arg is undocumented so unclear why its needed

2022-01-28 20:48 UTC, alangenfeld requested changes
to your queue at least for some docs cleanup but potentially for deeper restructuring

2022-03-03 20:11 UTC, closed without merging