Add optional name parameter to Map ConfigType
dagster-io/dagster pull request #6432
Opened 2022-01-31 20:41 UTC by benpankow

## Summary

Adds an optional `name` parameter to the `Map` config type. Specifying a name provides context as to the role of the keys in the given map, and is rendered in the type printer (and will be rendered in the schema YAML editor):

`Map(str, {"image": str, "python_file": str}, name="location_name")
```yaml
{
    [location_name: String]: {
        image: String,
        python_file: String
    }
}
```

In the above case, the name indicates that the key specifies a location name.

## Rationale

Without a name field, a map config type can be fairly inscrutable. If the `Map` lives in a `Field`, the field's description could be used to explain the role of the keys and values, but this is not always the case.

The name field helps give concrete meaning to the key type, otherwise all the end user is shown is that it can be any string, or any int, etc.

## Test Plan

New unit tests.

2022-01-31 20:42 UTC, benpankow commented
Current dependencies on/for this PR:
* master
  * **PR #6383** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/6383" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #6432** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/6432" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  (this PR)

This comment was auto-generated by [Graphite](https://graphite.dev?utm_source=gh).

2022-01-31 22:38 UTC, gibsondan reviewed
will defer to @alangenfeld on the implementation but the API makes sense to me

2022-01-31 23:09 UTC, alangenfeld requested changes
im a tiny bit concerned about using `given_name` in this way but I think it should be fine. Def deserves leaving some nice comments for future person trying to deal with it.

2022-01-31 23:09 UTC, alangenfeld commented on python_modules/dagster/dagster/config/field_utils.py
> +            given_name=name,
this is a bit clever using this field on the parent for giving custom types names for storing the key label. 

definitely deserves some comments

2022-01-31 23:09 UTC, alangenfeld commented on python_modules/dagster/dagster/config/type_printer.py
> +            if config_type_snap.given_name:
related: deserves comment

2022-02-02 17:42 UTC, alangenfeld approved these changes
🙏

2022-02-03 06:57 UTC, merged