solid -> op in versioning error
dagster-io/dagster pull request #6434
Opened 2022-01-31 22:13 UTC by sryza

## Summary

## Test Plan

## Checklist

- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2022-02-01 17:37 UTC, dpeng817 requested changes
This should be using the `node_type_str` property so that it can properly switch between the two

2022-02-01 22:52 UTC, dpeng817 requested changes
This should be using the `node_type_str` property so that it can properly switch between the two

2022-02-01 22:52 UTC, dpeng817 commented on python_modules/dagster/dagster/core/execution/resolve_versions.py
> +                    f"Received None version for input {input_name} to op {solid_def.name}."
here too 🥺

2022-02-02 02:01 UTC, sryza commented on python_modules/dagster/dagster/core/execution/resolve_versions.py
> +                    f"Received None version for input {input_name} to op {solid_def.name}."
oops - thanks

2022-02-02 21:10 UTC, dpeng817 approved these changes

2022-02-02 21:26 UTC, merged