support forkserver in multiprocess executor
dagster-io/dagster pull request #6446
Opened 2022-02-01 18:52 UTC by alangenfeld

## Summary

Make the multiprocessing executor configurable in how it starts its subprocesses. Instead of only `spawn` we now also support `forkserver`.

We could potentially work to support `fork` but we use threads for cacnelation so out of the box I dont think it will work.

This is a little tricky since not all OS support `forkserver` so we have to be careful about that. 

That said, `forkserver` with the dagster preload is a big win for fast op Jobs so I think its worth persuing making that default when available. Will put that in a follow up diff.

## Test Plan

added a basic test, can add more

going to fire a PR that changes the default to `forkserver` and see what happens in BK

2022-02-01 18:52 UTC, alangenfeld commented
Current dependencies on/for this PR:
* master
  * **PR #6446** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/6446" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  (this PR)

This comment was auto-generated by [Graphite](https://graphite.dev?utm_source=gh).

2022-02-01 18:59 UTC, mgasner commented on python_modules/dagster/dagster/core/definitions/executor_definition.py
> +                    description="A server process is started and then subprocesses are forked from that.",
maybe link to the python docs for these

2022-02-01 18:59 UTC, mgasner commented on python_modules/dagster/dagster/core/executor/multiprocess.py
> +                f"The selected start_method '{start_method}' is not available. "
maybe also print the os/python version (e.g. `sys.platform` and `sys.version`) to make our lives easier when helping users debug

2022-02-03 20:56 UTC, alangenfeld commented
A comparison between forkserver and spawn for a simple job 

![Screen Shot 2022-02-03 at 2 53 41 PM](https://user-images.githubusercontent.com/202219/152427228-0a1e2ec4-8f60-44af-bd24-22a355506ca7.png)

2022-02-07 16:27 UTC, gibsondan requested changes
for the back-compat / snapshot question - I don't see a test change that would have caused it to change naturally and I think last time the default snapshot ID was changed it caused issues?

2022-02-07 16:27 UTC, gibsondan commented on python_modules/dagster-graphql/dagster_graphql_tests/graphql/snapshots/snap_test_pipeline_snapshot.py
> +    "pipelineSnapshotId": "4a20d826ecc8a9a7728ec4bb15b6ab8e727e5f85",
no back-compat issues being introduced here?

2022-02-07 16:27 UTC, gibsondan commented on python_modules/dagster/dagster/core/executor/child_process_executor.py
> +def execute_child_process_command(multiprocessing, command):
this name might benefit from a noun of some sort - multiprocess_context?

2022-02-11 19:40 UTC, gibsondan approved these changes
my confusion was that executors are user code, I am no longer confused

2022-02-11 20:30 UTC, merged