Add AssetOut and AssetOutputDefinition
dagster-io/dagster pull request #6461
Opened 2022-02-02 00:24 UTC by OwenKephart

This implements a bunch of the changes we were talking about in past conversations.

1. removes any asset-related parameters to Out/OutputDefinition
2. creates a new subclass of Out/OutputDefinition (AssetOut/AssetOutputDefinition) which accept these parameters
3. removes ability for the asset_key parameter to be a function of the output context (must be a static AssetKey)
4. removes the ability for the asset_partitions_fn to be a static set (must be a function of the output context)
5. adds ability for AssetOuts to explicitly define the other AssetKeys that they depend on (must be a subset of the asset keys define on the Inputs/Outputs of its op).

To keep the changes a little more under control, this diff does not attempt similar changes on the In/InputDefinition side of things.

This passes all the same tests as the (now abandoned) pr: https://github.com/dagster-io/dagster/pull/6307

2022-02-02 02:33 UTC, sryza reviewed
Would it be accurate to say that the only user-facing change is that `AssetOut` is expected for `multi_asset` instead of `Out`?

2022-02-02 02:33 UTC, sryza commented on python_modules/dagster/dagster/core/definitions/events.py
> +class AssetKey(NamedTuple("_AssetKey", [("path", Union[Tuple[str, ...], Sequence[str]])])):
I think `Tuple[str, ...]` might satisfy `Sequence[str]`, which would make these type annotations simpler.

2022-02-02 16:53 UTC, alangenfeld reviewed
@sryza raised concerns about this subclassing approach in other discussions around this so we should think through those and consider alternatives before moving forward with this. 

I think the through line of this current approach includes moving the serialization information down to where `OutputDefSnap` is and building the requisite data-structures from that in the host process. If this sounds right to others i think its a sign this route has merit, if not then other paths may be better.

One benefit of this over the current approach is it factors this static asset information in to the snapshot so it can be viewed historically and is part of the identity of the graph, which i think makes sense.

2022-02-02 16:53 UTC, alangenfeld commented on python_modules/dagster/dagster/core/host_representation/external_data.py
> +        "asset_key dependencies depended_by op_name op_description job_names partitions_def_data output_name output_description",
one thing i don't quite grok about these `ExternalAsset...` objects is why this information gets serialized. Looking at the contents I would expect them to be derivable from information already in the `ExternalRepositoryData` and these classes would be objects that `ExternalRepository` would build internally after loading `ExternalRepositoryData`

2022-02-02 16:53 UTC, alangenfeld commented on python_modules/dagster/dagster/core/host_representation/external_data.py
> +        "asset_key dependencies depended_by op_name op_description job_names partitions_def_data output_name output_description",
Ahhh I think I see - the information currently on `OutputDefinition` never made its way to `OutputDefSnap` as I assumed and we encoded it here instead.

2022-02-02 17:43 UTC, OwenKephart commented
> I think the through line of this current approach includes moving the serialization information down to where `OutputDefSnap` is and building the requisite data-structures from that in the host process. If this sounds right to others i think its a sign this route has merit, if not then other paths may be better.

I see what you mean here. It would potentially get kinda messy, as there are a bunch of extra properties we'd need to have on OutputDefSnap (asset_key, dependencies, partition_def). Could maybe just bundle those all into an AssetOutData thing or something I suppose.

Beyond that, it doesn't seem like there are any technical blockers to reconstructing from the serialized data rather than the in-memory jobs. I also don't have a great mental model of what consequences swapping this implementation might have for the data people currently have stored.

2022-02-02 17:52 UTC, alangenfeld commented
> just bundle those all into an AssetOutData thing or something

if this feels better than adding an `OutputDefSnap` sibling class ie `AssetOutDefSnap`, should we take a similar approach at the `Out` layer ie `Out(asset=Asset(key=...))` instead of subclassing?

2022-02-07 20:00 UTC, alangenfeld requested changes
to your queue if were putting it on ice for a bit

2022-03-03 20:11 UTC, closed without merging