Merge sean/metadata-rename into master
dagster-io/dagster pull request #6601
Opened 2022-02-15 04:08 UTC by smackesey

Repo-wide rename of metadata and friends:

- EventMetadataEntry > MetadataEntry
- XMetadataEntryData > XMetadataValue
- parse_metadata > normalize_metadata

The goal is to get everything internal and intercept old names with a
deprecation warning at the top level. Multiple strategies are possible. The one
I went with here is to use a backport of PEP 562, which is integrated into
Python 3.7 and allows you to override __getattr__ and __dir__. This is used to
intercept imports from `dagster`.

## Test Plan

The existing test suite.

## Checklist

- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2022-02-15 04:08 UTC, smackesey commented
Current dependencies on/for this PR:
* master
  * **PR #6601** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/6601" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  (this PR)

This comment was auto-generated by [Graphite](https://graphite.dev?utm_source=gh).

2022-02-15 17:36 UTC, alangenfeld requested changes
I expect there to be back compat test failures given these changes to serialized class artifacts. 

I think effectively we have two choices 
* ensure the new class names serialize identical to their previous names. This will allow events written in `>0.14` to be deserialized by `<0.14`
* add fallback handlers for the old names to remap them to the new ones. This is bare minimum as we must be able to read the old artifacts. If we only do this, `dagit`, `daemon` etc must be `>0.14` if any user code is `>0.14`

An example for serialize as old is here: https://github.com/dagster-io/dagster/pull/5467

2022-02-15 17:38 UTC, alangenfeld reviewed
I would advocate for the full back & forth compat to minimize potential thrash experienced by users.

2022-02-16 23:59 UTC, sryza approved these changes
Bombs away!

2022-02-16 23:59 UTC, sryza commented on docs/sphinx/sections/api/apidocs/ops.rst
>  Event metadata
We should rename this heading, right?

2022-02-17 01:28 UTC, merged