switch arg nam for metadata value class
dagster-io/dagster pull request #6675
Opened 2022-02-17 16:41 UTC by smackesey

This adjusts the new `MetadataEntry` class to (temporarily) accept either `value` or `entry_data` for its payload arg. In 0.15.0 will only be `value`.

2022-02-17 16:41 UTC, smackesey commented
Current dependencies on/for this PR:
* master
  * **PR #6675** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/6675" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  (this PR)

This comment was auto-generated by [Graphite](https://graphite.dev?utm_source=gh).

2022-02-17 17:47 UTC, sryza requested changes
as discussed over slack, this could break storage and is worth reconsidering

2022-02-22 15:43 UTC, smackesey commented
@sryza Having thought about this some more, handled properly this won't break storage. We can just use custom serialization logic to map older `entry_data` fields to `value` in 0.15.0. Given that, I think this diff is important to make a clean break with the "entry data" terminology.

2022-02-23 18:08 UTC, sryza reviewed
We're ultimately going to deprecate this class, right? If that's the case, it might make things easier just to leave things be?

2022-02-23 18:27 UTC, smackesey commented
@sryza I didn't think the class was being deprecated-- just deprecating `description`. We're recommending users avoid instantiating `MetadataEntry` directly, but internally everything is passed around as lists of `MetadataEntry`, and per previous discussion I thought that was not going to change.

2022-02-23 22:37 UTC, sryza reviewed
This makes sense to me, but I think I'm relatively blind to the difficulties (or lack there-of) with storage back-compatibility, so I'd like @alangenfeld to take a look as well.

E.g. are there issues here with storage _forward_-compatibility?

2022-02-23 22:44 UTC, smackesey commented
> E.g. are there issues here with storage forward-compatibility?

Could you explain a little what you mean by this? My interpretation of "forward-compatibility" is: will this format limit our ability to change how these values are persisted in the future? If that's what you're asking, then I don' think so.

2022-03-07 19:31 UTC, smackesey commented on python_modules/dagster/dagster/core/definitions/metadata/__init__.py
> +        ) from None
This is used to [suppress error context](https://stackoverflow.com/a/24752607/1244455), it's useful if you want to clean up your error messages when you are catching one error and replacing it with another (especially of the same type, as I did here).

2022-03-07 19:38 UTC, alangenfeld approved these changes
seems fine to me

adding some tests not a bad idea

2022-03-07 20:20 UTC, merged