enable vixie-style cron strings
dagster-io/dagster pull request #6810
Opened 2022-02-25 18:50 UTC by prha

We disallowed a class of cron strings that are valid from `croniter`'s point of view (e.g. `@daily`), because `schedule_execution_time_iterator` would barf when trying to do it's special-cased perf optimizations.

This PR re-enables that might by using `croniter`'s `expand` method to parse the cron schedule structure (instead of using split).

## Test Plan
BK

2022-02-28 17:19 UTC, gibsondan requested changes
only question is about OPTIMIZED_KEYWORD_CRON_SCHEDULES / keeping the special-case logic for daily/hourly/monthly/weekly with these new cron strings - My recollection is that the optimization there made a big deal when calculating hourly partition sets in particular. Otherwise this looks great

2022-02-28 17:19 UTC, gibsondan commented on python_modules/dagster/dagster/utils/schedules.py
> +OPTIMIZED_KEYWORD_CRON_SCHEDULES = set(["@monthly", "@weekly", "@daily", "@hourly"])
unused?

2022-03-01 00:51 UTC, prha commented on python_modules/dagster/dagster/core/definitions/schedule_definition.py
> +                f"Found invalid cron schedule '{self._cron_schedule}' for schedule '{name}''."
It's not really clear to me what a good resource would be.   Wikipedia?

https://en.wikipedia.org/wiki/Cron has a `Nonstandard predefined scheduling definitions` section.

2022-03-01 00:53 UTC, prha commented on docs/content/concepts/partitions-schedules-sensors/schedules.mdx
> +Here's a simple schedule that runs a job every day, at midnight. The `cron_schedule` accepts standard [cron expressions](https://en.wikipedia.org/wiki/Cron). It also accepts `"@hourly"`, `"@daily"`,
Tried pinning... it conflicts with our airflow 1.0 integration.

2022-03-02 20:40 UTC, gibsondan approved these changes

2022-03-04 01:05 UTC, merged