[dagit] Always collapse the left Jobs navigation by default
dagster-io/dagster pull request #7204
Opened 2022-03-25 21:05 UTC by bengotow

## Summary
Per discussion with Josh here! https://github.com/dagster-io/dagster/issues/7170

## Test Plan

## Checklist

- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2022-03-30 16:57 UTC, hellendag requested changes
See inline comments

2022-03-30 16:57 UTC, hellendag commented on js_modules/dagit/packages/core/src/app/LayoutProvider.tsx
> +        isCollapsible: true,
I think if this is always true, there is more code that can be cleaned up in `App` and `AppTopNav`. E.g. the hamburger icon should always be visible, the CSS can be simplified.

2022-04-01 20:46 UTC, bengotow commented
Hey @hellendag! Could I get another look at this one? Per discussion with Josh we ended up making this a feature flag so we can A/B test with some users, so it's a smaller change now.

2022-04-02 01:51 UTC, hellendag approved these changes

2022-04-07 22:01 UTC, merged