small improvements for code loading readability
dagster-io/dagster pull request #7246
Opened 2022-03-30 22:50 UTC by sryza

As I was trying to grok this code, I found a couple small things confusing. Changes are:
* In `_get_code_pointer_dict_from_kwargs ` factor out logic that's the same across code pointer types.
* Use the name `attribute` instead of `fn_name` in code pointer. While many attributes are constructed using decorated functions, that's not a requirement.

2022-03-31 02:27 UTC, gibsondan requested changes
cli_target changes look good. I think the back-compat integration test failures are real - code pointers are returned over the gRPC interface, so we are sadly doomed to these names (or at least to a path that accepts the bad names and converts them to the good names somehow) for the forseeable future

2022-03-31 02:30 UTC, gibsondan commented
here is where we return them over gRPC: https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/grpc/server.py#L355

2022-04-12 20:33 UTC, sryza commented
@gibsondan mind taking another look? Also feel free to say that this is frivolous and can abandon it.

2022-04-26 15:09 UTC, sryza commented
Ping @gibsondan. Also feel free to say that this is frivolous and can abandon it.

2022-04-26 15:10 UTC, sryza commented
Actually nvm just going to close- I think more trouble than it's worth.

2022-04-26 15:10 UTC, closed without merging