Census
dagster-io/dagster pull request #7249
Opened 2022-03-31 10:34 UTC by dehume

## Summary

Adding a basic module for [Census](https://www.getcensus.com/) which would all for reverse ETL. A lot of the structure for this module is taken from the [dagster-fivetran module](https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-fivetran). Overall this adds:
* A resource for interacting with the Census API
* A custom type for a CensusOutput
* An reusable op that can trigger a Census sync and poll until the sync has finished running

## Test Plan

Tests cover the resource and the pipeline run of the op

## Checklist

- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2022-04-12 16:31 UTC, OwenKephart requested changes
On the whole, looks great! Thanks for putting this together. Had some comments in-line, and you'll also need a setup.py / tox.ini file in here (those can basically be copied from dagster-fivetran), but otherwise this looks ready to merge in.

2022-04-13 12:38 UTC, dehume commented on python_modules/libraries/dagster-census/README.md
> +[here](https://docs.dagster.io/_apidocs/libraries/dagster-census).
Sounds good removing the README for now

2022-04-13 20:27 UTC, OwenKephart commented
Looks like you'll need to:

- rebase
- tox -e pylint in libraries/dagster_airbyte (and fix the errors)
- make black at the top level

but after those quick fixes, this should be ready to merge!

Thanks so much for working on this, awesome to have a new integration!

2022-04-20 22:06 UTC, OwenKephart approved these changes
great! merging this in now so it goes out in tomorrow's release :)

2022-04-20 22:06 UTC, merged