[rfc] Resources on repos, resource overrides onjob
dagster-io/dagster pull request #7498
Opened 2022-04-20 02:32 UTC by dpeng817

One possible implementation world for resources on repositories and partial resources for jobs. In the 0.15.0 timeframe, this could be opt-in via a flag.

2022-04-25 16:24 UTC, sryza reviewed
Nice. Main thoughts:
* Would you mind spelling out your concerns about affecting pipeline users in a little more detail? My gut is not to be too concerned about them, as long as we're not breaking code that currently works.
* If we do go the partial route, naming the argument "partial" feels a little too vague. Thoughts on something more explicit like `unsatisfied_resources_ok`?
* It feels a little gnarly that `to_job` can return two totally independent types. If someone tries to treat the produced object like a job definition, e.g. by calling `execute_in_process` on it, they'll get a confusing error like "Object of type X doesn't have member Y", when ideally they might get an error like "Job X can't be executed, because it's missing a definition for required resource Y".

2022-04-25 16:24 UTC, sryza commented on python_modules/dagster/dagster/core/definitions/decorators/repository_decorator.py
> +                    "PartitionSetDefinition, ScheduleDefinition, SensorDefinition, or dictionary of resources. "
"dictionary that maps resource keys to ResourceDefinitions"

2022-04-25 16:26 UTC, sryza commented on python_modules/dagster/dagster/core/definitions/repository_definition.py
> +def is_resource_dict(defn: Any) -> bool:
I think we prefer `object` to `Any` in these cases, because it enforces that we can't assume anything about the object until we've verified its type.

2022-04-27 22:36 UTC, dpeng817 commented
> * Would you mind spelling out your concerns about affecting pipeline users in a little more detail? My gut is not to be too concerned about them, as long as we're not breaking code that currently works.
Unless we did a big lift, if we wanted to make all job definitions accept partial resource requirements, we would need to do the same for pipelines. I think we could more or less alleviate this by still performing resource fulfillment checks if a certain gate isn't satisfied, but the place that gate where that check occurs will need to move
> * If we do go the partial route, naming the argument "partial" feels a little too vague. Thoughts on something more explicit like `unsatisfied_resources_ok`?
`allow_unsatisfied_resources` perhaps?
> * It feels a little gnarly that `to_job` can return two totally independent types. If someone tries to treat the produced object like a job definition, e.g. by calling `execute_in_process` on it, they'll get a confusing error like "Object of type X doesn't have member Y", when ideally they might get an error like "Job X can't be executed, because it's missing a definition for required resource Y".
Yea I think that's reasonable. Will try and re-spin with just JobDefinition.

2022-04-27 23:16 UTC, sryza commented
> Unless we did a big lift, if we wanted to make all job definitions accept partial resource requirements, we would need to do the same for pipelines. I think we could more or less alleviate this by still performing resource fulfillment checks if a certain gate isn't satisfied, but the place that gate where that check occurs will need to move

I'm saying: what's bad about doing the same for pipelines?

> allow_unsatisfied_resources perhaps?

Sounds good to me.

2022-04-28 17:10 UTC, alangenfeld reviewed
I don't love `to_job` with a a bool arg that makes it return a not job. 

What are your thoughts on explicit method that return a `PartialJobDefinition` / `PendingJobDefinition` object?

Could do  like `set_executor_def` / `set_resource_defs` / `with_resource_defs` / `with_executor_def` . These would also be callable on the `PendingJobDefinition`. 

Or just `to_partial_job`/ `to_pending_job`.

2022-04-28 17:13 UTC, alangenfeld commented on python_modules/dagster/dagster/core/definitions/graph_definition.py
>          partitions_def: Optional["PartitionsDefinition"] = None,
<!-- GRAPHITE_METADATA {"trueLocation":{"startLine":455,"endLine":462,"prLink":"https://app.graphite.dev/github/pr/dagster-io/dagster/7498"}} -->
<i class='graphite__hidden'>[Re: lines 455 to 462]<br/></i>

is `resource_defs` the only one of these properties that should be possible to inherit from the repository def? <span class='graphite__hidden'><br/><br/>See this comment inline on <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/7498?utm_source=unchanged-line-comment">Graphite</a>.</span>

2022-04-28 17:27 UTC, sryza commented
> What are your thoughts on explicit method that return a PartialJobDefinition / PendingJobDefinition object?

I'm worried that the meaning of "pending" / "partial" won't be super obvious. I worry that they imply you can't use it like a non-partial job definition, when in fact you can use it in most of the situations you can use a non-partial job definition: put it on a repository, target it with a schedule or sensor. The only thing you can't do is `execute_in_process`.

2022-04-28 17:42 UTC, dpeng817 commented
> What are your thoughts on explicit method that return a `PartialJobDefinition` / `PendingJobDefinition` object?

I might just rework this to always return a job definition, and just make sure explicit resource checks are always happening otherwise.

2022-04-28 21:26 UTC, alangenfeld requested changes
back to you for next iteration

2022-04-30 15:42 UTC, sryza commented
> if we want to just allow JobDefinitions to loadable and not executable thats more ux changes (disable launch button etc)
I don't think there would be much value in this FWIW.

2022-05-06 18:51 UTC, dpeng817 commented on python_modules/dagster/dagster_tests/core_tests/definitions_tests/test_repository_definition.py
> +    assert the_repo.get_all_jobs()[0] != the_job_with_name
We are probably aware of this, and it's probably not high impact, but thought I would flag.

2022-05-23 21:11 UTC, dpeng817 commented
Going with a `with_resources` based approach

2022-05-23 21:11 UTC, closed without merging