WIP - add metadata to definitions as tags
dagster-io/dagster pull request #7507
Opened 2022-04-20 22:04 UTC by jamiedemaria

poking around with adding metadata to the job decorator and converting text and json metadata to tags in JobDefinition

2022-04-24 02:50 UTC, prha commented
I think this looks good!

I think next steps are probably to display this metadata on the job root page, kind of in a uniform way.  So that probably means threading the metadata through to the ExternalPipeline and adding fields to query it in on the graphql object.

I'm not so sure about the `searchable` parts of the metadata.  I think we can start off by exposing everything and then see  if we even need to distinguish between searchable and non-searchable metadata.

2022-05-19 17:06 UTC, prha requested changes
See inline comments

2022-05-19 17:06 UTC, prha commented on python_modules/dagster/dagster/core/definitions/metadata/__init__.py
> +    @property
let's remove searchable until we know how it's going to be used

2022-05-19 19:23 UTC, jamiedemaria commented
closing in favor of https://github.com/dagster-io/dagster/pull/7849

2022-05-19 19:23 UTC, closed without merging