use generic Output type annotations in hacker news
dagster-io/dagster pull request #7600
Opened 2022-04-26 21:25 UTC by sryza

## Summary

## Test Plan

## Checklist

- [ ] My change requires a change to the documentation and I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2022-04-27 19:48 UTC, OwenKephart approved these changes
oh cool I didn't know this was a thing

2022-04-27 19:49 UTC, OwenKephart commented
> 

oh it is not

2022-05-03 17:10 UTC, dpeng817 commented
This should be landable now!

2022-05-03 17:10 UTC, dpeng817 requested changes
To your queue to verify everything works

2022-05-05 16:49 UTC, dpeng817 requested changes

2022-05-05 16:49 UTC, dpeng817 commented on examples/hacker_news/hacker_news/ops/id_range_for_time.py
> +def id_range_for_time(context) -> Output[Tuple[int, int]]:
you're using the wrong tuple here

2022-05-12 15:18 UTC, merged