[rfc] Resources on repos
dagster-io/dagster pull request #7640
Opened 2022-04-28 22:35 UTC by dpeng817

This PR allows a dictionary of resources to be provided to the repository. Those resources are utilized by graphs provided to the repository definition to construct jobs.

2022-04-29 21:05 UTC, sryza reviewed
This looks good to me! I see that it still has the rfc tag - what stuff do you think we need to consider before merging?

2022-05-03 00:29 UTC, dpeng817 commented
cc @sryza I think the only remaining question is: are we okay with using a dictionary of resources instead of a more richly-structured object

2022-05-06 00:10 UTC, dpeng817 commented on python_modules/dagster/dagster_tests/daemon_tests/test_sensor_run.py
> +config_job = config_graph.to_job(name="config_job")
The necessity here was a bit surprising to me. Were we just de-duping before, and I've somehow broken that?

2022-05-06 20:38 UTC, dpeng817 commented on python_modules/dagster/dagster_tests/daemon_tests/test_sensor_run.py
> +config_job = config_graph.to_job(name="config_job")
Ah this is because we previously weren't catching duplicates as a result of graph coercion.

2022-05-06 20:41 UTC, dpeng817 commented on python_modules/dagster/dagster_tests/daemon_tests/test_sensor_run.py
> +config_job = config_graph.to_job(name="config_job")
In order to preserve existing behavior, we'll have to move job construction from sensors/schedules to the very end.

2022-05-09 23:42 UTC, sryza reviewed
Yeehaw! This looks almost there to me. What do we expect to happen in this case?

```
@op(required_resource_keys="resource1"}
def my_op():
    ...

@graph
def my_graph():
    my_op()

@sensor(job=my_graph)
def my_sensor():
    ...

@repository
def my_repo():
    return [my_sensor, resource_defs={"resource1": ...}]
```

2022-05-10 00:24 UTC, dpeng817 commented
cc @sryza yup I think that https://github.com/dagster-io/dagster/pull/7817 should address part of that, but then we also need to make sure that when sensors/schedules foist a graph, they use the resource set.

2022-05-10 14:18 UTC, sryza commented
> Got it - makes sense. Mind including a test in this PR that codifies whatever error behavior we expect in the mean time?

Unless we're sure they'll all land in the same release.

2022-05-17 16:31 UTC, alangenfeld requested changes
seems like we are going in a `with_resources` direction

2022-05-23 21:11 UTC, dpeng817 commented
closing in favor of with_resources approach

2022-05-23 21:11 UTC, closed without merging