GCP:GCS:GCSFileManager Adds optional write keys
dagster-io/dagster pull request #8095
Opened 2022-05-27 14:46 UTC by will-holley

### Summary & Motivation

- This PR adds an optional `key` arg to `GCSFileManager.write` and `GCSFileManager.write_data` which, if provided, will be set as the GCS blob key.
- I was not satisfied with non-deterministic UUID4s as the only option for keys naming.

### How I Tested These Changes

- Added a true positive case to `dagster_gcp_tests` and tests pass.

2022-06-09 18:08 UTC, dpeng817 requested changes
Thanks for doing this! Just some styling stuff and this should be good to go.

2022-06-15 00:08 UTC, dpeng817 commented
We use `opt_str_param` to perform runtime type checking, and give explicit error messages when users provide incorrectly typed values.

2022-06-27 17:02 UTC, dpeng817 commented
@will-holley had some back and forth on this one with the team; it's a bit of a tricky scenario because adding the key arg will not match the args of the base class `FileManager`. However, because the method in question is only ever invoked by users,  it should be fine. Two things to get this forward:
1. Move key to be the last argument
2. pylint ignore the resulting error using a comment a la `# pylint: ignore=arguments-differ`.

2022-08-09 16:56 UTC, dpeng817 approved these changes
GCP tests pass, looks good!

2022-08-09 16:57 UTC, merged

2022-08-09 17:07 UTC, will-holley commented
Thanks for reviewing, @dpeng817!