fix(dagster/decorators): op_decorator documentation update
dagster-io/dagster pull request #8179
Opened 2022-06-03 08:30 UTC by mict0

Updating legacy return types from Solid to OpDefintion

### Summary & Motivation
It's weird to see legacy types for newcomers.

### How I Tested These Changes

2022-06-09 17:28 UTC, dpeng817 requested changes
Thanks for doing this! A simple change and this should be good to go.

2022-06-09 17:28 UTC, dpeng817 commented on python_modules/dagster/dagster/core/definitions/decorators/op_decorator.py
> +def op(name: Callable[..., Any]) -> OpDefinition:
When using a type annotation imported as a future, you need to use quotations around the annotation:
```suggestion
def op(name: Callable[..., Any]) -> "OpDefinition":
```

2022-06-09 17:28 UTC, dpeng817 commented on python_modules/dagster/dagster/core/definitions/decorators/op_decorator.py
> +) -> Union[OpDefinition, _Op]:
Same as [1]:
```suggestion
) -> Union["OpDefinition", _Op]:
```

2022-06-15 18:45 UTC, dpeng817 commented
@mict0 only one more small change, just need to get rid of the import of `SolidDefinition` in `op_decorator.py` now that it's no longer used :)

2022-06-16 10:27 UTC, mict0 commented
> @mict0 only one more small change, just need to get rid of the import of `SolidDefinition` in `op_decorator.py` now that it's no longer used :)

Actually it's used in line 8 `class OpDefinition(SolidDefinition):` since OpDefinition is inheriting from SolidDefinition, not sure if bigger change is needed. I think you'd like to keep SolidDefinition for legacy code, but maybe should create separate class OpDefinition for the future use-cases

2022-06-16 21:59 UTC, dpeng817 commented
@mict0 the line you're referring to is within `op_definition.py`, but the proposed changes are in `op_decorator.py`. The only place the `SolidDefinition` import was used within that file was these annotations, so it's necessary to get rid of the import in that file.

2022-06-17 09:31 UTC, mict0 commented
> @mict0 the line you're referring to is within `op_definition.py`, but the proposed changes are in `op_decorator.py`. The only place the `SolidDefinition` import was used within that file was these annotations, so it's necessary to get rid of the import in that file.

oh, you're right my bad. changes added, import is removed

2022-06-17 22:25 UTC, dpeng817 approved these changes

2022-06-17 22:26 UTC, dpeng817 commented
Thanks for your contribution @mict0 ! This will go into the next release, and we'll shout it out in the changelog :)

2022-06-17 22:26 UTC, merged