[dagit] Add Materialize button to the Asset Catalog
dagster-io/dagster pull request #8206
Opened 2022-06-06 15:11 UTC by bengotow

### Summary & Motivation

This PR adds a Materialize button to the Asset Catalog. This was somewhat painful because the button requires a ton of context about the assets which we don't load in the asset table view. In this implementation, the data is loaded for the assets you select via a wrapper around the Materialize button.

<img width="446" alt="image" src="https://user-images.githubusercontent.com/1037212/172189446-7a5adacc-4cab-4edc-a189-2353062b4039.png">

### How I Tested These Changes

2022-06-07 14:08 UTC, hellendag requested changes
Looks like there are a bunch of conflict markers.

2022-06-07 14:08 UTC, hellendag commented on js_modules/dagit/packages/core/src/assets/AssetTable.tsx
> +>>>>>>> 3321992479 (Defer fetching data required to launch assets until you click the button!)
eep

2022-06-08 16:42 UTC, hellendag approved these changes

2022-06-08 21:07 UTC, bengotow commented on js_modules/dagit/packages/core/src/assets/AssetTable.tsx
>                </Link>
Ahh nice I didn't realize we had this! Will fix.

2022-06-08 21:09 UTC, merged