reorder concept super-sections in left nav
dagster-io/dagster pull request #8315
Opened 2022-06-10 14:22 UTC by sryza

### Summary & Motivation

This reorders the concept sections based on somewhat-subjective opinions of importance. Some impressions:
* Almost every Dagster user uses Schedules, Sensors, and Partitions.
* Resources are a big source of confusion for early users and it's possible to use Dagster without them, so I moved them down.
* Many users don't use Dagster types.

### How I Tested These Changes

yarn dev

2022-06-10 20:16 UTC, erinkcochran87 reviewed
Thoughts about having the last part of the nav be in this order?

```
- Dagster types
- Logging
- Testing
```

I see logging and testing as related, and could see going from logging to testing as a natural progression.

2022-06-10 20:19 UTC, sryza commented
@erinkcochran87 👍, I made the change you suggested.

2022-06-10 20:46 UTC, erinkcochran87 requested changes
Just remembered that the sidenav order is also reflected in the **Guides** page. Could you update that to match and then this'll be good to go?

2022-06-11 17:23 UTC, sryza commented
@erinkcochran87 I updated the PR to reorder the concept page as well.

2022-06-11 19:05 UTC, erinkcochran87 approved these changes

2022-06-11 19:08 UTC, merged