[docs] - Update screenshots in tutorials
dagster-io/dagster pull request #8494
Opened 2022-06-20 19:32 UTC by erinkcochran87

### Summary & Motivation

This PR updates the screenshots in the SDA and ops/jobs tutorials and corrects some typos and formatting issues.

2022-06-20 23:56 UTC, shalabhc commented
Thanks Erin! The screenshots still look like the older version though - maybe you need to update the code wherever you are generating these? Eg the [asset_details](https://github.com/dagster-io/dagster/pull/8494/files#diff-6cde5a55291f92ea627f526b8340c0024d40bada5794c6bf15f20bec04a795fc) should have the Lineage tab next to Definition and the [top level the graph](https://github.com/dagster-io/dagster/pull/8494/files#diff-884f6c0498f378e795b5ef4c593b986265ca4a9fa45c25378f99f40a4818c5c5) view doesn't exist anymore.

2022-06-21 00:03 UTC, shalabhc requested changes
Added a comment above.

2022-06-21 15:44 UTC, erinkcochran87 commented
Thanks for pointing that out - I'll take a look!

2022-06-21 22:21 UTC, shalabhc approved these changes
Screenshots look good! I added a couple of comments about changing the text to match the UI. Approving!

2022-06-21 22:21 UTC, shalabhc commented on docs/content/tutorial/assets/defining-an-asset.mdx
>  Clicking on the "Materialize All" button will launch a run that will materialize the asset. After that run has completed, the shaded box underneath "cereals" holds information about that run. Clickin
This text should now be revised to match the new UI. Eg

Click on the "Materialize" button launches a run that materializes the asset. After the run has completed the Activity tab on the assets page holds information about that run. Click on the Run ID in the activity tab to go see details about the run. This opens a view that includes a structured stream of logs and events that occurred during the run execution.

2022-06-21 22:21 UTC, shalabhc commented on docs/content/tutorial/assets/defining-an-asset.mdx
>  To see a history of all the materializations for your asset, you can navigate to the _Asset Details_ page for it. Click the "cereals" link in the upper left corner of this run page, next to "Success"
Revise for new UI. Eg (the activity tab is already shown above)

Click the "cereals" link in the upper left corner of this run page to go back to the asset details page.

2022-06-23 15:55 UTC, merged