Feature/phazure/8602 dagster_databricks - support configuration of job / cluster permissions
dagster-io/dagster pull request #8683
Opened 2022-06-30 00:02 UTC by Phazure

### Summary & Motivation
For productionized jobs which use databricks_pyspark_step_launcher, the databricks token provided is typically that of a prod service principal to align with best practices. When debugging, it can be helpful for developers to have access to the complete databricks job run within the Databricks workspace - however, because the databricks job run (and cluster) is owned only by the service principal, developers won't have access unless the permissions are explicitly added separately via the Databricks API. It would be great if we could provide the configurations to add these permissions within the DatabricksPySparkStepLauncher class.

### How I Tested These Changes
Tested by building / installing a new wheel for dagster_databricks.

2022-06-30 19:31 UTC, OwenKephart requested changes
This is definitely valuable functionality, my only concern is that it's a bit dangerous to allow users to grant themselves permissions through run config. The fact that you've locked this down to only allow users to change cluster permissions for new clusters (not existing) makes a ton of sense, but I think it'd be worthwhile to include a test that confirms that if you attempt to set permissions on an existing cluster then an exception will be raised.

Beyond that, I have some comments on bits of the implementation, but overall I'm on board with this direction

2022-06-30 19:31 UTC, OwenKephart commented on python_modules/libraries/dagster-databricks/dagster_databricks/databricks_pyspark_step_launcher.py
> +            for permission_level, accessor in self.permissions["cluster_permissions"].items():
this logic appears identical to the logic above, so this might be worth refactoring

2022-07-05 01:10 UTC, Phazure commented on python_modules/libraries/dagster-databricks/dagster_databricks/databricks_pyspark_step_launcher.py
> +    DATABRICKS_RUN_RETRIES = 3
Rm'd.

2022-07-05 01:10 UTC, Phazure commented on python_modules/libraries/dagster-databricks/dagster_databricks/databricks_pyspark_step_launcher.py
> +            response = requests.patch(
Agreed, updated.

2022-07-05 01:13 UTC, Phazure commented on python_modules/libraries/dagster-databricks/dagster_databricks/databricks_pyspark_step_launcher.py
> +            if not response.ok:
Agreed - in this case, `perform_query` will raise the error for us if the request failed.

2022-07-05 01:14 UTC, Phazure commented on python_modules/libraries/dagster-databricks/dagster_databricks/databricks_pyspark_step_launcher.py
> +        if "new" in self.run_config["cluster"] and "cluster_permissions" in self.permissions:
Done.

2022-07-05 01:17 UTC, Phazure commented
@OwenKephart Glad we find this useful - comments have been addressed, and test case ensuring existing cluster perms _cannot_  be adjusted has been added.

2022-07-05 17:34 UTC, OwenKephart approved these changes
Thanks again for the contribution! I'll merge this in and this should get into this week's release

2022-07-05 17:35 UTC, merged