Add MetaDataEntry.path to PickledObjectS3IOManager
dagster-io/dagster pull request #8732
Opened 2022-07-04 16:01 UTC by danielgafni

### Summary & Motivation
I noticed this was missing and fixed this little issue.

### How I Tested These Changes
Running Dagster locally with these modifications produces the desired result:

![image](https://user-images.githubusercontent.com/49863538/177189119-5a1688b3-0d32-4986-99ca-669844b24a73.png)

2022-07-05 06:37 UTC, danielgafni commented
Or maybe this should be a `MetadataEntry.url` ?

2022-07-05 17:53 UTC, prha commented
Yeah, I think `MetadataEntry.url` would be preferred here.

cc @smackesey / @sryza  since I see yielding `MetadataEntry` is marked for deprecation but we will probably want a carve-out for the IO manager use case.

2022-07-05 17:57 UTC, sryza commented
@prha @danielgafni - the preferred invocation would be
```
context.add_output_metadata("metadata_label": MetadataValue.url(...))
```

2022-07-05 22:28 UTC, danielgafni commented
I see, thanks. I didn't find anything about the deprecation in the docs (although it was obvious from the code). The docs have a section about using MetaDataEntry. Probably this should be fixed?

2022-07-06 12:15 UTC, danielgafni commented
I'm thinking this should be a `path`, not a `url`. A url is clickable, while a path can be copied to clipboard on click. This (copying) is exactly what we need for an s3 path.

2022-07-06 15:19 UTC, sryza commented
> I'm thinking this should be a path, not a url. A url is clickable, while a path can be copied to clipboard on click. This (copying) is exactly what we need for an s3 path.

That reasoning makes sense to me.

> I see, thanks. I didn't find anything about the deprecation in the docs (although it was obvious from the code). The docs have a section about using MetaDataEntry. Probably this should be fixed?

Thanks for reporting this. I'll file an issue.

2022-07-06 16:32 UTC, sryza commented
@danielgafni it looks like all the tests passed, but the build is complaining about some code style and import ordering. If you run `make isort` and `make black` from the repo root, it should fix these.

2022-07-06 22:11 UTC, sryza requested changes
Marking this "Changes requested" a la my previous review.

2022-07-07 07:43 UTC, danielgafni commented
@sryza sorry, done

2022-07-07 21:11 UTC, merged