Document valid names for asset keys
dagster-io/dagster pull request #8765
Opened 2022-07-06 17:34 UTC by jamiedemaria

### Summary & Motivation
adds docs for valid asset key names

### How I Tested These Changes

2022-07-06 18:31 UTC, jamiedemaria commented
@sryza the original issue says to raise a clearer error. This is the current error 
```
UserWarning: Error loading repository location dagster_test.graph_job_op_toys.repo:dagster.core.errors.DagsterInvalidDefinitionError: "this/is/invalid__daily_temperature_highs" is not a valid name in Dagster. Names must be in regex ^[A-Za-z0-9_]+$.
```

Were you thinking that the wording of this should be changed (would affect all ops since this is raised in node definition) or that we should check name validity earlier in the stack (like in _Asset) and raise an asset specific error message?

2022-07-06 22:12 UTC, sryza requested changes

2022-07-06 22:12 UTC, sryza commented on python_modules/dagster/dagster/core/asset_defs/decorators.py
> +            the asset resides in.  The namespace + the name forms the asset key. The asset key must
This can be a sequence, right? I think this description is a little bit confusing with respect to that.

2022-07-13 17:40 UTC, sryza approved these changes
Nice

2022-07-14 15:26 UTC, merged