Mark dagster.{builtins,experimental,serdes,seven,utils} private
dagster-io/dagster pull request #8910
Opened 2022-07-15 21:11 UTC by smackesey

### Summary & Motivation

Marks `dagster.builtins`, `dagster.experimental`, `dagster.serdes`, `dagster.seven`, and `dagster.utils` private. Part of incremental privacy adoption for submodules. Add sys.meta_path mappings so that imports of e.g. `dagster.serdes` are mapped to `dagster._serdes`.

Changes were done by:

- Using VSCode pylance module renames
- Associated manual renames in the docs

Requires a sister PR in internal:

### How I Tested These Changes

BK

2022-07-15 21:11 UTC, smackesey commented
Current dependencies on/for this PR:
* master
  * **PR #8881** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/8881" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #8829** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/8829" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #8884** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/8884" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #8910** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/8910" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/8910?utm_source=stack-comment).

2022-07-22 01:16 UTC, dpeng817 commented on docs/content/integrations/dagstermill.mdx
> +from dagster._utils import script_relative_path
anything like this, would probably be nice to get it exported at the top level

2022-07-22 01:17 UTC, dpeng817 requested changes
Looks like a few docs files got caught up in this; I think the right thing to do there is export the symbols at the top level :/

2022-07-22 13:20 UTC, smackesey commented
>Looks like a few docs files got caught up in this

I added a new downstack PR for this: https://github.com/dagster-io/dagster/pull/8999

2022-07-22 18:46 UTC, dpeng817 approved these changes
Should be good in tandem with upstream docs changes

2022-07-23 01:39 UTC, merged