Fix handling of launch path when a repository location is still loading
dagster-io/dagster pull request #8983
Opened 2022-07-21 15:56 UTC by gibsondan

Summary:
Still a bit confused about how this managed to be hit in practice, but adding some defensive coding here nonetheless.

- has_external_pipeline should return False when a repo location is still loading, not throw an exception
- If you do manage to reach get_repository_location somehow while the location is still loading, it should raise an exception explaining that this is why rather than an issue from trying to call to_string() on a load error that doesn't exist

Will add a test in an environment where it's more feasible to have a location in a LOADING state

### Summary & Motivation

### How I Tested These Changes

2022-07-21 16:16 UTC, alangenfeld submitted a review, later dismissed

2022-07-21 18:07 UTC, rexledesma requested changes
we should ensure that

- the old location is still used for launching runs during update
- submitting runs do not fail during the update step

2022-07-21 22:29 UTC, rexledesma requested changes
a test for the loading code location entry should be pretty easy with mocks.

Also maybe we should raise a catch-all exception in the case that none of the conditional branches in this method execute? Right now it could technically return `None`

2022-07-29 20:20 UTC, gibsondan commented
@rexledesma test added!

2022-07-29 20:23 UTC, rexledesma approved these changes

2022-07-29 20:47 UTC, merged