stop relying on legacy APIs in some integrations
dagster-io/dagster pull request #8995
Opened 2022-07-21 23:49 UTC by sryza

### Summary & Motivation

This is by no means comprehensive - just a set of changes I made to get a feel for it.

I think it's fine if some error messages say "op" instead of solid for legacy APIs for the next couple releases.

### How I Tested These Changes

2022-07-22 01:04 UTC, dpeng817 requested changes
Good start, some of them still need InputDefinition/OutputDefinition migrated. Thanks for getting ahead on this.

2022-07-22 01:04 UTC, dpeng817 commented on python_modules/libraries/dagster-airflow/dagster_airflow/dagster_pipeline_factory.py
>          output_defs=[OutputDefinition(Nothing, "airflow_task_complete")],
needs to get rid of InputDefinition/OutputDefinition as well

2022-07-22 01:04 UTC, dpeng817 commented on python_modules/libraries/dagster-dbt/dagster_dbt/cli/solids.py
>      output_defs=[OutputDefinition(name="dbt_cli_output", dagster_type=DbtCliOutput)],
InputDefinition/OutputDefinition

2022-07-22 01:04 UTC, dpeng817 commented on python_modules/libraries/dagster-dbt/dagster_dbt/cli/solids.py
>      output_defs=[OutputDefinition(name="dbt_cli_output", dagster_type=DbtCliOutput)],
same as [1]

2022-07-22 01:04 UTC, dpeng817 commented on python_modules/libraries/dagster-dbt/dagster_dbt/cli/solids.py
>      output_defs=[OutputDefinition(name="dbt_cli_output", dagster_type=DbtCliOutput)],
etc

2022-07-22 15:36 UTC, sryza commented
@dpeng817 this isn't meant to be comprehensive. For the input / output defs that aren't done yet, I'm thinking we can do those later.

2022-08-15 17:37 UTC, dpeng817 approved these changes

2022-08-15 17:43 UTC, merged