add @public decorator to AssetsDefinition methods
dagster-io/dagster pull request #9066
Opened 2022-07-27 18:29 UTC by sryza

### Summary & Motivation

### How I Tested These Changes

2022-07-27 20:06 UTC, OwenKephart approved these changes
seems like the correct set of things to me

2022-07-28 21:25 UTC, sryza commented
@OwenKephart re-requesting review because I added in SourceAsset

2022-07-28 21:33 UTC, OwenKephart approved these changes
was it a deliberate choice to keep SourceAsset.with_resources private? I'm fine with that, just double checking

2022-07-29 20:53 UTC, dpeng817 requested changes
Gonna block this - I think that the set of things here is too broad. I don't think there is user utility for a lot of stuff like `can_subset` for example, and casting too wide a net on what properties/methods we directly communicate might make life difficult in the future. It also opens up a can of worms around APIs that aren't part of the public API but might be exposed through excessive property visibility. For example, if `AssetsDefinition.can_subset` is public, should `OpDefinition.compute_fn` be public (which returns a currently private class)? I think drawing that distinction is hard, and fwiw our docs don't have this level of detail right now. Look at JobDefinition's API docs https://docs.dagster.io/_apidocs/jobs#dagster.JobDefinition, which only expose `execute_in_process` and `with_hooks`.

2022-07-29 23:28 UTC, sryza commented
@dpeng817 we caught up on this in Slack, but repeating the high-level points here: I think that `can_subset` and the compute function are both part of the AssetsDefinition data model, and that data model should be visible to users.  I think `can_subset` is easy to expose, because the internal property is identical to the value that gets passed in, and thus we should make it public.  I think the compute function is more difficult to expose because of the way we wrap it, and, it's not extremely high priority, so we can punt on it for now.

2022-08-01 22:31 UTC, dpeng817 commented on python_modules/dagster/dagster/_core/definitions/source_asset.py
>              ("metadata_entries", Sequence[Union[MetadataEntry, PartitionMetadataEntry]]),
arguably, shouldn't this be public for people directly utilizing the `SourceAsset` object in some way?

2022-08-01 22:31 UTC, dpeng817 approved these changes

2022-08-01 22:42 UTC, merged