Add missing `job_name` argument
dagster-io/dagster pull request #9097
Opened 2022-07-29 18:15 UTC by metinsenturk

### Summary & Motivation

Creating a `RunRequest` for a partitioned job is missing `job_name` argument. This causes errors when using a sensor that triggers multiple jobs.

When a sensor defined to trigger multiple jobs, it asks for each RunRequest to have a `job_name` argument, therefore we need to have `job_name`, like below.

``` py
@sensor(jobs=[job1_with_no_partition, job2_with_partition], minimum_interval_seconds=60 * 20)
def my_cool_sensor(context: SensorEvaluationContext):
    """
    Checks a process and starts multiple jobs.
    """
    yield RunRequest(
        run_key=None, run_config={...}, job_name='job1_with_no_partition')
    yield job2_with_partition.run_request_for_partition(
        partition_key="my_partition_key", run_key="my_partition_key", job_name='job2_with_partition')

    context.update_cursor(...)

```

### How I Tested These Changes

I can add if needed.

2022-08-09 17:10 UTC, dpeng817 commented on python_modules/dagster/dagster/_core/definitions/job_definition.py
> +        job_name: Optional[str] = None,
I think we don't want to make this passable like so - I think we would just want to pass the current job's name to the run request.

2022-08-09 17:11 UTC, dpeng817 commented on python_modules/dagster/dagster/_core/definitions/job_definition.py
> +        return RunRequest(run_key=run_key, run_config=run_config, tags=run_request_tags, job_name=job_name)
```suggestion
        return RunRequest(run_key=run_key, run_config=run_config, tags=run_request_tags, job_name=self.name)
```

2022-08-09 17:11 UTC, dpeng817 commented on python_modules/dagster/dagster/_core/definitions/job_definition.py
> +        job_name: Optional[str] = None,
```suggestion
```

2022-08-09 17:11 UTC, dpeng817 requested changes
A few comments - but great catch.

2022-08-09 21:12 UTC, metinsenturk commented
> A few comments - but great catch.

Oh i didn't see the `self.job_name`. Great that it helps!

2022-08-15 22:58 UTC, dpeng817 approved these changes

2022-08-15 22:58 UTC, merged