ecs run launcher add hooks to change run tags
dagster-io/dagster pull request #9268
Opened 2022-08-07 15:30 UTC by prha

### Summary & Motivation
Enables subclasses to change the format of the ECS info stored in tags.

### How I Tested These Changes
BK

2022-08-09 20:25 UTC, gibsondan requested changes
we ended up doing this differently i think?

2022-08-09 20:28 UTC, prha commented
This is separate.... in case we want to change the stored run tags to remove the serverless account id from the arn/cluster.

2022-09-14 01:08 UTC, gibsondan approved these changes
better late than never

2022-09-14 01:08 UTC, gibsondan commented on python_modules/libraries/dagster-aws/dagster_aws/ecs/launcher.py
> +    def get_ecs_info(self, run_id) -> EcsInfo:
bit confused why we took out the underscore - them being overridden by a subclass doesn't necc make them public I think?

2022-09-14 01:08 UTC, gibsondan commented on python_modules/libraries/dagster-aws/dagster_aws/ecs/launcher.py
> +    def get_ecs_info(self, run_id) -> EcsInfo:
def _get_ecs_info_from_run_tags?

2022-10-07 15:36 UTC, closed without merging