RFC: Allow the user of env vars to override the default io manager
dagster-io/dagster pull request #9324
Opened 2022-08-09 22:07 UTC by gibsondan

Summary:
Could imagine using this in different execution environments where filesystem as the default doesn't make sense. The calling environment sets the env var like in the test.

### Summary & Motivation

### How I Tested These Changes

2022-08-12 00:10 UTC, sryza requested changes
Requesting changes for q management

2022-08-30 00:04 UTC, mingfang commented
+1
Env vars enables us to run the same code in different environments(dev,qa,prod, etc) without making any code changes.
We use env vars in all of our in house apps, so it would be great if we can manage dagster the same way.

2022-08-30 14:48 UTC, sryza commented
@mingfang have you seen the pattern in use in the fully-featured example: https://github.com/dagster-io/dagster/blob/master/examples/project_fully_featured/project_fully_featured/repository.py#L27? Would this work for you?

2022-08-30 14:54 UTC, mingfang commented
@sryza 
That's better than nothing I guess. 
But I much rather using something like `dotenv` and 
then move all configuration to either `.env` files and/or just-in-time env vars as part of my Kubernetes deployments.

2022-09-26 17:03 UTC, jmsanders commented on python_modules/dagster/dagster/_core/definitions/job_definition.py
> +    io_manager_env_var = os.getenv("DEFAULT_IO_MANAGER_DEFINITION_ATTRIBUTE")
I put together a kind of fun proof-of-concept for this type of approach while out:

https://github.com/jmsanders/depenv

The ergonomics potentially leave something to be desired although I like your idea in this PR of using a json string.

But in general, I agree with @sryza re: the slippery slope. It feels odd to me that you could set IO managers this way but not other resources. And I'm not quite sure I'm ready to fully advocate for setting everything this way without dogfooding the idea a bit more.

2022-09-27 18:11 UTC, closed without merging