Add mapping_to and mapping_from methods for graphIn and graphOut
dagster-io/dagster pull request #9352
Opened 2022-08-11 23:24 UTC by dpeng817

In order to create graphs with inputs/outputs without the decorator, it's necessary to define input/output mappings that map a graph's outer inputs/outputs to those of inner nodes. Previously, this was only possible using InputDefinition / OutputDefinition, but this adds the capability to `GraphIn`/`GraphOut`. I opted for static methods since the interface is a bit cleaner, but using instance methods may be a bit more future-proof if we end up adding further stuff to `GraphIn`/`GraphOut` in the future.

2022-08-12 00:13 UTC, sryza reviewed
Why not just enable people to directly construct InputMappings and OutputMappings?

2022-08-12 00:13 UTC, sryza commented on python_modules/dagster/dagster/_core/definitions/input.py
> +    Users should not construct objects of this class directly. Instead, they should construct using :py:meth:`dagster.GraphIn.mapping_to`."""
Line length

2022-08-12 00:26 UTC, dpeng817 commented
cc @sryza under the hood, Input/OutputMapping use deprecated APIs I think we'd rather not expose. We can change this but it's a non trivial amount of work, and a breaking change. Given that in the past they were constructed via an InputDefinition, I think this is a natural extension.

2022-08-12 01:14 UTC, dpeng817 commented
Current dependencies on/for this PR:
* master
  * **PR #9352** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9352" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈
    * **PR #9355** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9355" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/9352?utm_source=stack-comment).

2022-08-12 17:38 UTC, sryza commented
I think the `mapping_to` method made more sense in the world of `InputDefinition`s than it does in the world of `In`s, because, in the former, the object with the `mapping_to` method knew the outer name.  I.e. it saved you the redundancy of needing to write the outer name twice.  But now that `GraphOut` doesn't hold the outer name, it's not really relevant to the mapping.

2022-08-12 18:04 UTC, dpeng817 commented
@sryza  Hmm I guess since users would previously only construct `InputMapping`/`OutputMapping` from an `InputDefinition`/`OutputDefinition`, it should be okay to change the base class directly..

2022-08-15 17:56 UTC, dpeng817 commented
cc @sryza I think changing the base class is probably the right move, but doing so is blocked on the removal of composite solid from the codebase (input definitions are pulled off of the input mapping for checking inputs). I think it's fine to keep this PR waiting until that is the case.

2022-08-16 18:12 UTC, sryza requested changes
requesting changes for queue management

2022-08-30 17:23 UTC, closed without merging