[docs] Add registry auth information to docker agent docs
dagster-io/dagster pull request #9409
Opened 2022-08-17 16:52 UTC by benpankow

## Summary

Starts to document examples of mounting Docker access creds into the Docker agent.

2022-08-17 16:52 UTC, benpankow commented
Current dependencies on/for this PR:
* master
  * **PR #9409** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9409" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/9409?utm_source=stack-comment).

2022-08-18 20:54 UTC, erinkcochran87 reviewed
@benpankow After reading through the changes, it sounds like users should be granting registry permissions *before* they do anything else with the agent setup - is that correct?

If that's the case, I don't think the end of this guide is the right place for this section. To me, it feels like it was tacked on and makes the steps feel like they're out of order. Some thoughts on addressing this:

- Make the registry access step 1 and bump the other steps down (current step 1 becomes step 2, etc.)
- Fold this info into the prereqs section

2022-08-18 20:54 UTC, erinkcochran87 commented on docs/content/dagster-cloud/deployment/agents/docker.mdx
> +## Granting Registry Access to Docker Agent
Can you make this guy use sentence case, please?

2022-08-18 20:54 UTC, erinkcochran87 commented on docs/content/dagster-cloud/deployment/agents/docker.mdx
> +The Docker agent runs Docker operations from within the `dagster-cloud-agent` container, including pulling user code images and running them as new containers. The `dagster-cloud-agent` container req
```suggestion
The Docker agent runs Docker operations from within the `dagster-cloud-agent` container, including pulling user code images and running them as new containers. The `dagster-cloud-agent` container requires access to credentials in order to perform these operations.

Depending on the registry provider you're using, authentication may look different. Credentials are often stored in the Docker config file (`~/.docker/config.json`).
```

- Splitting into two paragraphs to improve readability. I don't think this takes away from what's being said, but feel free to push back on this.
- Removed the semicolon preceding the name of the Docker file. As the file name itself isn't a complete sentence, this isn't needed

2022-08-18 20:54 UTC, erinkcochran87 commented on docs/content/dagster-cloud/deployment/agents/docker.mdx
> +    # Replace $YOUR_REGISTRY with the GCR registry you are using, e.g. https://gcr.io
This should be formatted the same way as other code blocks, like on line 117. Without it, the formatting looks funky when the site is built + rendered.

2022-08-19 22:18 UTC, benpankow commented
> users should be granting registry permissions _before_ they do anything else with the agent setup - is that correct?

Usually the setup should be done immediately before running the agent, e.g. in the same startup script that they run the agent (whether locally, in a VM etc). I've updated the PR structure to slot in this information earlier on which will hopefully make this more clear. Let me know what you think.

2022-08-24 17:55 UTC, erinkcochran87 reviewed
Two small changes (fixing a link and the section heading) but this otherwise looks good!

2022-08-24 17:55 UTC, erinkcochran87 commented on docs/content/dagster-cloud/deployment/agents/docker.mdx
> +## Step 3: Granting registry access to Docker agent
```suggestion
## Step 3: Grant registry access to the agent
```

Making this section heading consistent with other headings in the guide.

2022-08-24 17:55 UTC, erinkcochran87 commented on docs/content/dagster-cloud/deployment/agents/docker.mdx
> +- **Access to a container registry to which you can push images with Dagster code.** Additionally, your Docker agent must have the permissions required to pull images from the registry. See [below](#
```suggestion
- **Access to a container registry to which you can push images with Dagster code.** Additionally, your Docker agent must have the permissions required to pull images from the registry. See [below](#step-3-grant-registry-access-to-the-agent) for more details.
```

This fixes a broken link, updating it to use the new name of the section heading.

2022-09-15 16:11 UTC, alangenfeld requested changes
to your queue for recommended changes

2024-09-30 19:59 UTC, closed without merging