Make OutputMapping compliant with new APIs
dagster-io/dagster pull request #9554
Opened 2022-08-30 21:44 UTC by dpeng817

### Summary & Motivation
OutputMapping previously required an OutputDefinition to be constructed. This removes the usage of OutputDefinition from OutputMapping, and adds a new construction method.

### How I Tested These Changes

2022-08-30 21:44 UTC, dpeng817 commented
Current dependencies on/for this PR:
* master
  * **PR #9553** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9553" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #9554** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9554" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/9554?utm_source=stack-comment).

2022-08-30 22:12 UTC, sryza approved these changes
Had a small comment that I think is worth addressing. Otherwise, LGTM

2022-08-30 22:12 UTC, sryza commented on python_modules/dagster/dagster/_core/definitions/graph_definition.py
> +                output_mapping.get_definition(is_dynamic=dynamic_mappings[output_mapping.out_name])
It's a little awkward to pass in a boolean to determine the type of the returned object. Thoughts on just constructing the `OutputDefinition` / `DynamicOutputDefinition` here with the data from the output mapping?

2022-08-30 22:35 UTC, dpeng817 reviewed
That works. cc@alangenfeld@sryza, this actually inadvertently solves the dynamic graph issue as well from https://github.com/dagster-io/dagster/pull/9522/files.

2022-08-30 22:47 UTC, sryza requested changes
Sorry actually one more thing - why have this `create` function instead of just using the constructor?

2022-08-30 23:30 UTC, sryza approved these changes

2022-08-31 14:28 UTC, alangenfeld approved these changes
cool

2022-08-31 14:28 UTC, alangenfeld commented on python_modules/dagster/dagster_tests/core_tests/graph_tests/test_graph.py
> +    assert mapped_out.execute_in_process().success
assert the correct value also

2022-08-31 20:13 UTC, sryza approved these changes
I love it

2022-09-01 15:17 UTC, merged