Cragify core subfolders
dagster-io/dagster pull request #9749
Opened 2022-09-20 22:32 UTC by dpeng817

### Summary & Motivation

### How I Tested These Changes

2022-09-20 22:32 UTC, dpeng817 commented
Current dependencies on/for this PR:
* master
  * **PR #9749** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9749" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/9749?utm_source=stack-comment).

2022-10-27 17:27 UTC, alangenfeld requested changes
Definitely want behavior changes separated out from mass conversion PRs. 

PR summary should include how the mass modification was performed.

2022-10-27 17:27 UTC, alangenfeld commented on python_modules/dagster/dagster/_core/definitions/reconstruct.py
> +        )
this is a behavior change - before `None` would flow through now we coerce in to empty set. Pretty sure None vs empty set is meaningful so dont think we want this change.

2022-10-27 17:27 UTC, alangenfeld commented on python_modules/dagster/dagster/_core/execution/execution_result.py
> +        )
this seems extremely dubious - how is the run successful and the events failures?

2022-10-28 22:52 UTC, closed without merging