daemon workspace refactor
dagster-io/dagster pull request #9833
Opened 2022-09-29 16:44 UTC by alangenfeld

Move the daemons to using the same WorkspaceProcessContext -> WorkspaceRequestContext that we use in the webserver.

Instead of eagerly creating request contexts, they are done on demand. This is to prevent large memory costs when there are large voluems of sensor/schedule requests happening async. 

### How I Tested These Changes

bk

2022-09-29 16:44 UTC, alangenfeld commented
Current dependencies on/for this PR:
* master
  * **PR #9833** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/9833" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/9833?utm_source=stack-comment).

2022-10-03 19:00 UTC, gibsondan requested changes
wow this was not for the faint of heart - broadly looks great

only thing is the surprising new logic in scheduler, see inline - and some answer for log_verbose_checks? just want to make sure the scheduler doesn't get impossibly spammy when no real work is happening, there may be a better solution than the boolean for that though

2022-10-03 20:58 UTC, alangenfeld commented on python_modules/dagster/dagster/_scheduler/scheduler.py
> +        return
this was an unhandled error state revealed by typing the function - `get_external_schedule_execution_data` can return `Union["ScheduleExecutionData", "ExternalScheduleExecutionErrorData"]` and we were always treating the data as `ScheduleExecutionData` previously

2022-10-03 20:58 UTC, alangenfeld commented on python_modules/dagster/dagster/_core/workspace/context.py
> +    """
looking at how things played out we only ever use this to replace the instance to one that has specific over-rides for certain test cases. I will think on if i can drop this class.

2022-10-03 20:58 UTC, alangenfeld commented on python_modules/dagster/dagster/_daemon/sensor.py
> +            yield None
should only be `yield` -> `yield None`, `mypy` was complaining after i added return types to some of these generator function s

2022-10-03 21:13 UTC, alangenfeld commented on python_modules/dagster/dagster/_scheduler/scheduler.py
> +        return
resolved by aligning the behavior of in process repo location to the grpc one and correcting the return types on the base class

2022-10-03 21:31 UTC, alangenfeld commented on python_modules/dagster/dagster/_scheduler/scheduler.py
> +            log_verbose_checks=True,  # what to do about this ???
I am thinking there is no need to tie it to workspace state if the goal is just to reduce logging volume, I will just add some explicit code for it

2022-10-04 15:05 UTC, alangenfeld reviewed
feedback addressed

2022-10-04 15:17 UTC, gibsondan commented on python_modules/dagster/dagster/_core/host_representation/repository_location.py
> +            raise DagsterUserCodeProcessError.from_error_info(result.error)
error's a bit odd since its in the same process, but in-process is essentially for testing anyway

2022-10-04 15:29 UTC, gibsondan approved these changes

2022-10-04 16:55 UTC, merged